### ISSUE TITLE
Mipnerf OOM during first initialization

### ISSUE THREAD

**Issue by belkahorry** [nerfstudio-project/nerfstudio#1035]
Thanks for sharing this excellent work.
I've tried nerfacto which worked fine.
After 8x downscale,the resolution of images is only 480x270:
`ns-train mipnerf nerfstudio-data --downscale-factor 8 --data ./`

```
logging events to: outputs/mipnerf/2022-11-27_222917
[10:29:25 PM] Skipping 0 files in dataset split train.                                       nerfstudio_dataparser.py:96
              Skipping 0 files in dataset split val.                                         nerfstudio_dataparser.py:96
Setting up training dataset...
Caching all 155 images.
Setting up evaluation dataset...
Caching all 17 images.
No checkpoints to load, training from scratch
Printing profiling stats, from longest to shortest duration in seconds
Traceback (most recent call last):
  File "/home/horry/anaconda3/envs/torch/bin/ns-train", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/horry/Nerf/nerfstudio/scripts/train.py", line 248, in entrypoint
    main(
  File "/home/horry/Nerf/nerfstudio/scripts/train.py", line 234, in main
    launch(
  File "/home/horry/Nerf/nerfstudio/scripts/train.py", line 173, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "/home/horry/Nerf/nerfstudio/scripts/train.py", line 88, in train_loop
    trainer.train()
  File "/home/horry/Nerf/nerfstudio/nerfstudio/engine/trainer.py", line 151, in train
    loss, loss_dict, metrics_dict = self.train_iteration(step)
  File "/home/horry/Nerf/nerfstudio/nerfstudio/utils/profiler.py", line 43, in wrapper
    ret = func(*args, **kwargs)
  File "/home/horry/Nerf/nerfstudio/nerfstudio/engine/trainer.py", line 315, in train_iteration
    _, loss_dict, metrics_dict = self.pipeline.get_train_loss_dict(step=step)
  File "/home/horry/Nerf/nerfstudio/nerfstudio/utils/profiler.py", line 43, in wrapper
    ret = func(*args, **kwargs)
  File "/home/horry/Nerf/nerfstudio/nerfstudio/pipelines/base_pipeline.py", line 255, in get_train_loss_dict
    model_outputs = self.model(ray_bundle)
  File "/home/horry/anaconda3/envs/torch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/horry/Nerf/nerfstudio/nerfstudio/models/base_model.py", line 138, in forward
    return self.get_outputs(ray_bundle)
  File "/home/horry/Nerf/nerfstudio/nerfstudio/models/mipnerf.py", line 120, in get_outputs
    field_outputs_fine = self.field.forward(ray_samples_pdf)
  File "/home/horry/Nerf/nerfstudio/nerfstudio/fields/base_field.py", line 104, in forward
    density, density_embedding = self.get_density(ray_samples)
  File "/home/horry/Nerf/nerfstudio/nerfstudio/fields/vanilla_nerf_field.py", line 96, in get_density
    encoded_xyz = self.position_encoding(gaussian_samples.mean, covs=gaussian_samples.cov)
  File "/home/horry/anaconda3/envs/torch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/horry/Nerf/nerfstudio/nerfstudio/field_components/encodings.py", line 153, in forward
    encoded_inputs = expected_sin(
  File "/home/horry/Nerf/nerfstudio/nerfstudio/utils/math.py", line 193, in expected_sin
    return torch.exp(-0.5 * x_vars) * torch.sin(x_means)
RuntimeError: CUDA out of memory. Tried to allocate 384.00 MiB (GPU 0; 15.74 GiB total capacity; 13.18 GiB already allocated; 287.00 MiB free; 13.41 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
wandb: Synced sweet-violet-28: https://wandb.ai/belkahorry/nerfstudio-project/runs/hahkjmlw
wandb: Synced 6 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: outputs/mipnerf/2022-11-27_222917/wandb/run-20221127_222919-hahkjmlw/logs
```
I knew original mip360(multinerf) got OOM bug during computing SSIM in eval step. But may fixed by #81. So how can i fix this one?

**Comment by tancik** [comment]
LPIPS requires a fair amount of memory, you could try removing all references to it in the model file, ie https://github.com/nerfstudio-project/nerfstudio/blob/aac7aa4786f6a6a7ba5da7acfc79db73359d6b28/nerfstudio/models/mipnerf.py#L89
You can also decrease the batch size using the `--pipeline.datamanager.train-num-rays-per-batch` argument.
