### ISSUE TITLE
zmq.error.ZMQError: Operation cannot be accomplished in current state

### ISSUE THREAD

**Issue by chauncy-hw** [nerfstudio-project/nerfstudio#1096]
Thank you for your great work! 

**Describe the bug**
The program can run normally. But when I open the viewer, the program will report the following error. However, no other programs are running in the system. I don't think this is a simple memory overflow problem.

RuntimeError: CUDA out of memory. Tried to allocate 19.04 GiB (GPU 0; 15.73 GiB total capacity; 273.18 MiB already allocated; 12.65 GiB free; 350.00 MiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
zmq.error.ZMQError: Operation cannot be accomplished in current state.

**Comment by tancik** [comment]
Are you running the latest version of the code? This was an issue like this for a brief period that has since been fixed.
If you are running the latest, which model are you training? What is your training command?

**Comment by rishikeshrmadan** [comment]
Greetings,
Using the latest version 0.1.12, facing the same error with instant-ngp (even when loading pre-trained models), viewer loads but crashes as soon as one navigates within it.  200W / 270W |   7267MB /  7981MB are the stats on the 3070 desktop I am using. Nerfacto is working fine.

**Comment by chauncy-hw** [comment]
I am using Nerfacto. After I updated the code, reinstalled tinycudann, and restarted the computer, the code worked fine. Thank you!

**Comment by KamiCalcium** [comment]
Having the same issue with latest docker image when running instantngp. (0.1.14)

**Comment by tancik** [comment]
`instant-ngp` can use a lot of memory ( it is scene dependent). How much memory does your GPU have?

**Comment by SizheAn** [comment]
> `instant-ngp` can use a lot of memory ( it is scene dependent). How much memory does your GPU have?

@tancik For me it is a bit different, it is also a zmq error finally but the complete log is this:

```
Viewer at: https://viewer.nerf.studio/versions/22-12-16-0/?websocket_url=ws://localhost:7007         
Printing profiling stats, from longest to shortest duration in seconds
ViewerState._render_image_in_viewer: 0.0672              
Trainer.train_iteration: 0.0386              
VanillaPipeline.get_train_loss_dict: 0.0257              
Traceback (most recent call last):
  File "/home/user/nerfstudio/nerfstudio/viewer/server/viewer_utils.py", line 814, in _render_image_in_viewer
    render_thread.join()
  File "/home/user/nerfstudio/nerfstudio/viewer/server/viewer_utils.py", line 161, in join
    raise self.exc
  File "/home/user/nerfstudio/nerfstudio/viewer/server/viewer_utils.py", line 147, in run
    outputs = self.graph.get_outputs_for_camera_ray_bundle(self.camera_ray_bundle)
  File "/home/user/.local/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/user/nerfstudio/nerfstudio/models/base_model.py", line 176, in get_outputs_for_camera_ray_bundle
    outputs = self.forward(ray_bundle=ray_bundle)
  File "/home/user/nerfstudio/nerfstudio/models/base_model.py", line 138, in forward
    return self.get_outputs(ray_bundle)
  File "/home/user/nerfstudio/nerfstudio/models/instant_ngp.py", line 181, in get_outputs
    field_outputs = self.field(ray_samples)
  File "/home/user/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/nerfstudio/nerfstudio/fields/base_field.py", line 111, in forward
    field_outputs = self.get_outputs(ray_samples, density_embedding=density_embedding)
  File "/home/user/nerfstudio/nerfstudio/fields/instant_ngp_field.py", line 174, in get_outputs
    rgb = self.mlp_head(h).view(*ray_samples.frustums.directions.shape[:-1], -1).to(directions)
  File "/home/user/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/tinycudann/modules.py", line 156, in forward
    x_padded.to(torch.float).contiguous(),
RuntimeError: CUDA error: unknown error
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/bin/ns-train", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/user/nerfstudio/scripts/train.py", line 248, in entrypoint
    main(
  File "/home/user/nerfstudio/scripts/train.py", line 234, in main
    launch(
  File "/home/user/nerfstudio/scripts/train.py", line 173, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "/home/user/nerfstudio/scripts/train.py", line 88, in train_loop
    trainer.train()
  File "/home/user/nerfstudio/nerfstudio/engine/trainer.py", line 187, in train
    self._update_viewer_state(step)
  File "/home/user/nerfstudio/nerfstudio/utils/decorators.py", line 58, in wrapper
    ret = func(self, *args, **kwargs)
  File "/home/user/nerfstudio/nerfstudio/engine/trainer.py", line 250, in _update_viewer_state
    self.viewer_state.update_scene(self, step, self.pipeline.model, num_rays_per_batch)
  File "/home/user/nerfstudio/nerfstudio/utils/decorators.py", line 82, in wrapper
    ret = func(*args, **kwargs)
  File "/home/user/nerfstudio/nerfstudio/viewer/server/viewer_utils.py", line 417, in update_scene
    self._render_image_in_viewer(camera_object, graph, is_training)
  File "/home/user/nerfstudio/nerfstudio/utils/decorators.py", line 82, in wrapper
    ret = func(*args, **kwargs)
  File "/home/user/nerfstudio/nerfstudio/utils/profiler.py", line 43, in wrapper
    ret = func(*args, **kwargs)
  File "/home/user/nerfstudio/nerfstudio/viewer/server/viewer_utils.py", line 820, in _render_image_in_viewer
    self.vis["renderingState/log_errors"].write(
  File "/home/user/nerfstudio/nerfstudio/viewer/server/visualizer.py", line 146, in write
    return self.window.send({"type": "write", "path": path, "data": data})
  File "/home/user/nerfstudio/nerfstudio/viewer/server/visualizer.py", line 50, in send
    self.client.send_multipart(
  File "/home/user/.local/lib/python3.10/site-packages/zmq/sugar/socket.py", line 675, in send_multipart
    self.send(msg, zmq.SNDMORE | flags, copy=copy, track=track)
  File "/home/user/.local/lib/python3.10/site-packages/zmq/sugar/socket.py", line 620, in send
    return super().send(data, flags=flags, copy=copy, track=track)
  File "zmq/backend/cython/socket.pyx", line 746, in zmq.backend.cython.socket.Socket.send
  File "zmq/backend/cython/socket.pyx", line 793, in zmq.backend.cython.socket.Socket.send
  File "zmq/backend/cython/socket.pyx", line 255, in zmq.backend.cython.socket._send_copy
  File "zmq/backend/cython/socket.pyx", line 250, in zmq.backend.cython.socket._send_copy
  File "zmq/backend/cython/checkrc.pxd", line 28, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Operation cannot be accomplished in current state
```
so seems like
```
RuntimeError: CUDA error: unknown error
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```
is the real error. I'm using only one 3080. Original instant-ngp implementation does not cause any problem tho.

**Comment by tancik** [comment]
Yea, it seems like a different issue. You should run with `CUDA_LAUNCH_BLOCKING=1` to see where it is actually being raised.

**Comment by KamiCalcium** [comment]
> Yea, it seems like a different issue. You should run with `CUDA_LAUNCH_BLOCKING=1` to see where it is actually being raised.

Where should I add the flag ```CUDA_LAUNCH_BLOCKING=1```? I tried inserting between ```ns-train instant-ngp --data data`` but it does not work

**Comment by KamiCalcium** [comment]
> Yea, it seems like a different issue. You should run with `CUDA_LAUNCH_BLOCKING=1` to see where it is actually being raised.

@tancik Sorry I was logging the wrong account: @SizheAn. I found out it might be viewer's problem since the zmq error happens only when I open the viewer. This is the error log:

```
  File "/home/user/.local/lib/python3.10/site-packages/aioice/turn.py", line 216, in request_with_retry
    response, addr = await self.request(request)
  File "/home/user/.local/lib/python3.10/site-packages/aioice/turn.py", line 203, in request
    return await transaction.run()
  File "/home/user/.local/lib/python3.10/site-packages/aioice/stun.py", line 299, in run
    return await self.__future
aioice.stun.TransactionFailed: STUN transaction failed (403 - Forbidden IP)
Task exception was never retrieved
future: <Task finished name='Task-54' coro=<TurnClientMixin.send_data() done, defined at /home/user/.local/lib/python3.10/site-packages/aioice/turn.py:244> exception=TransactionFailed(Message(message_method=Method.CHANNEL_BIND, message_class=Class.ERROR, transaction_id=b'\xad\xc5\x1e\x12\xeaf<\xfeu0\xe6`'))>
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/aioice/turn.py", line 263, in send_data
    await self.channel_bind(channel, addr)
  File "/home/user/.local/lib/python3.10/site-packages/aioice/turn.py", line 88, in channel_bind
    await self.request_with_retry(request)
  File "/home/user/.local/lib/python3.10/site-packages/aioice/turn.py", line 216, in request_with_retry
    response, addr = await self.request(request)
  File "/home/user/.local/lib/python3.10/site-packages/aioice/turn.py", line 203, in request
    return await transaction.run()
  File "/home/user/.local/lib/python3.10/site-packages/aioice/stun.py", line 299, in run
    return await self.__future
aioice.stun.TransactionFailed: STUN transaction failed (403 - Forbidden IP)
Task exception was never retrieved
future: <Task finished name='Task-56' coro=<TurnClientMixin.send_data() done, defined at /home/user/.local/lib/python3.10/site-packages/aioice/turn.py:244> exception=TransactionFailed(Message(message_method=Method.CHANNEL_BIND, message_class=Class.ERROR, transaction_id=b'\x10\xd0\xb9\x023\xfbG\x19i\n\xbfW'))>
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/aioice/turn.py", line 263, in send_d
```

Also about the viewer I have a question (might relate to the previous bug): seems like if I run the program with docker, it is not able to render anything:
![image](https://user-images.githubusercontent.com/61800479/212790141-b612126c-2be3-47fe-9de7-6a913c0bbdf3.png), whereas if I run it without docker everything looks fine. Any clue why it happens?

**Comment by tancik** [comment]
For the flag, run `CUDA_LAUNCH_BLOCKING=1 ns-train ...`

For the docker, Im not sure. You can try running with `--viewer.skip-openrelay True` to see if that helps. 

This github issue is turning into a series of issues. The discord may be a better place to work through some of this troubleshooting.
