### ISSUE TITLE
NameError: name '_C' is not defined

### ISSUE THREAD

**Issue by tojiboyevf** [nerfstudio-project/nerfstudio#1120]
**Describe the bug**
I run following command:
```
```
And then it shows this error

```
Traceback (most recent call last):
  File "/home/user/.local/bin/ns-train", line 5, in <module>
    from scripts.train import entrypoint
  File "/home/user/nerfstudio/scripts/train.py", line 50, in <module>
    from nerfstudio.configs.method_configs import AnnotatedBaseConfigUnion
  File "/home/user/nerfstudio/nerfstudio/configs/method_configs.py", line 39, in <module>
    from nerfstudio.field_components.temporal_distortions import TemporalDistortionKind
  File "/home/user/nerfstudio/nerfstudio/field_components/__init__.py", line 17, in <module>
    from .encodings import Encoding, ScalingAndOffset
  File "/home/user/nerfstudio/nerfstudio/field_components/encodings.py", line 34, in <module>
    import tinycudann as tcnn
  File "/home/user/.local/lib/python3.8/site-packages/tinycudann/__init__.py", line 9, in <module>
    from tinycudann.modules import free_temporary_memory, NetworkWithInputEncoding, Network, Encoding
  File "/home/user/.local/lib/python3.8/site-packages/tinycudann/modules.py", line 33, in <module>
    if _C is None:
NameError: name '_C' is not defined
```
How to solve this issue?
I pulled docker image with versions `0.1.13` and `0.1.10`. I also tried to build Docker image but the same error
Other parameters:
```
NVIDIA-SMI 520.61.05    Driver Version: 520.61.05    CUDA Version: 11.8 
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy
```

**Comment by akristoffersen** [comment]
I noticed this as well when working with Tinycuda as well, but for the colab. Could you try `pip install Cython`?

**Comment by tojiboyevf** [comment]
> I noticed this as well when working with Tinycuda as well, but for the colab. Could you try `pip install Cython`?

Thanks for your response!
Yeah, I tried to install Cython. It also didn't help.

**Comment by mabl** [comment]
The problem here is that nerfstudio hard-codes the CUDA architecture version in the Docker skript (`TCNN_CUDA_ARCHITECTURES`). When run on a GPU with lower than the default 8.5 architecture, a bug in `tiny-cuda-nn` is triggered in a code path that is supposed to tell you, that no backend for your architecture has been found.

Try either removing the environmental variable definition or lower the the architecture to match your hardware.
