### ISSUE TITLE
Error occured when loading old pretrained model

### ISSUE THREAD

**Issue by belkahorry** [nerfstudio-project/nerfstudio#1125]
These pre-trained models were trained with several versions prior to 0.1.13. After I upgraded to 0.1.13, they all reported the following error:
```
[09:58:41 AM] Auto image downscale factor of 1                                              nerfstudio_dataparser.py:294
[09:58:42 AM] Skipping 0 files in dataset split train.                                      nerfstudio_dataparser.py:156
              Skipping 0 files in dataset split val.                                        nerfstudio_dataparser.py:156
Setting up training dataset...
Caching all 155 images.
Setting up evaluation dataset...
Caching all 17 images.
Loading latest checkpoint from load_dir
Printing profiling stats, from longest to shortest duration in seconds
Traceback (most recent call last):
  File "/home/xxx/anaconda3/envs/torch/bin/ns-train", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/xxx/Nerf/nerfstudio/scripts/train.py", line 248, in entrypoint
    main(
  File "/home/xxx/Nerf/nerfstudio/scripts/train.py", line 234, in main
    launch(
  File "/home/xxx/Nerf/nerfstudio/scripts/train.py", line 173, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "/home/xxx/Nerf/nerfstudio/scripts/train.py", line 87, in train_loop
    trainer.setup()
  File "/home/xxx/Nerf/nerfstudio/nerfstudio/engine/trainer.py", line 120, in setup
    self._load_checkpoint()
  File "/home/xxx/Nerf/nerfstudio/nerfstudio/engine/trainer.py", line 289, in _load_checkpoint
    self.pipeline.load_pipeline(loaded_state["pipeline"])
  File "/home/xxx/Nerf/nerfstudio/nerfstudio/pipelines/base_pipeline.py", line 368, in load_pipeline
    self.load_state_dict(state)  # type: ignore
  File "/home/xxx/anaconda3/envs/torch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1604, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for VanillaPipeline:
	size mismatch for _model.field.mlp_base.params: copying a param with shape torch.Size([11448112]) from checkpoint, the shape in current model is torch.Size([12199312]).

```

**Comment by tancik** [comment]
Unfortunately underlying changes make the model no longer compatible. Our intention is to continually update an improve nerfacto which will lead to issues when running older version of the model. I'd recommend either reverting to the older version of nerfstudio, or retrain the model.
