### ISSUE TITLE
PermissionError: [Errno 1] Operation not permitted:

### ISSUE THREAD

**Issue by tojiboyevf** [nerfstudio-project/nerfstudio#1130]
I am trying to preprocess custom data using docker. I run following command:
```
ns-process-data images --data project/images/ --output-dir ./data
```
And it's showing this error:
```
Traceback (most recent call last):
  File "/home/user/.local/bin/ns-process-data", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/user/nerfstudio/scripts/process_data.py", line 706, in entrypoint
    tyro.cli(Commands).main()
  File "/home/user/nerfstudio/scripts/process_data.py", line 95, in main
    num_frames = process_data_utils.copy_images(self.data, image_dir=image_dir, verbose=self.verbose)
  File "/home/user/nerfstudio/nerfstudio/process_data/process_data_utils.py", line 170, in copy_images
    num_frames = len(copy_images_list(image_paths, image_dir, verbose))
  File "/home/user/nerfstudio/nerfstudio/process_data/process_data_utils.py", line 136, in copy_images_list
    shutil.copy(image_path, copied_image_path)
  File "/usr/lib/python3.8/shutil.py", line 419, in copy
    copymode(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.8/shutil.py", line 308, in copymode
    chmod_func(dst, stat.S_IMODE(st.st_mode))
PermissionError: [Errno 1] Operation not permitted: 'data/images/frame_00001.png'
```
I tried nerfstudio docker images with `0.1.10`, `0.1.13` versions and I also tried to build docker image using nerfstudio Dockerfile and each case I got the same error.
I am using server remotely. Other paramters of server:
```
NVIDIA-SMI 520.61.05    Driver Version: 520.61.05    CUDA Version: 11.8 
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy
```

**Comment by tancik** [comment]
Can you check the permissions for the the current directory you are running this code, the `data` directory, and the `data/images` directory. It seems like one of them might not have full permissions.

**Comment by tojiboyevf** [comment]
When I run `ls -la` it printed these lines:
```
drwxrwxrwx 1 1037 users  36 Dec 14 22:44 data
drwxrwxrwx 1 1037 users  12 Dec 14 18:14 project
```
I solved the problem but in a different way.
I commented all lines related to non root user in Dockerfile. Now the Dockerfile looks like this:
```
# Define base image.
FROM nvidia/cudagl:11.3.1-devel

# Set environment variables.
## Set non-interactive to prevent asking for user inputs blocking image creation.
ENV DEBIAN_FRONTEND=noninteractive
## Set timezone as it is required by some packages.
ENV TZ=Europe/Berlin
## CUDA architectures, required by tiny-cuda-nn.
ENV TCNN_CUDA_ARCHITECTURES=86
## CUDA Home, required to find CUDA in some packages.
ENV CUDA_HOME="/usr/local/cuda"

# Install required apt packages.
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    cmake \
    ffmpeg \
    git \
    libatlas-base-dev \
    libboost-filesystem-dev \
    libboost-graph-dev \
    libboost-program-options-dev \
    libboost-system-dev \
    libboost-test-dev \
    libcgal-dev \
    libeigen3-dev \
    libfreeimage-dev \
    libgflags-dev \
    libglew-dev \
    libgoogle-glog-dev \
    libmetis-dev \
    libprotobuf-dev \
    libqt5opengl5-dev \
    libsuitesparse-dev \
    nano \
    protobuf-compiler \
    python3.8-dev \
    python3-pip \
    qtbase5-dev \
    wget

# Install GLOG (required by ceres).
RUN git clone --branch v0.6.0 https://github.com/google/glog.git --single-branch && \
    cd glog && \
    mkdir build && \
    cd build && \
    cmake .. && \
    make -j && \
    make install && \
    cd ../.. && \
    rm -r glog
# Add glog path to LD_LIBRARY_PATH.
ENV LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:/usr/local/lib"

# Install Ceres-solver (required by colmap).
RUN git clone --branch 2.1.0 https://ceres-solver.googlesource.com/ceres-solver.git --single-branch && \
    cd ceres-solver && \
    git checkout $(git describe --tags) && \
    mkdir build && \
    cd build && \
    cmake .. -DBUILD_TESTING=OFF -DBUILD_EXAMPLES=OFF && \
    make -j && \
    make install && \
    cd ../.. && \
    rm -r ceres-solver

# Install colmap.
RUN git clone --branch 3.7 https://github.com/colmap/colmap.git --single-branch && \
    cd colmap && \
    mkdir build && \
    cd build && \
    cmake .. && \
    make -j && \
    make install && \
    cd ../.. && \
    rm -r colmap
    
# Create non root user and setup environment.
# RUN useradd -m -d /home/user -u 1000 user

# Switch to new uer and workdir.
# USER 1000:1000
# WORKDIR /home/user

# Add local user binary folder to PATH variable.
# ENV PATH="${PATH}:/home/user/.local/bin"
# SHELL ["/bin/bash", "-c"]

# Upgrade pip and install packages.
RUN python3.8 -m pip install --upgrade pip setuptools pathtools promise
# Install pytorch and submodules.
RUN python3.8 -m pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 torchaudio==0.12.1 --extra-index-url https://download.pytorch.org/whl/cu113
# Install tynyCUDNN.
RUN python3.8 -m pip install git+https://github.com/NVlabs/tiny-cuda-nn.git#subdirectory=bindings/torch
# RUN pip install git+https://github.com/NVlabs/tiny-cuda-nn.git@v1.5#subdirectory=bindings/torch --force-reinstall

# Copy nerfstudio folder and give ownership to user.
ADD . /home/user/nerfstudio
# USER root
# RUN chown -R user:user /home/user/nerfstudio
# USER 1000:1000

# Install nerfstudio dependencies.
RUN cd /home/user/nerfstudio && \
    python3.8 -m pip install -e . && \
    cd ..

# Change working directory
WORKDIR /workspace
```

With this docker image I can also train nerf models. But I am using it just to preprocess the custom data. We can close this issue

**Comment by yurkovak** [comment]
I had the same issue when using a given Dockerfile. In case someone else encounters this, it can be solved without re-building the image by running with an extra `user` argument as follows:
```docker run -v /folder/of/your/data:/workspace/ --user $(id -u):$(id -g) nerfstudion```
