### ISSUE TITLE
NotImplementedError: TSDF mesh reconstruction not implemented yet.

### ISSUE THREAD

**Issue by LHXhh** [nerfstudio-project/nerfstudio#1137]
Could you please help me? I don't know if my environment has some wrong, or it's truly the NotImplementedError: TSDF mesh reconstruction not implemented yet.

(nerfstudio) root@autodl-container-90b311823c-a2fde68a:/nerfstudio_0/nerfstudio# ns-export tsdf --load-config ./outputs/dataset-Processed_DJI/nerfacto/2022-12-16_162203/config.yml --output-dir ./mesh
Traceback (most recent call last):
  File "/root/miniconda3/envs/nerfstudio/bin/ns-export", line 8, in <module>
    sys.exit(entrypoint())
  File "/root/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/scripts/exporter.py", line 132, in entrypoint
    tyro.cli(tyro.conf.FlagConversionOff[Commands]).main()
  File "/root/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/scripts/exporter.py", line 94, in main
    raise NotImplementedError("TSDF mesh reconstruction not implemented yet.")
NotImplementedError: TSDF mesh reconstruction not implemented yet.

**Comment by tancik** [comment]
It looks like you aren't using the latest version of the code, either update the pip package or pull the latest git version.

**Comment by LHXhh** [comment]
Thank you very much!
