### ISSUE TITLE
RuntimeError: Error writing 'renders/render_output.mp4': Unrecognized option 'qp'.

### ISSUE THREAD

**Issue by LHXhh** [nerfstudio-project/nerfstudio#1138]
The rendering process is done, but there is some wrong while output vedio.

(nerfstudio) root@autodl-container-90b311823c-a2fde68a:/nerfstudio_0/nerfstudio# ns-render --load-config outputs/dataset-Processed_DJI/nerfacto/2022-12-16_200202/config.yml --traj filename --camera-path-filename outputs/dataset-Processed_DJI/nerfacto/2022-12-16_200202/camera_path.json --output-path renders/render_output.mp4
[20:40:46] Auto image downscale factor of 4                                                 nerfstudio_dataparser.py:202
           Skipping 0 files in dataset split train.                                          nerfstudio_dataparser.py:91
           Auto image downscale factor of 4                                                 nerfstudio_dataparser.py:202
           Skipping 0 files in dataset split test.                                           nerfstudio_dataparser.py:91
Loading latest checkpoint from load_dir
✅ Done loading checkpoint from 
outputs/dataset-Processed_DJI/nerfacto/2022-12-16_200202/nerfstudio_models/step-000030000.ckpt
Creating trajectory video
🎥 Rendering 🎥 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0.20 fps 09:37
Traceback (most recent call last):
  File "/root/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/mediapy/__init__.py", line 1492, in write_video
    writer.add_image(image)
  File "/root/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/mediapy/__init__.py", line 1402, in add_image
    if self._proc.stdin.write(data) != len(data):
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/nerfstudio/bin/ns-render", line 8, in <module>
    sys.exit(entrypoint())
  File "/root/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/scripts/render.py", line 164, in entrypoint
    tyro.cli(RenderTrajectory).main()
  File "/root/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/scripts/render.py", line 150, in main
    _render_trajectory_video(
  File "/root/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/scripts/render.py", line 97, in _render_trajectory_video
    media.write_video(output_filename, images, fps=fps)
  File "/root/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/mediapy/__init__.py", line 1492, in write_video
    writer.add_image(image)
  File "/root/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/mediapy/__init__.py", line 1366, in __exit__
    self.close()
  File "/root/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/mediapy/__init__.py", line 1415, in close
    raise RuntimeError(f"Error writing '{self.path}': {s}")
RuntimeError: Error writing 'renders/render_output.mp4': Unrecognized option 'qp'.
Error splitting the argument list: Option not found

**Comment by tancik** [comment]
This is an issue with FFMPEG. Likely the version you have is too old - https://github.com/KuntaiDu/dds/issues/1

**Comment by poorboy44** [comment]
I have the same issue when trying to follow the first (poster) tutorial. My ffmpeg version is 4.3

Traceback (most recent call last):
  File "/home/scotty-dell/anaconda3/envs/nerfstudio/lib/python3.9/site-packages/mediapy/__init__.py", line 1492, in write_video
    writer.add_image(image)
  File "/home/scotty-dell/anaconda3/envs/nerfstudio/lib/python3.9/site-packages/mediapy/__init__.py", line 1402, in add_image
    if self._proc.stdin.write(data) != len(data):
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/scotty-dell/anaconda3/envs/nerfstudio/bin/ns-render", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/scotty-dell/anaconda3/envs/nerfstudio/lib/python3.9/site-packages/scripts/render.py", line 164, in entrypoint
    tyro.cli(RenderTrajectory).main()
  File "/home/scotty-dell/anaconda3/envs/nerfstudio/lib/python3.9/site-packages/scripts/render.py", line 150, in main
    _render_trajectory_video(
  File "/home/scotty-dell/anaconda3/envs/nerfstudio/lib/python3.9/site-packages/scripts/render.py", line 97, in _render_trajectory_video
    media.write_video(output_filename, images, fps=fps)
  File "/home/scotty-dell/anaconda3/envs/nerfstudio/lib/python3.9/site-packages/mediapy/__init__.py", line 1492, in write_video
    writer.add_image(image)
  File "/home/scotty-dell/anaconda3/envs/nerfstudio/lib/python3.9/site-packages/mediapy/__init__.py", line 1366, in __exit__
    self.close()
  File "/home/scotty-dell/anaconda3/envs/nerfstudio/lib/python3.9/site-packages/mediapy/__init__.py", line 1415, in close
    raise RuntimeError(f"Error writing '{self.path}': {s}")
RuntimeError: Error writing 'renders/output.mp4': Unrecognized option 'qp'.
Error splitting the argument list: Option not found


(nerfstudio) scotty-dell@scottydell-XPS-8930:~/nerfstudio_dat$ conda list | grep ffmpeg
ffmpeg                    4.3                  hf484d3e_0    pytorch

**Comment by tancik** [comment]
Can you try installing ffmpeg with apt, `apt-get install ffmpeg`?
Unfortunately `mediapy` doesn't provide much guidance on ffmpeg requirements.

**Comment by LHXhh** [comment]
@tancik Thank you very much, I installed ffmpeg via `sudo apt-get install ffmpeg`, and it successfully export vedio, though I don‘’t know it's truly the problem.

**Comment by rockywind** [comment]
Hi,
I met the same error when I  installed ffmpeg via `sudo apt-get install ffmpeg`
 
![image](https://user-images.githubusercontent.com/14838781/218710556-4e0fcbf7-ccc4-40b5-b4f1-afb5bd88e363.png)

**Comment by machenmusik** [comment]
Looks from above like ffmpeg 4.3 may have been too old, in which case 3.4.11 is almost certainly too old?  I'd suggest trying a newer ffmpeg version 4.4 or 5.x

**Comment by rockywind** [comment]
Thanks,
I tried the code below, but I can't get more newer ffmpeg version.
`
apt-get update
apt-get upgrade
apt-get install ffmpeg`

**Comment by machenmusik** [comment]
Sorry it didn't help; hopefully you can find newer from https://ffmpeg.org/ and related sites.  I suspect that your ffmpeg is not built with libx264 / h264 support enabled.

**Comment by rockywind** [comment]
Hi,
I solved the proble by using `conda install ffmpeg`.

**Comment by jizongFox** [comment]
> Hi, I solved the proble by using `conda install ffmpeg`.

Problem solved. But I observed that `ffmpeg` is installed under`ffmpeg-4.2.2-h20bf706_0`, which indicates that an older version can also work.

Best,

**Comment by KiriBaimian** [comment]
> > Hi, I solved the proble by using `conda install ffmpeg`.
> 
> Problem solved. But I observed that `ffmpeg` is installed under`ffmpeg-4.2.2-h20bf706_0`, which indicates that an older version can also work.
> 
> Best,

problem solved by `conda install ffmpeg`, but dont konw why. I initially installed the latest version 6.0 ffmpeg, still “Unrecognized option 'qp'” :sweat_smile:

**Comment by Angelalilyer** [comment]
> Looks from above like ffmpeg 4.3 may have been too old, in which case 3.4.11 is almost certainly too old? I'd suggest trying a newer ffmpeg version 4.4 or 5.x, built with h264 encoder like libx264 enabled.

I have met both of these conditions, but I still reported the same error

 ffmpeg -version 
ffmpeg version 5.1 Copyright (c) 2000-2022 the FFmpeg developers
built with gcc 9 (Ubuntu 9.4.0-1ubuntu1~20.04.2)
configuration: --enable-shared --enable-libx264 --enable-gpl --prefix=/usr/bin/ffmpeg
libavutil      57. 28.100 / 57. 28.100
libavcodec     59. 37.100 / 59. 37.100
libavformat    59. 27.100 / 59. 27.100
libavdevice    59.  7.100 / 59.  7.100
libavfilter     8. 44.100 /  8. 44.100
libswscale      6.  7.100 /  6.  7.100
libswresample   4.  7.100 /  4.  7.100
libpostproc    56.  6.100 / 56.  6.100

**Comment by zhangzjjjjjj** [comment]
Hi Angelalilyer, it may have been too long. I encountered a similar issue in another open source project, where I installed version 4.3.2 using `Conda install ffmpeg - c conda-forge`, which was useful to me.


> > Looks from above like ffmpeg 4.3 may have been too old, in which case 3.4.11 is almost certainly too old? I'd suggest trying a newer ffmpeg version 4.4 or 5.x, built with h264 encoder like libx264 enabled.
> 
> I have met both of these conditions, but I still reported the same error
> 
> ffmpeg -version ffmpeg version 5.1 Copyright (c) 2000-2022 the FFmpeg developers built with gcc 9 (Ubuntu 9.4.0-1ubuntu1~20.04.2) configuration: --enable-shared --enable-libx264 --enable-gpl --prefix=/usr/bin/ffmpeg libavutil 57. 28.100 / 57. 28.100 libavcodec 59. 37.100 / 59. 37.100 libavformat 59. 27.100 / 59. 27.100 libavdevice 59. 7.100 / 59. 7.100 libavfilter 8. 44.100 / 8. 44.100 libswscale 6. 7.100 / 6. 7.100 libswresample 4. 7.100 / 4. 7.100 libpostproc 56. 6.100 / 56. 6.100

**Comment by jingyangcarl** [comment]
solved by `conda install ffmpeg -c conda-forge`

**Comment by vizionmasterla** [comment]
I found that installing ffmpeg=4.2.2

conda install -c conda-forge ffmpeg=4.2.2


seems to work.
