### ISSUE TITLE
Try to export pcd in Google Colab but failed

### ISSUE THREAD

**Issue by lbj96347** [nerfstudio-project/nerfstudio#1157]
**Describe the bug**

```
Traceback (most recent call last):
  File "/usr/local/bin/ns-export", line 5, in <module>
    from scripts.exporter import entrypoint
  File "/usr/local/lib/python3.8/site-packages/scripts/exporter.py", line 20, in <module>
    from nerfstudio.exporter import texture_utils, tsdf_utils
  File "/usr/local/lib/python3.8/site-packages/nerfstudio/exporter/texture_utils.py", line 36, in <module>
    from nerfstudio.exporter.exporter_utils import Mesh
  File "/usr/local/lib/python3.8/site-packages/nerfstudio/exporter/exporter_utils.py", line 29, in <module>
    import pymeshlab
  File "/usr/local/lib/python3.8/site-packages/pymeshlab/__init__.py", line 11, in <module>
    from .pmeshlab import *
ImportError: /usr/local/lib/python3.8/site-packages/pymeshlab/lib/libmeshlab-common.so: symbol __cxa_throw_bad_array_new_length version Qt_5 not defined in file libQt5Xml.so.5 with link time reference
```

After training the project, I tried to export pcd by using ns-export in Google Colab I got the error message above. 

Need some help. Thanks.

**Comment by akristoffersen** [comment]
Hi, here is the current workaround from another issue: [link](https://github.com/nerfstudio-project/nerfstudio/issues/1121#issuecomment-1360501564)
