### ISSUE TITLE
[Colab] Qt5 in pymeshlab error

### ISSUE THREAD

**Issue by MarioAuditore** [nerfstudio-project/nerfstudio#1176]
**Describe the bug**
When I try to export the model as point cloud via
`!ns-export pointcloud --load-config outputs/data-nerfstudio-custom_data/nerfacto/2022-12-26_174349/config.yml --output-dir exports/pcd/ --num-points 1000000 --remove-outliers True --estimate-normals False --use-bounding-box True --bounding-box-min -1 -1 -1 --bounding-box-max 1 1 1`
or
`!ns-export poisson --load-config outputs/data-nerfstudio-custom_data/nerfacto/2022-12-26_174349/config.yml --output-dir exports/mesh/ --target-num-faces 50000 --num-pixels-per-side 2048 --normal-output-name normals --num-points 1000000 --remove-outliers True --use-bounding-box True --bounding-box-min -1 -1 -1 --bounding-box-max 1 1 1`

I get an error^
`Traceback (most recent call last):
  File "/usr/local/bin/ns-export", line 5, in <module>
    from scripts.exporter import entrypoint
  File "/usr/local/lib/python3.8/site-packages/scripts/exporter.py", line 20, in <module>
    from nerfstudio.exporter import texture_utils, tsdf_utils
  File "/usr/local/lib/python3.8/site-packages/nerfstudio/exporter/texture_utils.py", line 36, in <module>
    from nerfstudio.exporter.exporter_utils import Mesh
  File "/usr/local/lib/python3.8/site-packages/nerfstudio/exporter/exporter_utils.py", line 29, in <module>
    import pymeshlab
  File "/usr/local/lib/python3.8/site-packages/pymeshlab/__init__.py", line 11, in <module>
    from .pmeshlab import *
ImportError: /usr/local/lib/python3.8/site-packages/pymeshlab/lib/libmeshlab-common.so: symbol __cxa_throw_bad_array_new_length version Qt_5 not defined in file libQt5Xml.so.5 with link time reference`

**To Reproduce**
1. Upload poster data or custom images
2. Train model with normals enabled
`!ns-train nerfacto --viewer.websocket-port 7007 --pipeline.model.predict-normals True nerfstudio-data --data data/nerfstudio/$scene --downscale-factor 4 `
3. Attempt to export in Colab

**Expected behavior**
Export to mesh and creation of file with mesh

**Additional context**
Link to my copy of Colab: https://colab.research.google.com/drive/1q-pn8MVuKxt9XRfYqrntb31Mrw0-rNDC?usp=sharing

**Comment by akristoffersen** [comment]
hi, could you try running `!conda remove --force qt-main` after training and then try exporting? This was found to fix `ns-export` issues for others and should be updated with a PR soon.
