### ISSUE TITLE
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 

### ISSUE THREAD

**Issue by fegato** [nerfstudio-project/nerfstudio#1188]
I can't understand why this happens...

 Traceback (most recent call last):

  File "C:\Users\david\anaconda3\envs\nerfstudio\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\david\anaconda3\envs\nerfstudio\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\david\anaconda3\envs\nerfstudio\Scripts\ns-train.exe\__main__.py", line 7, in <module>
  File "C:\Users\david\anaconda3\envs\nerfstudio\lib\site-packages\scripts\train.py", line 248, in entrypoint
    main(
  File "C:\Users\david\anaconda3\envs\nerfstudio\lib\site-packages\scripts\train.py", line 232, in main
    config.save_config()
  File "C:\Users\david\anaconda3\envs\nerfstudio\lib\site-packages\nerfstudio\configs\experiment_config.py", line 120, in save_config
    base_dir.mkdir(parents=True, exist_ok=True)
  File "C:\Users\david\anaconda3\envs\nerfstudio\lib\pathlib.py", line 1288, in mkdir
    self._accessor.mkdir(self, mode)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'outputs\\C:\\Users\\david\\data\\nerfstudio\\newdata\\nerfacto\\2022-12-30_190240'

**Comment by fegato** [comment]
sorry I'm dumb... :)

**Comment by wtj-zhong** [comment]
did you solve this problem i have the same problem

**Comment by tancik** [comment]
Try using relative paths instead of absolute paths.
