### ISSUE TITLE
Image dimensions do not match those of the initialized video

### ISSUE THREAD

**Issue by mitming** [nerfstudio-project/nerfstudio#1242]
**Describe the bug**
 I trained a nerfacto on nerfstudio-posters_v3 dataset, when I tried to render the outputs into videos, the error happened.

**To Reproduce**
1. run training code `ns-train nerfacto --data data/nerfstudio/poster`
2. run render code `ns-render --load-config PATH_TO_CONFIG`

**Expected behavior**
I think there should be rendered videos.

**Screenshots**
```
[14:54:27] Auto image downscale factor of 2                                                 nerfstudio_dataparser.py:314
           Skipping 0 files in dataset split train.                                         nerfstudio_dataparser.py:165
           Skipping 0 files in dataset split test.                                          nerfstudio_dataparser.py:165
Setting up training dataset...
Caching all 204 images.
Setting up evaluation dataset...
Caching all 22 images.
Loading latest checkpoint from load_dir
✅ Done loading checkpoint from
outputs/data-nerfstudio-posters_v3/nerfacto/2023-01-17_142500/nerfstudio_models/step-000029999.ckpt
Creating trajectory video
🎥 Rendering 🎥 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% ? --:--
Traceback (most recent call last):
  File "/home/tiger/.local/bin/ns-render", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/tiger/code/nerfstudio/scripts/render.py", line 283, in entrypoint
    tyro.cli(RenderTrajectory).main()
  File "/home/tiger/code/nerfstudio/scripts/render.py", line 276, in main
    render_height=render_height,
  File "/home/tiger/code/nerfstudio/scripts/render.py", line 128, in _render_trajectory_video
    writer.add_image(render_image)
  File "/home/tiger/.local/lib/python3.7/site-packages/mediapy/__init__.py", line 1396, in add_image
    raise ValueError(f'Image dimensions {image.shape[:2]} do not match'
ValueError: Image dimensions (960, 540) do not match those of the initialized video (736, 952).
```

**Additional context**

**Comment by tancik** [comment]
How did you create the camera path? Did you use the viewer? What version are you running?

**Comment by machenmusik** [comment]
Looks like the issue stems from https://github.com/nerfstudio-project/nerfstudio/blob/main/scripts/render.py#L245
With spiral trajectory, looks like the render width and height (image dimensions) aren't known yet, so defaults are used.

**Comment by machenmusik** [comment]
#1245 should fix this.
