### ISSUE TITLE
depth-nerfacto AssertionError

### ISSUE THREAD

**Issue by LownyCGI** [nerfstudio-project/nerfstudio#1243]
Error when running command `ns-train depth-nerfacto --data data/office06 --pipeline.model.predict-normals True`

![image](https://user-images.githubusercontent.com/36165420/212884995-962b5e37-e697-4ba3-98c5-87177434748f.png)

**Comment by tancik** [comment]
Can you post the entire error.

**Comment by LownyCGI** [comment]
![Screenshot_20230117_224252](https://user-images.githubusercontent.com/36165420/212996788-b98beb21-ef01-4e85-85f3-87e05e5a18d5.jpg)

**Comment by tancik** [comment]
It looks like your dataset doesn't point to any depth data. They should be included in the `transforms.json` - https://docs.nerf.studio/en/latest/quickstart/data_conventions.html#depth-images

**Comment by tancik** [comment]
Closing, feel free to reopen if it is still and issue.

**Comment by colin-de** [comment]
I got an error when evaluating the depth-nerfacto
```
$ ns-eval --load-config outputs/scene1_50_depth_nf/depth-nerfacto/2023-05-24_190752/config.yml 
[19:15:51] Auto image downscale factor of 1                                                 nerfstudio_dataparser.py:336
           Skipping 0 files in dataset split train.                                         nerfstudio_dataparser.py:163
           Skipping 0 files in dataset split test.                                          nerfstudio_dataparser.py:163
Setting up training dataset...
Caching all 45 images.
Setting up evaluation dataset...
Caching all 5 images.
Loading latest checkpoint from load_dir
✅ Done loading checkpoint from 
outputs/scene1_50_depth_nf/depth-nerfacto/2023-05-24_190752/nerfstudio_models/step-000029999.ckpt
Traceback (most recent call last):
  File "/home/workstationpatrick/anaconda3/envs/nerfstudio/bin/ns-eval", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/workstationpatrick/code/nerfstudio/nerfstudio/scripts/eval.py", line 61, in entrypoint
    tyro.cli(ComputePSNR).main()
  File "/home/workstationpatrick/code/nerfstudio/nerfstudio/scripts/eval.py", line 44, in main
    metrics_dict = pipeline.get_average_eval_image_metrics()
  File "/home/workstationpatrick/code/nerfstudio/nerfstudio/utils/profiler.py", line 127, in inner
    out = func(*args, **kwargs)
  File "/home/workstationpatrick/code/nerfstudio/nerfstudio/pipelines/base_pipeline.py", line 360, in get_average_eval_image_metrics
    metrics_dict, _ = self.model.get_image_metrics_and_images(outputs, batch)
  File "/home/workstationpatrick/code/nerfstudio/nerfstudio/models/depth_nerfacto.py", line 110, in get_image_metrics_and_images
    ground_truth_depth = batch["depth_image"]
KeyError: 'depth_image'
```

I've provided depth path in transform.json like this

```        {
            "file_path": "images/frame_00048.png",
            "transform_matrix": [
                [
                    -0.06754559364620445,
                    -0.9938039039739098,
                    -0.08826886894708329,
                    2.01663763900657
                ],
                [
                    0.9912304365922343,
                    -0.0769146597141719,
                    0.10745397477162737,
                    -0.17035738301746994
                ],
                [
                    -0.11357734964397706,
                    -0.08023674698832625,
                    0.9902839239736154,
                    3.206818223516781
                ],
                [
                    0.0,
                    0.0,
                    0.0,
                    1.0
                ]
            ],
            "colmap_im_id": 48,
            "depth_file_path": "depth/frame_00048.png"
        },
```
