### ISSUE TITLE
No module named 'scripts'

### ISSUE THREAD

**Issue by Scolymus** [nerfstudio-project/nerfstudio#1292]
**Describe the bug**
I'm running this python script (let's call it myscript.py):

```
import subprocess
subprocess.run(["ns-process-data", "video", "--data", save_path_video, "--output-dir", save_path_colmap])
```

where `save_path_video` and `save_path_colmap` are the pathnames for the original mp4 file and the folder where colmap will print the cloud. However, I'm getting the following error:

```
Traceback (most recent call last):
  File "/home/user/.local/bin/ns-process-data", line 5, in <module>
  from scripts.process_data import entrypoint
  ModuleNotFoundError: No module named 'scripts'
```

What's happening? I run my app within a docker, which starts by (I simplified it):

```
FROM dromni/nerfstudio:0.1.15

USER root:root

# Variable arguments
WORKDIR /code
COPY ./myscript.py /code/app/src/myscript.py

#Start the app
CMD python3 /app/src/myscript.py
```

I understand that this is sufficient to install the nerfstudio within the docker. Should I change the docker construction?

**To Reproduce**
Run the docker.

**Expected behavior**
Module script should be found

**Screenshots**

**Additional context**

**Comment by tancik** [comment]
Hmm, it seems like `nerfstudio` wasn't installed. I'm not familiar with Docker, so I'm not sure how it handles installation.

**Comment by Zunhammer** [comment]
The problem likely is caused by changing the user to root and/or chaning the workdir. The docker image from the dromni repository is meant to be used as a final solution and all pip packages are installed in the user space inside the image. If you want to modify code of nerfstudio or add something to the docker you preferably should use the Dockerfile in the nerfstudio repository. Also, if the only change you do is to add a file there is no need to rebuild the image, simply mount the file and overwrite the entrypoint instead.

**Comment by Scolymus** [comment]
yep, it's working. It was due a pip install I was doing afterwards. It was automatically unninstalling nerfstudio to install diferent versions of packages nerfstudio is based, and later it wasn't installing nerfstudio again due to version incompatibility. 

ns-process-data works fine now. However, ns-train is not. It seems I'm facing same problem as this user https://github.com/nerfstudio-project/nerfstudio/issues/1297

Could it be because torch is instaled for cuda 11.6 (+116) but CUDA in Dockerfile is 11.7? 

I'm running on T4, and the traceback is:

```
2023-01-31T16:31:23.349775782Z Traceback (most recent call last):
2023-01-31T16:31:23.349802344Z   File "/home/user/.local/bin/ns-train", line 5, in <module>
2023-01-31T16:31:23.349838440Z     from scripts.train import entrypoint
2023-01-31T16:31:23.349858032Z   File "/home/user/nerfstudio/scripts/train.py", line 49, in <module>
2023-01-31T16:31:23.349910737Z     from nerfstudio.configs.method_configs import AnnotatedBaseConfigUnion
2023-01-31T16:31:23.349918024Z   File "/home/user/nerfstudio/nerfstudio/configs/method_configs.py", line 47, in <module>
2023-01-31T16:31:23.349993392Z     from nerfstudio.field_components.temporal_distortions import TemporalDistortionKind
2023-01-31T16:31:23.350002202Z   File "/home/user/nerfstudio/nerfstudio/field_components/__init__.py", line 17, in <module>
2023-01-31T16:31:23.350056206Z     from .encodings import Encoding, ScalingAndOffset
2023-01-31T16:31:23.350062750Z   File "/home/user/nerfstudio/nerfstudio/field_components/encodings.py", line 34, in <module>
2023-01-31T16:31:23.350136700Z     import tinycudann as tcnn
2023-01-31T16:31:23.350144957Z   File "/home/user/.local/lib/python3.10/site-packages/tinycudann/__init__.py", line 9, in <module>
2023-01-31T16:31:23.350193661Z     from tinycudann.modules import free_temporary_memory, NetworkWithInputEncoding, Network, Encoding
2023-01-31T16:31:23.350199765Z   File "/home/user/.local/lib/python3.10/site-packages/tinycudann/modules.py", line 35, in <module>
2023-01-31T16:31:23.350270164Z     raise EnvironmentError(f"Could not find compatible tinycudann extension for compute capability {system_compute_capability}.")
2023-01-31T16:31:23.350276006Z OSError: Could not find compatible tinycudann extension for compute capability 75.
```

**Comment by tancik** [comment]
@Scolymus It looks like tinycudann wasn't installed correctly.

**Comment by Scolymus** [comment]
ok, it works now. I use this trick https://github.com/nerfstudio-project/nerfstudio/issues/1056#issuecomment-1410879632
