### ISSUE TITLE
Error when running docker container

### ISSUE THREAD

**Issue by GrapeApe230** [nerfstudio-project/nerfstudio#1297]
**Describe the bug**
When using the docker container interactively it returns 

[15:01:14] ❌ Completion script generation failed: ['ns-train', '--tyro-print-completion', 'bash']        install.py:107
           Traceback (most recent call last):                                                             install.py:111
             File "/home/user/.local/bin/ns-train", line 5, in <module>
               from scripts.train import entrypoint
             File "/home/user/nerfstudio/scripts/train.py", line 49, in <module>
               from nerfstudio.configs.method_configs import AnnotatedBaseConfigUnion
             File "/home/user/nerfstudio/nerfstudio/configs/method_configs.py", line 47, in <module>
               from nerfstudio.field_components.temporal_distortions import TemporalDistortionKind
             File "/home/user/nerfstudio/nerfstudio/field_components/__init__.py", line 17, in <module>
               from .encodings import Encoding, ScalingAndOffset
             File "/home/user/nerfstudio/nerfstudio/field_components/encodings.py", line 34, in <module>
               import tinycudann as tcnn
             File "/home/user/.local/lib/python3.10/site-packages/tinycudann/__init__.py", line 9, in
           <module>
               from tinycudann.modules import free_temporary_memory, NetworkWithInputEncoding, Network,
           Encoding
             File "/home/user/.local/lib/python3.10/site-packages/tinycudann/modules.py", line 35, in
           <module>
               raise EnvironmentError(f"Could not find compatible tinycudann extension for compute
           capability {system_compute_capability}.")
           OSError: Could not find compatible tinycudann extension for compute capability 75.

**To Reproduce**
$ docker run --gpus all -v ~/workspace:/workspace/ -v /srv/nerfstudio/.cache/:/home/user/.cache/ -p 7007:7007 --rm -it dromni/nerfstudio:0.1.16

**Expected behavior**
--

**Screenshots**
![image](https://user-images.githubusercontent.com/39072577/215118856-4d8ba2dd-eb8d-4c6d-85f8-57f7001cd4c2.png)

**Additional context**
Running on
Headless Ubuntu 22.04
Nvidia Driver Version: 525.78.01 
CUDA Version: 12.0
Quadro RTX 5000

**Comment by XinyueZ** [comment]
same issue , either run or build from repo.

**Comment by Zunhammer** [comment]
Please try again with dromni/nerfstudio:0.1.16 which was rebuilt. Also, please use global paths, no realtives!
