### ISSUE TITLE
Permission denied when downloading data in docker container

### ISSUE THREAD

**Issue by Alpe6825** [nerfstudio-project/nerfstudio#1309]
I try to run `ns-download-data nerfstudio --capture-name=poster` inside the docker container but get the following error:

`Traceback (most recent call last):
  File "/home/user/.local/bin/ns-download-data", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/user/nerfstudio/scripts/downloads/download_data.py", line 321, in entrypoint
    main(tyro.cli(Commands))
  File "/home/user/nerfstudio/scripts/downloads/download_data.py", line 315, in main
    dataset.download(dataset.save_dir)
  File "/home/user/nerfstudio/scripts/downloads/download_data.py", line 187, in download
    download_capture_name(save_dir, "nerfstudio", self.capture_name, capture_name_to_file_id=nerfstudio_file_ids)
  File "/home/user/nerfstudio/scripts/downloads/download_data.py", line 155, in download_capture_name
    gdown.download(url, output=str(download_path))
  File "/home/user/.local/lib/python3.10/site-packages/gdown/download.py", line 136, in download
    sess, cookies_file = _get_session(
  File "/home/user/.local/lib/python3.10/site-packages/gdown/download.py", line 70, in _get_session
    os.makedirs(cache_dir)
  File "/usr/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/user/.cache/gdown'
`

**Comment by Zunhammer** [comment]
Please mount a folder and use the "--save-dir" flag to choose a mounted folder.

**Comment by yj-uh** [comment]
Below script worked for me.
```bash
mkdir datasets .cache
chmod 777 datasets .cache
docker run --gpus all -v `pwd`/datasets:/datasets -v workspace:/workspace/ -v `pwd`/.cache:/home/user/.cache/ -p 7007:7007 --rm -it \
            dromni/nerfstudio:0.1.16 \
            ns-download-data nerfstudio --save-dir /datasets --capture-name=poster
```

**Comment by Alpe6825** [comment]
thx for the hints. With version 0.1.19 it works by default.
