### ISSUE TITLE
"OSError: Unknown compute capability. Ensure PyTorch with CUDA support is installed"

### ISSUE THREAD

**Issue by rockywind** [nerfstudio-project/nerfstudio#1314]
**Describe the bug**
When I run the script bellow,
````
python scripts/render_my.py \
--load-config outputs/data-nerfstudio-posters_v3/nerfacto/2023-01-31_151351/config.yml \
--traj spiral \
--output-path renders/render_output_poseter_v3_nerffacto.mp4 \
--output-format images
````
I met the error below
````
Traceback (most recent call last):
  File "scripts/render_my.py", line 331, in <module>
    entrypoint()
  File "scripts/render_my.py", line 327, in entrypoint
    tyro.cli(RenderTrajectory).main()
  File "scripts/render_my.py", line 277, in main
    _, pipeline, _ = eval_setup(
  File "/DATA2/xiaoquan.wang/nerfstudio/nerfstudio/utils/eval_utils.py", line 87, in eval_setup
    config = yaml.load(config_path.read_text(), Loader=yaml.Loader)
  File "/home/zongmu/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/home/zongmu/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/yaml/constructor.py", line 51, in get_single_data
    return self.construct_document(node)
  File "/home/zongmu/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/yaml/constructor.py", line 60, in construct_document
    for dummy in generator:
  File "/home/zongmu/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/yaml/constructor.py", line 620, in construct_python_object
    state = self.construct_mapping(node, deep=deep)
  File "/home/zongmu/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/yaml/constructor.py", line 218, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "/home/zongmu/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/yaml/constructor.py", line 143, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/home/zongmu/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/yaml/constructor.py", line 105, in construct_object
    data = next(generator)
  File "/home/zongmu/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/yaml/constructor.py", line 617, in construct_python_object
    instance = self.make_python_instance(suffix, node, newobj=True)
  File "/home/zongmu/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/yaml/constructor.py", line 722, in make_python_instance
    return super(UnsafeConstructor, self).make_python_instance(
  File "/home/zongmu/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/yaml/constructor.py", line 585, in make_python_instance
    cls = self.find_python_name(suffix, node.start_mark)
  File "/home/zongmu/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/yaml/constructor.py", line 719, in find_python_name
    return super(UnsafeConstructor, self).find_python_name(name, mark, unsafe=True)
  File "/home/zongmu/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/yaml/constructor.py", line 551, in find_python_name
    __import__(module_name)
  File "/DATA2/xiaoquan.wang/nerfstudio/nerfstudio/models/nerfacto.py", line 38, in <module>
    from nerfstudio.field_components.field_heads import FieldHeadNames
  File "/DATA2/xiaoquan.wang/nerfstudio/nerfstudio/field_components/__init__.py", line 17, in <module>
    from .encodings import Encoding, ScalingAndOffset
  File "/DATA2/xiaoquan.wang/nerfstudio/nerfstudio/field_components/encodings.py", line 34, in <module>
    import tinycudann as tcnn
  File "/home/zongmu/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/tinycudann/__init__.py", line 9, in <module>
    from tinycudann.modules import free_temporary_memory, NetworkWithInputEncoding, Network, Encoding
  File "/home/zongmu/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/tinycudann/modules.py", line 16, in <module>
    raise EnvironmentError("Unknown compute capability. Ensure PyTorch with CUDA support is installed.")
OSError: Unknown compute capability. Ensure PyTorch with CUDA support is installed.
````
I modified the render.py for changing the GPU ID.
![image](https://user-images.githubusercontent.com/14838781/215714743-fc199a20-090f-42de-9ceb-8f7d70953b68.png)

But, when I set the "**os.environ["CUDA_VISIBLE_DEVICES"] = "0"**", It's OK!

**Comment by tancik** [comment]
Do you have different graphics card generations? Sounds like pytorch was only installed for support for one of them.

**Comment by rockywind** [comment]
Sorry, I found the another graphic card is disable!
