### ISSUE TITLE
"gpu_partition - [CreateCommunicator] warn:failed get env VCUDA_PORT   "

### ISSUE THREAD

**Issue by rockywind** [nerfstudio-project/nerfstudio#1318]
Hi,
When I run the comman of "ns-install-cli", I met the error below.
````
[17:33:55] ❌ Completion script generation failed: ['ns-train', '--tyro-print-completion', 'bash']        install.py:107
           **gpu_partition - [CreateCommunicator] warn:failed get env VCUDA_PORT                            install.py:109**
           gpu_partition - [BackTraceStack] warn:/usr/local/lib/aistation/libgpu_partition.so(+0x318bc)                 
           [0x7f67f025a8bc]                                                                                             
           gpu_partition - [BackTraceStack]                                                                             
           warn:/usr/local/lib/aistation/libgpu_partition.so(cuDevicePrimaryCtxRetain+0x254)                            
           [0x7f67f025bdd4]                                                                                             
           gpu_partition - [BackTraceStack]                                                                             
           warn:/opt/conda/envs/nerfstudio/lib/python3.8/site-packages/tinycudann_bindings_80/_C.cpython-               
           38-x86_64-linux-gnu.so(+0x6d7a32) [0x7f663405da32]                                                           
           gpu_partition - [BackTraceStack]                                                                             
           warn:/opt/conda/envs/nerfstudio/lib/python3.8/site-packages/tinycudann_bindings_80/_C.cpython-               
           38-x86_64-linux-gnu.so(+0x6d7bf7) [0x7f663405dbf7]                                                           
           gpu_partition - [BackTraceStack]                                                                             
           warn:/opt/conda/envs/nerfstudio/lib/python3.8/site-packages/tinycudann_bindings_80/_C.cpython-               
           38-x86_64-linux-gnu.so(+0x6db578) [0x7f6634061578]                                                           
                                                                                                                        
Traceback (most recent call last):
  File "/opt/conda/envs/nerfstudio/bin/ns-install-cli", line 8, in <module>
    sys.exit(entrypoint())
  File "/rockywin.wang/NeRF/nerfstudio/scripts/completions/install.py", line 282, in entrypoint
    tyro.cli(main, description=__doc__)
  File "/opt/conda/envs/nerfstudio/lib/python3.8/site-packages/tyro/_cli.py", line 124, in cli
    _cli_impl(
  File "/opt/conda/envs/nerfstudio/lib/python3.8/site-packages/tyro/_cli.py", line 325, in _cli_impl
    out, consumed_keywords = _calling.call_from_args(
  File "/opt/conda/envs/nerfstudio/lib/python3.8/site-packages/tyro/_calling.py", line 188, in call_from_args
    return unwrapped_f(*positional_args, **kwargs), consumed_keywords  # type: ignore
  File "/rockywin.wang/NeRF/nerfstudio/scripts/completions/install.py", line 251, in main
    completion_paths = list(
  File "/opt/conda/envs/nerfstudio/lib/python3.8/concurrent/futures/_base.py", line 619, in result_iterator
    yield fs.pop().result()
  File "/opt/conda/envs/nerfstudio/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/opt/conda/envs/nerfstudio/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/opt/conda/envs/nerfstudio/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/rockywin.wang/NeRF/nerfstudio/scripts/completions/install.py", line 253, in <lambda>
    lambda path_or_entrypoint_and_shell: _generate_completion(
  File "/rockywin.wang/NeRF/nerfstudio/scripts/completions/install.py", line 112, in _generate_completion
    raise e
  File "/rockywin.wang/NeRF/nerfstudio/scripts/completions/install.py", line 99, in _generate_completion
    new = subprocess.run(
  File "/opt/conda/envs/nerfstudio/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ns-train', '--tyro-print-completio1.0.4 in /opt/conda/envs/nerfstudio/lib/python3.8/site-pa
````

**Comment by yigetan0909** [comment]
Hi!
I have a problem similar to yours. Have you solved this problem? How did you solve it?
