### ISSUE TITLE
custom model training not working

### ISSUE THREAD

**Issue by Sinicyn78** [nerfstudio-project/nerfstudio#1351]
model poster is working.
custom model training is not working...

Traceback (most recent call last):
  File "C:\Users\Sinicyn\anaconda3\envs\nerfstudio\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Sinicyn\anaconda3\envs\nerfstudio\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Sinicyn\anaconda3\envs\nerfstudio\Scripts\ns-train.exe\__main__.py", line 7, in <module>
  File "C:\Users\Sinicyn\anaconda3\envs\nerfstudio\lib\site-packages\scripts\train.py", line 247, in entrypoint
    main(
  File "C:\Users\Sinicyn\anaconda3\envs\nerfstudio\lib\site-packages\scripts\train.py", line 231, in main
    config.save_config()
  File "C:\Users\Sinicyn\anaconda3\envs\nerfstudio\lib\site-packages\nerfstudio\configs\experiment_config.py", line 122, in save_config
    base_dir.mkdir(parents=True, exist_ok=True)
  File "C:\Users\Sinicyn\anaconda3\envs\nerfstudio\lib\pathlib.py", line 1288, in mkdir
    self._accessor.mkdir(self, mode)
OSError: [WinError 123] Синтаксическая ошибка в имени файла, имени папки или метке тома: 'outputs\\C:\\Users\\Sinicyn\\data\\nerfstudio\\ar\\out\\nerfacto\\2023-02-04_200838'

**Comment by tancik** [comment]
Don't use an absolute path (with C:\), use a relative path. Ie, `--data data\nerfstudio\ar\out\nerfacto\2023-02-04_200838`

**Comment by Sinicyn78** [comment]
> Don't use an absolute path (with C:), use a relative path. Ie, `--data data\nerfstudio\ar\out\nerfacto\2023-02-04_200838`

Thank you very much! Helped.
