### ISSUE TITLE
"FileNotFoundError: [Errno 2] No such file or directory: 'data/own_data/data_pk_230_exhau_nerfplayer/extra.json'"

### ISSUE THREAD

**Issue by rockywind** [nerfstudio-project/nerfstudio#1364]
Hi,
When I trained the nerfplayer model, I met the error below!

````
[11:46:15] Saving config to:                                                                    experiment_config.py:124
           outputs/data_pk2_230_2gpu_lr*2_ex_nerfplayer/nerfplayer-nerfacto/2023-02-07_114615/c                         
           onfig.yml                                                                                                    
[11:46:22] Saving checkpoints to:                                                                         trainer.py:122
           outputs/data_pk2_230_2gpu_lr*2_ex_nerfplayer/nerfplayer-nerfacto/2023-02-07_114615/nerfstudio_               
           models                                                                                                       
[11:46:22] Saving checkpoints to:                                                                         trainer.py:122
           outputs/data_pk2_230_2gpu_lr*2_ex_nerfplayer/nerfplayer-nerfacto/2023-02-07_114615/nerfstudio_               
           models                                                                                                       
logging events to: outputs/data_pk2_230_2gpu_lr*2_ex_nerfplayer/nerfplayer-nerfacto/2023-02-07_114615
Traceback (most recent call last):
  File "/home/zongmu/anaconda3/envs/nerfstudio/bin/ns-train", line 8, in <module>
    sys.exit(entrypoint())
  File "/DATA2/xiaoquan.wang/nerfstudio/scripts/train.py", line 247, in entrypoint
    main(
  File "/DATA2/xiaoquan.wang/nerfstudio/scripts/train.py", line 233, in main
    launch(
  File "/DATA2/xiaoquan.wang/nerfstudio/scripts/train.py", line 205, in launch
    process_context.join()
  File "/home/zongmu/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/zongmu/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/DATA2/xiaoquan.wang/nerfstudio/scripts/train.py", line 140, in _distributed_worker
    output = main_func(local_rank, world_size, config, global_rank)
  File "/DATA2/xiaoquan.wang/nerfstudio/scripts/train.py", line 86, in train_loop
    trainer.setup()
  File "/DATA2/xiaoquan.wang/nerfstudio/nerfstudio/engine/trainer.py", line 147, in setup
    self.pipeline = self.config.pipeline.setup(
  File "/DATA2/xiaoquan.wang/nerfstudio/nerfstudio/configs/base_config.py", line 59, in setup
    return self._target(self, **kwargs)
  File "/DATA2/xiaoquan.wang/nerfstudio/nerfstudio/pipelines/base_pipeline.py", line 222, in __init__
    self.datamanager: VanillaDataManager = config.datamanager.setup(
  File "/DATA2/xiaoquan.wang/nerfstudio/nerfstudio/configs/base_config.py", line 59, in setup
    return self._target(self, **kwargs)
  File "/DATA2/xiaoquan.wang/nerfstudio/nerfstudio/data/datamanagers/base_datamanager.py", line 322, in __init__
    self.dataparser = self.config.dataparser.setup()
  File "/DATA2/xiaoquan.wang/nerfstudio/nerfstudio/configs/base_config.py", line 59, in setup
    return self._target(self, **kwargs)
  File "/DATA2/xiaoquan.wang/nerfstudio/nerfstudio/data/dataparsers/dycheck_dataparser.py", line 213, in __init__
    extra_dict = load_from_json(extra_path)
  File "/DATA2/xiaoquan.wang/nerfstudio/nerfstudio/utils/io.py", line 30, in load_from_json
    with open(filename, encoding="UTF-8") as file:
FileNotFoundError: [Errno 2] No such file or directory: 'data/own_data/data_pk_230_exhau_nerfplayer/extra.json'
````

This the train script.
````
ns-train nerfplayer-nerfacto  --viewer.websocket-port=7008 \
                --machine.num-gpus 2 \
                --optimizers.fields.optimizer.lr 0.02 \
                --experiment-name data_pk2_230_2gpu_lr*2_ex_nerfplayer \
                --data data/own_data/data_pk_230_exhau_nerfplayer \
                --vis tensorboard 
````

**Comment by tancik** [comment]
Can you try running without the `*` in the experiment name.

**Comment by rockywind** [comment]
Hi,
The error is still exists when I remove the `*`.
  ````
export CUDA_VISIBLE_DEVICES=1,2
ns-train nerfplayer-nerfacto  --viewer.websocket-port=7008 \
                --machine.num-gpus 2 \
                --experiment-name data_pk2_230_2gpu_ex_nerfplayer \
                --data data/own_data/data_pk_230_exhau_nerfplayer \
                --vis tensorboard 
  ````

**Comment by tancik** [comment]
what do you get if you run `ls data/own_data/data_pk_230_exhau_nerfplayer`?
How did you process the data?

**Comment by rockywind** [comment]
Hi,
This is the training data structure.
![image](https://user-images.githubusercontent.com/14838781/217197505-07445cd8-b907-4c2e-b104-0b6bea71d01d.png)
This is the data process scripts.
````
ns-process-data images \
--data /DATA2/xiaoquan.wang/nerfstudio/data/own_data/pk2_230/ \
--output_dir  /DATA2/xiaoquan.wang/nerfstudio/data/own_data/data_pk_230_exhau/ \
--camera-type fisheye \
--matching-method exhaustive \
--num-downscales 1 \
--sfm-tool hloc
````

**Comment by tancik** [comment]
Oh, I see. You are running `nerfplayer-nerfacto` not `nerfacto`. Nerfplayer uses a different dataset format.
Can you try 
```
ns-train nerfacto  --viewer.websocket-port=7008 \
              --machine.num-gpus 2 \
              --experiment-name data_pk2_230_2gpu_ex_nerfplayer \
              --data data/own_data/data_pk_230_exhau_nerfplayer \
              --vis tensorboard 
```

**Comment by rockywind** [comment]
Hi,
 I can run the ````ns-train nerfacto ```` successfully,
but, I can't run ````nerfplayer-nerfacto ````,
so I want to know how to run it.

**Comment by tancik** [comment]
`nerfplayer-nerfacto` require data with time. Some data you can use is the iphone subset from this dataset - https://hangg7.com/dycheck/

**Comment by rockywind** [comment]
Hi,

- Are there any tutorial for me to make custome data for traing ````nerfplayer-nerfacto ````.

I can capture data with time using our collection car.

- Can I train the ````nerfplayer-nerfacto ```` model with nuscenes dataset?

**Comment by tancik** [comment]
`nerfplayer` is a recently added model so no tutorial exists yet. If you happen to get the data up and running, feel free to submit at pr ;)

**Comment by rockywind** [comment]
Thanks
I will try it in nuscene dataset and our own dataset.

**Comment by JRopes** [comment]
I would also be very interested in a tutorial on the new Dynamic NeRFs and how to use it with custom datasets!

**Comment by wuhongsheng** [comment]
nerfplayer Currently only [DyCheck](https://hangg7.com/dycheck/) dataset is supported.
