### ISSUE TITLE
Cannot reload CheckPoint / Model - Nerfacto

### ISSUE THREAD

**Issue by MarMar54321** [nerfstudio-project/nerfstudio#1436]
**Describe the bug**
It looks like when i try to reload a model from that i have created a render ( Video or a Mesh ) i cannot reload the model i receive the following error when i try to load the model:

ns-train nerfacto --data data/<data>/ --load-dir outputs/<data>/nerfacto/20
23-02-15_200144/nerfstudio_models/ --viewer.start-train False

Loading latest checkpoint from load_dir
Printing profiling stats, from longest to shortest duration in seconds
Traceback (most recent call last):
  File "/home/user/.local/bin/ns-train", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/user/nerfstudio/scripts/train.py", line 247, in entrypoint
    main(
  File "/home/user/nerfstudio/scripts/train.py", line 233, in main
    launch(
  File "/home/user/nerfstudio/scripts/train.py", line 172, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "/home/user/nerfstudio/scripts/train.py", line 86, in train_loop
    trainer.setup()
  File "/home/user/nerfstudio/nerfstudio/engine/trainer.py", line 153, in setup
    self._load_checkpoint()
  File "/home/user/nerfstudio/nerfstudio/engine/trainer.py", line 325, in _load_checkpoint
    self.optimizers.load_optimizers(loaded_state["optimizers"])
  File "/home/user/nerfstudio/nerfstudio/engine/optimizers.py", line 156, in load_optimizers
    self.optimizers[k].load_state_dict(v)
  File "/home/user/.local/lib/python3.10/site-packages/torch/optim/optimizer.py", line 171, in load_state_dict
    raise ValueError("loaded state dict contains a parameter group "
ValueError: loaded state dict contains a parameter group that doesn't match the size of optimizer's group

**To Reproduce**
1. Create a Nerf
2. Render
3. Add Camera ( a vew )
4. Render - for the export command Copy Command
5. render video out
6. try to reload the Checkpoint again 

**Expected behavior**
Reloading the Checkpoint so thta i have not to always have to recreate a new Nerf if i want to make changes.

**Screenshots**

**Additional context**

**Comment by MarMar54321** [comment]
It looks like this is only the case if i use the following option "--pipeline.model.predict-normals True" for generating the normals. Other Checkpoints without this options seem to work fine.

**Comment by tancik** [comment]
Does it work if you add `--pipeline.model.predict-normals True` to your command when you try to reload a checkpoint?

**Comment by MarMar54321** [comment]
That does fix the issue. In version 0.1.16 this was not required. Anyway, Thank You for the quick support!

**Comment by machenmusik** [comment]
(This may be worth a documentation change to note that loading/viewing prior checkpoints will fail unless predict-normal settings match.)
