### ISSUE TITLE
nerfstudio/nerfstudio/data/datasets/depth_dataset.py", line 36, in __init__  assert ( AssertionError")

### ISSUE THREAD

**Issue by rockywind** [nerfstudio-project/nerfstudio#1440]
Hi,
This is my train script.
````
ns-train depth-nerfacto --data data/nerfstudio/poster/posters_v3 --vis tensorboard
````
This was the detailed error log.
````
Printing profiling stats, from longest to shortest duration in seconds
Traceback (most recent call last):
  File "/opt/conda/envs/nerfstudio/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/envs/nerfstudio/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/.vscode-server/extensions/ms-python.python-2022.18.2/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/root/.vscode-server/extensions/ms-python.python-2022.18.2/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/root/.vscode-server/extensions/ms-python.python-2022.18.2/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/root/.vscode-server/extensions/ms-python.python-2022.18.2/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/root/.vscode-server/extensions/ms-python.python-2022.18.2/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/root/.vscode-server/extensions/ms-python.python-2022.18.2/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/rockywin.wang/NeRF/nerfstudio/scripts/train_depth.py", line 264, in <module>
    entrypoint()
  File "/rockywin.wang/NeRF/nerfstudio/scripts/train_depth.py", line 255, in entrypoint
    main(
  File "/rockywin.wang/NeRF/nerfstudio/scripts/train_depth.py", line 241, in main
    launch(
  File "/rockywin.wang/NeRF/nerfstudio/scripts/train_depth.py", line 180, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "/rockywin.wang/NeRF/nerfstudio/scripts/train_depth.py", line 94, in train_loop
    trainer.setup()
  File "/rockywin.wang/NeRF/nerfstudio/nerfstudio/engine/trainer.py", line 148, in setup
    self.pipeline = self.config.pipeline.setup(
  File "/rockywin.wang/NeRF/nerfstudio/nerfstudio/configs/base_config.py", line 59, in setup
    return self._target(self, **kwargs)
  File "/rockywin.wang/NeRF/nerfstudio/nerfstudio/pipelines/base_pipeline.py", line 222, in __init__
    self.datamanager: VanillaDataManager = config.datamanager.setup(
  File "/rockywin.wang/NeRF/nerfstudio/nerfstudio/configs/base_config.py", line 59, in setup
    return self._target(self, **kwargs)
  File "/rockywin.wang/NeRF/nerfstudio/nerfstudio/data/datamanagers/base_datamanager.py", line 327, in __init__
    self.train_dataset = self.create_train_dataset()
  File "/rockywin.wang/NeRF/nerfstudio/nerfstudio/data/datamanagers/depth_datamanager.py", line 41, in create_train_dataset
    return DepthDataset(
  File "/rockywin.wang/NeRF/nerfstudio/nerfstudio/data/datasets/depth_dataset.py", line 36, in __init__
    assert (
AssertionError
````
I have synchronized image and sparse point cloud.
I don't know how to generate the depth map from synchronized point cloud.

**Comment by tancik** [comment]
We don't currently have a pipeline for that. The dataset must be created manually.

**Comment by rockywind** [comment]
Hi, @tancik 
how can I generate the depth from the point cloud manually?

**Comment by tancik** [comment]
There is no general way to do this, it will depend on the format of the data. But at a high level, for each camera, you want to project the point cloud points back into the camera frame and record there distances. If multiple point project to the same pixel, you will probably want to take the min distance.

**Comment by rockywind** [comment]
Thanks, I have a try.
