### ISSUE TITLE
Fail to install ns-install-cli

### ISSUE THREAD

**Issue by XinyangHan** [nerfstudio-project/nerfstudio#1449]
After installing other Prerequisites, I started to install ns-install-cli. But run into this error:

[23:03:38] 🤷 .zshrc not found, skipping.                                                                 install.py:210
           🔍 Found .bashrc!                                                                              install.py:212
           ✔ Wrote new completion to                                                                      install.py:117
           /home/xinyang/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/scripts/completions/bash/               
           _ns-dev-test!                                                                                                
           ✔ Wrote new completion to                                                                      install.py:117
           /home/xinyang/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/scripts/completions/bash/               
           _ns-install-cli!                                                                                             
[23:03:40] ✔ Wrote new completion to                                                                      install.py:117
           /home/xinyang/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/scripts/completions/bash/               
           _ns-process-data!                                                                                            
[23:03:41] ✔ Wrote new completion to                                                                      install.py:117
           /home/xinyang/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/scripts/completions/bash/               
           _ns-download-data!                                                                                           
[23:03:44] ✔ Wrote new completion to                                                                      install.py:117
           /home/xinyang/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/scripts/completions/bash/               
           _ns-eval!                                                                                                    
           ✔ Wrote new completion to                                                                      install.py:117
           /home/xinyang/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/scripts/completions/bash/               
           _ns-render!                                                                                                  
           ❌ Completion script generation failed: ['ns-train', '--tyro-print-completion', 'bash']        install.py:107
           Traceback (most recent call last):                                                             install.py:111
             File "/home/xinyang/miniconda3/envs/nerfstudio/bin/ns-train", line 5, in <module>                          
               from scripts.train import entrypoint                                                                     
             File                                                                                                       
           "/home/xinyang/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/scripts/train.py", line                
           49, in <module>                                                                                              
               from nerfstudio.configs.method_configs import AnnotatedBaseConfigUnion                                   
             File                                                                                                       
           "/home/xinyang/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/configs/metho               
           d_configs.py", line 49, in <module>                                                                          
               from nerfstudio.models.depth_nerfacto import DepthNerfactoModelConfig                                    
             File                                                                                                       
           "/home/xinyang/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/models/depth_               
           nerfacto.py", line 28, in <module>                                                                           
               from nerfstudio.models.nerfacto import NerfactoModel, NerfactoModelConfig                                
             File                                                                                                       
           "/home/xinyang/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/models/nerfac               
           to.py", line 39, in <module>                                                                                 
               from nerfstudio.field_components.spatial_distortions import SceneContraction                             
             File                                                                                                       
           "/home/xinyang/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/field_compone               
           nts/spatial_distortions.py", line 20, in <module>                                                            
               from functorch import jacrev, vmap                                                                       
             File                                                                                                       
           "/home/xinyang/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/functorch/__init__.py",                
           line 13, in <module>                                                                                         
               from . import _C                                                                                         
           ImportError:                                                                                                 
           /home/xinyang/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/functorch/../torch/lib/li               
           btorch_cuda_cpp.so: undefined symbol: _ZTIN4c10d4WorkE                                                       
                                                                                                                        
Traceback (most recent call last):
  File "/home/xinyang/miniconda3/envs/nerfstudio/bin/ns-install-cli", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/xinyang/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/scripts/completions/install.py", line 282, in entrypoint
    tyro.cli(main, description=__doc__)
  File "/home/xinyang/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/tyro/_cli.py", line 124, in cli
    _cli_impl(
  File "/home/xinyang/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/tyro/_cli.py", line 327, in _cli_impl
    out, consumed_keywords = _calling.call_from_args(
  File "/home/xinyang/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/tyro/_calling.py", line 188, in call_from_args
    return unwrapped_f(*positional_args, **kwargs), consumed_keywords  # type: ignore
  File "/home/xinyang/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/scripts/completions/install.py", line 251, in main
    completion_paths = list(
  File "/home/xinyang/miniconda3/envs/nerfstudio/lib/python3.8/concurrent/futures/_base.py", line 619, in result_iterator
    yield fs.pop().result()
  File "/home/xinyang/miniconda3/envs/nerfstudio/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/home/xinyang/miniconda3/envs/nerfstudio/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/home/xinyang/miniconda3/envs/nerfstudio/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/xinyang/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/scripts/completions/install.py", line 253, in <lambda>
    lambda path_or_entrypoint_and_shell: _generate_completion(
  File "/home/xinyang/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/scripts/completions/install.py", line 112, in _generate_completion
    raise e
  File "/home/xinyang/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/scripts/completions/install.py", line 99, in _generate_completion
    new = subprocess.run(
  File "/home/xinyang/miniconda3/envs/nerfstudio/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ns-train', '--tyro-print-completion', 'bash']' returned non-zero exit status 1.

**Comment by XinyangHan** [comment]
Reinstall functorch can solve this

**Comment by XinyangHan** [comment]
Reinstall functorch can solve this

**Comment by XinyangHan** [comment]
Solved

**Comment by brentyi** [comment]
glad you got this fixed!

**Comment by cxzhou35** [comment]
> Solved

Can you share your solution to solve this issue? I got the same problem.

**Comment by TangTang001** [comment]
can you share the solution, when i run ns-train, get the same import error in functorch

**Comment by liuyi0316** [comment]
could you share how to address it?

**Comment by liuyi0316** [comment]
pip install viser==0.1.24
pip install tyro==0.5.3
i solved， you guys can try it
