### ISSUE TITLE
CUDA 11.3 error with "functorch"

### ISSUE THREAD

**Issue by JaylonXiwei** [nerfstudio-project/nerfstudio#1540]
I was following the tutorial for CUDA 11.3, everything is good until I got error from training model.

According to the instruction, functorch is not required for CUDA 11.3. But when I want to train, I got this error. Could anyone help me, please?

`ns-train nerfacto --data data/nerfstudio/poster
Traceback (most recent call last):
  File "/home/cjml/anaconda3/envs/nerfstudio/bin/ns-train", line 5, in <module>
    from scripts.train import entrypoint
  File "/home/cjml/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/scripts/train.py", line 49, in <module>
    from nerfstudio.configs.method_configs import AnnotatedBaseConfigUnion
  File "/home/cjml/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/configs/method_configs.py", line 49, in <module>
    from nerfstudio.models.depth_nerfacto import DepthNerfactoModelConfig
  File "/home/cjml/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/models/depth_nerfacto.py", line 28, in <module>
    from nerfstudio.models.nerfacto import NerfactoModel, NerfactoModelConfig
  File "/home/cjml/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/models/nerfacto.py", line 39, in <module>
    from nerfstudio.field_components.spatial_distortions import SceneContraction
  File "/home/cjml/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/field_components/spatial_distortions.py", line 20, in <module>
    from functorch import jacrev, vmap
ModuleNotFoundError: No module named 'functorch'
`
This is my CUDA version
`
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Mon_May__3_19:15:13_PDT_2021
Cuda compilation tools, release 11.3, V11.3.109
Build cuda_11.3.r11.3/compiler.29920130_0
`

**Comment by JaylonXiwei** [comment]
When I tried to run "pip install nerfstudio"

It force install torch-1.13.1, which will replace the previous torch==1.12.1+cu113 installed.

**Comment by tancik** [comment]
If you have pytorch 1.13.1, install functorch 1.13.1. If you have pytorch 1.12.1, install functorch 0.2.1.

**Comment by tancik** [comment]
Closing. For the lastest version 0.3.1 which uses pytorch 2, `functorch` should be uninstalled.
