### ISSUE TITLE
Usage about nerf-player model

### ISSUE THREAD

**Issue by DOGEwbx** [nerfstudio-project/nerfstudio#1602]
Hi, thanks for your effort to implement nerfplayer into nerf-studio. But I failed to run nerf-player on DNeRF dataset. Does anyone know which Dynamic scene should I run with nerfplayer and any runnable commands would be appreciate.

The error message is as fllows

[08:15:42] Saving checkpoints to: outputs/unnamed/nerfplayer-ngp/2023-03-14_081541/nerfstudio_models      trainer.py:128                                                            
Traceback (most recent call last):                                                                                                                                                  
  File "/userhome/wangbingxuan/anaconda3/envs/nerfstudio/bin/ns-train", line 8, in <module>                                                                                         
    sys.exit(entrypoint())                                                                                                                                                          
  File "/userhome/wangbingxuan/code/nerfstudio/scripts/train.py", line 247, in entrypoint                                                                                           
    main(                                                                                                                                                                           
  File "/userhome/wangbingxuan/code/nerfstudio/scripts/train.py", line 233, in main                                                                                                 
    launch(                                                                                                                                                                         
  File "/userhome/wangbingxuan/code/nerfstudio/scripts/train.py", line 172, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "/userhome/wangbingxuan/code/nerfstudio/scripts/train.py", line 86, in train_loop
    trainer.setup()
  File "/userhome/wangbingxuan/code/nerfstudio/nerfstudio/engine/trainer.py", line 141, in setup
    self.pipeline = self.config.pipeline.setup(
  File "/userhome/wangbingxuan/code/nerfstudio/nerfstudio/configs/base_config.py", line 59, in setup
  return self._target(self, **kwargs)
  File "/userhome/wangbingxuan/code/nerfstudio/nerfstudio/pipelines/dynamic_batch.py", line 57, in __init__
    super().__init__(config, device, test_mode, world_size, local_rank)
  File "/userhome/wangbingxuan/code/nerfstudio/nerfstudio/pipelines/base_pipeline.py", line 231, in __init__
    self.datamanager: VanillaDataManager = config.datamanager.setup(
  File "/userhome/wangbingxuan/code/nerfstudio/nerfstudio/configs/base_config.py", line 59, in setup
    return self._target(self, **kwargs)
  File "/userhome/wangbingxuan/code/nerfstudio/nerfstudio/data/datamanagers/base_datamanager.py", line 384, in __init__
    self.train_dataset = self.create_train_dataset()
  File "/userhome/wangbingxuan/code/nerfstudio/nerfstudio/data/datamanagers/depth_datamanager.py", line 41, in create_train_dataset
    return DepthDataset(
  File "/userhome/wangbingxuan/code/nerfstudio/nerfstudio/data/datasets/depth_dataset.py", line 36, in __init__
    assert (
AssertionError

**Comment by m0o0scar** [comment]
Hi @DOGEwbx , I'm having the same error, did you find a way to run the training?
