### ISSUE TITLE
NameError: name 'tcnn' is not defined

### ISSUE THREAD

**Issue by mmhhkk123** [nerfstudio-project/nerfstudio#1615]
**Describe the bug**
when run  " **ns-train nerfacto --data data/nerfstudio/poster** ", ouput:
...
Caching all 22 images.
Traceback (most recent call last):
  File "/home/mhk/anaconda3/envs/nerfstudio2/bin/ns-train", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/mhk/conda_space/nerfstudio/scripts/train.py", line 247, in entrypoint
    main(
  File "/home/mhk/conda_space/nerfstudio/scripts/train.py", line 233, in main
    launch(
  File "/home/mhk/conda_space/nerfstudio/scripts/train.py", line 172, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "/home/mhk/conda_space/nerfstudio/scripts/train.py", line 86, in train_loop
    trainer.setup()
  File "/home/mhk/conda_space/nerfstudio/nerfstudio/engine/trainer.py", line 141, in setup
    self.pipeline = self.config.pipeline.setup(
  File "/home/mhk/conda_space/nerfstudio/nerfstudio/configs/base_config.py", line 57, in setup
    return self._target(self, **kwargs)
  File "/home/mhk/conda_space/nerfstudio/nerfstudio/pipelines/base_pipeline.py", line 236, in __init__
    self._model = config.model.setup(
  File "/home/mhk/conda_space/nerfstudio/nerfstudio/configs/base_config.py", line 57, in setup
    return self._target(self, **kwargs)
  File "/home/mhk/conda_space/nerfstudio/nerfstudio/models/base_model.py", line 82, in __init__
    self.populate_modules()  # populate the modules
  File "/home/mhk/conda_space/nerfstudio/nerfstudio/models/nerfacto.py", line 152, in populate_modules
    self.field = TCNNNerfactoField(
  File "/home/mhk/conda_space/nerfstudio/nerfstudio/fields/nerfacto_field.py", line 131, in __init__
    self.direction_encoding = tcnn.Encoding(
**NameError: name 'tcnn' is not defined**

**To Reproduce**

conda create --name nerfstudio -y python=3.8
conda activate nerfstudio
python -m pip install --upgrade pip

pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 -f https://download.pytorch.org/whl/torch_stable.html
pip install git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch

git clone https://github.com/nerfstudio-project/nerfstudio.git
cd nerfstudio
pip install --upgrade pip setuptools
pip install -e .

ns-download-data nerfstudio --capture-name=poster
ns-train nerfacto --data data/nerfstudio/poster

**my platform**: ubuntu20, RTX3060
**Forgive me for my poor English，I want to know how to solve this problem，Thank you for everyone's help!**

**Comment by JRopes** [comment]
It seems that you have not installed tiny-cuda-nn correctly. You need to build it and then intall its PyTorch bindings.

**Comment by RONINGOD** [comment]
pip install functorch==0.2.1 when using cuda 11.3.

**Comment by wanger-666** [comment]
> pip install functorch==0.2.1 when using cuda 11.3.

Thank you!

**Comment by ppjiong11** [comment]
Have you solved this problem? How did you solve it? I would like to ask your advice.

**Comment by RONINGOD** [comment]
> Have you solved this problem? How did you solve it? I would like to ask your advice.

Yes, my solution is `pip install funtorch==0.2.1` due to its default version doesn't fit cuda 11.3 and I choose to install tcnn by manual compilation in my conda environment.

**Comment by ppjiong11** [comment]
I still report the same error after installing functorch," NameError: name 'tcnn' is not defined". May I ask what is "install tcnn by manual compilation"?

**Comment by RONINGOD** [comment]
> I still report the same error after installing functorch," NameError: name 'tcnn' is not defined". May I ask what is "install tcnn by manual compilation"?
Following this step instead of`pip install git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch`: https://github.com/NVlabs/tiny-cuda-nn#compilation-windows--linux and https://github.com/NVlabs/tiny-cuda-nn#pytorch-extension. After you install tcnn, you can import tinycudann correctly in your Python environment.

**Comment by ppjiong11** [comment]
Thank you, according to your way I successfully run through, thank you!

**Comment by ethanweber** [comment]
Closing the issue now that the solution is written here. 🙂
