### ISSUE TITLE
getting error while running ns-export suddenly

### ISSUE THREAD

**Issue by soyams** [nerfstudio-project/nerfstudio#1624]
ns-export command throwing error with video dataset but not while running image dataset.

![image](https://user-images.githubusercontent.com/108407593/225889932-ab951fde-4c73-4833-a9e7-1e389c657947.png)

Earlier ns-export command was running successfully but suddenly it started throwing error. Also single dataset is running at a time.

Seems like bug in "rich" library, still need help to solve it.

**Comment by tancik** [comment]
Can you see if this change fixes your error?
https://github.com/nerfstudio-project/nerfstudio/pull/1600/files

**Comment by Zunhammer** [comment]
Same issue here, any progress on this so far?
`/workspace$ ns-export poisson --load-config outputs/unnamed/nerfacto/2023-04-24_171122/config.yml --output-dir /workspace/2023-04-24_15-08-11/exports/mesh/ --num-points 10000000 --target-num-faces 500000                           
[17:31:09] Auto image downscale factor of 1                                                 nerfstudio_dataparser.py:314
           Skipping 0 files in dataset split train.                                         nerfstudio_dataparser.py:165
           Skipping 0 files in dataset split test.                                          nerfstudio_dataparser.py:165
Setting up training dataset...
Caching 250 out of 1119 images, without resampling.
Setting up evaluation dataset...
Caching all 124 images.
Loading latest checkpoint from load_dir
✅ Done loading checkpoint from outputs/unnamed/nerfacto/2023-04-24_171122/nerfstudio_models/step-000029999.ckpt
Checking that the pipeline has a normal output.
☁ Computing Point Cloud ☁ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% --:--
Traceback (most recent call last):
  File "/home/user/.local/bin/ns-export", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/user/nerfstudio/scripts/exporter.py", line 368, in entrypoint
    tyro.cli(Commands).main()
  File "/home/user/nerfstudio/scripts/exporter.py", line 262, in main
    pcd = generate_point_cloud(
  File "/home/user/nerfstudio/nerfstudio/exporter/exporter_utils.py", line 133, in generate_point_cloud
    ray_bundle, _ = pipeline.datamanager.next_train(0)
  File "/home/user/nerfstudio/nerfstudio/data/datamanagers/base_datamanager.py", line 478, in next_train
    image_batch = next(self.iter_train_image_dataloader)
  File "/home/user/nerfstudio/nerfstudio/data/utils/dataloaders.py", line 131, in __iter__
    collated_batch = self._get_collated_batch()
  File "/home/user/nerfstudio/nerfstudio/data/utils/dataloaders.py", line 117, in _get_collated_batch
    batch_list = self._get_batch_list()
  File "/home/user/nerfstudio/nerfstudio/data/utils/dataloaders.py", line 110, in _get_batch_list
    for res in track(results, description="Loading data batch", transient=True):
  File "/home/user/.local/lib/python3.10/site-packages/rich/progress.py", line 167, in track
    with progress:
  File "/home/user/.local/lib/python3.10/site-packages/rich/progress.py", line 1169, in __enter__
    self.start()
  File "/home/user/.local/lib/python3.10/site-packages/rich/progress.py", line 1160, in start
    self.live.start(refresh=True)
  File "/home/user/.local/lib/python3.10/site-packages/rich/live.py", line 113, in start
    self.console.set_live(self)
  File "/home/user/.local/lib/python3.10/site-packages/rich/console.py", line 835, in set_live
    raise errors.LiveError("Only one live display may be active at once")
rich.errors.LiveError: Only one live display may be active at once
`

**Comment by tancik** [comment]
Can you try this change to see if it makes a difference. https://github.com/nerfstudio-project/nerfstudio/pull/1600/files
