### ISSUE TITLE
I have trouble loading "c10_cuda.dll"

### ISSUE THREAD

**Issue by ninjasaid2k** [nerfstudio-project/nerfstudio#1664]
**Describe the bug**
I encountered an error message when running the ns-process-data command in the NerfStudio environment. The error message indicates that there was a problem loading the c10_cuda.dll library that is part of the torch package.

**To Reproduce**
1. Activate the NerfStudio environment using conda activate nerfstudio
2. Run the ns-process-data command by typing ns-process-data --help in the command prompt
3. The error message should appear in the console
```
(nerfstudio) C:\Users\*****\nerfstudio>ns-process-data --help
Traceback (most recent call last):
  File "C:\Users\*****\AppData\Local\Programs\Python\Python310\Lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\*****\AppData\Local\Programs\Python\Python310\Lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\*****\AppData\Local\Programs\Python\Python310\Scripts\ns-process-data.exe\__main__.py", line 4, in <module>
  File "C:\Users\*****\AppData\Local\Programs\Python\Python310\lib\site-packages\scripts\process_data.py", line 18, in <module>
    from nerfstudio.process_data import (
  File "C:\Users\*****\AppData\Local\Programs\Python\Python310\lib\site-packages\nerfstudio\process_data\colmap_utils.py", line 27, in <module>
    import torch
  File "C:\Users\*****\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\__init__.py", line 122, in <module>
    raise err
OSError: [WinError 127] The specified procedure could not be found. Error loading "C:\Users\*****\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\lib\c10_cuda.dll" or one of its dependencies.
```
**Expected behavior**
I expected the ns-process-data command to run without errors and to be able to process my data as intended.

**Additional context**
Operating System: Windows 10
Python version: 3.8.16
```
(nerfstudio) C:\Users\*****\nerfstudio>python --version
Python 3.8.16

```Torch version: 2.0.0

**Comment by tancik** [comment]
We don't currently support torch 2.0.0, can you install torch 1.13.1
`pip install torch==1.13.1 torchvision functorch --extra-index-url https://download.pytorch.org/whl/cu117`
