### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'text' using metashape

### ISSUE THREAD

**Issue by aaronhdgolf** [nerfstudio-project/nerfstudio#1714]
(nerfstudio) D:\nerfstudio>ns-process-data metashape --data D:\360\RichmondCC --xml cameras.xml --output-dir output
[06:50:12]  Done copying images.                                                             process_data_utils.py:216
[07:29:51]  Done downscaling images.                                                         process_data_utils.py:337
Traceback (most recent call last):
  File "C:\Users\Ryzen-dual.conda\envs\nerfstudio\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Ryzen-dual.conda\envs\nerfstudio\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Ryzen-dual.conda\envs\nerfstudio\Scripts\ns-process-data.exe__main__.py", line 7, in <module>
  File "C:\Users\Ryzen-dual.conda\envs\nerfstudio\lib\site-packages\scripts\process_data.py", line 970, in entrypoint
    tyro.cli(Commands).main()
  File "C:\Users\Ryzen-dual.conda\envs\nerfstudio\lib\site-packages\scripts\process_data.py", line 855, in main
    metashape_utils.metashape_to_json(
  File "C:\Users\Ryzen-dual.conda\envs\nerfstudio\lib\site-packages\nerfstudio\process_data\metashape_utils.py", line 82, in metashape_to_json
    data["cx"] = float(calib.find("cx").text) + data["w"] / 2.0  # type: ignore
AttributeError: 'NoneType' object has no attribute 'text'

**Comment by f-dy** [comment]
This was fixed by https://github.com/nerfstudio-project/nerfstudio/pull/1605

The line
```
   data["cx"] = float(calib.find("cx").text) + data["w"] / 2.0  # type: ignore
```
was changed to
```
        s["cx"] = _find_param(calib, "cx") + s["w"] / 2.0  # type: ignore
```
where _find_param uses the default value of 0 if "cx" is not found

**Comment by f-dy** [comment]
@tancik can you please close this issue?
