### ISSUE TITLE
Error when using ns-process-data images --sfm-tool hloc

### ISSUE THREAD

**Issue by Diana-Zeng** [nerfstudio-project/nerfstudio#1716]
**Describe the bug**
scipy.io.matlab._miobase.MatReadError: Mat file appears to be empty

**To Reproduce**
1. Go to :
ns-process-data images --data /media/diana/001/c \
                       --output /home/diana/NeRF/nerfstudio/selfdata/20230404/cc \
                       --camera perspective \
                       --matching vocab_tree \
                       --sfm-tool hloc \
                       --feature-type superpoint_aachen \
                       --matcher-type superglue \
                       --colmap-cmd /home/diana/COLMAP/colmap/build/src/exe/colmap'
2.See error:
process_data_utils.py:363
[2023/04/10 18:58:47 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-r1024',
 'preprocessing': {'grayscale': True, 'resize_max': 1024}}
[2023/04/10 18:58:47 hloc INFO] Skipping the extraction.
[2023/04/10 18:58:47 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}
[2023/04/10 18:58:47 hloc INFO] Found 1440 images in root /home/diana/NeRF/nerfstudio/selfdata/20230404/cc/images.
Traceback (most recent call last):
  File "/home/diana/anaconda3/envs/nerfstudio/bin/ns-process-data", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/diana/NeRF/nerfstudio/scripts/process_data.py", line 833, in entrypoint
    tyro.cli(Commands).main()
  File "/home/diana/NeRF/nerfstudio/scripts/process_data.py", line 165, in main
    self._run_colmap(image_dir, colmap_dir)
  File "/home/diana/NeRF/nerfstudio/scripts/process_data.py", line 231, in _run_colmap
    hloc_utils.run_hloc(
  File "/home/diana/NeRF/nerfstudio/nerfstudio/process_data/hloc_utils.py", line 110, in run_hloc
    retrieval_path = extract_features.main(retrieval_conf, image_dir, outputs)
  File "/home/diana/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/diana/Tools/Hierarchical-Localization/hloc/extract_features.py", line 251, in main
    model = Model(conf['model']).eval().to(device)
  File "/home/diana/Tools/Hierarchical-Localization/hloc/utils/base_model.py", line 17, in __init__
    self._init(conf)
  File "/home/diana/Tools/Hierarchical-Localization/hloc/extractors/netvlad.py", line 82, in _init
    mat = loadmat(checkpoint, struct_as_record=False, squeeze_me=True)
  File "/home/diana/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/scipy/io/matlab/_mio.py", line 225, in loadmat
    MR, _ = mat_reader_factory(f, **kwargs)
  File "/home/diana/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/scipy/io/matlab/_mio.py", line 74, in mat_reader_factory
    mjv, mnv = _get_matfile_version(byte_stream)
  File "/home/diana/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/scipy/io/matlab/_miobase.py", line 234, in _get_matfile_version
    raise MatReadError("Mat file appears to be empty")
scipy.io.matlab._miobase.MatReadError: Mat file appears to be empty

********************
I don't understand why the error occurred.  Would you please help me to know the reason and tell me how to solve this problem? Thanks a lot.

**Comment by geyan21** [comment]
Hi @Diana-Zeng , I encountered the same problem when running on my custom data. It's caused by the number of images and corresponding matching method. And changing to **--matching-method exhaustive** works for me. Hope it helps
