### ISSUE TITLE
Shape mismatch for ns-process-data with depth debug

### ISSUE THREAD

**Issue by MvWouden** [nerfstudio-project/nerfstudio#1722]
**Describe the bug**
A shape mismatch was encountered during image data processing.
This only occurred when non-square images were used with the flags `--use-sfm-depth` and `--include-depth-debug`.
I would possibly be willing to fix this issue.

**To Reproduce**
1. Have a sample dataset with non-square "vertical" images (height taller than width)
2. Use the CLI command `ns-process-data` like:
```
ns-process-data images --data <path/to/data> --output-dir <path/to/output> --use-sfm-depth --include-depth-debug
```

**Expected behavior**
The following output/trace should appear:
```
( ●    ) Copying images...[09:49:11] 🎉 Done copying images.                                                             process_data_utils.py:237
[09:49:28] 🎉 Done downscaling images.                                                         process_data_utils.py:363
[09:49:34] 🎉 Done extracting COLMAP features.                                                       colmap_utils.py:137
[09:50:04] 🎉 Done matching COLMAP features.                                                         colmap_utils.py:151
[09:50:49] 🎉 Done COLMAP bundle adjustment.                                                         colmap_utils.py:173
[09:50:53] 🎉 Done refining intrinsics.                                                              colmap_utils.py:182
Traceback (most recent call last):
  File "...\3.10.5\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "...\3.10.5\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "...\venv\Scripts\ns-process-data.exe\__main__.py", line 7, in <module>
  File "...\nerfstudio\scripts\process_data.py", line 833, in entrypoint
    tyro.cli(Commands).main()
  File "...\nerfstudio\scripts\process_data.py", line 174, in main
    image_id_to_depth_path = colmap_utils.create_sfm_depth(
  File "...\nerfstudio\process_data\colmap_utils.py", line 604, in create_sfm_depth
    debug = 0.3 * input_image + 0.7 + overlay
ValueError: operands could not be broadcast together with shapes (4032,3024,3) (3024,4032,3)
```

**Additional context**
| What | Value |
|--------|--------|
| Platform | Windows |
| Nerfstudio version | Latest Source (11th of April 2023) |
| Python version | 3.10.5 |
| CUDA version | 11.7 | 
| PyTorch version | 1.13.1+cu117 |

The overlay is created as `overlay = overlay.reshape([W, H, 3])`, perhaps this should be `overlay = overlay.reshape([H, W, 3])`?

**Comment by MvWouden** [comment]
Update:

Changing

```python
overlay = overlay.reshape([W, H, 3])
```

to 

```python
overlay = overlay.reshape([H, W, 3])
```

does indeed resolve the error.
However, I'm not sure if this is the "correct" solution.
