### ISSUE TITLE
 ns-render on nerfplayer-nerfacto model - size mismatch for datamanager.eval_ray_generator.pose

### ISSUE THREAD

**Issue by Paralelopipet** [nerfstudio-project/nerfstudio#1723]
While trying to run ns-render command on model trained with nerfplayer-nerfacto I got the following ERROR:

    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
    RuntimeError: Error(s) in loading state_dict for VanillaPipeline:
          size mismatch for datamanager.eval_camera_optimizer.pose_adjustment: copying a param with shape torch.Size([1, 6]) from checkpoint, the shape in current model is torch.Size([475, 6]).
          size mismatch for datamanager.eval_ray_generator.pose_optimizer.pose_adjustment: copying a param with shape torch.Size([1, 6]) from checkpoint, the shape in current model is torch.Size([475, 6]).

Exact command: **ns-render --load-config /home/ddd26/rds/hpc-work/nerfstudio/data/outputs/apple/nerfplayer-nerfacto/2023-04-10_232956/config.yml** 

When trying the to render a video with model trained with nerfplayer-ngp and nerfacto everything goes smoothly.

**Comment by stephenjarrell19** [comment]
Have you gotten the nerfplayer-nerfacto model to work well without depth input?

**Comment by Paralelopipet** [comment]
I didn't get nerfplayer-nerfacto to work on data nerfstudio-data configuration if that is what you mean by "without depth". If there are training parameters that can be set to train without depth information please tell me, as I haven't found any thing in "ns-train nerfplayer-nerfacto -h" that looked like it does the job.

The error when I tried training with command  "ns-train nerfplayer-nerfacto  nerfstudio-data --data data/nerfstudio/poster/":

Traceback (most recent call last):
  File "/home/ddd26/.conda/envs/nerfstudio/bin/ns-train", line 8, in <module>
    sys.exit(entrypoint())
  File "/rds/user/ddd26/hpc-work/nerfstudio/scripts/train.py", line 247, in entrypoint
    main(
  File "/rds/user/ddd26/hpc-work/nerfstudio/scripts/train.py", line 233, in main
    launch(
  File "/rds/user/ddd26/hpc-work/nerfstudio/scripts/train.py", line 172, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "/rds/user/ddd26/hpc-work/nerfstudio/scripts/train.py", line 86, in train_loop
    trainer.setup()
  File "/rds/user/ddd26/hpc-work/nerfstudio/nerfstudio/engine/trainer.py", line 153, in setup
    self.pipeline = self.config.pipeline.setup(
  File "/rds/user/ddd26/hpc-work/nerfstudio/nerfstudio/configs/base_config.py", line 60, in setup
    return self._target(self, **kwargs)
  File "/rds/user/ddd26/hpc-work/nerfstudio/nerfstudio/pipelines/base_pipeline.py", line 231, in __init__
    self.datamanager: VanillaDataManager = config.datamanager.setup(
  File "/rds/user/ddd26/hpc-work/nerfstudio/nerfstudio/configs/base_config.py", line 60, in setup
    return self._target(self, **kwargs)
  File "/rds/user/ddd26/hpc-work/nerfstudio/nerfstudio/data/datamanagers/base_datamanager.py", line 411, in __init__
    self.train_dataset = self.create_train_dataset()
  File "/rds/user/ddd26/hpc-work/nerfstudio/nerfstudio/data/datamanagers/depth_datamanager.py", line 41, in create_train_dataset
    return DepthDataset(
  File "/rds/user/ddd26/hpc-work/nerfstudio/nerfstudio/data/datasets/depth_dataset.py", line 36, in __init__
    assert (
AssertionError

Where the latest assert is the following one:

 def __init__(self, dataparser_outputs: DataparserOutputs, scale_factor: float = 1.0):
        super().__init__(dataparser_outputs, scale_factor)
        assert (
            "depth_filenames" in dataparser_outputs.metadata.keys()
            and dataparser_outputs.metadata["depth_filenames"] is not None
        )
        self.depth_filenames = self.metadata["depth_filenames"]
        self.depth_unit_scale_factor = self.metadata["depth_unit_scale_factor"]

**Comment by stephenjarrell19** [comment]
How did you get a model trained with nerfplayer-ngp or perfecto then? I had to modify all of the modules that required depth information and ran into CUDA problems that Killed my process

**Comment by Paralelopipet** [comment]
Well default dataset type for nerfplayer-ngp and nerfplayer-nerfacto are dycheck-data, so I managed to use dataset provided by https://github.com/KAIR-BAIR/dycheck to reproduce training process, but I still failed to evaluate it on nerfplayer-nerfacto. I assumed that maybe other dataset types are not supported for nerfplayer 🤔.
