### ISSUE TITLE
CUDA out of memory in the viewer

### ISSUE THREAD

**Issue by mpizenberg** [nerfstudio-project/nerfstudio#1726]
**Describe the bug**

The viewer is getting cuda OOM errors as follows.

```
Printing profiling stats, from longest to shortest duration in seconds
Trainer.train_iteration: 5.0188
VanillaPipeline.get_train_loss_dict: 4.9420
ViewerState._render_image_in_viewer: 0.4619
Traceback (most recent call last):
  File "C:\Users\MatthieuPIZENBERG\anaconda3\envs\nerfstudio\lib\site-packages\nerfstudio\viewer\server\viewer_utils.py", line 883, in _render_image_in_viewer
    render_thread.join()
  File "C:\Users\MatthieuPIZENBERG\anaconda3\envs\nerfstudio\lib\site-packages\nerfstudio\viewer\server\viewer_utils.py", line 167, in join
    raise self.exc
  File "C:\Users\MatthieuPIZENBERG\anaconda3\envs\nerfstudio\lib\site-packages\nerfstudio\viewer\server\viewer_utils.py", line 154, in run
    outputs = self.graph.get_outputs_for_camera_ray_bundle(self.camera_ray_bundle)
  File "C:\Users\MatthieuPIZENBERG\anaconda3\envs\nerfstudio\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\MatthieuPIZENBERG\anaconda3\envs\nerfstudio\lib\site-packages\nerfstudio\models\base_model.py", line 177, in get_outputs_for_camera_ray_bundle
    outputs = self.forward(ray_bundle=ray_bundle)
  File "C:\Users\MatthieuPIZENBERG\anaconda3\envs\nerfstudio\lib\site-packages\nerfstudio\models\base_model.py", line 139, in forward
    return self.get_outputs(ray_bundle)
  File "C:\Users\MatthieuPIZENBERG\anaconda3\envs\nerfstudio\lib\site-packages\nerfstudio\models\nerfacto.py", line 267, in get_outputs
    field_outputs = self.field(ray_samples, compute_normals=self.config.predict_normals)
  File "C:\Users\MatthieuPIZENBERG\anaconda3\envs\nerfstudio\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\MatthieuPIZENBERG\anaconda3\envs\nerfstudio\lib\site-packages\nerfstudio\fields\base_field.py", line 111, in forward
    field_outputs = self.get_outputs(ray_samples, density_embedding=density_embedding)
  File "C:\Users\MatthieuPIZENBERG\anaconda3\envs\nerfstudio\lib\site-packages\nerfstudio\fields\nerfacto_field.py", line 323, in get_outputs
    h = torch.cat(
RuntimeError: CUDA out of memory. Tried to allocate 378.00 MiB (GPU 0; 4.00 GiB total capacity; 1.35 GiB already allocated; 0 bytes free; 2.14 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

I’ve tried to look for a `max_split_size_mb` in the CLI arguments as the error mentions it but I don’t see one. Any idea how I could avoid these OOM errors in the viewer?

**Additional context**

I’m opening the viewer only once the training is done to avoid having too much at the same time but it seems not enough to avoid the OOM error. I’m reconstructing a short video amounting to 5000 images, but limiting training to 1000 images at a time, because loading all of them gets me OOM issues during training. Here is the command I use for training.

```sh
ns-train nerfacto --data my-scene  --pipeline.datamanager.train-num-images-to-sample-from 1000 --pipeline.datamanager.train-num-times-to-repeat-images 8000
```

nerfstudio version: 0.1.19
OS: Windows

**Q:** Any idea of what I can do to avoid OOM but still keeping good reconstructions, even at the price of time?

**Comment by iSach** [comment]
If it does not happen when using wandb instead of the viewer (`--vis wandb`), you can try to reduce the batch size for rendering in the viewer:
`ns-train [...] --viewer.num-rays-per-chunk 32000`

By default, it's often at 65536, but you can try lowering by 2 until it works. This will make rendering slower but it should fit in memory.

**Comment by karun2016** [comment]
The issue is back again. I have just created a new conda env with the latest code a couple of days back.
 I tried both  --viewer.num-rays-per-chunk 32000, 16000 and   export 'PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:1024' and  export 'PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:512'. Still having the Cuda OOM issue.
 
The viewer version is **https://viewer.nerf.studio/versions/23-05-15-1**.  

The command: **ns-train semantic-nerfw --data data/sitcoms3d/Frasier-apartment --viewer.num-rays-per-chunk 16000** ...

**"torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1024.00 MiB (GPU 0; 15.73 GiB total capacity; 13.81 GiB already allocated; 40.12 MiB free; 14.12 GiB
reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF"**

**Comment by XuYunqiu** [comment]
> The issue is back again. I have just created a new conda env with the latest code a couple of days back. I tried both --viewer.num-rays-per-chunk 32000, 16000 and export 'PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:1024' and export 'PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:512'. Still having the Cuda OOM issue.
> 
> The viewer version is **https://viewer.nerf.studio/versions/23-05-15-1**.
> 
> The command: **ns-train semantic-nerfw --data data/sitcoms3d/Frasier-apartment --viewer.num-rays-per-chunk 16000** ...
> 
> **"torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1024.00 MiB (GPU 0; 15.73 GiB total capacity; 13.81 GiB already allocated; 40.12 MiB free; 14.12 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF"**

I meet the same issue. Is there any solution?

**Comment by mattgauf** [comment]
Using: dromni/nerfstudio:0.3.1
GPU: RTX 3070 Ti 8GB

I'm also having this issue, I've tried the workarounds already mentioned to no success. I am still new to nerfstudio and running compute in a docker container... but I thought I'd add that I noticed wandb reports about half of the memory usage the xnvidia control panel (in the host) does.

Wandb: 3456MB
Nvidia: 6127MB

This stands out to me because I can run nerfacto using the normal viewer just fine... but if I run it using wandb it crashes.

**Comment by tancik** [comment]
When you run wandb it does an evaluation process that is not run when the normal viewer is used. This evaluation takes up a fair amount of memory, particularly the LPIPS calculation which is dependent on the resolution of the images.

**Comment by mattgauf** [comment]
I think I follow,  wandb is just reporting the memory used in the eval; the difference between the numers is the memory used by the normal training process.

Apart from image size, would `--pipeline.model.eval-num-rays-per-chunk` help reduce memory usage when using `--vis wandb` or is it a separate eval than the model defines?
