### ISSUE TITLE
ns-viewer does not start on the blender-data lego scene, pose_adjustment size mismatch

### ISSUE THREAD

**Issue by agrechnev** [nerfstudio-project/nerfstudio#1728]
First I train nerfacto on the traditional LEGO scene like this:

ns-train nerfacto --pipeline.model.near-plane 2 --pipeline.model.far-plane 10 --max-num-iterations 4000 --experiment-name bl_lego blender-data --data data/nerf_synthetic/lego

The visualizer works perfectly fine while training. But when finish training and want to start ns-viewer with the command

ns-viewer --load-config outputs/bl_lego/nerfacto/2023-04-13_121027/config.yml

I get the following error

-------------
Loading latest checkpoint from load_dir
Traceback (most recent call last):
  File "/home/seymour/.local/bin/ns-viewer", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/seymour/.local/lib/python3.10/site-packages/scripts/viewer/run_viewer.py", line 108, in entrypoint
    tyro.cli(RunViewer).main()
  File "/home/seymour/.local/lib/python3.10/site-packages/scripts/viewer/run_viewer.py", line 48, in main
    config, pipeline, _ = eval_setup(
  File "/home/seymour/.local/lib/python3.10/site-packages/nerfstudio/utils/eval_utils.py", line 105, in eval_setup
    checkpoint_path = eval_load_checkpoint(config, pipeline)
  File "/home/seymour/.local/lib/python3.10/site-packages/nerfstudio/utils/eval_utils.py", line 62, in eval_load_checkpoint
    pipeline.load_pipeline(loaded_state["pipeline"], loaded_state["step"])
  File "/home/seymour/.local/lib/python3.10/site-packages/nerfstudio/pipelines/base_pipeline.py", line 375, in load_pipeline
    self.load_state_dict(state, strict=True)
  File "/home/seymour/.local/lib/python3.10/site-packages/nerfstudio/pipelines/base_pipeline.py", line 115, in load_state_dict
    super().load_state_dict(pipeline_state, strict=False)
  File "/home/seymour/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1604, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for VanillaPipeline:
        size mismatch for datamanager.eval_camera_optimizer.pose_adjustment: copying a param with shape torch.Size([100, 6]) from checkpoint, the shape in current model is torch.Size([200, 6]).
        size mismatch for datamanager.eval_ray_generator.pose_optimizer.pose_adjustment: copying a param with shape torch.Size([100, 6]) from checkpoint, the shape in current model is torch.Size([200, 6]).
-------------

In comparison, ns-viewer works just fine. I am not sure if it's a bug, or I am doing something stupid.

My system:
Ubuntu 22.04
Python 3.10.6
nerfstudio 0.1.19, PIP-installed
torch  1.12.1+cu113
cuda 11.5.1
GeForce 1660

**Comment by tancik** [comment]
I'm a little confused is `ns-viewer` working or not?

> ns-viewer --load-config outputs/bl_lego/nerfacto/2023-04-13_121027/config.yml
I get the following error ...

> In comparison, ns-viewer works just fine. I am not sure if it's a bug, or I am doing something stupid.

**Comment by agrechnev** [comment]
Sorry, missed a part of the sentecnce.
It should be

In comparison, ns-viewer works just fine for nerstudio data (e.g. poster).

ns-viewer does NOT work with lego (blender data)
ns-viewer works fine with poster (nerfstudio data)

**Comment by jurrejelle** [comment]
Issue also holds for ns-export: DNeRF Lego data has a size mismatch, also probably from them using different datasets. 
I'd argue training using the validation dataset is weird anyways, since val only has 10 frames where train has 50 (and thus you train with less data)

I removed the validation and test dataset, and copied train to both of them (so now all 3 datasets val,train,test are the same 50 images and the same json file). It's not quite the spirit of machine learning, but if we're gonna have mismatches because of the way the data directories is structured and which sets are used between different programs, this should fix that. I'm pretty sure nerfstudio creates its own training / evaluation split anyways

Of course the actual solution would be fixing this within nerfstudio, but unfortunately that's out of scope for me at the moment
