### ISSUE TITLE
Dock version works only <= dromni/nerfstudio:0.1.16

### ISSUE THREAD

**Issue by XinyueZ** [nerfstudio-project/nerfstudio#1796]
Hey

I have reported at Discord, maybe someone else has similar issues.

`dromni/nerfstudio:0.1.16` of Docker works for me, and the version since this won't work. 

Pull: `docker pull dromni/nerfstudio:0.2.1`

After run `docker run --gpus all -v /home/ubuntu/work/nerfswork:/workspace/  -p 7008:7008 --rm  -it --shm-size=20gb dromni/nerfstudio:0.2.1`

Get error:
```
❌ Completion script generation failed: ['ns-train', '--tyro-print-completion', 'bash']        install.py:110
           /home/user/.local/lib/python3.10/site-packages/torch/cuda/__init__.py:88: UserWarning: CUDA    install.py:114
           initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions                  
           before calling NumCudaDevices() that might have already set an error? Error 804: forward                     
           compatibility was attempted on non supported HW (Triggered internally at                                     
           ../c10/cuda/CUDAFunctions.cpp:109.)                                                                          
             return torch._C._cuda_getDeviceCount() > 0                                                                 
           Traceback (most recent call last):                                                                           
             File "/home/user/.local/bin/ns-train", line 5, in <module>                                                 
               from scripts.train import entrypoint                                                                     
             File "/home/user/nerfstudio/scripts/train.py", line 49, in <module>                                        
               from nerfstudio.configs.method_configs import AnnotatedBaseConfigUnion                                   
             File "/home/user/nerfstudio/nerfstudio/configs/method_configs.py", line 51, in <module>                    
               from nerfstudio.field_components.temporal_distortions import TemporalDistortionKind                      
             File "/home/user/nerfstudio/nerfstudio/field_components/__init__.py", line 17, in <module>                 
               from .encodings import Encoding, ScalingAndOffset                                                        
             File "/home/user/nerfstudio/nerfstudio/field_components/encodings.py", line 35, in <module>                
               import tinycudann as tcnn                                                                                
             File "/home/user/.local/lib/python3.10/site-packages/tinycudann/__init__.py", line 9, in                   
           <module>                                                                                                     
               from tinycudann.modules import free_temporary_memory, NetworkWithInputEncoding, Network,                 
           Encoding                                                                                                     
             File "/home/user/.local/lib/python3.10/site-packages/tinycudann/modules.py", line 18, in                   
           <module>                                                                                                     
               raise EnvironmentError("Unknown compute capability. Ensure PyTorch with CUDA support is                  
           installed.")                                                                                                 
           OSError: Unknown compute capability. Ensure PyTorch with CUDA support is installed.
``` 
My Nvidia

``` 
Fri Apr 21 10:56:00 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.65.01    Driver Version: 515.65.01    CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA TITAN RTX    Off  | 00000000:08:00.0 Off |                  N/A |
| 41%   27C    P8     1W / 280W |   7244MiB / 24576MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA TITAN RTX    Off  | 00000000:09:00.0 Off |                  N/A |
| 40%   24C    P8     1W / 280W |      3MiB / 24576MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  NVIDIA TITAN RTX    Off  | 00000000:42:00.0 Off |                  N/A |
| 40%   26C    P8     5W / 280W |      3MiB / 24576MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  NVIDIA TITAN RTX    Off  | 00000000:43:00.0 Off |                  N/A |
| 41%   25C    P8     9W / 280W |      3MiB / 24576MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
```

**Comment by XinyueZ** [comment]
Can anyone help?
