### ISSUE TITLE
Can't run ns-train from a directory containing a local folder named "scripts"

### ISSUE THREAD

**Issue by dllu** [nerfstudio-project/nerfstudio#1857]
**Describe the bug**

When attempting to run `ns-train` from a directory containing a local directory named "scripts" that contains `__init__.py`, it doesn't work.

**To Reproduce**

1. run `ns-train` from a clean directory to ensure that it works (it prints out a useful help message)
2. run `mkdir -p scripts && touch scripts/__init__.py`
3. now it says 

```
Traceback (most recent call last):
  File "/home/danlu/.local/bin/ns-train", line 5, in <module>
    from scripts.train import entrypoint
ModuleNotFoundError: No module named 'scripts.train'
```

**Expected behavior**

It should work

**Screenshots**

```
test $ ns-train

WARNING: Using a slow implementation of HashEncoding.
🏃 🏃 Install tcnn for speedups 🏃 🏃
pip install git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch

usage: ns-train [-h]
                {nerfacto,nerfacto-big,depth-nerfacto,volinga,instant-ngp,instant-ngp-bounded,mipnerf,semantic-nerfw,vanilla-nerf,tensorf,dnerf,phototourism,
nerfplayer-nerfacto,nerfplayer-ngp,neus,neus-facto}

Train a radiance field with nerfstudio. For real captures, we recommend using the nerfacto model.

Nerfstudio allows for customizing your training and eval configs from the CLI in a powerful way, but there are some things to understand.

The most demonstrative and helpful example of the CLI structure is the difference in output between the following commands:

    ns-train -h
    ns-train nerfacto -h nerfstudio-data
    ns-train nerfacto nerfstudio-data -h

In each of these examples, the -h applies to the previous subcommand (ns-train, nerfacto, and nerfstudio-data).

In the first example, we get the help menu for the ns-train script. In the second example, we get the help menu for the nerfacto model. In the third example,
we get the help menu for the nerfstudio-data dataparser.

With our scripts, your arguments will apply to the preceding subcommand in your command, and thus where you put your arguments matters! Any optional
arguments you discover from running

    ns-train nerfacto -h nerfstudio-data

need to come directly after the nerfacto subcommand, since these optional arguments only belong to the nerfacto subcommand:

    ns-train nerfacto {nerfacto optional args} nerfstudio-data

╭─ arguments ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ -h, --help        show this help message and exit                                                                                                         │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─ subcommands ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ {nerfacto,nerfacto-big,depth-nerfacto,volinga,instant-ngp,instant-ngp-bounded,mipnerf,semantic-nerfw,vanilla-nerf,tensorf,dnerf,phototourism,nerfplayer-… │
│     nerfacto          Recommended real-time model tuned for real captures. This model will be continually updated.                                        │
│     nerfacto-big                                                                                                                                          │
│     depth-nerfacto    Nerfacto with depth supervision.                                                                                                    │
│     volinga           Real-time rendering model from Volinga. Directly exportable to NVOL format at https://volinga.ai/                                   │
│     instant-ngp       Implementation of Instant-NGP. Recommended real-time model for unbounded scenes.                                                    │
│     instant-ngp-bound…Implementation of Instant-NGP. Recommended for bounded real and synthetic scenes                                                    │
│     mipnerf           High quality model for bounded scenes. (slow)                                                                                       │
│     semantic-nerfw    Predicts semantic segmentations and filters out transient objects.                                                                  │
│     vanilla-nerf      Original NeRF model. (slow)                                                                                                         │
│     tensorf           tensorf                                                                                                                             │
│     dnerf             Dynamic-NeRF model. (slow)                                                                                                          │
│     phototourism      Uses the Phototourism data.                                                                                                         │
│     nerfplayer-nerfac…NeRFPlayer with nerfacto backbone.                                                                                                  │
│     nerfplayer-ngp    NeRFPlayer with InstantNGP backbone.                                                                                                │
│     neus              Implementation of NeuS. (slow)                                                                                                      │
│     neus-facto                                                                                                                                            │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
test $ mkdir scripts && touch scripts/__init__.py
test $ ns-train
Traceback (most recent call last):
  File "/home/danlu/.local/bin/ns-train", line 5, in <module>
    from scripts.train import entrypoint
ModuleNotFoundError: No module named 'scripts.train'
```

**Additional context**

Maybe try one of the suggestions in https://stackoverflow.com/questions/69774664/importing-python-modules-when-there-is-a-sibling-directory-with-the-same-name

**Comment by jkulhanek** [comment]
Was resolved in #1897
