### ISSUE TITLE
RuntimeError: Windows not yet supported for torch.compile

### ISSUE THREAD

**Issue by dzj727** [nerfstudio-project/nerfstudio#1975]
Hello. I encountered a bug. The content is as follows. May I know how to solve it. Thank you.

(nerfstudio) PS C:\Users\dzj> ns-train nerfacto --data data/nerfstudio/person
Traceback (most recent call last):
  File "D:\Anaconda3\envs\nerfstudio\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Anaconda3\envs\nerfstudio\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Anaconda3\envs\nerfstudio\Scripts\ns-train.exe\__main__.py", line 4, in <module>
  File "D:\Anaconda3\envs\nerfstudio\lib\site-packages\nerfstudio\scripts\train.py", line 62, in <module>
    from nerfstudio.configs.method_configs import AnnotatedBaseConfigUnion
  File "D:\Anaconda3\envs\nerfstudio\lib\site-packages\nerfstudio\configs\method_configs.py", line 28, in <module>
    from nerfstudio.configs.external_methods import get_external_methods
  File "D:\Anaconda3\envs\nerfstudio\lib\site-packages\nerfstudio\configs\external_methods.py", line 24, in <module>
    from nerfstudio.engine.trainer import TrainerConfig
  File "D:\Anaconda3\envs\nerfstudio\lib\site-packages\nerfstudio\engine\trainer.py", line 35, in <module>
    from nerfstudio.configs.experiment_config import ExperimentConfig
  File "D:\Anaconda3\envs\nerfstudio\lib\site-packages\nerfstudio\configs\experiment_config.py", line 35, in <module>
    from nerfstudio.pipelines.base_pipeline import VanillaPipelineConfig
  File "D:\Anaconda3\envs\nerfstudio\lib\site-packages\nerfstudio\pipelines\base_pipeline.py", line 40, in <module>
    from nerfstudio.data.datamanagers.base_datamanager import (
  File "D:\Anaconda3\envs\nerfstudio\lib\site-packages\nerfstudio\data\datamanagers\base_datamanager.py", line 45, in <module>
    from nerfstudio.cameras.cameras import CameraType
  File "D:\Anaconda3\envs\nerfstudio\lib\site-packages\nerfstudio\cameras\cameras.py", line 31, in <module>
    import nerfstudio.utils.math
  File "D:\Anaconda3\envs\nerfstudio\lib\site-packages\nerfstudio\utils\math.py", line 201, in <module>
    def intersect_aabb(
  File "D:\Anaconda3\envs\nerfstudio\lib\site-packages\torch\__init__.py", line 1425, in fn
    return compile(model,
  File "D:\Anaconda3\envs\nerfstudio\lib\site-packages\torch\__init__.py", line 1441, in compile
    return torch._dynamo.optimize(backend=backend, nopython=fullgraph, dynamic=dynamic, disable=disable)(model)
  File "D:\Anaconda3\envs\nerfstudio\lib\site-packages\torch\_dynamo\eval_frame.py", line 413, in optimize
    check_if_dynamo_supported()
  File "D:\Anaconda3\envs\nerfstudio\lib\site-packages\torch\_dynamo\eval_frame.py", line 375, in check_if_dynamo_supported
    raise RuntimeError("Windows not yet supported for torch.compile")
RuntimeError: Windows not yet supported for torch.compile

**Comment by jkulhanek** [comment]
Can you please upgrade to the newest version 0.3.1 and try again? #1961 #1962

**Comment by dzj727** [comment]
> Can you please upgrade to the newest version 0.3.1 and try again? #1961 #1962

I'm sorry. Which part is being updated?

**Comment by dzj727** [comment]
> Can you please upgrade to the newest version 0.3.1 and try again? #1961 #1962

The version I'm using now is Torch 2.0.1 with CUDA 11.7

**Comment by jkulhanek** [comment]
I am sorry I didn’t make it clear. What version of nerfstudio are you using? Can you try installing either the head of the main branch or nerfstudio 0.3.1?

**Comment by dzj727** [comment]
Thank you.My nerfstudio version is nerfstudio-0.3.0.I will try to update it.
