### ISSUE TITLE
Any export command does not work

### ISSUE THREAD

**Issue by NeuroLord** [nerfstudio-project/nerfstudio#1981]
**Describe the bug**
Running ns-export with any argument does not end well, but ends with the error "ValueError: invalid literal for int() with base 10: 'material_0'"

**To Reproduce**
1. One of the commands that gives me an error: "ns-export pointcloud --load-config outputs\me\nerfacto\2023-05-23_143946\config.yml --output-dir exports\pcd\ --num-points 1000000 --remove-outliers True --estimate-normals False --use-bounding-box True --bounding-box-min -1 -1 -1 --bounding-box-max 1 1 1"

**Expected behavior**
Ready point cloud in a specified folder

**Additional context**
I was able to do the export twice, then without exactly changing a word in the code tried to do another one and it didn't work

**Full traceback of the error in the console:** 

_"(nerfstudio2) K:\Programs\Nerfstudio>ns-export pointcloud --load-config outputs\me\nerfacto\2023-05-23_143946\config.yml --output-dir exports\pcd\ --num-points 1000000 --remove-outliers True --estimate-normals False --use-bounding-box True --bounding-box-min -1 -1 -1 --bounding-box-max 1 1 1
[23:34:22] Auto image downscale factor of 4                                                 nerfstudio_dataparser.py:336
           Skipping 0 files in dataset split train.                                         nerfstudio_dataparser.py:163
           Skipping 0 files in dataset split test.                                          nerfstudio_dataparser.py:163
Setting up training dataset...
Caching all 152 images.
Setting up evaluation dataset...
Caching all 16 images.
Loading latest checkpoint from load_dir
Traceback (most recent call last):
  File "F:\Programs\Anaconda\envs\nerfstudio2\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "F:\Programs\Anaconda\envs\nerfstudio2\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "F:\Programs\Anaconda\envs\nerfstudio2\Scripts\ns-export.exe\__main__.py", line 7, in <module>
  File "F:\Programs\Anaconda\envs\nerfstudio2\lib\site-packages\nerfstudio\scripts\exporter.py", line 444, in entrypoint
    tyro.cli(Commands).main()
  File "F:\Programs\Anaconda\envs\nerfstudio2\lib\site-packages\nerfstudio\scripts\exporter.py", line 93, in main
    _, pipeline, _, _ = eval_setup(self.load_config)
  File "F:\Programs\Anaconda\envs\nerfstudio2\lib\site-packages\nerfstudio\utils\eval_utils.py", line 106, in eval_setup
    checkpoint_path, step = eval_load_checkpoint(config, pipeline)
  File "F:\Programs\Anaconda\envs\nerfstudio2\lib\site-packages\nerfstudio\utils\eval_utils.py", line 56, in eval_load_checkpoint
    load_step = sorted(int(x[x.find("-") + 1 : x.find(".")]) for x in os.listdir(config.load_dir))[-1]
  File "F:\Programs\Anaconda\envs\nerfstudio2\lib\site-packages\nerfstudio\utils\eval_utils.py", line 56, in <genexpr>
    load_step = sorted(int(x[x.find("-") + 1 : x.find(".")]) for x in os.listdir(config.load_dir))[-1]
ValueError: invalid literal for int() with base 10: 'material_0'_

**Comment by tancik** [comment]
Can you list the contents of `outputs\me\nerfacto\2023-05-23_143946\nerfstudio_models`

**Comment by NeuroLord** [comment]
> Can you list the contents of `outputs\me\nerfacto\2023-05-23_143946\nerfstudio_models`

It contains a training checkpoint, PLY, OBJ and RGB texture
