### ISSUE TITLE
depth-nerfacto model invokes "PicklingError"

### ISSUE THREAD

**Issue by ardaturkyasar** [nerfstudio-project/nerfstudio#1989]
Hi!

Thank you for this amazing library first of all, I appreciate your effort to keep it up!

I would like to train a depth-supervised nerfacto model, but I am keeping getting "PicklingError" before training starts. Here is the full error code:

`Traceback (most recent call last):
  File "/home/virtualxdesign/.local/bin/ns-train", line 8, in <module>
    sys.exit(entrypoint())
  File "/mnt/d/NerfResearch/nerfstudio/nerfstudio/scripts/train.py", line 260, in entrypoint
    main(
  File "/mnt/d/NerfResearch/nerfstudio/nerfstudio/scripts/train.py", line 246, in main
    launch(
  File "/mnt/d/NerfResearch/nerfstudio/nerfstudio/scripts/train.py", line 200, in launch
    process_context = mp.spawn(
  File "/home/virtualxdesign/.local/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 239, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/virtualxdesign/.local/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    process.start()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/usr/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class 'nerfstudio.data.datamanagers.base_datamanager.VanillaDataManager'>: it's not the same object as nerfstudio.data.datamanagers.base_datamanager.VanillaDataManager`

System information: WSL2 Ubuntu 20.04.6
Nerfstudio version: 0.3.1
Used dataset is in nerfstudio-data format

Full command:
`ns-train depth-nerfacto --vis wandb --data {path_to_data} --output-dir {output_path} --experiment-name {experiment_name} --machine.num-gpus 2 --pipeline.datamanager.train-num-rays-per-batch 16384 nerfstudio-data --orientation-method vertical --center-method focus`

I have no problem using nerfacto, or nerfacto-big , so I am wondering if I am missing something, or this is just a bug. I would be glad if you can help me about that. Thank you!

**Comment by tancik** [comment]
Hmm, thats odd. Can you try with only 1 gpu.

**Comment by ardaturkyasar** [comment]
That worked! Works fine with 1 gpu. Thank you!
