### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory:

### ISSUE THREAD

**Issue by 2680347338** [nerfstudio-project/nerfstudio#2013]
Hi,The data I processed with KIRI Engine APP would show this error during training.
Here are the errors reported

Setting up training dataset...
Caching all 222 images.
Setting up evaluation dataset...
Caching all 24 images.
Traceback (most recent call last):
  File "/root/miniconda3/envs/nerfstudio/bin/ns-train", line 8, in <module>
    sys.exit(entrypoint())
  File "/root/autodl-fs/nerfstudio/nerfstudio/scripts/train.py", line 257, in entrypoint
    main(
  File "/root/autodl-fs/nerfstudio/nerfstudio/scripts/train.py", line 242, in main
    launch(
  File "/root/autodl-fs/nerfstudio/nerfstudio/scripts/train.py", line 189, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "/root/autodl-fs/nerfstudio/nerfstudio/scripts/train.py", line 99, in train_loop
    trainer.setup()
  File "/root/autodl-fs/nerfstudio/nerfstudio/engine/trainer.py", line 144, in setup
    self.pipeline = self.config.pipeline.setup(
  File "/root/autodl-fs/nerfstudio/nerfstudio/configs/base_config.py", line 57, in setup
    return self._target(self, **kwargs)
  File "/root/autodl-fs/nerfstudio/nerfstudio/pipelines/base_pipeline.py", line 245, in __init__
    self.datamanager: VanillaDataManager = config.datamanager.setup(
  File "/root/autodl-fs/nerfstudio/nerfstudio/configs/base_config.py", line 57, in setup
    return self._target(self, **kwargs)
  File "/root/autodl-fs/nerfstudio/nerfstudio/data/datamanagers/base_datamanager.py", line 405, in __init__
    super().__init__()
  File "/root/autodl-fs/nerfstudio/nerfstudio/data/datamanagers/base_datamanager.py", line 184, in __init__
    self.setup_eval()
  File "/root/autodl-fs/nerfstudio/nerfstudio/data/datamanagers/base_datamanager.py", line 469, in setup_eval
    self.eval_image_dataloader = CacheDataloader(
  File "/root/autodl-fs/nerfstudio/nerfstudio/data/utils/dataloaders.py", line 81, in __init__
    self.cached_collated_batch = self._get_collated_batch()
  File "/root/autodl-fs/nerfstudio/nerfstudio/data/utils/dataloaders.py", line 119, in _get_collated_batch
    batch_list = self._get_batch_list()
  File "/root/autodl-fs/nerfstudio/nerfstudio/data/utils/dataloaders.py", line 113, in _get_batch_list
    batch_list.append(res.result())
  File "/root/miniconda3/envs/nerfstudio/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/root/miniconda3/envs/nerfstudio/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/root/miniconda3/envs/nerfstudio/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/autodl-fs/nerfstudio/nerfstudio/data/datasets/base_dataset.py", line 121, in __getitem__
    data = self.get_data(image_idx)
  File "/root/autodl-fs/nerfstudio/nerfstudio/data/datasets/base_dataset.py", line 99, in get_data
    image = self.get_image(image_idx)
  File "/root/autodl-fs/nerfstudio/nerfstudio/data/datasets/base_dataset.py", line 85, in get_image
    image = torch.from_numpy(self.get_numpy_image(image_idx).astype("float32") / 255.0)
  File "/root/autodl-fs/nerfstudio/nerfstudio/data/datasets/base_dataset.py", line 66, in get_numpy_image
    pil_image = Image.open(image_filename)
  File "/root/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/PIL/Image.py", line 3236, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/root/autodl-fs/nerfstudio/data/nerfstudio/camera_pose_flower/images_2/0175.png'

**Comment by 2680347338** [comment]
Amazingly, once I converted the image format to 'jpg', the error disappeared

**Comment by tancik** [comment]
Does a file exist at `/root/autodl-fs/nerfstudio/data/nerfstudio/camera_pose_flower/images_2/0175.png`
What are the permissions?

**Comment by 2680347338** [comment]
> Does a file exist at `/root/autodl-fs/nerfstudio/data/nerfstudio/camera_pose_flower/images_2/0175.png` What are the permissions?

Thank you for your reply, the images are there and the paths are fine because the images are not the same each time they are prompted.
All images under images_2 file are rw-r-r permissions
