### ISSUE TITLE
Error when training with instant-ngp: ImportError: cannot import name 'csrc' from 'nerfacc'

### ISSUE THREAD

**Issue by DarkTemplar91** [nerfstudio-project/nerfstudio#2029]
Hello! Thank you for your amazing work!

When trying to train my dataset with instant-ngp I get the following error:

```
Traceback (most recent call last):
  File "D:\Conda\envs\nerfstudio\lib\site-packages\nerfacc\cuda\_backend.py", line 53, in <module>
    from nerfacc import csrc as _C
ImportError: cannot import name 'csrc' from 'nerfacc' (D:\Conda\envs\nerfstudio\lib\site-packages\nerfacc\__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Conda\envs\nerfstudio\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Conda\envs\nerfstudio\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Conda\envs\nerfstudio\Scripts\ns-train.exe\__main__.py", line 7, in <module>
  File "D:\Conda\envs\nerfstudio\lib\site-packages\nerfstudio\scripts\train.py", line 260, in entrypoint
    main(
  File "D:\Conda\envs\nerfstudio\lib\site-packages\nerfstudio\scripts\train.py", line 246, in main
    launch(
  File "D:\Conda\envs\nerfstudio\lib\site-packages\nerfstudio\scripts\train.py", line 185, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "D:\Conda\envs\nerfstudio\lib\site-packages\nerfstudio\scripts\train.py", line 100, in train_loop
    trainer.train()
  File "D:\Conda\envs\nerfstudio\lib\site-packages\nerfstudio\engine\trainer.py", line 240, in train
    loss, loss_dict, metrics_dict = self.train_iteration(step)
  File "D:\Conda\envs\nerfstudio\lib\site-packages\nerfstudio\utils\profiler.py", line 127, in inner
    out = func(*args, **kwargs)
  File "D:\Conda\envs\nerfstudio\lib\site-packages\nerfstudio\engine\trainer.py", line 446, in train_iteration
    _, loss_dict, metrics_dict = self.pipeline.get_train_loss_dict(step=step)
  File "D:\Conda\envs\nerfstudio\lib\site-packages\nerfstudio\pipelines\dynamic_batch.py", line 77, in get_train_loss_dict
    model_outputs, loss_dict, metrics_dict = super().get_train_loss_dict(step)
  File "D:\Conda\envs\nerfstudio\lib\site-packages\nerfstudio\utils\profiler.py", line 127, in inner
    out = func(*args, **kwargs)
  File "D:\Conda\envs\nerfstudio\lib\site-packages\nerfstudio\pipelines\base_pipeline.py", line 276, in get_train_loss_dict
    model_outputs = self._model(ray_bundle)  # train distributed data parallel model if world_size > 1
  File "D:\Conda\envs\nerfstudio\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\Conda\envs\nerfstudio\lib\site-packages\nerfstudio\models\base_model.py", line 140, in forward
    return self.get_outputs(ray_bundle)
  File "D:\Conda\envs\nerfstudio\lib\site-packages\nerfstudio\models\instant_ngp.py", line 179, in get_outputs
    ray_samples, ray_indices = self.sampler(
  File "D:\Conda\envs\nerfstudio\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\Conda\envs\nerfstudio\lib\site-packages\nerfstudio\model_components\ray_samplers.py", line 482, in forward
    ray_indices, starts, ends = self.occupancy_grid.sampling(
  File "D:\Conda\envs\nerfstudio\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "D:\Conda\envs\nerfstudio\lib\site-packages\nerfacc\estimators\occ_grid.py", line 164, in sampling
    intervals, samples, _ = traverse_grids(
  File "D:\Conda\envs\nerfstudio\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "D:\Conda\envs\nerfstudio\lib\site-packages\nerfacc\grid.py", line 158, in traverse_grids
    t_mins, t_maxs, hits = ray_aabb_intersect(rays_o, rays_d, aabbs)
  File "D:\Conda\envs\nerfstudio\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "D:\Conda\envs\nerfstudio\lib\site-packages\nerfacc\grid.py", line 43, in ray_aabb_intersect
    t_mins, t_maxs, hits = _C.ray_aabb_intersect(
  File "D:\Conda\envs\nerfstudio\lib\site-packages\nerfacc\cuda\__init__.py", line 11, in call_cuda
    from ._backend import _C
  File "D:\Conda\envs\nerfstudio\lib\site-packages\nerfacc\cuda\_backend.py", line 76, in <module>
    _C = load(
  File "D:\Conda\envs\nerfstudio\lib\site-packages\torch\utils\cpp_extension.py", line 1284, in load
    return _jit_compile(
  File "D:\Conda\envs\nerfstudio\lib\site-packages\torch\utils\cpp_extension.py", line 1508, in _jit_compile
    _write_ninja_file_and_build_library(
  File "D:\Conda\envs\nerfstudio\lib\site-packages\torch\utils\cpp_extension.py", line 1610, in _write_ninja_file_and_build_library
    _write_ninja_file_to_build_library(
  File "D:\Conda\envs\nerfstudio\lib\site-packages\torch\utils\cpp_extension.py", line 2055, in _write_ninja_file_to_build_library
    _write_ninja_file(
  File "D:\Conda\envs\nerfstudio\lib\site-packages\torch\utils\cpp_extension.py", line 2195, in _write_ninja_file
    cl_paths = subprocess.check_output(['where',
  File "D:\Conda\envs\nerfstudio\lib\subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "D:\Conda\envs\nerfstudio\lib\subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['where', 'cl']' returned non-zero exit status 1.
```

This issue persist with different datasets and both on my personal windows machine, and on an ubuntu machine as well.
(Granted, the traceback is not the same, but the core issue seems to be)

I have tried reinstalling nerfacc, building it from wheel, updating nerfstudio, but neither of those helped.

Here is the stacktrace that I am getting, when on the Ubuntu machine:

```
Traceback (most recent call last):
  File "/srv/data/mszanto/conda/envs/nerfstudio/lib/python3.8/site-packages/nerfacc/cuda/_backend.py", line 53, in <module>
    from nerfacc import csrc as _C
ImportError: cannot import name 'csrc' from 'nerfacc' (/srv/data/mszanto/conda/envs/nerfstudio/lib/python3.8/site-packages/nerfacc/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/data/mszanto/conda/envs/nerfstudio/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1893, in _run_ninja_build
    subprocess.run(
  File "/srv/data/mszanto/conda/envs/nerfstudio/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/srv/data/mszanto/conda/envs/nerfstudio/bin/ns-train", line 8, in <module>
    sys.exit(entrypoint())
  File "/srv/data/mszanto/conda/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/scripts/train.py", line 260, in entrypoint
    main(
  File "/srv/data/mszanto/conda/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/scripts/train.py", line 246, in main
    launch(
  File "/srv/data/mszanto/conda/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/scripts/train.py", line 185, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "/srv/data/mszanto/conda/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/scripts/train.py", line 100, in train_loop
    trainer.train()
  File "/srv/data/mszanto/conda/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/engine/trainer.py", line 240, in train
    loss, loss_dict, metrics_dict = self.train_iteration(step)
  File "/srv/data/mszanto/conda/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/utils/profiler.py", line 127, in inner
    out = func(*args, **kwargs)
  File "/srv/data/mszanto/conda/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/engine/trainer.py", line 446, in train_iteration
    _, loss_dict, metrics_dict = self.pipeline.get_train_loss_dict(step=step)
  File "/srv/data/mszanto/conda/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/pipelines/dynamic_batch.py", line 77, in get_train_loss_dict
    model_outputs, loss_dict, metrics_dict = super().get_train_loss_dict(step)
  File "/srv/data/mszanto/conda/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/utils/profiler.py", line 127, in inner
    out = func(*args, **kwargs)
  File "/srv/data/mszanto/conda/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/pipelines/base_pipeline.py", line 276, in get_train_loss_dict
    model_outputs = self._model(ray_bundle)  # train distributed data parallel model if world_size > 1
  File "/srv/data/mszanto/conda/envs/nerfstudio/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/srv/data/mszanto/conda/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/models/base_model.py", line 140, in forward
    return self.get_outputs(ray_bundle)
  File "/srv/data/mszanto/conda/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/models/instant_ngp.py", line 179, in get_outputs
    ray_samples, ray_indices = self.sampler(
  File "/srv/data/mszanto/conda/envs/nerfstudio/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/srv/data/mszanto/conda/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/model_components/ray_samplers.py", line 482, in forward
    ray_indices, starts, ends = self.occupancy_grid.sampling(
  File "/srv/data/mszanto/conda/envs/nerfstudio/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/srv/data/mszanto/conda/envs/nerfstudio/lib/python3.8/site-packages/nerfacc/estimators/occ_grid.py", line 164, in sampling
    intervals, samples, _ = traverse_grids(
  File "/srv/data/mszanto/conda/envs/nerfstudio/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/srv/data/mszanto/conda/envs/nerfstudio/lib/python3.8/site-packages/nerfacc/grid.py", line 158, in traverse_grids
    t_mins, t_maxs, hits = ray_aabb_intersect(rays_o, rays_d, aabbs)
  File "/srv/data/mszanto/conda/envs/nerfstudio/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/srv/data/mszanto/conda/envs/nerfstudio/lib/python3.8/site-packages/nerfacc/grid.py", line 43, in ray_aabb_intersect
    t_mins, t_maxs, hits = _C.ray_aabb_intersect(
  File "/srv/data/mszanto/conda/envs/nerfstudio/lib/python3.8/site-packages/nerfacc/cuda/__init__.py", line 11, in call_cuda
    from ._backend import _C
  File "/srv/data/mszanto/conda/envs/nerfstudio/lib/python3.8/site-packages/nerfacc/cuda/_backend.py", line 61, in <module>
    _C = load(
  File "/srv/data/mszanto/conda/envs/nerfstudio/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1284, in load
    return _jit_compile(
  File "/srv/data/mszanto/conda/envs/nerfstudio/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1509, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/srv/data/mszanto/conda/envs/nerfstudio/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1624, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/srv/data/mszanto/conda/envs/nerfstudio/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1909, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'nerfacc_cuda': [1/5] /usr/bin/nvcc  -DTORCH_EXTENSION_NAME=nerfacc_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /srv/data/mszanto/conda/envs/nerfstudio/lib/python3.8/site-packages/torch/include -isystem /srv/data/mszanto/conda/envs/nerfstudio/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /srv/data/mszanto/conda/envs/nerfstudio/lib/python3.8/site-packages/torch/include/TH -isystem /srv/data/mszanto/conda/envs/nerfstudio/lib/python3.8/site-packages/torch/include/THC -isystem /srv/data/mszanto/conda/envs/nerfstudio/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' -O3 -std=c++17 -c /srv/data/mszanto/conda/envs/nerfstudio/lib/python3.8/site-packages/nerfacc/cuda/csrc/pdf.cu -o pdf.cuda.o
FAILED: pdf.cuda.o
/usr/bin/nvcc  -DTORCH_EXTENSION_NAME=nerfacc_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /srv/data/mszanto/conda/envs/nerfstudio/lib/python3.8/site-packages/torch/include -isystem /srv/data/mszanto/conda/envs/nerfstudio/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /srv/data/mszanto/conda/envs/nerfstudio/lib/python3.8/site-packages/torch/include/TH -isystem /srv/data/mszanto/conda/envs/nerfstudio/lib/python3.8/site-packages/torch/include/THC -isystem /srv/data/mszanto/conda/envs/nerfstudio/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' -O3 -std=c++17 -c /srv/data/mszanto/conda/envs/nerfstudio/lib/python3.8/site-packages/nerfacc/cuda/csrc/pdf.cu -o pdf.cuda.o
nvcc fatal   : Value 'c++17' is not defined for option 'std'
[2/5] /usr/bin/nvcc  -DTORCH_EXTENSION_NAME=nerfacc_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /srv/data/mszanto/conda/envs/nerfstudio/lib/python3.8/site-packages/torch/include -isystem /srv/data/mszanto/conda/envs/nerfstudio/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /srv/data/mszanto/conda/envs/nerfstudio/lib/python3.8/site-packages/torch/include/TH -isystem /srv/data/mszanto/conda/envs/nerfstudio/lib/python3.8/site-packages/torch/include/THC -isystem /srv/data/mszanto/conda/envs/nerfstudio/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' -O3 -std=c++17 -c /srv/data/mszanto/conda/envs/nerfstudio/lib/python3.8/site-packages/nerfacc/cuda/csrc/camera.cu -o camera.cuda.o
FAILED: camera.cuda.o
/usr/bin/nvcc  -DTORCH_EXTENSION_NAME=nerfacc_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /srv/data/mszanto/conda/envs/nerfstudio/lib/python3.8/site-packages/torch/include -isystem /srv/data/mszanto/conda/envs/nerfstudio/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /srv/data/mszanto/conda/envs/nerfstudio/lib/python3.8/site-packages/torch/include/TH -isystem /srv/data/mszanto/conda/envs/nerfstudio/lib/python3.8/site-packages/torch/include/THC -isystem /srv/data/mszanto/conda/envs/nerfstudio/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' -O3 -std=c++17 -c /srv/data/mszanto/conda/envs/nerfstudio/lib/python3.8/site-packages/nerfacc/cuda/csrc/camera.cu -o camera.cuda.o
nvcc fatal   : Value 'c++17' is not defined for option 'std'
[3/5] /usr/bin/nvcc  -DTORCH_EXTENSION_NAME=nerfacc_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /srv/data/mszanto/conda/envs/nerfstudio/lib/python3.8/site-packages/torch/include -isystem /srv/data/mszanto/conda/envs/nerfstudio/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /srv/data/mszanto/conda/envs/nerfstudio/lib/python3.8/site-packages/torch/include/TH -isystem /srv/data/mszanto/conda/envs/nerfstudio/lib/python3.8/site-packages/torch/include/THC -isystem /srv/data/mszanto/conda/envs/nerfstudio/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' -O3 -std=c++17 -c /srv/data/mszanto/conda/envs/nerfstudio/lib/python3.8/site-packages/nerfacc/cuda/csrc/grid.cu -o grid.cuda.o
FAILED: grid.cuda.o
/usr/bin/nvcc  -DTORCH_EXTENSION_NAME=nerfacc_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /srv/data/mszanto/conda/envs/nerfstudio/lib/python3.8/site-packages/torch/include -isystem /srv/data/mszanto/conda/envs/nerfstudio/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /srv/data/mszanto/conda/envs/nerfstudio/lib/python3.8/site-packages/torch/include/TH -isystem /srv/data/mszanto/conda/envs/nerfstudio/lib/python3.8/site-packages/torch/include/THC -isystem /srv/data/mszanto/conda/envs/nerfstudio/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' -O3 -std=c++17 -c /srv/data/mszanto/conda/envs/nerfstudio/lib/python3.8/site-packages/nerfacc/cuda/csrc/grid.cu -o grid.cuda.o
nvcc fatal   : Value 'c++17' is not defined for option 'std'
[4/5] /usr/bin/nvcc  -DTORCH_EXTENSION_NAME=nerfacc_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /srv/data/mszanto/conda/envs/nerfstudio/lib/python3.8/site-packages/torch/include -isystem /srv/data/mszanto/conda/envs/nerfstudio/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /srv/data/mszanto/conda/envs/nerfstudio/lib/python3.8/site-packages/torch/include/TH -isystem /srv/data/mszanto/conda/envs/nerfstudio/lib/python3.8/site-packages/torch/include/THC -isystem /srv/data/mszanto/conda/envs/nerfstudio/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' -O3 -std=c++17 -c /srv/data/mszanto/conda/envs/nerfstudio/lib/python3.8/site-packages/nerfacc/cuda/csrc/scan.cu -o scan.cuda.o
FAILED: scan.cuda.o
/usr/bin/nvcc  -DTORCH_EXTENSION_NAME=nerfacc_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /srv/data/mszanto/conda/envs/nerfstudio/lib/python3.8/site-packages/torch/include -isystem /srv/data/mszanto/conda/envs/nerfstudio/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /srv/data/mszanto/conda/envs/nerfstudio/lib/python3.8/site-packages/torch/include/TH -isystem /srv/data/mszanto/conda/envs/nerfstudio/lib/python3.8/site-packages/torch/include/THC -isystem /srv/data/mszanto/conda/envs/nerfstudio/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' -O3 -std=c++17 -c /srv/data/mszanto/conda/envs/nerfstudio/lib/python3.8/site-packages/nerfacc/cuda/csrc/scan.cu -o scan.cuda.o
nvcc fatal   : Value 'c++17' is not defined for option 'std'
ninja: build stopped: subcommand failed.
```

Is there a know solution for this problem?
Thank you in advance!

**Comment by zhumorui** [comment]
Same issue on ubuntu 22.04 while trying ns-train instant-ngp:

Printing profiling stats, from longest to shortest duration in seconds
Trainer.train_iteration: 44.8143             
VanillaPipeline.get_train_loss_dict: 44.8140             
Traceback (most recent call last):
  File "/home/morin/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfacc/cuda/_backend.py", line 53, in <module>
    from nerfacc import csrc as _C
ImportError: cannot import name 'csrc' from 'nerfacc' (/home/morin/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfacc/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/morin/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1893, in _run_ninja_build
    subprocess.run(
  File "/home/morin/anaconda3/envs/nerfstudio/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

**Comment by zhumorui** [comment]
I have solved this issue by referencing [#autonomousvision/sdfstudio#46](https://github.com/autonomousvision/sdfstudio/issues/46). Here is the possible solution:

```bash
pip uninstall nerfacc
pip install git+https://github.com/KAIR-BAIR/nerfacc.git
```
I hope this resolves your problem!

**Comment by DarkTemplar91** [comment]
Thank you so much, it works for me now!

**Comment by DarkTemplar91** [comment]
> I have solved this issue by referencing [#autonomousvision/sdfstudio#46](https://github.com/autonomousvision/sdfstudio/issues/46). Here is the possible solution:
> 
> ```shell
> pip uninstall nerfacc
> pip install git+https://github.com/KAIR-BAIR/nerfacc.git
> ```
> 
> I hope this resolves your problem!

Thank you so much, it works for me now!
