### ISSUE TITLE
Completion script generation failed at Docker 

### ISSUE THREAD

**Issue by aboutyy** [nerfstudio-project/nerfstudio#2052]
**Describe the bug**
I install the docker image by two ways:
docker pull dromni/nerfstudio:0.3.1
docker build --build-arg CUDA_ARCHITECTURES=86 --tag nerfstudio-86 -f Dockerfile .

When using 
sudo docker run -it --rm --gpus all nerfstudio-86 nvidia-smi 
it outputs right.

The neither work out, having similar problems.

**To Reproduce**
sudo docker run -it --rm --gpus all dromni/nerfstudio:0.3.1

**Additional context**

My graphics is NVIDIA GeForce RTX 3090/PCIe/SSE2 / NVIDIA Corporation. And I am still having problems.

sudo docker run -it --rm --gpus all dromni/nerfstudio:0.3.1

==========
== CUDA ==
CUDA Version 11.8.0

Container image Copyright (c) 2016-2022, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

[07:33:03] shrug .zshrc not found, skipping. install.py:370
mag Found .bashrc! install.py:372
heavy_check_mark Wrote new completion to install.py:134
/home/user/nerfstudio/nerfstudio/scripts/completions/bash/_ns-install-cli!
heavy_check_mark Wrote new completion to install.py:134
/home/user/nerfstudio/nerfstudio/scripts/completions/bash/_ns-dev-test!
[07:33:06] heavy_check_mark Wrote new completion to install.py:134
/home/user/nerfstudio/nerfstudio/scripts/completions/bash/_ns-dev-sync-viser-message-defs!
heavy_check_mark Wrote new completion to install.py:134
/home/user/nerfstudio/nerfstudio/scripts/completions/bash/_ns-process-data!
heavy_check_mark Wrote new completion to install.py:134
/home/user/nerfstudio/nerfstudio/scripts/completions/bash/_ns-download-data!
[07:33:08] heavy_check_mark Wrote new completion to install.py:134
/home/user/nerfstudio/nerfstudio/scripts/completions/bash/_ns-render!
heavy_check_mark Wrote new completion to /home/user/nerfstudio/nerfstudio/scripts/completions/bash/_ns-eval! install.py:134
heavy_check_mark Wrote new completion to install.py:134
/home/user/nerfstudio/nerfstudio/scripts/completions/bash/_ns-viewer!
x Completion script generation failed: ['ns-train', '--tyro-print-completion', 'bash'] install.py:124
/home/user/.local/lib/python3.10/site-packages/torch/cuda/init.py:107: UserWarning: CUDA install.py:128
initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions
before calling NumCudaDevices() that might have already set an error? Error 804: forward
compatibility was attempted on non supported HW (Triggered internally at
../c10/cuda/CUDAFunctions.cpp:109.)
return torch._C._cuda_getDeviceCount() > 0
Traceback (most recent call last):
File "/home/user/.local/bin/ns-train", line 5, in
from nerfstudio.scripts.train import entrypoint
File "/home/user/nerfstudio/nerfstudio/scripts/train.py", line 62, in
from nerfstudio.configs.method_configs import AnnotatedBaseConfigUnion
File "/home/user/nerfstudio/nerfstudio/configs/method_configs.py", line 55, in
from nerfstudio.field_components.temporal_distortions import TemporalDistortionKind
File "/home/user/nerfstudio/nerfstudio/field_components/init.py", line 17, in
from .encodings import Encoding as Encoding
File "/home/user/nerfstudio/nerfstudio/field_components/encodings.py", line 34, in
import tinycudann as tcnn
File "/home/user/.local/lib/python3.10/site-packages/tinycudann/init.py", line 9, in

from tinycudann.modules import free_temporary_memory, NetworkWithInputEncoding, Network,
Encoding
File "/home/user/.local/lib/python3.10/site-packages/tinycudann/modules.py", line 18, in

raise EnvironmentError("Unknown compute capability. Ensure PyTorch with CUDA support is
installed.")
OSError: Unknown compute capability. Ensure PyTorch with CUDA support is installed.

[07:33:09] x Completion script generation failed: ['ns-export', '--tyro-print-completion', 'bash'] install.py:124
/home/user/.local/lib/python3.10/site-packages/torch/cuda/init.py:107: UserWarning: CUDA install.py:128
initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions
before calling NumCudaDevices() that might have already set an error? Error 804: forward
compatibility was attempted on non supported HW (Triggered internally at
../c10/cuda/CUDAFunctions.cpp:109.)
return torch._C._cuda_getDeviceCount() > 0
Traceback (most recent call last):
File "/home/user/.local/bin/ns-export", line 5, in
from nerfstudio.scripts.exporter import entrypoint
File "/home/user/nerfstudio/nerfstudio/scripts/exporter.py", line 46, in
from nerfstudio.fields.sdf_field import SDFField
File "/home/user/nerfstudio/nerfstudio/fields/sdf_field.py", line 31, in
from nerfstudio.field_components.embedding import Embedding
File "/home/user/nerfstudio/nerfstudio/field_components/init.py", line 17, in
from .encodings import Encoding as Encoding
File "/home/user/nerfstudio/nerfstudio/field_components/encodings.py", line 34, in
import tinycudann as tcnn
File "/home/user/.local/lib/python3.10/site-packages/tinycudann/init.py", line 9, in

from tinycudann.modules import free_temporary_memory, NetworkWithInputEncoding, Network,
Encoding
File "/home/user/.local/lib/python3.10/site-packages/tinycudann/modules.py", line 18, in

raise EnvironmentError("Unknown compute capability. Ensure PyTorch with CUDA support is
installed.")
OSError: Unknown compute capability. Ensure PyTorch with CUDA support is installed.

Traceback (most recent call last):
File "/home/user/.local/bin/ns-install-cli", line 8, in
sys.exit(entrypoint())
File "/home/user/nerfstudio/nerfstudio/scripts/completions/install.py", line 412, in entrypoint
tyro.cli(main, description=doc)
File "/home/user/.local/lib/python3.10/site-packages/tyro/_cli.py", line 177, in cli
output = _cli_impl(
File "/home/user/.local/lib/python3.10/site-packages/tyro/_cli.py", line 429, in _cli_impl
out, consumed_keywords = _calling.call_from_args(
File "/home/user/.local/lib/python3.10/site-packages/tyro/_calling.py", line 204, in call_from_args
return unwrapped_f(*positional_args, **kwargs), consumed_keywords # type: ignore
File "/home/user/nerfstudio/nerfstudio/scripts/completions/install.py", line 393, in main
_generate_completions_files(completions_dir, scripts_dir, shells_supported, shells_found)
File "/home/user/nerfstudio/nerfstudio/scripts/completions/install.py", line 324, in _generate_completions_files
completion_paths = list(
File "/usr/lib/python3.10/concurrent/futures/_base.py", line 621, in result_iterator
yield _result_or_cancel(fs.pop())
File "/usr/lib/python3.10/concurrent/futures/_base.py", line 319, in _result_or_cancel
return fut.result(timeout)
File "/usr/lib/python3.10/concurrent/futures/_base.py", line 458, in result
return self.__get_result()
File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
raise self._exception
File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/home/user/nerfstudio/nerfstudio/scripts/completions/install.py", line 326, in
lambda path_or_entrypoint_and_shell: _generate_completion(
File "/home/user/nerfstudio/nerfstudio/scripts/completions/install.py", line 129, in _generate_completion
raise e
File "/home/user/nerfstudio/nerfstudio/scripts/completions/install.py", line 116, in _generate_completion
new = subprocess.run(
File "/usr/lib/python3.10/subprocess.py", line 524, in run
raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ns-export', '--tyro-print-completion', 'bash']' returned non-zero exit status 1.

**Comment by aboutyy** [comment]
Upgrated my nvidia driver version from 510 to 525 and it worked. The error occurs because cuda 11.8 requires [nvidia driver version > 525.61.05.](https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html)
