### ISSUE TITLE
download and train data dosent work

### ISSUE THREAD

**Issue by amirgame197** [nerfstudio-project/nerfstudio#2096]
**Describe the bug**
i have installed nerfstudio and all of its dependencies. then i ran the downloading a test data command to get on section2 on main readme.md file
but after 5 seconds it gaves me this error :

```
(nerfstudio) C:\Users\amirg>ns-download-data nerfstudio --capture-name=poster
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\programs\miniconda3\envs\nerfstudio\Scripts\ns-download-data.exe\__main__.py", line 4, in <module>
  File "C:\Users\amirg\nerfstudio\nerfstudio\scripts\downloads\download_data.py", line 30, in <module>
    from nerfstudio.configs.base_config import PrintableConfig
  File "C:\Users\amirg\nerfstudio\nerfstudio\configs\base_config.py", line 108, in <module>
    @dataclass
     ^^^^^^^^^
  File "D:\programs\miniconda3\envs\nerfstudio\Lib\dataclasses.py", line 1223, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "D:\programs\miniconda3\envs\nerfstudio\Lib\dataclasses.py", line 1213, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\programs\miniconda3\envs\nerfstudio\Lib\dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\programs\miniconda3\envs\nerfstudio\Lib\dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'nerfstudio.configs.base_config.LocalWriterConfig'> for field local_writer is not allowed: use default_factory
```
what is the problem? i couldnt even run the second command because its giving me same error (almost)

**Comment by amirgame197** [comment]
it is still a problem...

**Comment by tancik** [comment]
What version of python are you using?

**Comment by amirgame197** [comment]
> What version of python are you using?

3.11

**Comment by amirgame197** [comment]
@tancik is there any problem with my python version?

**Comment by liyiming88** [comment]
Hi I encountered the same issue. Have you solved it yet?

**Comment by amirgame197** [comment]
@liyiming88 @yoponchik 
hi. sorry, for some reason i was not receiving the notifications from github. the issue is still there and i haven't touched nerfstudio for a while
