### ISSUE TITLE
rich MarkupError

### ISSUE THREAD

**Issue by forEachWhileTrue** [nerfstudio-project/nerfstudio#2105]
Hello there,

I'm running nerfstudio on an Azure Maching Learning VM with Ubuntu 18.04.
When I try to process data with `ns-process-data images` I get an error which is thrown by the rich library after downscaling the images:

<img width="1354" alt="Screenshot 2023-06-20 at 15 17 41" src="https://github.com/nerfstudio-project/nerfstudio/assets/45185395/576403a8-ba9d-431c-98db-21626782e66e">

I already processed polycam data which worked without problems. So this error only appears in combination with colmap.

Hope you can help me and thanks in advance!

**Comment by forEachWhileTrue** [comment]
I'm a bit in a hurry to get this running, so if someone could help me out here, I would really appreciate it. :)

**Comment by tancik** [comment]
Can you check that your terminal is set up to use UTF-8

**Comment by forEachWhileTrue** [comment]
> Can you check that your terminal is set up to use UTF-8

Yes, it is but it’s still not working.

**Comment by Terry10086** [comment]
Here is the error information
`──────────────────────────────────────────────  💀 💀 💀 ERROR 💀 💀 💀  ───────────────────────────────────────────────
Error running command: colmap feature_extractor --database_path data/nerfstudio/render/colmap/database.db --image_path 
data/nerfstudio/render/images --ImageReader.single_camera 1 --ImageReader.camera_model OPENCV --SiftExtraction.use_gpu 1
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Traceback (most recent call last):
  File "/home/yangtongyu/.conda/envs/nerfstudio/bin/ns-process-data", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/yangtongyu/nerf/nerfstudio/nerfstudio/scripts/process_data.py", line 408, in entrypoint
    tyro.cli(Commands).main()
  File "/home/yangtongyu/nerf/nerfstudio/nerfstudio/process_data/images_to_nerfstudio_dataset.py", line 82, in main
    self._run_colmap()
  File "/home/yangtongyu/nerf/nerfstudio/nerfstudio/process_data/colmap_converter_to_nerfstudio_dataset.py", line 199, in _run_colmap
    colmap_utils.run_colmap(
  File "/home/yangtongyu/nerf/nerfstudio/nerfstudio/process_data/colmap_utils.py", line 129, in run_colmap
    run_command(feature_extractor_cmd, verbose=verbose)
  File "/home/yangtongyu/nerf/nerfstudio/nerfstudio/utils/scripts.py", line 37, in run_command
    CONSOLE.print(out.stderr.decode("utf-8"))
  File "/home/yangtongyu/.conda/envs/nerfstudio/lib/python3.8/site-packages/rich/console.py", line 1673, in print
    renderables = self._collect_renderables(
  File "/home/yangtongyu/.conda/envs/nerfstudio/lib/python3.8/site-packages/rich/console.py", line 1537, in _collect_renderables
    self.render_str(
  File "/home/yangtongyu/.conda/envs/nerfstudio/lib/python3.8/site-packages/rich/console.py", line 1429, in render_str
    rich_text = render_markup(
  File "/home/yangtongyu/.conda/envs/nerfstudio/lib/python3.8/site-packages/rich/markup.py", line 158, in render
    print(pop_style(style_name))
  File "/home/yangtongyu/.conda/envs/nerfstudio/lib/python3.8/site-packages/rich/markup.py", line 145, in pop_style
    raise KeyError(style_name)
KeyError: 'home/conda/feedstock_root/build_artifacts/colmap_1686935602614/work/src/base/database.cc, line 270'
(nerfstudio) yangtongyu@amax21-1:~/nerf/nerfstudio$ ns-process-data images --data data/nerfstudio/render --output-dir data/nerfstudio/render
[12:02:24] 🎉 Done copying images.                                                             process_data_utils.py:241
[12:02:27] 🎉 Done downscaling images.                                                         process_data_utils.py:364
──────────────────────────────────────────────  💀 💀 💀 ERROR 💀 💀 💀  ───────────────────────────────────────────────
Error running command: colmap feature_extractor --database_path data/nerfstudio/render/colmap/database.db --image_path 
data/nerfstudio/render/images --ImageReader.single_camera 1 --ImageReader.camera_model OPENCV --SiftExtraction.use_gpu 1
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Traceback (most recent call last):
  File "/home/yangtongyu/.conda/envs/nerfstudio/bin/ns-process-data", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/yangtongyu/nerf/nerfstudio/nerfstudio/scripts/process_data.py", line 408, in entrypoint
    tyro.cli(Commands).main()
  File "/home/yangtongyu/nerf/nerfstudio/nerfstudio/process_data/images_to_nerfstudio_dataset.py", line 82, in main
    self._run_colmap()
  File "/home/yangtongyu/nerf/nerfstudio/nerfstudio/process_data/colmap_converter_to_nerfstudio_dataset.py", line 199, in _run_colmap
    colmap_utils.run_colmap(
  File "/home/yangtongyu/nerf/nerfstudio/nerfstudio/process_data/colmap_utils.py", line 129, in run_colmap
    run_command(feature_extractor_cmd, verbose=verbose)
  File "/home/yangtongyu/nerf/nerfstudio/nerfstudio/utils/scripts.py", line 37, in run_command
    CONSOLE.print(out.stderr.decode("utf-8"))
  File "/home/yangtongyu/.conda/envs/nerfstudio/lib/python3.8/site-packages/rich/console.py", line 1673, in print
    renderables = self._collect_renderables(
  File "/home/yangtongyu/.conda/envs/nerfstudio/lib/python3.8/site-packages/rich/console.py", line 1537, in _collect_renderables
    self.render_str(
  File "/home/yangtongyu/.conda/envs/nerfstudio/lib/python3.8/site-packages/rich/console.py", line 1429, in render_str
    rich_text = render_markup(
  File "/home/yangtongyu/.conda/envs/nerfstudio/lib/python3.8/site-packages/rich/markup.py", line 161, in render
    raise MarkupError(
rich.errors.MarkupError: closing tag '[/home/conda/feedstock_root/build_artifacts/colmap_1686935602614/work/src/base/database.cc, line 270]' at position 13 doesn't match any open tag`

**Comment by forEachWhileTrue** [comment]
Hey, is there another solution? Because my terminal supports UTF-8 but it's still not working. :(

**Comment by lan-creator** [comment]
Hi everyone, has anyone finished this problem? I found that if I use only cpu to process it will be fine (but this is too slow). Does colmap/ns-process-data can use gpu?

**Comment by HugoFeng** [comment]
I'm using the official docker image and encontered the same problem. My solution is to edit line 37 of scripts.py, using try and except with print() instead of rich console if anything goes wrong. So that it prints the correct error messages.

**Comment by HugoFeng** [comment]
> Here is the error information `────────────────────────────────────────────── 💀 💀 💀 ERROR 💀 💀 💀 ─────────────────────────────────────────────── Error running command: colmap feature_extractor --database_path data/nerfstudio/render/colmap/database.db --image_path data/nerfstudio/render/images --ImageReader.single_camera 1 --ImageReader.camera_model OPENCV --SiftExtraction.use_gpu 1 ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── Traceback (most recent call last): File "/home/yangtongyu/.conda/envs/nerfstudio/bin/ns-process-data", line 8, in <module> sys.exit(entrypoint()) File "/home/yangtongyu/nerf/nerfstudio/nerfstudio/scripts/process_data.py", line 408, in entrypoint tyro.cli(Commands).main() File "/home/yangtongyu/nerf/nerfstudio/nerfstudio/process_data/images_to_nerfstudio_dataset.py", line 82, in main self._run_colmap() File "/home/yangtongyu/nerf/nerfstudio/nerfstudio/process_data/colmap_converter_to_nerfstudio_dataset.py", line 199, in _run_colmap colmap_utils.run_colmap( File "/home/yangtongyu/nerf/nerfstudio/nerfstudio/process_data/colmap_utils.py", line 129, in run_colmap run_command(feature_extractor_cmd, verbose=verbose) File "/home/yangtongyu/nerf/nerfstudio/nerfstudio/utils/scripts.py", line 37, in run_command CONSOLE.print(out.stderr.decode("utf-8")) File "/home/yangtongyu/.conda/envs/nerfstudio/lib/python3.8/site-packages/rich/console.py", line 1673, in print renderables = self._collect_renderables( File "/home/yangtongyu/.conda/envs/nerfstudio/lib/python3.8/site-packages/rich/console.py", line 1537, in _collect_renderables self.render_str( File "/home/yangtongyu/.conda/envs/nerfstudio/lib/python3.8/site-packages/rich/console.py", line 1429, in render_str rich_text = render_markup( File "/home/yangtongyu/.conda/envs/nerfstudio/lib/python3.8/site-packages/rich/markup.py", line 158, in render print(pop_style(style_name)) File "/home/yangtongyu/.conda/envs/nerfstudio/lib/python3.8/site-packages/rich/markup.py", line 145, in pop_style raise KeyError(style_name) KeyError: 'home/conda/feedstock_root/build_artifacts/colmap_1686935602614/work/src/base/database.cc, line 270' (nerfstudio) yangtongyu@amax21-1:~/nerf/nerfstudio$ ns-process-data images --data data/nerfstudio/render --output-dir data/nerfstudio/render [12:02:24] 🎉 Done copying images. process_data_utils.py:241 [12:02:27] 🎉 Done downscaling images. process_data_utils.py:364 ────────────────────────────────────────────── 💀 💀 💀 ERROR 💀 💀 💀 ─────────────────────────────────────────────── Error running command: colmap feature_extractor --database_path data/nerfstudio/render/colmap/database.db --image_path data/nerfstudio/render/images --ImageReader.single_camera 1 --ImageReader.camera_model OPENCV --SiftExtraction.use_gpu 1 ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── Traceback (most recent call last): File "/home/yangtongyu/.conda/envs/nerfstudio/bin/ns-process-data", line 8, in <module> sys.exit(entrypoint()) File "/home/yangtongyu/nerf/nerfstudio/nerfstudio/scripts/process_data.py", line 408, in entrypoint tyro.cli(Commands).main() File "/home/yangtongyu/nerf/nerfstudio/nerfstudio/process_data/images_to_nerfstudio_dataset.py", line 82, in main self._run_colmap() File "/home/yangtongyu/nerf/nerfstudio/nerfstudio/process_data/colmap_converter_to_nerfstudio_dataset.py", line 199, in _run_colmap colmap_utils.run_colmap( File "/home/yangtongyu/nerf/nerfstudio/nerfstudio/process_data/colmap_utils.py", line 129, in run_colmap run_command(feature_extractor_cmd, verbose=verbose) File "/home/yangtongyu/nerf/nerfstudio/nerfstudio/utils/scripts.py", line 37, in run_command CONSOLE.print(out.stderr.decode("utf-8")) File "/home/yangtongyu/.conda/envs/nerfstudio/lib/python3.8/site-packages/rich/console.py", line 1673, in print renderables = self._collect_renderables( File "/home/yangtongyu/.conda/envs/nerfstudio/lib/python3.8/site-packages/rich/console.py", line 1537, in _collect_renderables self.render_str( File "/home/yangtongyu/.conda/envs/nerfstudio/lib/python3.8/site-packages/rich/console.py", line 1429, in render_str rich_text = render_markup( File "/home/yangtongyu/.conda/envs/nerfstudio/lib/python3.8/site-packages/rich/markup.py", line 161, in render raise MarkupError( rich.errors.MarkupError: closing tag '[/home/conda/feedstock_root/build_artifacts/colmap_1686935602614/work/src/base/database.cc, line 270]' at position 13 doesn't match any open tag`

same problem, seems like my output dir is within my NAS, which may goes wrong with some linux file permissions. When I change the output dir to a folder under docker /workspace/ , everything goes well.

**Comment by Jordan-Pierce** [comment]
Agree with @HugoFeng and @deephog, the issue might be coming from a database.db lock, which is based on it's location. I'm working on a remote Linux machine and ran into the issue. I moved the output folder somewhere up the directories and it worked as expected.

**Comment by qf-wei** [comment]
hey guys I got a possible solution,

If you're mounting the NAS on Linux using the `mount` command, make sure to toss in the `nobrl` option. This little trick helps avoid those annoying locking problems.

Just run something like this:

`
sudo mount -t cifs -o username=USERNAME,uid=$(id -u),gid=$(id -g),iocharset=utf8,nobrl //192.168.X.XX/Main /nas/Main
`

This should sort out those pesky errors about file permissions and database locks.
