### ISSUE TITLE
`!ns-viewer --load-config` No such file or directory: 'outputs/unnamed/nerfacto/2023-06-23_173438/config.yml'

### ISSUE THREAD

**Issue by ZemtsH** [nerfstudio-project/nerfstudio#2123]
Error while I am trying run `!ns-viewer --load-config outputs/unnamed/nerfacto/2023-06-23_173438/config.yml`
```
2023-06-23 18:41:29.546218: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "/usr/local/bin/ns-viewer", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.10/dist-packages/nerfstudio/scripts/viewer/run_viewer.py", line 112, in entrypoint
    tyro.cli(RunViewer).main()
  File "/usr/local/lib/python3.10/dist-packages/nerfstudio/scripts/viewer/run_viewer.py", line 57, in main
    config, pipeline, _, step = eval_setup(
  File "/usr/local/lib/python3.10/dist-packages/nerfstudio/utils/eval_utils.py", line 88, in eval_setup
    config = yaml.load(config_path.read_text(), Loader=yaml.Loader)
  File "/usr/lib/python3.10/pathlib.py", line 1134, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/usr/lib/python3.10/pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
FileNotFoundError: [Errno 2] No such file or directory: 'outputs/unnamed/nerfacto/2023-06-23_173438/config.yml'
```

**Comment by jkulhanek** [comment]
Perhaps a stupid question from my side, but does the file "outputs/unnamed/nerfacto/2023-06-23_173438/config.yml" exist? Can you try running `!ls -la outputs/unnamed/nerfacto/2023-06-23_173438`?
