### ISSUE TITLE
Inference torch-based nerfacto models

### ISSUE THREAD

**Issue by Ilyabasharov** [nerfstudio-project/nerfstudio#2162]
**Describe the bug**
Cannot infer torch-based nerfacto-like models

**To Reproduce**
```bash
ns-train nerfacto --data data/nerfstudio/poster/ --pipeline.model.implementation torch
ns-viewer --load-config <your_experiment_path>/config.yml --vis viewer_beta
```

**Expected behavior**
Inference without errors :)

**Additional context**
```bash
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/user/nerfstudio/nerfstudio/viewer_beta/render_state_machine.py", line 178, in run
    outputs = self._render_img(action.camera_state)
  File "/home/user/nerfstudio/nerfstudio/viewer_beta/render_state_machine.py", line 154, in _render_img
    outputs = self.viewer.get_model().get_outputs_for_camera_ray_bundle(camera_ray_bundle)
  File "/home/user/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/user/nerfstudio/nerfstudio/models/base_model.py", line 179, in get_outputs_for_camera_ray_bundle
    outputs = self.forward(ray_bundle=ray_bundle)
  File "/home/user/nerfstudio/nerfstudio/models/base_model.py", line 142, in forward
    return self.get_outputs(ray_bundle)
  File "/home/user/nerfstudio/nerfstudio/models/nerfacto.py", line 277, in get_outputs
    ray_samples, weights_list, ray_samples_list = self.proposal_sampler(ray_bundle, density_fns=self.density_fns)
  File "/home/user/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/nerfstudio/nerfstudio/model_components/ray_samplers.py", line 50, in forward
    return self.generate_ray_samples(*args, **kwargs)
  File "/home/user/nerfstudio/nerfstudio/model_components/ray_samplers.py", line 603, in generate_ray_samples
    density = density_fns[i_level](ray_samples.frustums.get_positions())
  File "/home/user/nerfstudio/nerfstudio/fields/base_field.py", line 67, in density_fn
    density, _ = self.get_density(ray_samples)
  File "/home/user/nerfstudio/nerfstudio/fields/density_fields.py", line 105, in get_density
    self.mlp_base(positions_flat).view(*ray_samples.frustums.shape, -1).to(positions)
  File "/home/user/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/home/user/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/nerfstudio/nerfstudio/field_components/mlp.py", line 179, in forward
    return self.pytorch_fwd(in_tensor)
  File "/home/user/nerfstudio/nerfstudio/field_components/mlp.py", line 169, in pytorch_fwd
    x = layer(x)
  File "/home/user/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 must have the same dtype
```

**Comment by Tianchong-Jiang** [comment]
You need to have the line
`with torch.autocast(device_type=cpu_or_cuda_str, enabled=self.mixed_precision):`
in inference as well.
