### ISSUE TITLE
instant-ngp throws value error while training evaluation (about LPIPS data range)

### ISSUE THREAD

**Issue by WeiGuaa** [nerfstudio-project/nerfstudio#2192]
**Describe the bug**
When I was training instant-ngp, a value error was thrown, which seems to be related to the calculation of LPIPS.

**To Reproduce**
Instant-ngp has the same error message in both lego and apsen dataset training.
The command line is as follows:
`ns-train instant-ngp --vis viewer+wandb --data data/blender/lego blender-data`
`ns-train instant-ngp --vis viewer+wandb --data data/nerfstudio/aspen  --max-num-iterations 500000`

**Expected behavior**
Details of the error thrown:
1. lego
`26 Traceback (most recent call last):
27   File "/home/jxwei/app/miniconda3/envs/nerfstudio/bin/ns-train", line 8, in <module>
28     sys.exit(entrypoint())
29   File "/home/jxwei/src/nerfstudio/nerfstudio/scripts/train.py", line 261, in entrypoint
30     main(
31   File "/home/jxwei/src/nerfstudio/nerfstudio/scripts/train.py", line 246, in main
32     launch(
33   File "/home/jxwei/src/nerfstudio/nerfstudio/scripts/train.py", line 189, in launch
34     main_func(local_rank=0, world_size=world_size, config=config)
35   File "/home/jxwei/src/nerfstudio/nerfstudio/scripts/train.py", line 100, in train_loop
36     trainer.train()
37   File "/home/jxwei/src/nerfstudio/nerfstudio/engine/trainer.py", line 292, in train
38     self.eval_iteration(step)
39   File "/home/jxwei/src/nerfstudio/nerfstudio/utils/decorators.py", line 70, in wrapper
40     ret = func(self, *args, **kwargs)
41   File "/home/jxwei/src/nerfstudio/nerfstudio/utils/profiler.py", line 127, in inner
42     out = func(*args, **kwargs)
43   File "/home/jxwei/src/nerfstudio/nerfstudio/engine/trainer.py", line 513, in eval_iteration
44     metrics_dict, images_dict = self.pipeline.get_eval_image_metrics_and_images(step=step)
45   File "/home/jxwei/src/nerfstudio/nerfstudio/utils/profiler.py", line 127, in inner
46     out = func(*args, **kwargs)
47   File "/home/jxwei/src/nerfstudio/nerfstudio/pipelines/base_pipeline.py", line 340, in get_eval_image_metrics_and_images
48     metrics_dict, images_dict = self.model.get_image_metrics_and_images(outputs, batch)
49   File "/home/jxwei/src/nerfstudio/nerfstudio/models/instant_ngp.py", line 254, in get_image_metrics_and_images
50     lpips = self.lpips(image, rgb)
51   File "/home/jxwei/app/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
52     return forward_call(*args, **kwargs)
53   File "/home/jxwei/app/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/torchmetrics/metric.py", line 290, in forward
54     self._forward_cache = self._forward_reduce_state_update(*args, **kwargs)
55   File "/home/jxwei/app/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/torchmetrics/metric.py", line 357, in _forward_reduce_state_update
56     self.update(*args, **kwargs)
57   File "/home/jxwei/app/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/torchmetrics/metric.py", line 446, in wrapped_func
58     update(*args, **kwargs)
59   File "/home/jxwei/app/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/torchmetrics/image/lpip.py", line 140, in update
60     loss, total = _lpips_update(img1, img2, net=self.net, normalize=self.normalize)
61   File "/home/jxwei/app/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/torchmetrics/functional/image/lpips.py", line 346, in _lpips_update
62     raise ValueError(
63 ValueError: Expected both input arguments to be normalized tensors with shape [N, 3, H, W]. Got input with shape torch.Size([1, 3, 800, 800]) and torch.Size([1, 3, 800, 800]) and values in range [tensor(0., device='cuda:0'), tensor(1., device='cuda:0')] and [tensor(0.0497, device='cuda:0'), tensor(1.0000, device='cuda:0')] when all values are expected to be in the [0, 1] range.`

2. aspen:
‘22 Traceback (most recent call last):
23   File "/home/jxwei/app/miniconda3/envs/nerfstudio/bin/ns-train", line 8, in <module>
24     sys.exit(entrypoint())
25   File "/home/jxwei/src/nerfstudio/nerfstudio/scripts/train.py", line 261, in entrypoint
26     main(
27   File "/home/jxwei/src/nerfstudio/nerfstudio/scripts/train.py", line 246, in main
28     launch(
29   File "/home/jxwei/src/nerfstudio/nerfstudio/scripts/train.py", line 189, in launch
30     main_func(local_rank=0, world_size=world_size, config=config)
31   File "/home/jxwei/src/nerfstudio/nerfstudio/scripts/train.py", line 100, in train_loop
32     trainer.train()
33   File "/home/jxwei/src/nerfstudio/nerfstudio/engine/trainer.py", line 292, in train
34     self.eval_iteration(step)
35   File "/home/jxwei/src/nerfstudio/nerfstudio/utils/decorators.py", line 70, in wrapper
36     ret = func(self, *args, **kwargs)
37   File "/home/jxwei/src/nerfstudio/nerfstudio/utils/profiler.py", line 127, in inner
38     out = func(*args, **kwargs)
39   File "/home/jxwei/src/nerfstudio/nerfstudio/engine/trainer.py", line 513, in eval_iteration
40     metrics_dict, images_dict = self.pipeline.get_eval_image_metrics_and_images(step=step)
41   File "/home/jxwei/src/nerfstudio/nerfstudio/utils/profiler.py", line 127, in inner
42     out = func(*args, **kwargs)
43   File "/home/jxwei/src/nerfstudio/nerfstudio/pipelines/base_pipeline.py", line 340, in get_eval_image_metrics_and_images
44     metrics_dict, images_dict = self.model.get_image_metrics_and_images(outputs, batch)
45   File "/home/jxwei/src/nerfstudio/nerfstudio/models/instant_ngp.py", line 254, in get_image_metrics_and_images
46     lpips = self.lpips(image, rgb)
47   File "/home/jxwei/app/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
48     return forward_call(*args, **kwargs)
49   File "/home/jxwei/app/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/torchmetrics/metric.py", line 290, in forward
50     self._forward_cache = self._forward_reduce_state_update(*args, **kwargs)
51   File "/home/jxwei/app/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/torchmetrics/metric.py", line 357, in _forward_reduce_state_update
52     self.update(*args, **kwargs)
53   File "/home/jxwei/app/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/torchmetrics/metric.py", line 446, in wrapped_func
54     update(*args, **kwargs)
55   File "/home/jxwei/app/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/torchmetrics/image/lpip.py", line 140, in update
56     loss, total = _lpips_update(img1, img2, net=self.net, normalize=self.normalize)
57   File "/home/jxwei/app/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/torchmetrics/functional/image/lpips.py", line 346, in _lpips_update
58     raise ValueError(
59 ValueError: Expected both input arguments to be normalized tensors with shape [N, 3, H, W]. Got input with shape torch.Size([1, 3, 1000, 1504]) and torch.Size([1, 3, 1000, 1504]) and values in range [tensor(0., device='cuda:0'), tensor(1., device='cuda:0')] and [tensor(0.0049, device='cuda:0'), tensor(1.0000, device='cuda:0')] when all values are expected to be in the [0, 1] range.’

 The informations of `pip list`.
Package                  Version      Editable project location
------------------------ ------------ --------------------------
absl-py                  1.4.0
addict                   2.4.0
ansi2html                1.8.0
anyio                    3.7.0
appdirs                  1.4.4
argon2-cffi              21.3.0
argon2-cffi-bindings     21.2.0
arrow                    1.2.3
asttokens                2.2.1
async-lru                2.0.2
attrs                    23.1.0
av                       10.0.0
Babel                    2.12.1
backcall                 0.2.0
beautifulsoup4           4.12.2
bidict                   0.22.1
bleach                   6.0.0
cachetools               5.3.1
certifi                  2023.5.7
cffi                     1.15.1
cfgv                     3.3.1
charset-normalizer       3.1.0
click                    8.1.3
cmake                    3.26.4
comm                     0.1.3
ConfigArgParse           1.5.5
contourpy                1.1.0
cryptography             41.0.1
cycler                   0.11.0
dash                     2.11.1
dash-core-components     2.0.0
dash-html-components     2.0.0
dash-table               5.0.0
debugpy                  1.6.7
decorator                5.1.1
defusedxml               0.7.1
descartes                1.1.0
distlib                  0.3.6
docker-pycreds           0.4.0
docstring-parser         0.14.1
exceptiongroup           1.1.2
executing                1.2.0
fastjsonschema           2.17.1
filelock                 3.12.2
fire                     0.5.0
Flask                    2.2.5
fonttools                4.40.0
fqdn                     1.5.1
frozendict               2.3.8
gdown                    4.7.1
gitdb                    4.0.10
GitPython                3.1.31
google-auth              2.21.0
google-auth-oauthlib     1.0.0
grpcio                   1.56.0
h5py                     3.9.0
identify                 2.5.24
idna                     3.4
imageio                  2.31.1
importlib-metadata       6.7.0
importlib-resources      5.12.0
ipykernel                6.24.0
ipython                  8.12.2
ipython-genutils         0.2.0
ipywidgets               8.0.7
isoduration              20.11.0
itsdangerous             2.1.2
jaxtyping                0.2.19
jedi                     0.18.2
Jinja2                   3.1.2
joblib                   1.3.1
json5                    0.9.14
jsonpointer              2.4
jsonschema               4.17.3
jupyter                  1.0.0
jupyter_client           8.3.0
jupyter-console          6.6.3
jupyter_core             5.3.1
jupyter-events           0.6.3
jupyter-lsp              2.2.0
jupyter_server           2.7.0
jupyter_server_terminals 0.4.4
jupyterlab               4.0.2
jupyterlab-pygments      0.2.2
jupyterlab_server        2.23.0
jupyterlab-widgets       3.0.8
kiwisolver               1.4.4
lazy_loader              0.3
lightning-utilities      0.9.0
lit                      16.0.6
lpips                    0.1.4
Markdown                 3.4.3
markdown-it-py           3.0.0
MarkupSafe               2.1.3
matplotlib               3.7.1
matplotlib-inline        0.1.6
mdurl                    0.1.2
mediapy                  1.1.8
mistune                  3.0.1
mpmath                   1.3.0
msgpack                  1.0.5
msgpack-numpy            0.4.8
nbclassic                1.0.0
nbclient                 0.8.0
nbconvert                7.6.0
nbformat                 5.7.0
nerfacc                  0.5.2
nerfstudio               0.3.2        /home/jxwei/src/nerfstudio
nest-asyncio             1.5.6
networkx                 3.1
ninja                    1.11.1
nodeenv                  1.8.0
notebook                 6.5.4
notebook_shim            0.2.3
numpy                    1.24.4
nuscenes-devkit          1.1.9
oauthlib                 3.2.2
open3d                   0.17.0
opencv-python            4.6.0.66
overrides                7.3.1
packaging                23.1
pandas                   2.0.3
pandocfilters            1.5.0
parso                    0.8.3
pathtools                0.1.2
pexpect                  4.8.0
pickleshare              0.7.5
Pillow                   10.0.0
pip                      23.1.2
pkgutil_resolve_name     1.3.10
platformdirs             3.8.0
plotly                   5.15.0
pre-commit               3.3.2
prometheus-client        0.17.0
prompt-toolkit           3.0.39
protobuf                 3.20.3
psutil                   5.9.5
ptyprocess               0.7.0
pure-eval                0.2.2
pyasn1                   0.5.0
pyasn1-modules           0.3.0
pycocotools              2.0.6
pycparser                2.21
pyequilib                0.5.6
Pygments                 2.15.1
pyliblzfse               0.4.1
pymeshlab                2022.2.post4
pyngrok                  6.0.0
pyparsing                3.1.0
pyquaternion             0.9.9
pyrsistent               0.19.3
PySocks                  1.7.1
python-dateutil          2.8.2
python-engineio          4.4.1
python-json-logger       2.0.7
python-socketio          5.8.0
pytz                     2023.3
PyWavelets               1.4.1
PyYAML                   6.0
pyzmq                    25.1.0
qtconsole                5.4.3
QtPy                     2.3.1
rawpy                    0.18.1
requests                 2.31.0
requests-oauthlib        1.3.1
retrying                 1.3.4
rfc3339-validator        0.1.4
rfc3986-validator        0.1.1
rich                     13.4.2
rsa                      4.9
scikit-image             0.21.0
scikit-learn             1.3.0
scipy                    1.10.1
Send2Trash               1.8.2
sentry-sdk               1.27.0
setproctitle             1.3.2
setuptools               68.0.0
shapely                  2.0.1
shtab                    1.6.2
six                      1.16.0
smmap                    5.0.0
sniffio                  1.3.0
soupsieve                2.4.1
stack-data               0.6.2
sympy                    1.12
tenacity                 8.2.2
tensorboard              2.13.0
tensorboard-data-server  0.7.1
termcolor                2.3.0
terminado                0.17.1
threadpoolctl            3.1.0
tifffile                 2023.7.4
tinycss2                 1.2.1
tinycudann               1.7
tomli                    2.0.1
torch                    2.0.1+cu118
torch-fidelity           0.3.0
torchmetrics             1.0.0
torchvision              0.15.2+cu118
tornado                  6.3.2
tqdm                     4.65.0
traitlets                5.9.0
trimesh                  3.22.3
triton                   2.0.0
typeguard                4.0.0
typing_extensions        4.7.1
tyro                     0.5.3
tzdata                   2023.3
uri-template             1.3.0
urllib3                  1.26.16
virtualenv               20.23.1
viser                    0.0.16
wandb                    0.15.4
wcwidth                  0.2.6
webcolors                1.13
webencodings             0.5.1
websocket-client         1.6.1
websockets               11.0.3
Werkzeug                 2.2.3
wheel                    0.38.4
widgetsnbextension       4.0.8
xatlas                   0.0.7
zipp                     3.15.0

**Additional context**
This error occurs in the middle and late stages of training. From the error message, it is because the value of rgb is not between 0 and 1, which causes an error to be thrown when calculating LPIPS.

Wondering why this problem occurs? Is it because of my personal reasons, or is there some other reason?

**Comment by Goulustis** [comment]
I'm also experiencing this problem. Have you have an lead on this problem? What GPU and cuda version are you using when you encountered this?

**Comment by AIBUWAN** [comment]
before [https://github.com/nerfstudio-project/nerfstudio/blob/4d80f0ceeefa13e91e14e9cdebec39232b5cb72e/nerfstudio/models/nerfacto.py#L385](url),you can add `gt_rgb = torch.clip(gt_rgb, min=0.0, max=1.0)`

**Comment by WeiGuaa** [comment]
> I'm also experiencing this problem. Have you have an lead on this problem? What GPU and cuda version are you using when you encountered this?

I thought it might be a problem with the model used, then I realized that instant-ngp has two versions in nerfstudio, instant-ngp and instant-ngp-bounded.

When training a LEGO dataset (synthetic, bounded), using the command:
`ns-train instant-ngp-bounded --vis viewer+wandb --data data/blender/lego/ --pipeline.model.background-color white blender-data`

can prevent this from happening.

But for the aspen dataset (real, unbounded), using the instant-ngp model should be right, and there may be some problems here.

I got an email with a solution in reply:
`before https://github.com/nerfstudio-project/nerfstudio/blob/4d80f0ceeefa13e91e14e9cdebec39232b5cb72e/nerfstudio/models/nerfacto.py#L385,you can add gt_rgb = torch.clip(gt_rgb, min=0.0, max=1.0)`

I hope this helps!

My GPU is an RTX4090 and the cuda version is 11.8
