### ISSUE TITLE
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

### ISSUE THREAD

**Issue by SomeoneRand0m101** [nerfstudio-project/nerfstudio#2202]
Running ns-train nerfacto --data data/nerfstudio/poster gives the following error:

C:\Users\user\miniconda3\envs\nerfstudio\lib\site-packages\torchmetrics\utilities\prints.py:61: FutureWarning: Importing `PeakSignalNoiseRatio` from `torchmetrics` was deprecated and will be removed in 2.0. Import `PeakSignalNoiseRatio` from `torchmetrics.image` instead.
  _future_warning(
Traceback (most recent call last):
  File "C:\Users\user\miniconda3\envs\nerfstudio\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\user\miniconda3\envs\nerfstudio\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\miniconda3\envs\nerfstudio\Scripts\ns-train.exe\__main__.py", line 7, in <module>
  File "C:\Users\user\nerfstudio\nerfstudio\scripts\train.py", line 261, in entrypoint
    main(
  File "C:\Users\user\nerfstudio\nerfstudio\scripts\train.py", line 246, in main
    launch(
  File "C:\Users\user\nerfstudio\nerfstudio\scripts\train.py", line 189, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "C:\Users\user\nerfstudio\nerfstudio\scripts\train.py", line 99, in train_loop
    trainer.setup()
  File "C:\Users\user\nerfstudio\nerfstudio\engine\trainer.py", line 148, in setup
    self.pipeline = self.config.pipeline.setup(
  File "C:\Users\user\nerfstudio\nerfstudio\configs\base_config.py", line 57, in setup
    return self._target(self, **kwargs)
  File "C:\Users\user\nerfstudio\nerfstudio\pipelines\base_pipeline.py", line 259, in __init__
    self._model = config.model.setup(
  File "C:\Users\user\nerfstudio\nerfstudio\configs\base_config.py", line 57, in setup
    return self._target(self, **kwargs)
  File "C:\Users\user\nerfstudio\nerfstudio\models\base_model.py", line 84, in __init__
    self.populate_modules()  # populate the modules
  File "C:\Users\user\nerfstudio\nerfstudio\models\nerfacto.py", line 233, in populate_modules
    self.lpips = LearnedPerceptualImagePatchSimilarity(normalize=True)
  File "C:\Users\user\miniconda3\envs\nerfstudio\lib\site-packages\torchmetrics\image\lpip.py", line 124, in __init__
    self.net = _NoTrainLpips(net=net_type)
  File "C:\Users\user\miniconda3\envs\nerfstudio\lib\site-packages\torchmetrics\functional\image\lpips.py", line 273, in __init__
    self.net = net_type(pretrained=not self.pnet_rand, requires_grad=self.pnet_tune)
  File "C:\Users\user\miniconda3\envs\nerfstudio\lib\site-packages\torchmetrics\functional\image\lpips.py", line 103, in __init__
    alexnet_pretrained_features = _get_net("alexnet", pretrained)
  File "C:\Users\user\miniconda3\envs\nerfstudio\lib\site-packages\torchmetrics\functional\image\lpips.py", line 58, in _get_net
    pretrained_features = getattr(tv, net)(weights=getattr(tv, _weight_map[net]).IMAGENET1K_V1).features
  File "C:\Users\user\miniconda3\envs\nerfstudio\lib\site-packages\torchvision\models\_utils.py", line 142, in wrapper
    return fn(*args, **kwargs)
  File "C:\Users\user\miniconda3\envs\nerfstudio\lib\site-packages\torchvision\models\_utils.py", line 228, in inner_wrapper
    return builder(*args, **kwargs)
  File "C:\Users\user\miniconda3\envs\nerfstudio\lib\site-packages\torchvision\models\alexnet.py", line 117, in alexnet
    model.load_state_dict(weights.get_state_dict(progress=progress))
  File "C:\Users\user\miniconda3\envs\nerfstudio\lib\site-packages\torchvision\models\_api.py", line 89, in get_state_dict
    return load_state_dict_from_url(self.url, progress=progress)
  File "C:\Users\user\miniconda3\envs\nerfstudio\lib\site-packages\torch\hub.py", line 750, in load_state_dict_from_url
    return torch.load(cached_file, map_location=map_location)
  File "C:\Users\user\miniconda3\envs\nerfstudio\lib\site-packages\torch\serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "C:\Users\user\miniconda3\envs\nerfstudio\lib\site-packages\torch\serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

Any solution on this?

**Comment by tancik** [comment]
Is this still an issue?

**Comment by dberga** [comment]
Here is the full error
`╭ Traceback (most recent call last) ╮
 /home/Imatge/miniconda3/envs/nerfstudio/bin/ns-export:8 in <module>                              
                                                                                                  
   5 from nerfstudio.scripts.exporter import entrypoint                                           
   6 if __name__ == '__main__':                                                                   
   7    sys.argv[0] = re.sub(r'(-script\.pyw\.exe)?$', '', sys.argv[0])                         
 ❱ 8    sys.exit(entrypoint())                                                                   
   9                                                                                              
                                                                                                  
 /home/Imatge/projects/ai4heritage/ai4heritage-gitlab/nerfstudio/nerfstudio/scripts/exporter.py:5 
 64 in entrypoint                                                                                 
                                                                                                  
   561 def entrypoint():                                                                          
   562    """Entrypoint for use with pyproject scripts."""                                       
   563    tyro.extras.set_accent_color("bright_yellow")                                          
 ❱ 564    tyro.cli(Commands).main()                                                              
   565                                                                                            
   566                                                                                            
   567 if __name__ == "__main__":                                                                 
                                                                                                                                            
 /home/Imatge/projects/ai4heritage/ai4heritage-gitlab/nerfstudio/nerfstudio/scripts/exporter.py:3                                           
 15 in main                                                                                                                                 
                                                                                                                                            
   312       if not self.output_dir.exists():                                                                                             
   313          self.output_dir.mkdir(parents=True)                                                                                      
   314                                                                                                                                    
 ❱ 315       _, pipeline, _, _ = eval_setup(self.load_config)                                                                             
   316                                                                                                                                    
   317       validate_pipeline(self.normal_method, self.normal_output_name, pipeline)                                                     
   318                                                                                            
                                                                                                  
 /home/Imatge/projects/ai4heritage/ai4heritage-gitlab/nerfstudio/nerfstudio/utils/eval_utils.py:1 
 10 in eval_setup                                                                                 
                                                                                                  
   107    pipeline.eval()                                                                        
   108                                                                                           
   109    # load checkpointed information                                                        
 ❱ 110    checkpoint_path, step = eval_load_checkpoint(config, pipeline)                         
   111                                                                                           
   112    return config, pipeline, checkpoint_path, step                                         
   113                                                                                            
                                                                                                  
 /home/Imatge/projects/ai4heritage/ai4heritage-gitlab/nerfstudio/nerfstudio/utils/eval_utils.py:6 
 1 in eval_load_checkpoint                                                                        
                                                                                                  
    58       load_step = config.load_step                                                       
    59    load_path = config.load_dir / f"step-{load_step:09d}.ckpt"                             
    60    assert load_path.exists(), f"Checkpoint {load_path} does not exist"                                                              
 ❱  61    loaded_state = torch.load(load_path, map_location="cpu")                                                                         
    62    pipeline.load_pipeline(loaded_state["pipeline"], loaded_state["step"])                                                           
    63    CONSOLE.print(f":white_check_mark: Done loading checkpoint from {load_path}")                                                    
    64    return load_path, load_step                                                                                                      
                                                                                                                                            
 /home/Imatge/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/serialization.py:797                                             
 in load                                                                                                                                    
                                                                                                                                            
    794          # If we want to actually tail call to torch.jit.load, we need to                                                        
    795          # reset back to the original position.                                                                                  
    796          orig_position = opened_file.tell()                                            
 ❱  797          with _open_zipfile_reader(opened_file) as opened_zipfile:                     
    798             if _is_torchscript_zip(opened_zipfile):                                   
    799                warnings.warn("'torch.load' received a zip file that looks like a To  
    800                           " dispatching to 'torch.jit.load' (call 'torch.jit.loa  
                                                                                                  
 /home/Imatge/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/serialization.py:283   
 in __init__                                                                                      
                                                                                                  
    280                                                                                           
    281 class _open_zipfile_reader(_opener):                                                      
    282    def __init__(self, name_or_buffer) -> None:                                           
 ❱  283       super().__init__(torch._C.PyTorchFileReader(name_or_buffer))                      
    284                                                                                           
    285                                                                                           
    286 class _open_zipfile_writer_file(_opener):                                                 

RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory`

**Comment by dberga** [comment]
Not sure but this could be because a corrupt training checkpoint. The solution could be re-training again.
