### ISSUE TITLE
ns-process-data video suddenly doesn't work anymore

### ISSUE THREAD

**Issue by francescofugazzi** [nerfstudio-project/nerfstudio#2230]
running the command now raise a error for an unrecognized 'r1' option.
It worked 2 days ago and today  I pulled the updates and stopped working. It works with images

COMMAND EXAMPLE: 
ns-process-data video --data .\datasets\casellegiardino.MOV --output-dir .\datasets\casellegiardino  --matching-method exhaustive --verbose

RESULT:
```
Number of frames in video: 8662
Number of frames to extract: 310
ffmpeg version 6.0-full_build-www.gyan.dev Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12.2.0 (Rev10, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libaribb24 --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libaom --enable-libjxl --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libvpl --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
Unrecognized option 'r1'.
Error splitting the argument list: Option not found
──────────────────────────────────────────────  💀 💀 💀 ERROR 💀 💀 💀  ───────────────────────────────────────────────
Error running command: ffmpeg -i "datasets\casellegiardino.MOV" -vsync vfr -r1 -filter_complex
"thumbnail=28,setpts=N/TB,split=4;scale=iw/1:ih/1;scale=iw/2:ih/2;scale=iw/4:ih/4;scale=iw/8:ih/8" -map ""
"datasets\casellegiardino\images\frame_%05d.png" -map "" "datasets\casellegiardino\images_2\frame_%05d.png" -map ""
"datasets\casellegiardino\images_4\frame_%05d.png" -map "" "datasets\casellegiardino\images_8\frame_%05d.png"
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Traceback (most recent call last):
  File "C:\Users\franz\anaconda3\envs\nerfstudio\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\franz\anaconda3\envs\nerfstudio\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\franz\anaconda3\envs\nerfstudio\Scripts\ns-process-data.exe\__main__.py", line 7, in <module>
  File "D:\Stable\nerfstudio\nerfstudio\scripts\process_data.py", line 404, in entrypoint
    tyro.cli(Commands).main()
  File "D:\Stable\nerfstudio\nerfstudio\process_data\video_to_nerfstudio_dataset.py", line 61, in main
    summary_log, num_extracted_frames = process_data_utils.convert_video_to_images(
  File "D:\Stable\nerfstudio\nerfstudio\process_data\process_data_utils.py", line 198, in convert_video_to_images
    run_command(ffmpeg_cmd, verbose=verbose)
  File "D:\Stable\nerfstudio\nerfstudio\utils\scripts.py", line 37, in run_command
    CONSOLE.print(out.stderr.decode("utf-8"))
AttributeError: 'NoneType' object has no attribute 'decode'
```

**Comment by francescofugazzi** [comment]
I saw an update was already pushed in regard here https://github.com/nerfstudio-project/nerfstudio/pull/2229/commits/2771956e514ac573086df2a74a688819008b0a7e and yet to be approved.
Anyway if i correct the same way it still doesn'ìt work as it reports that -vsync and -r are opposite

**Comment by SharkWipf** [comment]
> Anyway if i correct the same way it still doesn'ìt work as it reports that -vsync and -r are opposite
Hmm, that's curious. It's definitely working on my end, I've just run it in with that commit.
Maybe it's an ffmpeg 6 thing? Can you post the full error?

**Comment by SharkWipf** [comment]
To be clear, it does make perfect sense for those options to be mutually exclusive, I remember I needed both to make it work, but perhaps that was just in an earlier iteration.
It seems to work fine with the -r 1 removed entirely, I don't remember why I needed it exactly but it seems to be unneeded. I'll make a new PR.

**Comment by francescofugazzi** [comment]
I confirm that everything now works perfectly :)
