### ISSUE TITLE
viewer encounter cuda out of memory  error

### ISSUE THREAD

**Issue by tangsy2004** [nerfstudio-project/nerfstudio#2278]
**Describe the bug**
My gpu is 2080Ti when should not have trouble rendering a small scene. Training process works fine but viewer doesn't work.

**To Reproduce**
1.run ns-train 
2. click viewer link
or 
1. run ns-viewer --load-config ...
2. click viewer link

**error**:

```

  ns-viewer --load-config /data/hzScenicSpot/outputs/leifengta/nerfacto/2023-07-26_093021/config.yml 
  [18:48:28] Auto image downscale factor of 4                                                 nerfstudio_dataparser.py:324
  Setting up training dataset...
  Caching all 184 images.
  Setting up evaluation dataset...
  Caching all 20 images.
  
  WARNING: Using a slow implementation for the SHEncoding module. 
  🏃 🏃 Install tcnn for speedups 🏃 🏃
  pip install git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch
  
  
  WARNING: Using a slow implementation for the NeRFEncoding module. 
  🏃 🏃 Install tcnn for speedups 🏃 🏃
  pip install git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch
  
  
  WARNING: Using a slow implementation for the HashEncoding module. 
  🏃 🏃 Install tcnn for speedups 🏃 🏃
  pip install git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch
  
  
  WARNING: Using a slow implementation for the MLP module. 
  🏃 🏃 Install tcnn for speedups 🏃 🏃
  pip install git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch
  
  
  WARNING: Using a slow implementation for the MLP module. 
  🏃 🏃 Install tcnn for speedups 🏃 🏃
  pip install git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch
  
  
  WARNING: Using a slow implementation for the HashEncoding module. 
  🏃 🏃 Install tcnn for speedups 🏃 🏃
  pip install git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch
  
  
  WARNING: Using a slow implementation for the MLP module. 
  🏃 🏃 Install tcnn for speedups 🏃 🏃
  pip install git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch
  
  
  WARNING: Using a slow implementation for the HashEncoding module. 
  🏃 🏃 Install tcnn for speedups 🏃 🏃
  pip install git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch
  
  
  WARNING: Using a slow implementation for the MLP module. 
  🏃 🏃 Install tcnn for speedups 🏃 🏃
  pip install git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch
  
  Loading latest checkpoint from load_dir
  ✅ Done loading checkpoint from outputs/leifengta/nerfacto/2023-07-26_093021/nerfstudio_models/step-000029999.ckpt
  ╭─────────────────────────────────────────── Viewer ───────────────────────────────────────────╮
  │        ╷                                                                                     │
  │   HTTP │ https://viewer.nerf.studio/versions/23-05-15-1/?websocket_url=ws://localhost:7007   │
  │        ╵                                                                                     │
  ╰──────────────────────────────────────────────────────────────────────────────────────────────╯
  [18:48:34] disabled local writer                                                                           writer.py:186
  Exception in thread Thread-6:
  Traceback (most recent call last):
    File "/home/txt/miniconda3/envs/nerfstudio/lib/python3.8/threading.py", line 932, in _bootstrap_inner
      self.run()
    File "/data/nerf_method_and_data/nerfstudio/nerfstudio/viewer/server/render_state_machine.py", line 173, in run
      outputs = self._render_img(action.cam_msg)
    File "/data/nerf_method_and_data/nerfstudio/nerfstudio/viewer/server/render_state_machine.py", line 148, in _render_img
      outputs = self.viewer.get_model().get_outputs_for_camera_ray_bundle(camera_ray_bundle)
    File "/home/txt/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
      return func(*args, **kwargs)
    File "/data/nerf_method_and_data/nerfstudio/nerfstudio/models/base_model.py", line 179, in get_outputs_for_camera_ray_bundle
      outputs = self.forward(ray_bundle=ray_bundle)
    File "/data/nerf_method_and_data/nerfstudio/nerfstudio/models/base_model.py", line 142, in forward
      return self.get_outputs(ray_bundle)
    File "/data/nerf_method_and_data/nerfstudio/nerfstudio/models/nerfacto.py", line 279, in get_outputs
      ray_samples, weights_list, ray_samples_list = self.proposal_sampler(ray_bundle, density_fns=self.density_fns)
    File "/home/txt/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
      return forward_call(*args, **kwargs)
    File "/data/nerf_method_and_data/nerfstudio/nerfstudio/model_components/ray_samplers.py", line 50, in forward
      return self.generate_ray_samples(*args, **kwargs)
    File "/data/nerf_method_and_data/nerfstudio/nerfstudio/model_components/ray_samplers.py", line 602, in generate_ray_samples
      density = density_fns[i_level](ray_samples.frustums.get_positions())
    File "/data/nerf_method_and_data/nerfstudio/nerfstudio/fields/base_field.py", line 67, in density_fn
      density, _ = self.get_density(ray_samples)
    File "/data/nerf_method_and_data/nerfstudio/nerfstudio/fields/density_fields.py", line 105, in get_density
      self.mlp_base(positions_flat).view(*ray_samples.frustums.shape, -1).to(positions)
    File "/home/txt/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
      return forward_call(*args, **kwargs)
    File "/home/txt/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/nn/modules/container.py", line 217, in forward
      input = module(input)
    File "/home/txt/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
      return forward_call(*args, **kwargs)
    File "/data/nerf_method_and_data/nerfstudio/nerfstudio/field_components/encodings.py", line 387, in forward
      return self.pytorch_fwd(in_tensor)
    File "/data/nerf_method_and_data/nerfstudio/nerfstudio/field_components/encodings.py", line 373, in pytorch_fwd
      f_47 = f_4 * offset[..., 0:1] + f_7 * (1 - offset[..., 0:1])
  torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 320.00 MiB (GPU 0; 10.76 GiB total capacity; 9.00 GiB already allocated; 5.44 MiB free; 9.67 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
`
```

**Comment by maturk** [comment]
Hey, there might be some issues with your nerfstudio installation. TCNN does not seem to be installed, did you try the "pip install git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch" command?

**Comment by tangsy2004** [comment]
It's indeed a tinycuda problem. solved with installing a older version of tinycuda [https://github.com/nerfstudio-project/nerfstudio/issues/1120#issuecomment-1350310213](url)

**Comment by prakashknaikade** [comment]
I am running viewer on 16GB GPU and loading nerfact-big model with checkpoint size of 545mb,
but getting this error:
```shell
 » ns-viewer --load-config outputs/primaries_new/nerfacto/2023-08-17_190125/config.yml
/HPS/ColorNeRF/work/opt/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/tinycudann/modules.py:53: UserWarning: tinycudann was built for lower compute capability (75) than the system's (86). Performance may be suboptimal.
  warnings.warn(f"tinycudann was built for lower compute capability ({cc}) than the system's ({system_compute_capability}). Performance may be suboptimal.")
[14:29:54] Auto image downscale factor of 2                                                 nerfstudio_dataparser.py:349
Setting up training dataset...
Caching all 291 images.
Setting up evaluation dataset...
Caching all 32 images.
Loading latest checkpoint from load_dir
✅ Done loading checkpoint from outputs/primaries_new/nerfacto/2023-08-17_190125/nerfstudio_models/step-000020000.ckpt
╭─────────────────────────────────────────── Viewer ───────────────────────────────────────────╮
│        ╷                                                                                     │
│   HTTP │ https://viewer.nerf.studio/versions/23-05-15-1/?websocket_url=ws://localhost:7007   │
│        ╵                                                                                     │
╰──────────────────────────────────────────────────────────────────────────────────────────────╯
[14:30:04] disabled local writer                                                                           writer.py:186
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/HPS/ColorNeRF/work/opt/anaconda3/envs/nerfstudio/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/HPS/ColorNeRF/work/nerfstudio/nerfstudio/viewer/server/render_state_machine.py", line 173, in run
    outputs = self._render_img(action.cam_msg)
  File "/HPS/ColorNeRF/work/nerfstudio/nerfstudio/viewer/server/render_state_machine.py", line 148, in _render_img
    outputs = self.viewer.get_model().get_outputs_for_camera_ray_bundle(camera_ray_bundle)
  File "/HPS/ColorNeRF/work/opt/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/HPS/ColorNeRF/work/nerfstudio/nerfstudio/models/base_model.py", line 179, in get_outputs_for_camera_ray_bundle
    outputs = self.forward(ray_bundle=ray_bundle)
  File "/HPS/ColorNeRF/work/nerfstudio/nerfstudio/models/base_model.py", line 142, in forward
    return self.get_outputs(ray_bundle)
  File "/HPS/ColorNeRF/work/nerfstudio/nerfstudio/models/nerfacto.py", line 283, in get_outputs
    field_outputs = self.field.forward(ray_samples, compute_normals=self.config.predict_normals)
  File "/HPS/ColorNeRF/work/nerfstudio/nerfstudio/fields/base_field.py", line 126, in forward
    field_outputs = self.get_outputs(ray_samples, density_embedding=density_embedding)
  File "/HPS/ColorNeRF/work/nerfstudio/nerfstudio/fields/nerfacto_field.py", line 298, in get_outputs
    rgb = self.mlp_head(h).view(*outputs_shape, -1).to(directions)
  File "/HPS/ColorNeRF/work/opt/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/HPS/ColorNeRF/work/nerfstudio/nerfstudio/field_components/mlp.py", line 178, in forward
    return self.tcnn_encoding(in_tensor)
  File "/HPS/ColorNeRF/work/opt/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/HPS/ColorNeRF/work/opt/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/tinycudann/modules.py", line 186, in forward
    output = _module_function.apply(
  File "/HPS/ColorNeRF/work/opt/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/HPS/ColorNeRF/work/opt/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/tinycudann/modules.py", line 98, in forward
    native_ctx, output = native_tcnn_module.fwd(input, params)
RuntimeError: /tmp/pip-req-build-qjtunxh4/include/tiny-cuda-nn/gpu_memory.h:584 cuMemCreate(&m_handles.back(), n_bytes_to_allocate, &prop, 0) failed: CUDA_ERROR_OUT_OF_MEMORY
```
