### ISSUE TITLE
ns-exports pointcloud  fails with two issues.

### ISSUE THREAD

**Issue by karun2016** [nerfstudio-project/nerfstudio#2421]
**Bug**
I updated my nerfstudio on Ubuntu 20.04 to the latest one on github. After training using nerfacto model, when I tried using ns-export to generate pointcloud, I am getting these two error messages.

*** Error 1 *** ----
Unable to load the following plugins:

        libio_e57.so: libio_e57.so does not seem to be a Qt Plugin.

Cannot load library /home/krun2016/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/pymeshlab/lib/plugins/libio_e57.so: (/lib/x86_64-linux-gnu/libp11-kit.so.0: undefined symbol: ffi_type_pointer, version LIBFFI_BASE_7.0)
---------

*** Error 2 *** ----
Traceback (most recent call last):
  File "/home/krun2016/anaconda3/envs/nerfstudio/bin/ns-export", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/krun2016/nerfstudio/nerfstudio/scripts/exporter.py", line 485, in entrypoint
    tyro.cli(Commands).main()
  File "/home/krun2016/nerfstudio/nerfstudio/scripts/exporter.py", line 149, in main
    pcd = generate_point_cloud(
  File "/home/krun2016/nerfstudio/nerfstudio/exporter/exporter_utils.py", line 153, in generate_point_cloud
    assert (
AssertionError: Normal values from method output must be in [0, 1]
------

**To Reproduce**
 ns-export command line:
*** ns-export pointcloud --load-config /home/krun2016/nerfstudio/outputs/sample1/nerfacto/2023-09-12_135956/config.yml --output-dir exports/sample1 --num-points 1000000 --remove-outliers True --normal-method model_output --normal-output-name normals --use-bounding-box True --bounding-box-min -1 -1 -1 --bounding-box-max 1 1 1 ***

**Expected behavior**
It was exporting fine before the latest update.

**Screenshots**

**Additional context**

**Comment by kerrj** [comment]
Does rendering videos work? Also, could you try without the bounding box crop? when you say it freezes, at what point of the export script does it freeze?

**Comment by LemonZhong** [comment]
I have the same problem:
AssertionError: Normal values from method output must be in [0, 1]
which never happened in the past

**Comment by karun2016** [comment]
**Error : ns-export fails. Some additional observations.**
======================================================

**Data set:** Trained using NeRF_DATA/nerf_synthetic/lego data set from here https://drive.google.com/drive/folders/1lrDkQanWtTznf48FCaW5lX9ToRdNDF1a.

**Example 1: Use only the 100 training images of NeRF_DATA/nerf_synthetic/lego/training.**
I created my own input for nerfacto by running ns-process-data as below:
$ns-process-data images --data ~/data/nerf/nerf_synthetic/lego/train --output-dir ~/data/nerf/nerf_synthetic/nerfstudio/nerf-lego --num-downscales=0 --no-gpu --verbose

And trained via this command:
$ _ns-train nerfacto --data ~/data/nerf/nerf_synthetic/nerfstudio/nerf-lego --output-dir ~/nerfstudio/outputs --experiment-name nerf-lego --pipeline.model.predict-normals True --max-num-iterations 100000_
At the end of training the lego model looks quite good.

**Result (Good): With the above training, I am able to ns-export both pointcould and poisson mesh without any issue.**


**Example 2: Use both training and validation images of NeRF_DATA/nerf_synthetic/lego.**
Now we have 200 images in the training set.
Again I created my own input for nerfacto by running ns-process-data as above and trained for 100000 iterations.
At the end of training the lego model looks quite good.

Now when I tried exporting this one,
 **I ran into assertion problem Error problem whether**
1) I use '--use-bounding-box True' or  '--use-bounding-box False'.
or
2) When  I use '--normal-method model_output' it gives assertion error.

3) **I also run into  'zero' progress mode** (see  0% --:-- at the bottom) when I
I switch to '--normal-method open3d' option.

See example command lines below:
_$ ns-export poisson --load-config outputs/nerf-lego-all/nerfacto/2023-09-18_103133/config.yml --output-dir exports/nerf-lego-all --num-points 1000000 --remove-outliers True --normal-method model_output --normal-output-name normals --use-bounding-box True --bounding-box-min -1 -1 -1 --bounding-box-max 1 1 1_
[12:43:03] Auto image downscale factor of 1                                                 nerfstudio_dataparser.py:349
Setting up training dataset...
Caching all 180 images.
Setting up evaluation dataset...
Caching all 20 images.
Loading latest checkpoint from load_dir
✅ Done loading checkpoint from outputs/nerf-lego-all/nerfacto/2023-09-18_103133/nerfstudio_models/step-000099999.ckpt
Checking that the pipeline has a normal output.
☁ Computing Point Cloud ☁ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% --:--
...
AssertionError: Normal values from method output must be in [0, 1]

Example 2: Without Bounding box.
_$ ns-export poisson --load-config outputs/nerf-lego-all/nerfacto/2023-09-18_103133/config.yml --output-dir exports/nerf-lego-all --num-points 1000000 --remove-outliers True --normal-method model_output --normal-output-name normals --use-bounding-box True_
[13:02:35] Auto image downscale factor of 1                                                 nerfstudio_dataparser.py:349
Setting up training dataset...
Caching all 180 images.
Setting up evaluation dataset...
Caching all 20 images.
Loading latest checkpoint from load_dir
✅ Done loading checkpoint from outputs/nerf-lego-all/nerfacto/2023-09-18_103133/nerfstudio_models/step-000099999.ckpt
Checking that the pipeline has a normal output.
☁ Computing Point Cloud ☁ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% --:--

**Comment by karun2016** [comment]
I also tried py-spy to get an idea about what is happening with exporter script. I gave up after 20+minutes. Here is a snap shot of what is happening. The exporter_utils.py is hogging all the time and without any progress message.
 83.00%  99.00%    1658s     2010s   generate_point_cloud (nerfstudio/exporter/exporter_utils.py)


![image](https://github.com/nerfstudio-project/nerfstudio/assets/23545979/307bd0d4-3697-4d5e-b547-8afb9f7b30a9)

**Comment by bhavikajalli** [comment]
Having the same 0% progress issue. Any ideas?

**Comment by tancik** [comment]
Does the region you are trying to extract have geometry in it?

**Comment by karun2016** [comment]
@tancik  I am trying to extract both the pointcloud and poisson mesh for the synthetic NeRF_data Lego. I understand that the synthetic nerf data may not result in a good mesh. I am ok with that. 
When I trained only with 100 images of the original traininig set of the Lego data, after 80000 iterations, I am able to extract both  the pointcloud and poisson mesh. 
But if I train with 200 images (100 training images +100 validation images) and after 100K iterations, the Lego looks decent. Only when I try to export this one, I get those errors.

**Comment by tancik** [comment]
I'll be honest, Im not entirely sure. I'd recommend attaching a debugger and stepping through these lines of code to see if points are being computed - https://github.com/nerfstudio-project/nerfstudio/blob/53037ba8a790a7aa089c8a4983c2aa210e01111c/nerfstudio/exporter/exporter_utils.py#L131-L191
