### ISSUE TITLE
Google colab export failure

### ISSUE THREAD

**Issue by Reznox7** [nerfstudio-project/nerfstudio#2532]
Traceback (most recent call last):
  File "/usr/local/bin/ns-export", line 5, in <module>
    from nerfstudio.scripts.exporter import entrypoint
  File "/usr/local/lib/python3.10/site-packages/nerfstudio/scripts/exporter.py", line 39, in <module>
    from nerfstudio.exporter import texture_utils, tsdf_utils
  File "/usr/local/lib/python3.10/site-packages/nerfstudio/exporter/texture_utils.py", line 34, in <module>
    from nerfstudio.exporter.exporter_utils import Mesh
  File "/usr/local/lib/python3.10/site-packages/nerfstudio/exporter/exporter_utils.py", line 28, in <module>
    import pymeshlab
  File "/usr/local/lib/python3.10/site-packages/pymeshlab/__init__.py", line 11, in <module>
    from .pmeshlab import *
ImportError: /usr/local/lib/python3.10/site-packages/pymeshlab/lib/libmeshlab-common.so: undefined symbol: _ZdlPvm, version Qt_5

Reproduced by trying to export a mesh from nerfstudio on Google Colaboratory:

The command is:
`!ns-export poisson --load-config outputs/unnamed/nerfacto/2023-10-13_101133/config.yml --output-dir exports/mesh/ --target-num-faces 50000 --num-pixels-per-side 2048 --normal-method open3d --num-points 1000000 --remove-outliers True --use-bounding-box True --bounding-box-min -1 -1 -1 --bounding-box-max 1 1 1`

**Comment by mohit-choithwani** [comment]
@Reznox7 This [link](https://github.com/nerfstudio-project/nerfstudio/issues/1121#issuecomment-1360501564) will help you.
