### ISSUE TITLE
Nerfstudio dataset unavailable through ns-download-data

### ISSUE THREAD

**Issue by j93hahn** [nerfstudio-project/nerfstudio#2544]
I ran this command to extract the full nerfstudio dataset:

`ns-download-data nerfstudio --save-dir nerfstudio --capture-name all`

However, it only downloaded these scenes: bww_entrance, campanile, desolation, library, poster, redwoods2, storefront, vegetation.

It outputted this error message for the remaining 10 datasets (which happen to be the ones that are reported on in the paper):

```
--2023-10-19 19:43:05--  https://data.nerf.studio/nerfstudio/Egypt.zip
Resolving data.nerf.studio (data.nerf.studio)... 34.102.68.79
Connecting to data.nerf.studio (data.nerf.studio)|34.102.68.79|:443... connected.
HTTP request sent, awaiting response... 404 File not found
2023-10-19 19:43:05 ERROR 404: File not found.

──────────────────────────────────────────────  💀 💀 💀 ERROR 💀 💀 💀  ───────────────────────────────────────────────
Error running command: wget https://data.nerf.studio/nerfstudio/Egypt.zip -O nerfstudio/nerfstudio/Egypt.zip
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Traceback (most recent call last):
  File "/share/data/pals/jjahn/mc3/envs/alpha/bin/ns-download-data", line 8, in <module>
    sys.exit(entrypoint())
  File "/share/data/pals/jjahn/nerfstudio/nerfstudio/scripts/downloads/download_data.py", line 481, in entrypoint
    main(tyro.cli(Commands))
  File "/share/data/pals/jjahn/nerfstudio/nerfstudio/scripts/downloads/download_data.py", line 475, in main
    dataset.download(dataset.save_dir)
  File "/share/data/pals/jjahn/nerfstudio/nerfstudio/scripts/downloads/download_data.py", line 205, in download
    download_capture_name(save_dir, "nerfstudio", self.capture_name, capture_name_to_file_id=nerfstudio_file_ids)
  File "/share/data/pals/jjahn/nerfstudio/nerfstudio/scripts/downloads/download_data.py", line 160, in download_capture_name
    run_command(f"wget {url} -O {download_path}", verbose=True)
  File "/share/data/pals/jjahn/nerfstudio/nerfstudio/utils/scripts.py", line 37, in run_command
    CONSOLE.print(out.stderr.decode("utf-8"))
AttributeError: 'NoneType' object has no attribute 'decode'
(alpha) [jjahn@gpu32 data]$ ns-download-data nerfstudio --save-dir nerfstudio --capture-name person
  File "/share/data/pals/jjahn/nerfstudio/nerfstudio/scripts/downloads/download_data.py", line 160, in download_capture_name
    run_command(f"wget {url} -O {download_path}", verbose=True)
  File "/share/data/pals/jjahn/nerfstudio/nerfstudio/utils/scripts.py", line 37, in run_command
    CONSOLE.print(out.stderr.decode("utf-8"))
AttributeError: 'NoneType' object has no attribute 'decode'
```

Are the links outdated? Or is there another way to access the other 10 datasets (Egypt, person, kitchen, plane, dozer, floating tree, aspen, stump, sculpture, Gianni hall)? Thank you!

**Comment by tancik** [comment]
Yea, we stopped hosing the data there. The latest version of nerfstudio should point to the new links. Alternatively you can find theme here - https://github.com/nerfstudio-project/nerfstudio/blob/f31f3bba12841955102f3f3846ee9f855f4a6878/nerfstudio/scripts/downloads/download_data.py#L115-L142
