### ISSUE TITLE
Unrecognized option 'qp'. Error splitting the argument list: Option not found

### ISSUE THREAD

**Issue by Angelalilyer** [nerfstudio-project/nerfstudio#2547]
**Describe the bug**
Traceback (most recent call last):
  File "/data/nerfstudio/nerfstudio/scripts/render.py", line 203, in _render_trajectory_video
    writer.add_image(render_image)
  File "/home/huangzhiqi/.local/lib/python3.8/site-packages/mediapy/__init__.py", line 1648, in add_image
    if self._proc.stdin.write(data) != len(data):
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/huangzhiqi/.local/bin/ns-render", line 8, in <module>
    sys.exit(entrypoint())
  File "/data/nerfstudio/nerfstudio/scripts/render.py", line 808, in entrypoint
    tyro.cli(Commands).main()
  File "/data/nerfstudio/nerfstudio/scripts/render.py", line 407, in main
    _render_trajectory_video(
  File "/data/nerfstudio/nerfstudio/scripts/render.py", line 203, in _render_trajectory_video
    writer.add_image(render_image)
  File "/usr/lib/python3.8/contextlib.py", line 525, in __exit__
    raise exc_details[1]
  File "/usr/lib/python3.8/contextlib.py", line 510, in __exit__
    if cb(*exc_details):
  File "/home/huangzhiqi/.local/lib/python3.8/site-packages/mediapy/__init__.py", line 1610, in __exit__
    self.close()
  File "/home/huangzhiqi/.local/lib/python3.8/site-packages/mediapy/__init__.py", line 1661, in close
    raise RuntimeError(f"Error writing '{self.path}': {s}")
RuntimeError: Error writing 'renders/poster/2023-10-20_150821.mp4': Unrecognized option 'qp'.
Error splitting the argument list: Option not found
**To Reproduce**
run the command " ns-render camera-path --load-config outputs/poster/nerfacto/2023-10-20_150821/config.yml --camera-path-filename /data/nerfstudio/data/nerfstudio/poster/camera_paths/2023-10-20_150821.json --output-path renders/poster/2023-10-20_150821.mp4"

**Expected behavior**

**Screenshots**
<img width="612" alt="8b05c99e4f2e7f58c4a52ac8412a785c" src="https://github.com/nerfstudio-project/nerfstudio/assets/67882975/cd12c624-f9d3-48eb-98f4-0bc096ae85bf">

**Additional context**

my ffmpeg version is:
ffmpeg version 5.1 Copyright (c) 2000-2022 the FFmpeg developers
built with gcc 9 (Ubuntu 9.4.0-1ubuntu1~20.04.2)
configuration: --enable-shared --enable-libx264 --enable-gpl --prefix=/usr/bin/ffmpeg
libavutil      57. 28.100 / 57. 28.100
libavcodec     59. 37.100 / 59. 37.100
libavformat    59. 27.100 / 59. 27.100
libavdevice    59.  7.100 / 59.  7.100
libavfilter     8. 44.100 /  8. 44.100
libswscale      6.  7.100 /  6.  7.100
libswresample   4.  7.100 /  4.  7.100
libpostproc    56.  6.100 / 56.  6.100

**Comment by baekhyun77** [comment]
Hello, have you solved this problem yet？

**Comment by yukyeongmin** [comment]
I could render with ffmpeg 4.2.2.

**Comment by AntonioMacaronio** [comment]
This fix works! I'm able to render once `ffmpeg` version is 4.2.2

For others, if your conda environment is running `ffmpeg` version 4.3, simply reinstall with version 4.2.2 using the command:
`conda install -c conda-forge ffmpeg=4.2.2`
