### ISSUE TITLE
OSerror when running colab

### ISSUE THREAD

**Issue by xiuyuan0216** [nerfstudio-project/nerfstudio#2563]
I met this error when directly running colab code.

Traceback (most recent call last):
  File "/usr/local/bin/ns-train", line 5, in <module>
    from nerfstudio.scripts.train import entrypoint
  File "/usr/local/lib/python3.10/dist-packages/nerfstudio/scripts/train.py", line 62, in <module>
    from nerfstudio.configs.method_configs import AnnotatedBaseConfigUnion
  File "/usr/local/lib/python3.10/dist-packages/nerfstudio/configs/method_configs.py", line 61, in <module>
    from nerfstudio.models.depth_nerfacto import DepthNerfactoModelConfig
  File "/usr/local/lib/python3.10/dist-packages/nerfstudio/models/depth_nerfacto.py", line 30, in <module>
    from nerfstudio.models.nerfacto import NerfactoModel, NerfactoModelConfig
  File "/usr/local/lib/python3.10/dist-packages/nerfstudio/models/nerfacto.py", line 27, in <module>
    from torchmetrics.functional import structural_similarity_index_measure
  File "/usr/local/lib/python3.10/dist-packages/torchmetrics/__init__.py", line 14, in <module>
    from torchmetrics import functional  # noqa: E402
  File "/usr/local/lib/python3.10/dist-packages/torchmetrics/functional/__init__.py", line 14, in <module>
    from torchmetrics.functional.audio._deprecated import _permutation_invariant_training as permutation_invariant_training
  File "/usr/local/lib/python3.10/dist-packages/torchmetrics/functional/audio/__init__.py", line 14, in <module>
    from torchmetrics.functional.audio.pit import permutation_invariant_training, pit_permutate
  File "/usr/local/lib/python3.10/dist-packages/torchmetrics/functional/audio/pit.py", line 22, in <module>
    from torchmetrics.utilities import rank_zero_warn
  File "/usr/local/lib/python3.10/dist-packages/torchmetrics/utilities/__init__.py", line 14, in <module>
    from torchmetrics.utilities.checks import check_forward_full_state_property
  File "/usr/local/lib/python3.10/dist-packages/torchmetrics/utilities/checks.py", line 25, in <module>
    from torchmetrics.metric import Metric
  File "/usr/local/lib/python3.10/dist-packages/torchmetrics/metric.py", line 30, in <module>
    from torchmetrics.utilities.data import (
  File "/usr/local/lib/python3.10/dist-packages/torchmetrics/utilities/data.py", line 22, in <module>
    from torchmetrics.utilities.imports import _TORCH_GREATER_EQUAL_1_12, _XLA_AVAILABLE
  File "/usr/local/lib/python3.10/dist-packages/torchmetrics/utilities/imports.py", line 50, in <module>
    _TORCHAUDIO_GREATER_EQUAL_0_10: Optional[bool] = compare_version("torchaudio", operator.ge, "0.10.0")
  File "/usr/local/lib/python3.10/dist-packages/lightning_utilities/core/imports.py", line 73, in compare_version
    pkg = importlib.import_module(package)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.10/dist-packages/torchaudio/__init__.py", line 1, in <module>
    from . import (  # noqa: F401
  File "/usr/local/lib/python3.10/dist-packages/torchaudio/_extension/__init__.py", line 45, in <module>
    _load_lib("libtorchaudio")
  File "/usr/local/lib/python3.10/dist-packages/torchaudio/_extension/utils.py", line 64, in _load_lib
    torch.ops.load_library(path)
  File "/usr/local/lib/python3.10/dist-packages/torch/_ops.py", line 643, in load_library
    ctypes.CDLL(path)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/local/lib/python3.10/dist-packages/torchaudio/lib/libtorchaudio.so: undefined symbol: _ZN3c104cuda9SetDeviceEi

**Comment by XanaGA** [comment]
I get the same error

**Comment by ichsan2895** [comment]
I get the same error too

**Comment by weber50432** [comment]
I get the same error

**Comment by l-rudolph** [comment]
Quickfix (works November 2023 - might change in the future!) attention, this version takes a bit longer, I experienced 8-20 minutes
replace the part of "Install Nerfstudio and Dependencies (~8 min)" before "# Installing COLMAP" with

#@markdown <h1>Install Nerfstudio and Dependencies (~8 min)</h1>
%cd /content/
!pip install --upgrade pip
#!pip install torch==2.0.1+cu118 torchvision==0.15.2+cu118 --extra-index-url https://download.pytorch.org/whl/cu118
!pip install ninja git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch
# Installing TinyCuda
#!gdown "https://drive.google.com/u/1/uc?id=1-7x7qQfB7bIw2zV4Lr6-yhvMpjXC84Q5&confirm=t"
#!pip install tinycudann-1.7-cp310-cp310-linux_x86_64.whl

**Comment by jthecodemonk** [comment]
Is there a resolution to the above problem? I get the same error!

**Comment by skkk256** [comment]
The same error? Is there any possible solution?

**Comment by skkk256** [comment]
> Quickfix (works November 2023 - might change in the future!) attention, this version takes a bit longer, I experienced 8-20 minutes replace the part of "Install Nerfstudio and Dependencies (~8 min)" before "# Installing COLMAP" with
> 
> %cd /content/ !pip install --upgrade pip #!pip install torch==2.0.1+cu118 torchvision==0.15.2+cu118 --extra-index-url https://download.pytorch.org/whl/cu118 !pip install ninja git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch #!gdown "https://drive.google.com/u/1/uc?id=1-7x7qQfB7bIw2zV4Lr6-yhvMpjXC84Q5&confirm=t" #!pip install tinycudann-1.7-cp310-cp310-linux_x86_64.whl

This doesn't seem to work. I get the same problem after replacing this part

**Comment by oguzhanguclu** [comment]
`pip uninstall torchaudio` fixed my problem.
