### ISSUE TITLE
tensorf MipNeRF360 Dataset

### ISSUE THREAD

**Issue by aiyb1314** [nerfstudio-project/nerfstudio#2576]
Traceback (most recent call last):
  File "/home/xuj/anaconda3/envs/nerfstudio/bin/ns-train", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/xuj/anaconda3/envs/nerfstudio/lib/python3.10/site-packages/nerfstudio/scripts/train.py", line 262, in entrypoint
    main(
  File "/home/xuj/anaconda3/envs/nerfstudio/lib/python3.10/site-packages/nerfstudio/scripts/train.py", line 247, in main
    launch(
  File "/home/xuj/anaconda3/envs/nerfstudio/lib/python3.10/site-packages/nerfstudio/scripts/train.py", line 189, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "/home/xuj/anaconda3/envs/nerfstudio/lib/python3.10/site-packages/nerfstudio/scripts/train.py", line 99, in train_loop
    trainer.setup()
  File "/home/xuj/anaconda3/envs/nerfstudio/lib/python3.10/site-packages/nerfstudio/engine/trainer.py", line 147, in setup
    self.pipeline = self.config.pipeline.setup(
  File "/home/xuj/anaconda3/envs/nerfstudio/lib/python3.10/site-packages/nerfstudio/configs/base_config.py", line 54, in setup
    return self._target(self, **kwargs)
  File "/home/xuj/anaconda3/envs/nerfstudio/lib/python3.10/site-packages/nerfstudio/pipelines/base_pipeline.py", line 263, in __init__
    self.datamanager: DataManager = config.datamanager.setup(
  File "/home/xuj/anaconda3/envs/nerfstudio/lib/python3.10/site-packages/nerfstudio/configs/base_config.py", line 54, in setup
    return self._target(self, **kwargs)
  File "/home/xuj/anaconda3/envs/nerfstudio/lib/python3.10/site-packages/nerfstudio/data/datamanagers/base_datamanager.py", line 403, in __init__
    self.train_dataparser_outputs: DataparserOutputs = self.dataparser.get_dataparser_outputs(split="train")
  File "/home/xuj/anaconda3/envs/nerfstudio/lib/python3.10/site-packages/nerfstudio/data/dataparsers/base_dataparser.py", line 165, in get_dataparser_outputs
    dataparser_outputs = self._generate_dataparser_outputs(split, **kwargs)
  File "/home/xuj/anaconda3/envs/nerfstudio/lib/python3.10/site-packages/nerfstudio/data/dataparsers/blender_dataparser.py", line 71, in _generate_dataparser_outputs
    meta = load_from_json(self.data / f"transforms_{split}.json")
  File "/home/xuj/anaconda3/envs/nerfstudio/lib/python3.10/site-packages/nerfstudio/utils/io.py", line 30, in load_from_json
    with open(filename, encoding="UTF-8") as file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/xuj/nerfstudio/data/nerf_360/garden/studio/transforms_train.json'

**Comment by maogeraaa** [comment]
Do you solve this problem?

**Comment by hundun0322** [comment]
just change the transforms.json to transforms_train.json
