### ISSUE TITLE
when i use nerfplayer for train, it will new bug

### ISSUE THREAD

**Issue by ZkzMMDC** [nerfstudio-project/nerfstudio#2582]
`ns-train nerfplayer-nerfacto --data /data01/zkz/NeRFPlayer/apple`

Traceback (most recent call last):
  File "/home/zkz/anaconda3/envs/nerfstudio/bin/ns-train", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/zkz/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/scripts/train.py", line 262, in entrypoint
    main(
  File "/home/zkz/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/scripts/train.py", line 247, in main
    launch(
  File "/home/zkz/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/scripts/train.py", line 189, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "/home/zkz/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/scripts/train.py", line 99, in train_loop
    trainer.setup()
  File "/home/zkz/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/engine/trainer.py", line 147, in setup
    self.pipeline = self.config.pipeline.setup(
  File "/home/zkz/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/configs/base_config.py", line 54, in setup
    return self._target(self, **kwargs)
  File "/home/zkz/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/pipelines/base_pipeline.py", line 263, in __init__
    self.datamanager: DataManager = config.datamanager.setup(
  File "/home/zkz/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/configs/base_config.py", line 54, in setup
    return self._target(self, **kwargs)
  File "/home/zkz/anaconda3/envs/nerfstudio/lib/python3.8/typing.py", line 729, in __call__
    result = self.__origin__(*args, **kwargs)
  File "/home/zkz/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/data/datamanagers/base_datamanager.py", line 403, in __init__
    self.train_dataparser_outputs: DataparserOutputs = self.dataparser.get_dataparser_outputs(split="train")
  File "/home/zkz/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/data/dataparsers/base_dataparser.py", line 165, in get_dataparser_outputs
    dataparser_outputs = self._generate_dataparser_outputs(split, **kwargs)
  File "/home/zkz/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/data/dataparsers/dycheck_dataparser.py", line 245, in _generate_dataparser_outputs
    image_filenames, depth_filenames, cams = self.process_frames(frame_names.tolist(), time_ids)
  File "/home/zkz/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/data/dataparsers/dycheck_dataparser.py", line 319, in process_frames
    ori_h, ori_w = cv2.imread(str(self.data / f"rgb/1x/{frame_names[0]}.png")).shape[:2]
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by ZkzMMDC** [comment]
Traceback (most recent call last):
  File "/home/zkz/anaconda3/envs/nerfstudio/bin/ns-train", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/zkz/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/scripts/train.py", line 262, in entrypoint
    main(
  File "/home/zkz/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/scripts/train.py", line 247, in main
    launch(
  File "/home/zkz/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/scripts/train.py", line 189, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "/home/zkz/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/scripts/train.py", line 99, in train_loop
    trainer.setup()
  File "/home/zkz/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/engine/trainer.py", line 147, in setup
    self.pipeline = self.config.pipeline.setup(
  File "/home/zkz/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/configs/base_config.py", line 54, in setup
    return self._target(self, **kwargs)
  File "/home/zkz/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/pipelines/base_pipeline.py", line 270, in __init__
    self._model = config.model.setup(
  File "/home/zkz/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/configs/base_config.py", line 54, in setup
    return self._target(self, **kwargs)
  File "/home/zkz/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/models/base_model.py", line 84, in __init__
    self.populate_modules()  # populate the modules
  File "/home/zkz/nerfplayer-nerfstudio-main/nerfplayer/nerfplayer_nerfacto.py", line 99, in populate_modules
    from nerfplayer.nerfplayer_nerfacto_field import NerfplayerNerfactoField, TemporalHashMLPDensityField
  File "/home/zkz/nerfplayer-nerfstudio-main/nerfplayer/nerfplayer_nerfacto_field.py", line 27, in <module>
    import tinycudann as tcnn
  File "/home/zkz/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/tinycudann-1.7-py3.8-linux-x86_64.egg/tinycudann/__init__.py", line 9, in <module>
    from tinycudann.modules import free_temporary_memory, NetworkWithInputEncoding, Network, Encoding
  File "/home/zkz/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/tinycudann-1.7-py3.8-linux-x86_64.egg/tinycudann/modules.py", line 51, in <module>
    _C = importlib.import_module(f"tinycudann_bindings._{cc}_C")
  File "/home/zkz/anaconda3/envs/nerfstudio/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /home/zkz/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/tinycudann-1.7-py3.8-linux-x86_64.egg/tinycudann_bindings/_89_C.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda9SetDeviceEi

**Comment by AvishkarArjan** [comment]
same issue, any soln yet ?
