### ISSUE TITLE
ns-process-data : 'utf-8' codec can't decode byte 0xb2 in position 10: invalid start byte

### ISSUE THREAD

**Issue by monkeycc** [nerfstudio-project/nerfstudio#2629]
WIN11
python 3.8
nerfstudio v0.3.4

`ns-process-data video --data E:\3D\DJI\1.MP4 --output-dir E:\3D\DJL\output`

```python

──────────────────────────────────────────────  💀 💀 💀 ERROR 💀 💀 💀  ───────────────────────────────────────────────
Error running command: ffprobe -v error -select_streams v:0 -count_packets             -show_entries
stream=nb_read_packets -of csv=p=0 "E:\3D\DJI\1.MP4"
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Traceback (most recent call last):
  File "E:\anaconda3\envs\nerfstudio\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "E:\anaconda3\envs\nerfstudio\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\anaconda3\envs\nerfstudio\Scripts\ns-process-data.exe\__main__.py", line 7, in <module>
  File "E:\2023_Code_WEB\nerfstudio-main\nerfstudio\scripts\process_data.py", line 493, in entrypoint
    tyro.cli(Commands).main()
  File "E:\2023_Code_WEB\nerfstudio-main\nerfstudio\process_data\video_to_nerfstudio_dataset.py", line 60, in main
    summary_log, num_extracted_frames = process_data_utils.convert_video_to_images(
  File "E:\2023_Code_WEB\nerfstudio-main\nerfstudio\process_data\process_data_utils.py", line 154, in convert_video_to_images
    num_frames = get_num_frames_in_video(video_path)
  File "E:\2023_Code_WEB\nerfstudio-main\nerfstudio\process_data\process_data_utils.py", line 102, in get_num_frames_in_video
    output = run_command(cmd)
  File "E:\2023_Code_WEB\nerfstudio-main\nerfstudio\utils\scripts.py", line 37, in run_command
    CONSOLE.print(out.stderr.decode("utf-8"))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb2 in position 10: invalid start byte

```

**Comment by monkeycc** [comment]
ffmpeg
