### ISSUE TITLE
Gaussian Splatting failed,  "too many values to unpack"

### ISSUE THREAD

**Issue by WBB97** [nerfstudio-project/nerfstudio#2641]
When i run the following command: 
```ns-train gaussian-splatting  --data ./data/nerfstudio/poster/posters_v3```

Full Error Message shows: 
```
Traceback (most recent call last):
  File "/root/miniconda3/bin/ns-train", line 8, in <module>
    sys.exit(entrypoint())
  File "/root/nerfstudio/nerfstudio/scripts/train.py", line 262, in entrypoint
    main(
  File "/root/nerfstudio/nerfstudio/scripts/train.py", line 247, in main
    launch(
  File "/root/nerfstudio/nerfstudio/scripts/train.py", line 189, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "/root/nerfstudio/nerfstudio/scripts/train.py", line 100, in train_loop
    trainer.train()
  File "/root/nerfstudio/nerfstudio/engine/trainer.py", line 253, in train
    loss, loss_dict, metrics_dict = self.train_iteration(step)
  File "/root/nerfstudio/nerfstudio/utils/profiler.py", line 127, in inner
    out = func(*args, **kwargs)
  File "/root/nerfstudio/nerfstudio/engine/trainer.py", line 473, in train_iteration
    _, loss_dict, metrics_dict = self.pipeline.get_train_loss_dict(step=step)
  File "/root/nerfstudio/nerfstudio/utils/profiler.py", line 127, in inner
    out = func(*args, **kwargs)
  File "/root/nerfstudio/nerfstudio/pipelines/base_pipeline.py", line 304, in get_train_loss_dict
    model_outputs = self._model(ray_bundle)  # train distributed data parallel model if world_size > 1
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/nerfstudio/nerfstudio/models/base_model.py", line 143, in forward
    return self.get_outputs(ray_bundle)
  File "/root/nerfstudio/nerfstudio/models/gaussian_splatting.py", line 613, in get_outputs
    rgb,_ = RasterizeGaussians.apply(
ValueError: too many values to unpack (expected 2)
```

The detailed steps I have done are:
```
git clone https://github.com/nerfstudio-project/nerfstudio.git -b gaussian-splatting --recurse-submodules
cd nerfstudio
pip install --upgrade pip setuptools
pip install -e .
```
Also i pull the code according to  #2636 
```
git clone https://github.com/nerfstudio-project/gsplat/.git --recurse-submodules
cd gsplat
pip install -e .
```

All installation are successful! And the poster dataset is downloaded from [https://drive.google.com/file/d/1dmjWGXlJnUxwosN6MVooCDQe970PkD-1/view?usp=sharing](url)

So is there a friend who can help me? Thank you very much!!!

**Comment by hariharan1412** [comment]
This error is associated with the recent commit, so 

please checkout  ``` 9e33b437dff6df5a9579c04b1eba46640df88a96 ``` this branch and run again, it will work
