### ISSUE TITLE
K-planes add-on doesn't run, torchtyping and cannot import name 'shift_directions_for_tcnn errors.

### ISSUE THREAD

**Issue by drk944** [nerfstudio-project/nerfstudio#2659]
**Describe the bug**
I've been using Nerfstudio and wanted to try out the K-planes add on. I installed it per the instructions however there seems to be some underlying dependency issues. The first error I get it `ModuleNotFoundError: No module named 'torchtyping'`. I fixed this by running `pip install torchtyping` but now get another error which is pasted below.

**To Reproduce**
From my conda environment: `pip install kplanes-nerfstudio`
Then I run `ns-train kplanes --data <data-folder>` using "data/blender/lego/" downloaded from `ns-download-data blender`

**Expected behavior**
Expecting it to start running and train.

**Screenshots**
This is the no module named torchtyping error I get at first:
```
Traceback (most recent call last):
  File "/home/drbenham/anaconda3/envs/nerfstudio/bin/ns-train", line 5, in <module>
    from nerfstudio.scripts.train import entrypoint
  File "/home/drbenham/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/scripts/train.py", line 62, in <module>
    from nerfstudio.configs.method_configs import AnnotatedBaseConfigUnion
  File "/home/drbenham/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/configs/method_configs.py", line 607, in <module>
    all_methods, all_descriptions = merge_methods(all_methods, all_descriptions, *discover_methods())
  File "/home/drbenham/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/plugins/registry.py", line 43, in discover_methods
    spec = discovered_entry_points[name].load()
  File "/home/drbenham/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 208, in load
    module = import_module(match.group('module'))
  File "/home/drbenham/anaconda3/envs/nerfstudio/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/drbenham/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/kplanes/kplanes_configs.py", line 13, in <module>
    from .kplanes import KPlanesModelConfig
  File "/home/drbenham/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/kplanes/kplanes.py", line 57, in <module>
    from .kplanes_field import KPlanesDensityField, KPlanesField
  File "/home/drbenham/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/kplanes/kplanes_field.py", line 24, in <module>
    from torchtyping import TensorType
ModuleNotFoundError: No module named 'torchtyping'
```

After pip installing torchtyping I now get the following error:
```
Traceback (most recent call last):
  File "/home/drbenham/anaconda3/envs/nerfstudio/bin/ns-train", line 5, in <module>
    from nerfstudio.scripts.train import entrypoint
  File "/home/drbenham/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/scripts/train.py", line 62, in <module>
    from nerfstudio.configs.method_configs import AnnotatedBaseConfigUnion
  File "/home/drbenham/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/configs/method_configs.py", line 607, in <module>
    all_methods, all_descriptions = merge_methods(all_methods, all_descriptions, *discover_methods())
  File "/home/drbenham/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/plugins/registry.py", line 43, in discover_methods
    spec = discovered_entry_points[name].load()
  File "/home/drbenham/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 208, in load
    module = import_module(match.group('module'))
  File "/home/drbenham/anaconda3/envs/nerfstudio/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/drbenham/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/kplanes/kplanes_configs.py", line 13, in <module>
    from .kplanes import KPlanesModelConfig
  File "/home/drbenham/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/kplanes/kplanes.py", line 57, in <module>
    from .kplanes_field import KPlanesDensityField, KPlanesField
  File "/home/drbenham/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/kplanes/kplanes_field.py", line 33, in <module>
    from nerfstudio.fields.base_field import Field, shift_directions_for_tcnn
ImportError: cannot import name 'shift_directions_for_tcnn' from 'nerfstudio.fields.base_field' (/home/drbenham/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/fields/base_field.py)
```

**Additional context**
I get the same issue when running `kplanes-dynamic` as well.

Not related to this problem, but further information about what data k-planes needs as an input would also be very helpful.

**Comment by brentyi** [comment]
The specific runtime error you're seeing does look like it was fixed upstream several months ago. Are you on the latest version of the k-Planes repository?
https://github.com/Giodiro/kplanes_nerfstudio/pull/13/files

If that doesn't help:
- You could try an older version of Nerfstudio, which can't guarantee 100% backwards compatibility between releases. `torchtyping` was removed in ~May (see #1838), so a release from around then would probably be good!
- It might be better to file an issue in the k-Planes extension repo, since the Nerfstudio maintainers aren't necessarily familiar with it.

**Comment by kenton0607** [comment]
I also faced same problem, and I solved this by modifying function name `shift_directions_for_tcnn` to `get_normalized_directions` in file/to/miniconda3/envs/nerfstudio/Lib/site-packages/nerfstudio/fields/base_fields.py.

You can find `shift_directions_for_tcnn` in the old version by checkout the branch (e.g. `git checkout v3.0.1`, and you can also confirm `shift_directions_for_tcnn` and `get_normalized_directions` are completely the same functions:)

**Comment by remmel** [comment]
```
pip install torchtyping
pip uninstall kplanes-nerfstudio
pip install git+https://github.com/Giodiro/kplanes_nerfstudio #to use latest version included the fix for 'shift_directions_for_tcnn'
```
