### ISSUE TITLE
'ViewerControl' object has no attribute 'viewer_state' 

### ISSUE THREAD

**Issue by bparker9** [nerfstudio-project/nerfstudio#2666]
Attribute error when method ViewerControl.get_camera() is called. No issues with rendering, or other typical behavior of the viewer.

**To Reproduce**
1. Implement the "Get Camera Matrix" example in the Python Viewer Control section of the documentation. 
2. Run ns-viewer
3. Click on dummy button within the viewer control panel
4. See error on console

Error output:

Traceback (most recent call last):
  File "\***/python3.8/site-packages/viser/infra/_infra.py", line 449, in wrapped
    inner()
  File "\***/python3.8/site-packages/viser/infra/_infra.py", line 257, in <lambda>
    lambda: self._handle_incoming_message(client_id, message)
  File "\***/python3.8/site-packages/viser/infra/_infra.py", line 94, in _handle_incoming_message
    cb(client_id, message)
  File "\***/viewer/viser/message_api.py", line 668, in _handle_gui_updates
    cb(GuiHandle(handle_state))
  File "\***/viewer/server/viewer_elements.py", line 218, in <lambda>
    self.gui_handle.on_update(lambda _: self.cb_hook(self))
  File "\***/viewer/server/viewer_state.py", line 150, in <lambda>
    element.cb_hook = lambda element: [prev_cb(element), self._interrupt_render(element)]
  File "\***/custom_model.py", line 126, in button_cb
    camera = self.viewer_control.get_camera(100,100)
  File "\***/viewer/server/viewer_elements.py", line 126, in get_camera
    return self.viewer_state.get_camera(img_height, img_width)
AttributeError: 'ViewerControl' object has no attribute 'viewer_state'

**Comment by bparker9** [comment]
I believe I found the source of the bug. When the viewer script instantiates the ViewerState object, the pipeline object is parsed for instances of ViewerControl. However the input to else: parse_object() is self.trainer where it should be self.pipeline-------
`
     if self.trainer is not None:
            self.viewer_controls: List[ViewerControl] = [
                e for (_, e) in parse_object(self.trainer, ViewerControl, "Trainer")
            ]
        else:
            self.viewer_controls: List[ViewerControl] = [
                e for (_, e) in parse_object(self.trainer, ViewerControl, "Pipeline")
            ]
`
