### ISSUE TITLE
Allow gaussian splatting to initialize start points from other data pipelines than COLMAP

### ISSUE THREAD

**Issue by kerrj** [nerfstudio-project/nerfstudio#2681]
Currently, gaussian splatting intakes a pointcloud for initialization either through: 1) using a COLMAP dataset, or 2) adding a pointcloud to `transforms.json` and using the nerfstudio dataparser to read it. Currently, data intake pipelines like polycam, metashape, etc do not output a pointcloud and thus gaussian splatting will use a random initialization of points, which produces much worse results.

To fix this, we should edit the data intake scripts to add point clouds to the output `transforms.json` files and use the nerfstudio dataparser to read them. #2557 added the capability to load .ply files in the nerfstudio dataparser 

- [ ] Add to the COLMAP data processing pipeline to save pointclouds of the SFM points as output, and add it to the `transforms.json`
- [ ] Switch to nerfstudio dataparser as the default for splatting
- [ ] implement pointcloud saving in other data processing pipelines

**Comment by jb-ye** [comment]
FYI, metashape has a script for exporting colmap dataset (undistorted images): https://github.com/agisoft-llc/metashape-scripts/blob/master/src/export_for_gaussian_splatting.py

**Comment by FreakTheMighty** [comment]
@kerrj is it your experience that the guassian-splat pipeline runs, just with reduced quality, when using other data sources? What I'm seeing ATM is that when using polycam as input an error is thrown.

```py
    assert colmap_path.exists(), f"Colmap path {colmap_path} does not exist."
AssertionError: Colmap path Garage/colmap/sparse/0 does not exist.
```

**Comment by Tekn1ck** [comment]
I am also getting this when using RealityCapture. It would be super to get this up and running. If we could export the point cloud that Reality Capture generates would that help?

    assert colmap_path.exists(), f"Colmap path {colmap_path} does not exist."
AssertionError: Colmap path C:\Users\1user\nerfstudio\data\nerfstudio\farmhouse\colmap\sparse\0 does not exist.

(nerfstudio) C:\Users\Tekuser\nerfstudio>ns-train nerfacto --data C:\Users\1user\nerfstudio\data\nerfstudio\farmhouse
[15:24:27] Using --data alias for --data.pipeline.datamanager.data

**Comment by brentyi** [comment]
I think these errors are because the default dataparser for `gaussian-splatting` is set to `colmap`, while all other models set it to `nerfstudio-data`. There are plans to transition splatting over to the latter.

Specifying the `nerfstudio-data` subcommand should help fix `assert colmap_path.exists()` errors: `ns-train gaussian-splatting --data /path/to/a/processed/dataset nerfstudio-data`

**Comment by Tekn1ck** [comment]
That worked and I was able to train a Gaussian splat! Next issue I have is outputting the splat to PLY I get this error below. Would anyone know how to solve this?

(nerfstudio) C:\Users\1user\nerfstudio>ns-export gaussian-splat --load-config C:\Users\1user\nerfstudio\outputs\farmhouse\gaussian-splatting\2024-01-19_003623\config.yml --output-dir C:\Users\1user\nerfstudio\outputs\farmhouse\gaussian-splatting\2024-01-19_003623\PLY
Traceback (most recent call last):
  File "C:\Users\1user\miniconda3\envs\nerfstudio\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\1user\miniconda3\envs\nerfstudio\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\1user\miniconda3\envs\nerfstudio\Scripts\ns-export.exe\__main__.py", line 4, in <module>
  File "C:\Users\1user\nerfstudio\nerfstudio\scripts\exporter.py", line 39, in <module>
    from nerfstudio.exporter import texture_utils, tsdf_utils
  File "C:\Users\1user\nerfstudio\nerfstudio\exporter\texture_utils.py", line 26, in <module>
    import mediapy as media
  File "C:\Users\1user\miniconda3\envs\nerfstudio\lib\site-packages\mediapy\__init__.py", line 130, in <module>
    import IPython.display
  File "C:\Users\1user\miniconda3\envs\nerfstudio\lib\site-packages\IPython\__init__.py", line 53, in <module>
    from .terminal.embed import embed
  File "C:\Users\1user\miniconda3\envs\nerfstudio\lib\site-packages\IPython\terminal\embed.py", line 15, in <module>
    from IPython.core.interactiveshell import DummyMod, InteractiveShell
  File "C:\Users\1user\miniconda3\envs\nerfstudio\lib\site-packages\IPython\core\interactiveshell.py", line 73, in <module>
    from IPython.core.history import HistoryManager
  File "C:\Users\1user\miniconda3\envs\nerfstudio\lib\site-packages\IPython\core\history.py", line 11, in <module>
    import sqlite3
  File "C:\Users\1user\miniconda3\envs\nerfstudio\lib\sqlite3\__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "C:\Users\1user\miniconda3\envs\nerfstudio\lib\sqlite3\dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: DLL load failed while importing _sqlite3: The specified module could not be found.

**Comment by kerrj** [comment]
Update on this.... items 1 and 2 are done thanks to @CardiacMangoes, it should be pretty straightforward (but a bit tedious) to update other pipelines to output a pointcloud `.ply` file and add it to the transforms.json

**Comment by kerrj** [comment]
#3122 adds metashape!

**Comment by jb-ye** [comment]
#3131 adds realitycapture and fixed existing bugs in calculating cx,cy!

**Comment by jb-ye** [comment]
@SchmidL using sparse point cloud should be okay.

**Comment by jb-ye** [comment]
@SchmidL Use ns-process-data to convert metashape / RC exports into nerfstudio format (i.e. https://github.com/nerfstudio-project/nerfstudio/pull/3122#issue-2274206385 and https://github.com/nerfstudio-project/nerfstudio/pull/3131#issue-2286033201), and train with the nerfstudio formattedd data.

**Comment by mini-full** [comment]
> @SchmidL Use ns-process-data to convert metashape / RC exports into nerfstudio format (i.e. [#3122 (comment)](https://github.com/nerfstudio-project/nerfstudio/pull/3122#issue-2274206385) and [#3131 (comment)](https://github.com/nerfstudio-project/nerfstudio/pull/3131#issue-2286033201)), and train with the nerfstudio formattedd data.

@jb-ye Hi, I am wondering how other open-sourced Gaussian Splatting methods can be used with nerfstudio formatted data. Quite a lot of them use input in COLMAP data format. Are there any methods that can convert nerfstudio format into COLMAP? I did do some searching but I cannot find one. Or just write a dataloader for those methods? Thank you for your time.

**Comment by Jameson-Crate** [comment]
I'd like to work on finishing this issue. Can someone clarify if this is the correct state of integrated pipelines:
- [x] Polycam
- [x] Metashape
- [x] RealityCapture
- [ ] KIRI Engine Capture
- [ ] Record3D Capture
- [ ] Spectacular AI
- [ ] ODM
- [ ] Aria
