### ISSUE TITLE
gsplat fails to build with gaussian splatting pipeline

### ISSUE THREAD

**Issue by pablovela5620** [nerfstudio-project/nerfstudio#2685]
**Describe the bug**
Unable to builfd gsplat for running gaussian splat method. I get the following error

```
Traceback (most recent call last):
  File "/home/pablo/micromamba/envs/nerfstudio/lib/python3.10/site-packages/gsplat/cuda/_backend.py", line 56, in <module>
    from gsplat import csrc as _C
ImportError: cannot import name 'csrc' from 'gsplat' (/home/pablo/micromamba/envs/nerfstudio/lib/python3.10/site-packages/gsplat/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pablo/micromamba/envs/nerfstudio/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1893, in _run_ninja_build
    subprocess.run(
  File "/home/pablo/micromamba/envs/nerfstudio/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pablo/micromamba/envs/nerfstudio/bin/ns-train", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/pablo/0Dev/repos/nerfstudio/nerfstudio/scripts/train.py", line 262, in entrypoint
    main(
  File "/home/pablo/0Dev/repos/nerfstudio/nerfstudio/scripts/train.py", line 247, in main
    launch(
  File "/home/pablo/0Dev/repos/nerfstudio/nerfstudio/scripts/train.py", line 189, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "/home/pablo/0Dev/repos/nerfstudio/nerfstudio/scripts/train.py", line 100, in train_loop
    trainer.train()
  File "/home/pablo/0Dev/repos/nerfstudio/nerfstudio/engine/trainer.py", line 250, in train
    loss, loss_dict, metrics_dict = self.train_iteration(step)
  File "/home/pablo/0Dev/repos/nerfstudio/nerfstudio/utils/profiler.py", line 127, in inner
    out = func(*args, **kwargs)
  File "/home/pablo/0Dev/repos/nerfstudio/nerfstudio/engine/trainer.py", line 471, in train_iteration
    _, loss_dict, metrics_dict = self.pipeline.get_train_loss_dict(step=step)
  File "/home/pablo/0Dev/repos/nerfstudio/nerfstudio/utils/profiler.py", line 127, in inner
    out = func(*args, **kwargs)
  File "/home/pablo/0Dev/repos/nerfstudio/nerfstudio/pipelines/base_pipeline.py", line 304, in get_train_loss_dict
    model_outputs = self._model(ray_bundle)  # train distributed data parallel model if world_size > 1
  File "/home/pablo/micromamba/envs/nerfstudio/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/pablo/0Dev/repos/nerfstudio/nerfstudio/models/base_model.py", line 143, in forward
    return self.get_outputs(ray_bundle)
  File "/home/pablo/0Dev/repos/nerfstudio/nerfstudio/models/gaussian_splatting.py", line 591, in get_outputs
    self.xys, depths, self.radii, conics, num_tiles_hit, _ = ProjectGaussians.apply(  # type: ignore
  File "/home/pablo/micromamba/envs/nerfstudio/lib/python3.10/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/pablo/micromamba/envs/nerfstudio/lib/python3.10/site-packages/gsplat/project_gaussians.py", line 67, in forward
    ) = _C.project_gaussians_forward(
  File "/home/pablo/micromamba/envs/nerfstudio/lib/python3.10/site-packages/gsplat/cuda/__init__.py", line 7, in call_cuda
    from ._backend import _C
  File "/home/pablo/micromamba/envs/nerfstudio/lib/python3.10/site-packages/gsplat/cuda/_backend.py", line 64, in <module>
    _C = load(
  File "/home/pablo/micromamba/envs/nerfstudio/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1284, in load
    return _jit_compile(
  File "/home/pablo/micromamba/envs/nerfstudio/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1509, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/home/pablo/micromamba/envs/nerfstudio/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1624, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/home/pablo/micromamba/envs/nerfstudio/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1909, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'gsplat_cuda': [1/5] /home/pablo/micromamba/envs/nerfstudio/bin/nvcc  -DTORCH_EXTENSION_NAME=gsplat_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/home/pablo/micromamba/envs/nerfstudio/lib/python3.10/site-packages/gsplat/cuda/csrc/third_party/glm -isystem /home/pablo/micromamba/envs/nerfstudio/lib/python3.10/site-packages/torch/include -isystem /home/pablo/micromamba/envs/nerfstudio/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /home/pablo/micromamba/envs/nerfstudio/lib/python3.10/site-packages/torch/include/TH -isystem /home/pablo/micromamba/envs/nerfstudio/lib/python3.10/site-packages/torch/include/THC -isystem /home/pablo/micromamba/envs/nerfstudio/include -isystem /home/pablo/micromamba/envs/nerfstudio/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_61,code=compute_61 -gencode=arch=compute_61,code=sm_61 --compiler-options '-fPIC' -O3 -std=c++17 -c /home/pablo/micromamba/envs/nerfstudio/lib/python3.10/site-packages/gsplat/cuda/csrc/backward.cu -o backward.cuda.o 
/home/pablo/micromamba/envs/nerfstudio/lib/python3.10/site-packages/gsplat/cuda/csrc/backward.cu(340): warning #177-D: variable "cx" was declared but never referenced

/home/pablo/micromamba/envs/nerfstudio/lib/python3.10/site-packages/gsplat/cuda/csrc/backward.cu(341): warning #177-D: variable "cy" was declared but never referenced

[2/5] /home/pablo/micromamba/envs/nerfstudio/bin/nvcc  -DTORCH_EXTENSION_NAME=gsplat_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/home/pablo/micromamba/envs/nerfstudio/lib/python3.10/site-packages/gsplat/cuda/csrc/third_party/glm -isystem /home/pablo/micromamba/envs/nerfstudio/lib/python3.10/site-packages/torch/include -isystem /home/pablo/micromamba/envs/nerfstudio/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /home/pablo/micromamba/envs/nerfstudio/lib/python3.10/site-packages/torch/include/TH -isystem /home/pablo/micromamba/envs/nerfstudio/lib/python3.10/site-packages/torch/include/THC -isystem /home/pablo/micromamba/envs/nerfstudio/include -isystem /home/pablo/micromamba/envs/nerfstudio/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_61,code=compute_61 -gencode=arch=compute_61,code=sm_61 --compiler-options '-fPIC' -O3 -std=c++17 -c /home/pablo/micromamba/envs/nerfstudio/lib/python3.10/site-packages/gsplat/cuda/csrc/forward.cu -o forward.cuda.o 
[3/5] c++ -MMD -MF ext.o.d -DTORCH_EXTENSION_NAME=gsplat_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/home/pablo/micromamba/envs/nerfstudio/lib/python3.10/site-packages/gsplat/cuda/csrc/third_party/glm -isystem /home/pablo/micromamba/envs/nerfstudio/lib/python3.10/site-packages/torch/include -isystem /home/pablo/micromamba/envs/nerfstudio/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /home/pablo/micromamba/envs/nerfstudio/lib/python3.10/site-packages/torch/include/TH -isystem /home/pablo/micromamba/envs/nerfstudio/lib/python3.10/site-packages/torch/include/THC -isystem /home/pablo/micromamba/envs/nerfstudio/include -isystem /home/pablo/micromamba/envs/nerfstudio/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++17 -O3 -c /home/pablo/micromamba/envs/nerfstudio/lib/python3.10/site-packages/gsplat/cuda/csrc/ext.cpp -o ext.o 
[4/5] /home/pablo/micromamba/envs/nerfstudio/bin/nvcc  -DTORCH_EXTENSION_NAME=gsplat_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/home/pablo/micromamba/envs/nerfstudio/lib/python3.10/site-packages/gsplat/cuda/csrc/third_party/glm -isystem /home/pablo/micromamba/envs/nerfstudio/lib/python3.10/site-packages/torch/include -isystem /home/pablo/micromamba/envs/nerfstudio/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /home/pablo/micromamba/envs/nerfstudio/lib/python3.10/site-packages/torch/include/TH -isystem /home/pablo/micromamba/envs/nerfstudio/lib/python3.10/site-packages/torch/include/THC -isystem /home/pablo/micromamba/envs/nerfstudio/include -isystem /home/pablo/micromamba/envs/nerfstudio/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_61,code=compute_61 -gencode=arch=compute_61,code=sm_61 --compiler-options '-fPIC' -O3 -std=c++17 -c /home/pablo/micromamba/envs/nerfstudio/lib/python3.10/site-packages/gsplat/cuda/csrc/bindings.cu -o bindings.cuda.o 
/home/pablo/micromamba/envs/nerfstudio/lib/python3.10/site-packages/gsplat/cuda/csrc/bindings.cu(229): warning #177-D: variable "num_cov3d" was declared but never referenced

[5/5] c++ forward.cuda.o backward.cuda.o bindings.cuda.o ext.o -shared -L/home/pablo/micromamba/envs/nerfstudio/lib/python3.10/site-packages/torch/lib -lc10 -lc10_cuda -ltorch_cpu -ltorch_cuda -ltorch -ltorch_python -L/home/pablo/micromamba/envs/nerfstudio/lib64 -lcudart -o gsplat_cuda.so
FAILED: gsplat_cuda.so 
c++ forward.cuda.o backward.cuda.o bindings.cuda.o ext.o -shared -L/home/pablo/micromamba/envs/nerfstudio/lib/python3.10/site-packages/torch/lib -lc10 -lc10_cuda -ltorch_cpu -ltorch_cuda -ltorch -ltorch_python -L/home/pablo/micromamba/envs/nerfstudio/lib64 -lcudart -o gsplat_cuda.so
/usr/bin/ld: cannot find -lcudart: No such file or directory
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

```

tinycuda installed no problem so cuda 11.8 is being found. When I run
`which nvcc` I get 
```
/home/pablo/micromamba/envs/nerfstudio/bin/nvcc
```
`nvcc --version`
```
(nerfstudio) pablo@pablo-ubuntu:~/0Dev/repos/nerfstudio$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0
```

**To Reproduce**
1. Follow install instructions described [here](https://docs.nerf.studio/quickstart/installation.html)
2. Download nerfstudio bww_entrace dataset using `ns-download-data nerfstudio --capture-name poster`
3. Run `ns-train gaussian-splatting --data data/nerfstudio/poster`

**Expected behavior**
Should build gsplat cuda extension and train Gaussian Splatting

**Additional context**
Running `ns-train nerfacto --data data/nerfstudio/poster` works fine
running on a 1080ti with compute version 61. I have gotten gaussian splatting working with [gaussian-splatting-lightning](https://github.com/yzslab/gaussian-splatting-lightning)

**Comment by Guangyun-Xu** [comment]
I also meet the same bug, fixed by the follow step:

1. uninstall gsplat `pip unstall gsplat`

2. install gsplat from source  `pip install git+https://github.com/nerfstudio-project/gsplat.git` or `pip install git+https://github.com/nerfstudio-project/gsplat.git@v0.1.0`

**Comment by pablovela5620** [comment]
> I also meet the same bug, fixed by the follow step:
> 
> 1. uninstall gsplat `pip unstall gsplat`
> 2. install gsplat from source  `pip install git+https://github.com/nerfstudio-project/gsplat.git` or `pip install git+https://github.com/nerfstudio-project/gsplat.git@v0.1.0`

This fixed things for me, probably not ideal for folks to have to uninstall/reinstall from source so I'll leave this issue open and make one on the gsplat repo

**Comment by brentyi** [comment]
I think this should be fixed by #2748. (it's a PyTorch bug, and upgrading from torch 2.0 to torch 2.1 fixes it)

**Comment by xabila** [comment]
i have the same problem,  with a fresh install...

Here is what i did : 

```
conda create --name gaussian2 -y python=3.8
 conda activate gaussian2
 pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121
 conda install -c "nvidia/label/cuda-12.1.0" cuda-toolkit
 pip install ninja git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch
  git clone https://github.com/nerfstudio-project/nerfstudio.git
  cd nerfstudio
  pip install --upgrade pip setuptools
  pip install -e .
  ns-download-data nerfstudio --capture-name=poster
  ns-train.exe splatfacto --data data\nerfstudio\poster\
```

**Comment by IceDragonFla** [comment]
> i have the same problem, with a fresh install...
> 
> Here is what i did :
> 
> ```
> conda create --name gaussian2 -y python=3.8
>  conda activate gaussian2
>  pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121
>  conda install -c "nvidia/label/cuda-12.1.0" cuda-toolkit
>  pip install ninja git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch
>   git clone https://github.com/nerfstudio-project/nerfstudio.git
>   cd nerfstudio
>   pip install --upgrade pip setuptools
>   pip install -e .
>   ns-download-data nerfstudio --capture-name=poster
>   ns-train.exe splatfacto --data data\nerfstudio\poster\
> ```

have you reinstall the package? I had same problem with cannot import 'csrs', i just uninstall gsplat and install with `pip install git+https://github.com/nerfstudio-project/gsplat.git`

**Comment by DanielRossi1** [comment]
I solved it just by downgrading nerfstudio version from pypi: https://pypi.org/project/nerfstudio/#history
To install it, i just followed the instruction here: https://docs.nerf.studio/quickstart/installation.html with cuda architecture 52.

This is my dockerfile:
```

# OS SETTINGS
# Here you can choose the OS and the CUDA version you want to mount

FROM nvidia/cuda:11.8.0-devel-ubuntu20.04

# other examples:
# FROM nvidia/cuda:11.7.1-base-ubuntu22.04
# FROM nvidia/cuda:11.3.1-base-ubuntu20.04 # supports python 3.8 - 3.9
# FROM nvidia/cuda:11.8.0-base-ubuntu18.04 # supports python 3.6 - 3.7
# FROM nvidia/cuda:11.1.1-devel-ubuntu20.04 # supports python 3.8 - 3.9
# FROM nvidia/cuda:11.8.0-devel-ubuntu18.04 # supports python 3.6 - 3.7
# FROM nvidia/cuda:11.7.1-cudnn8-devel-ubuntu18.04 # supports python 3.6 - 3.7 with cuDNN 8


# you can find more versions here:
# https://hub.docker.com/r/nvidia/cuda/
# https://hub.docker.com/r/nvidia/cuda/tags?page=1&name=base-ubuntu


# -----------------------------------------------------------------------------------------------------------------------------------------------------
# ENVIRONMENT SETTINGS
# In this section we want to specify which softwares we want to pre-install within the docker

# to be sure we set non interactive bash also here
ENV DEBIAN_FRONTEND=noninteractive

# configuration for x11 forwarding
LABEL com.nvidia.volues.needed="nvidia-docker"
ENV PATH /usr/local/nvidia/bin:${PATH}
ENV LD_LIBRARY_PATH /usr/local/nvidia/lib:/usr/local/nvidia/lib64:${LD_LIBRARY_PATH}
RUN apt-get update && DEBIAN_FRONTEND="noninteractive" apt-get install -y -q \
    x11-apps mesa-utils && rm -rf /var/lib/apt/lists/*

# remove all the packages within Debian base configuration (not wasting time installing things that will not be used)
RUN rm -f /etc/apt/sources.list.d/*.list

# install Ubuntu Software needed for the development (DEBIAN_FRONTEND="noninteractive" needed to avoid human interaction in the process)
RUN apt-get update && DEBIAN_FRONTEND="noninteractive" && apt-get install -y -q\
    sudo \
    git \
    curl \
    wget \
    vim \
    bash \
    bash-completion \
    build-essential \
    ffmpeg \
    python3.8 \
    python3.8-dev \
    python3-pip \
    python3-tk \
&& rm -rf /var/lib/apt/lists/*

# set python update alternatives - the highest is the preferred one
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 1
RUN update-alternatives --config python3

# remove python2
RUN ln -sf /usr/bin/python3 /usr/bin/python && \
    ln -sf /usr/bin/pip3 /usr/bin/pip

# -----------------------------------------------------------------------------------------------------------------------------------------------------
# USER SETTINGS

# the docker's user will be 'user' or $USER and its home will be '/user/home' or '/$USER/home'
ARG UID=1000
ARG GID=1000
ARG USER_NAME=user
ARG USER_HOME=/home/$USER_NAME

# create a new user within the Docker container
RUN groupadd -g $GID -o $USER_NAME \
    && useradd -m -u $UID -g $GID -o -s /bin/bash $USER_NAME \
    && echo "$USER_NAME:Docker!" | chpasswd \
    && mkdir -p /src && chown -R $USER_NAME:$USER_NAME /src \
    && mkdir -p /etc/sudoers.d \
    && usermod -aG video $USER_NAME \
    && echo "$USER_NAME ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/$USER_NAME

# -----------------------------------------------------------------------------------------------------------------------------------------------------
# FINAL SETUPS

# upgrade python pip
RUN pip install --upgrade pip

# install python packages in requirements directory
# project/
# |-- ai-base-docker/
# |   |   |-- build.sh
# |   |   |-- Dockerfile
# |   |   |-- run.sh
# |-- src/
# |   |   |-- model/
# |   |   |-- utils/
# |   |   |-- requirements/
# |   |       |-- base.txt
# |   |       |-- devel.txt

# COLMAP
RUN apt-get update && DEBIAN_FRONTEND="noninteractive" && apt-get install -y -q\
    git \
    cmake \
    ninja-build \
    build-essential \
    libboost-program-options-dev \
    libboost-filesystem-dev \
    libboost-graph-dev \
    libboost-system-dev \
    libeigen3-dev \
    libflann-dev \
    libfreeimage-dev \
    libmetis-dev \
    libgoogle-glog-dev \
    libgtest-dev \
    libsqlite3-dev \
    libglew-dev \
    qtbase5-dev \
    libqt5opengl5-dev \
    libcgal-dev \
    libceres-dev \
&& rm -rf /var/lib/apt/lists/*

WORKDIR ${USER_HOME}/src
RUN git clone https://github.com/colmap/colmap.git
WORKDIR ${USER_HOME}/src/colmap
RUN mkdir build
WORKDIR ${USER_HOME}/src/colmap/build
RUN cmake .. -GNinja
RUN ninja
RUN ninja install

RUN pip install torch==2.1.2+cu118 torchvision==0.16.2+cu118 --extra-index-url https://download.pytorch.org/whl/cu118
ENV TCNN_CUDA_ARCHITECTURES="52"
RUN pip install ninja git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch
RUN pip install --upgrade pip setuptools
RUN pip install nerfstudio==1.0.0

USER $USER_NAME
WORKDIR $USER_HOME

# if you need to download .whl packages from a link
# RUN python -m pip download --only-binary :all: --dest . --no-cache PACKAGE-DOWNLOAD-LINK.whl

# # remove all the created/copied/moved file by the docker
# RUN rm -rf *

# when the container is launched it will start a bash session
CMD ["/bin/bash"]

```

You can find the generalization of this dockerfile here: https://github.com/ProjectoOfficial/ai-base-docker

**Comment by chris-the-wiz** [comment]
i am also having the problem. I tried with the dockerfile from @DanielRossi1 as well as another one based on pytorch/pytorch:2.3.1-cuda11.8-cudnn8-devel image. 
 I am getting is a bunch of errors when running ninja:
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
[10/217] Building CXX object src/colmap/controllers/CMakeFiles/colmap_controllers.dir/option_manager.cc.o
FAILED: src/colmap/controllers/CMakeFiles/colmap_controllers.dir/option_manager.cc.o
(...)
 c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
[11/217] Building CXX object src/colmap/estimators/CMakeFiles/colmap_estimators.dir/pose.cc.o
FAILED: src/colmap/estimators/CMakeFiles/colmap_estimators.dir/pose.cc.o

there are multiple processes and they fail on different files

**Comment by dhanush70125** [comment]
> I also meet the same bug, fixed by the follow step:
> 
> 1. uninstall gsplat `pip unstall gsplat`
> 2. install gsplat from source  `pip install git+https://github.com/nerfstudio-project/gsplat.git` or `pip install git+https://github.com/nerfstudio-project/gsplat.git@v0.1.0`

Worked for me. Thanks

**Comment by gnehs** [comment]
Installing the prebuilt package can fix this issue

`pip install gsplat --index-url https://docs.gsplat.studio/whl/pt22cu118`

- This installs for `PyTorch 2.0` and `CUDA 11.8`
- Adjust the url according to the version you have installed.

**Comment by shreyasshivakumara** [comment]
> i have the same problem, with a fresh install...
> 
> Here is what i did :
> 
> ```
> conda create --name gaussian2 -y python=3.8
>  conda activate gaussian2
>  pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121
>  conda install -c "nvidia/label/cuda-12.1.0" cuda-toolkit
>  pip install ninja git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch
>   git clone https://github.com/nerfstudio-project/nerfstudio.git
>   cd nerfstudio
>   pip install --upgrade pip setuptools
>   pip install -e .
>   ns-download-data nerfstudio --capture-name=poster
>   ns-train.exe splatfacto --data data\nerfstudio\poster\
> ```

This works! Thanks! :)
