### ISSUE TITLE
ns-train returns error with gaussian-splatting or igs2gs model

### ISSUE THREAD

**Issue by sblat021** [nerfstudio-project/nerfstudio#2727]
Whenever I run ns-train with gaussian-splatting or igs2gs I get the following error (it works fine when using nerfacto): 

----------------
{NOTE] Not running eval iterations since only viewer is enabled.
Use --vis {wandb, tensorboard, viewer+wandb, viewer+tensorboard} to run with eval.
No Nerfstudio checkpoint to load, so training from scratch.
Disabled comet/tensorboard/wandb event writers
C:\Users\micro\anaconda3\envs\nerfstudio\lib\site-packages\torch\utils\cpp_extension.py:359: UserWarning: Error checking compiler version for cl:
[WinError 2] The system cannot find the file specified
  warnings.warn(f'Error checking compiler version for {compiler}: {error}')
( ●    ) gsplat: Setting up CUDA (This may take a few minutes the first time)INFO: Could not find files for the given pattern(s).
Printing profiling stats, from longest to shortest duration in seconds
VanillaPipeline.get_train_loss_dict: 0.6218
Trainer.train_iteration: 0.6218
Traceback (most recent call last):
  File "C:\Users\micro\anaconda3\envs\nerfstudio\lib\site-packages\gsplat\cuda\_backend.py", line 56, in <module>
    from gsplat import csrc as _C
ImportError: cannot import name 'csrc' from 'gsplat' (C:\Users\micro\anaconda3\envs\nerfstudio\lib\site-packages\gsplat\__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\micro\anaconda3\envs\nerfstudio\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\micro\anaconda3\envs\nerfstudio\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\micro\anaconda3\envs\nerfstudio\Scripts\ns-train.exe\__main__.py", line 7, in <module>
  File "C:\Apps\nerfstudio\nerfstudio\scripts\train.py", line 262, in entrypoint
    main(
  File "C:\Apps\nerfstudio\nerfstudio\scripts\train.py", line 247, in main
    launch(
  File "C:\Apps\nerfstudio\nerfstudio\scripts\train.py", line 189, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "C:\Apps\nerfstudio\nerfstudio\scripts\train.py", line 100, in train_loop
    trainer.train()
  File "C:\Apps\nerfstudio\nerfstudio\engine\trainer.py", line 250, in train
    loss, loss_dict, metrics_dict = self.train_iteration(step)
  File "C:\Apps\nerfstudio\nerfstudio\utils\profiler.py", line 127, in inner
    out = func(*args, **kwargs)
  File "C:\Apps\nerfstudio\nerfstudio\engine\trainer.py", line 471, in train_iteration
    _, loss_dict, metrics_dict = self.pipeline.get_train_loss_dict(step=step)
  File "C:\Apps\nerfstudio\nerfstudio\utils\profiler.py", line 127, in inner
    out = func(*args, **kwargs)
  File "C:\Apps\nerfstudio\nerfstudio\pipelines\base_pipeline.py", line 304, in get_train_loss_dict
    model_outputs = self._model(ray_bundle)  # train distributed data parallel model if world_size > 1
  File "C:\Users\micro\anaconda3\envs\nerfstudio\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Apps\nerfstudio\nerfstudio\models\base_model.py", line 143, in forward
    return self.get_outputs(ray_bundle)
  File "C:\Apps\nerfstudio\nerfstudio\models\gaussian_splatting.py", line 591, in get_outputs
    self.xys, depths, self.radii, conics, num_tiles_hit, _ = ProjectGaussians.apply(  # type: ignore
  File "C:\Users\micro\anaconda3\envs\nerfstudio\lib\site-packages\torch\autograd\function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "C:\Users\micro\anaconda3\envs\nerfstudio\lib\site-packages\gsplat\project_gaussians.py", line 67, in forward
    ) = _C.project_gaussians_forward(
  File "C:\Users\micro\anaconda3\envs\nerfstudio\lib\site-packages\gsplat\cuda\__init__.py", line 7, in call_cuda
    from ._backend import _C
  File "C:\Users\micro\anaconda3\envs\nerfstudio\lib\site-packages\gsplat\cuda\_backend.py", line 79, in <module>
    _C = load(
  File "C:\Users\micro\anaconda3\envs\nerfstudio\lib\site-packages\torch\utils\cpp_extension.py", line 1284, in load
    return _jit_compile(
  File "C:\Users\micro\anaconda3\envs\nerfstudio\lib\site-packages\torch\utils\cpp_extension.py", line 1509, in _jit_compile
    _write_ninja_file_and_build_library(
  File "C:\Users\micro\anaconda3\envs\nerfstudio\lib\site-packages\torch\utils\cpp_extension.py", line 1611, in _write_ninja_file_and_build_library
    _write_ninja_file_to_build_library(
  File "C:\Users\micro\anaconda3\envs\nerfstudio\lib\site-packages\torch\utils\cpp_extension.py", line 2048, in _write_ninja_file_to_build_library
    _write_ninja_file(
  File "C:\Users\micro\anaconda3\envs\nerfstudio\lib\site-packages\torch\utils\cpp_extension.py", line 2188, in _write_ninja_file
    cl_paths = subprocess.check_output(['where',
  File "C:\Users\micro\anaconda3\envs\nerfstudio\lib\subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\micro\anaconda3\envs\nerfstudio\lib\subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['where', 'cl']' returned non-zero exit status 1.
--------------------

1. After running COLMAP I run :  ns-train gaussian-splatting --data output
2. First few steps seem to work fine and then it crashes once it gets to: Trainer.train_iteration
3. See error message above

**Expected behavior**
I expect the COLMAP data to be trained using the gaussian-splatting or igs2gs model.

**Additional context**
I followed the installation instructions exactly. 

After nerfstudio dependencies I installed gsplat using: 
pip install git+https://github.com/nerfstudio-project/gsplat.git

After that I installed nerfstudio following instructions: 
git clone https://github.com/nerfstudio-project/nerfstudio.git
cd nerfstudio
pip install --upgrade pip setuptools
pip install -e .

Visual Studio 2019 is installed including Desktop development with C+.

**Comment by sblat021** [comment]
This was resolved by uninstalling gsplat and reinstalling it like so: 
pip install git+https://github.com/nerfstudio-project/gsplat.git@v0.1.0

However igs2gs is still returning an error: 

Trainer.train_iteration: 1.2786
Traceback (most recent call last):
  File "C:\Users\micro\anaconda3\envs\nerfstudio\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\micro\anaconda3\envs\nerfstudio\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\micro\anaconda3\envs\nerfstudio-igs2gs\Scripts\ns-train.exe\__main__.py", line 7, in <module>
  File "C:\Apps\nerfstudio\nerfstudio\scripts\train.py", line 262, in entrypoint
    main(
  File "C:\Apps\nerfstudio\nerfstudio\scripts\train.py", line 247, in main
    launch(
  File "C:\Apps\nerfstudio\nerfstudio\scripts\train.py", line 189, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "C:\Apps\nerfstudio\nerfstudio\scripts\train.py", line 100, in train_loop
    trainer.train()
  File "C:\Apps\nerfstudio\nerfstudio\engine\trainer.py", line 250, in train
    loss, loss_dict, metrics_dict = self.train_iteration(step)
  File "C:\Apps\nerfstudio\nerfstudio\utils\profiler.py", line 127, in inner
    out = func(*args, **kwargs)
  File "C:\Apps\nerfstudio\nerfstudio\engine\trainer.py", line 471, in train_iteration
    _, loss_dict, metrics_dict = self.pipeline.get_train_loss_dict(step=step)
  File "C:\Users\micro\anaconda3\envs\nerfstudio\lib\site-packages\igs2gs\igs2gs_pipeline.py", line 123, in get_train_loss_dict
    edited_image = self.ip2p.edit_image(
  File "C:\Users\micro\anaconda3\envs\nerfstudio\lib\site-packages\igs2gs\ip2p.py", line 154, in edit_image
    latent_model_input = torch.cat([latent_model_input, image_cond_latents], dim=1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 29 but got size 119 for tensor number 1 in the list.

**Comment by Lanig77** [comment]
hi, what is the command to remove previous gsplat install. I have exactly the same issue

**Comment by javieryu** [comment]
Worked for me.
```
pip uninstall gsplat
pip install git+https://github.com/nerfstudio-project/gsplat.git@v0.1.0
```

**Comment by vincenzorin** [comment]
If the error persists, consider installing from

`pip install git+https://github.com/nerfstudio-project/gsplat.git`

as suggested in https://github.com/nerfstudio-project/nerfstudio/issues/2685#issuecomment-1859660671

**Comment by brentyi** [comment]
If you're seeing this issue in PyTorch 2.0, there's also a good chance it's a PyTorch bug. Upgrading to 2.1 fixes it for some systems.

(https://github.com/nerfstudio-project/nerfstudio/pull/2748 has notes on why)

**Comment by ILLCamaras** [comment]
I have PyTorch 2.1.2+cu118 installed

and I've tried:
`pip uninstall gsplat`
`pip install git+https://github.com/nerfstudio-project/gsplat.git@v0.1.0.`

and also 

`pip uninstall gsplat`
`pip install git+https://github.com/nerfstudio-project/gsplat.git@v0.1.2.1.`

but I always get

`...`
`Installing collected packages: gsplat`
`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.`
`nerfstudio 1.0.0 requires gsplat==0.1.2.1, but you have gsplat 0.1.2 which is incompatible.`

**Comment by brentyi** [comment]
Do you have an extra period here?

`pip install git+https://github.com/nerfstudio-project/gsplat.git@v0.1.2.1.` => `pip install git+https://github.com/nerfstudio-project/gsplat.git@v0.1.2.1` may work.

**Comment by ILLCamaras** [comment]
Install apparently work with only a Yellow warning:
`WARNING: Failed to remove contents in a temporary directory 'C:\Users\carlo\AppData\Local\Temp\pip-req-build-w_szq5df'.`
`You can safely remove it manually.`

But it doesn't and I can't run `ns-train` either as `splatfacto`
or `gaussian-splatting`

Here the `splatfacto` error if could help

`Traceback (most recent call last):
  File "C:\Users\carlo\anaconda3\envs\nerfstudio\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\carlo\anaconda3\envs\nerfstudio\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\carlo\anaconda3\envs\nerfstudio\Scripts\ns-train.exe\__main__.py", line 4, in <module>
  File "C:\Users\carlo\nerfstudio\nerfstudio\scripts\train.py", line 62, in <module>
    from nerfstudio.configs.method_configs import AnnotatedBaseConfigUnion
  File "C:\Users\carlo\nerfstudio\nerfstudio\configs\method_configs.py", line 28, in <module>
    from nerfstudio.configs.external_methods import get_external_methods
  File "C:\Users\carlo\nerfstudio\nerfstudio\configs\external_methods.py", line 24, in <module>
    from nerfstudio.engine.trainer import TrainerConfig
  File "C:\Users\carlo\nerfstudio\nerfstudio\engine\trainer.py", line 39, in <module>
    from nerfstudio.viewer_legacy.server.viewer_state import ViewerLegacyState
  File "C:\Users\carlo\nerfstudio\nerfstudio\viewer_legacy\server\viewer_state.py", line 41, in <module>
    from nerfstudio.viewer_legacy.server.render_state_machine import RenderAction, RenderStateMachine
  File "C:\Users\carlo\nerfstudio\nerfstudio\viewer_legacy\server\render_state_machine.py", line 27, in <module>
    from nerfstudio.models.gaussian_splatting import GaussianSplattingModel
  File "C:\Users\carlo\nerfstudio\nerfstudio\models\gaussian_splatting.py", line 30, in <module>
    from gsplat.compute_cumulative_intersects import compute_cumulative_intersects
ModuleNotFoundError: No module named 'gsplat.compute_cumulative_intersects'

**Comment by brentyi** [comment]
Are you on the latest version of nerfstudio?

**Comment by ILLCamaras** [comment]
That's my intention, I've completely rebuilt the anaconda environment installing:

`git clone https://github.com/nerfstudio-project/nerfstudio.git`
`cd nerfstudio`
`pip install --upgrade pip setuptools`
`pip install -e .`

**Comment by brentyi** [comment]
Interesting, what's strange to me is this part of your error:
```
File "C:\Users\carlo\nerfstudio\nerfstudio\models\gaussian_splatting.py", line 30, in
from gsplat.compute_cumulative_intersects import compute_cumulative_intersects
ModuleNotFoundError: No module named 'gsplat.compute_cumulative_intersects'
```

We no longer have a `gaussian_splatting.py` in the repo, nor is the line that's producing this error present in the main branch when I search for it. Are you still getting this error despite a fresh clone of the repo?

**Comment by ILLCamaras** [comment]
I was rebuilding everything again but while installing it asked me to upgrade anaconda, I did it and I've lost ability to run Anaconda Navigator and installation went wrong. I'm uninstalling everything and start again from scratch. Thanks for help, I let you know.

**Comment by ILLCamaras** [comment]
I've reinstalled everything from Anaconda down to Nerfstudio following the guide but
`ns-train splatfacto --data C:\Users\carlo\3DGSprojects\1750_CM --pipeline.model.cull-alpha-thresh 0.002 --max-num-iterations 100000 colmap --load_3D_points=True --downscale_factor 2'
give me back the same error as before at first run, so I came back here and run

`pip uninstall gsplat`
`pip install git+https://github.com/nerfstudio-project/gsplat.git@v0.1.0`

and also

`pip uninstall gsplat`
`pip install git+https://github.com/nerfstudio-project/gsplat.git`

receiving the same error.
<img width="1027" alt="GS Error" src="https://github.com/nerfstudio-project/nerfstudio/assets/155579952/20d18ea2-439e-4a7c-9a85-bac983f54888">

 So I close the shell and run again the same command in a new one and now it's running! 
I'm around 15% now, it will take another 3h to complete. 
I'll post the results.

**Comment by ichsan2895** [comment]
Now, please run 
```
conda env export --no-builds > environment-nerfstudio.yml
```

so, in the next time, if (someday) your system breaks and you must reinstall python/conda, you can replicate the previous environment by running:
```
conda env create -f environment-nerfstudio.yml -n nerfstudio
```

**Comment by ILLCamaras** [comment]
Thanks @ichsan2895

**Comment by ljbuckers** [comment]
Same issues as above and it solved for me - many thanks.

**Comment by lukehollis** [comment]
This solved for me--and if it's helpful, I was able to resolve just by building from source w/o @version

pip install git+https://github.com/nerfstudio-project/gsplat.git

**Comment by Annkyotou** [comment]
I had the same problem, just for those who are using **Windows system** to install Gsplat, please try
`pip uninstall gsplat`
and then refer to 
https://github.com/nerfstudio-project/gsplat/blob/main/docs/INSTALL_WIN.md

**Comment by wslgqq277g** [comment]
> If the error persists, consider installing from
> 
> `pip install git+https://github.com/nerfstudio-project/gsplat.git`
> 
> as suggested in [#2685 (comment)](https://github.com/nerfstudio-project/nerfstudio/issues/2685#issuecomment-1859660671)

work for me

**Comment by luoziyou** [comment]
You can find the hidden error reason by entering the code below

```
python - << EOF
from gsplat import csrc as _C
EOF
```

And a message like this will pop up, suggesting some missing library

`ImportError: /lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.15' not found`

To solve the error, enter the lines below (https://github.com/unitreerobotics/unitree_rl_lab/issues/106)

```
conda remove libstdcxx-ng --force 
conda install -c conda-forge "libstdcxx-ng>=13" 
export LD_LIBRARY_PATH=$CONDA_PREFIX/lib:$LD_LIBRARY_PATH
```

You can verify the installation of the library via the line below

`strings $CONDA_PREFIX/lib/libstdc++.so.6 | grep CXXABI`


And then there should be no problems anymore with csrc (you can verify again by lines below)

```
python - << EOF
from gsplat import csrc as _C
EOF
```
