### ISSUE TITLE
Error checking compiler version for cl: [WinError 2] splatfacto model

### ISSUE THREAD

**Issue by IvanTymoshenko** [nerfstudio-project/nerfstudio#2820]
Good day. I am a total newbee here using Nerf and Gaussian Splatting. Also I am not a programmer. Just starting to open this world for myself. During the installation of Nerfstudio everything was fine. No errors occured. As soon as i am starting training using command `ns-train splatfacto --data data/nerfstudio/poster` it does not want to start the training and showing this error:

`No Nerfstudio checkpoint to load, so training from scratch.
Disabled comet/tensorboard/wandb event writers
C:\Users\user\.conda\envs\nerfstudio\lib\site-packages\torch\utils\cpp_extension.py:383: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
  warnings.warn(f'Error checking compiler version for {compiler}: {error}')
( ●    ) gsplat: Setting up CUDA (This may take a few minutes the first time)INFO: Could not find files for the given pattern(s).
Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Users\user\.conda\envs\nerfstudio\lib\site-packages\gsplat\cuda\_backend.py", line 56, in <module>
    from gsplat import csrc as _C
ImportError: cannot import name 'csrc' from 'gsplat' (C:\Users\user\.conda\envs\nerfstudio\lib\site-packages\gsplat\__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\.conda\envs\nerfstudio\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\user\nerfstudio\nerfstudio\viewer\render_state_machine.py", line 218, in run
    outputs = self._render_img(action.camera_state)
  File "C:\Users\user\nerfstudio\nerfstudio\viewer\render_state_machine.py", line 164, in _render_img
    outputs = self.viewer.get_model().get_outputs_for_camera(camera, obb_box=obb)
  File "C:\Users\user\.conda\envs\nerfstudio\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\user\nerfstudio\nerfstudio\models\splatfacto.py", line 866, in get_outputs_for_camera
    outs = self.get_outputs(camera.to(self.device))
  File "C:\Users\user\nerfstudio\nerfstudio\models\splatfacto.py", line 717, in get_outputs
    self.xys, depths, self.radii, conics, num_tiles_hit, cov3d = project_gaussians(  # type: ignore
  File "C:\Users\user\.conda\envs\nerfstudio\lib\site-packages\gsplat\project_gaussians.py", line 59, in project_gaussians
    return _ProjectGaussians.apply(
  File "C:\Users\user\.conda\envs\nerfstudio\lib\site-packages\torch\autograd\function.py", line 539, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "C:\Users\user\.conda\envs\nerfstudio\lib\site-packages\gsplat\project_gaussians.py", line 107, in forward
    ) = _C.project_gaussians_forward(
  File "C:\Users\user\.conda\envs\nerfstudio\lib\site-packages\gsplat\cuda\__init__.py", line 7, in call_cuda
    from ._backend import _C
  File "C:\Users\user\.conda\envs\nerfstudio\lib\site-packages\gsplat\cuda\_backend.py", line 86, in <module>
    _C = load(
  File "C:\Users\user\.conda\envs\nerfstudio\lib\site-packages\torch\utils\cpp_extension.py", line 1308, in load
    return _jit_compile(
  File "C:\Users\user\.conda\envs\nerfstudio\lib\site-packages\torch\utils\cpp_extension.py", line 1710, in _jit_compile
    _write_ninja_file_and_build_library(
  File "C:\Users\user\.conda\envs\nerfstudio\lib\site-packages\torch\utils\cpp_extension.py", line 1810, in _write_ninja_file_and_build_library
    _write_ninja_file_to_build_library(
  File "C:\Users\user\.conda\envs\nerfstudio\lib\site-packages\torch\utils\cpp_extension.py", line 2242, in _write_ninja_file_to_build_library
    _write_ninja_file(
  File "C:\Users\user\.conda\envs\nerfstudio\lib\site-packages\torch\utils\cpp_extension.py", line 2382, in _write_ninja_file
    cl_paths = subprocess.check_output(['where',
  File "C:\Users\user\.conda\envs\nerfstudio\lib\subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\user\.conda\envs\nerfstudio\lib\subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['where', 'cl']' returned non-zero exit status 1.
Printing profiling stats, from longest to shortest duration in seconds
Trainer.train_iteration: 0.0225
VanillaPipeline.get_train_loss_dict: 0.0215
Traceback (most recent call last):
  File "C:\Users\user\.conda\envs\nerfstudio\lib\site-packages\gsplat\cuda\_backend.py", line 56, in <module>
    from gsplat import csrc as _C
ImportError: cannot import name 'csrc' from 'gsplat' (C:\Users\user\.conda\envs\nerfstudio\lib\site-packages\gsplat\__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\.conda\envs\nerfstudio\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\user\.conda\envs\nerfstudio\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\.conda\envs\nerfstudio\Scripts\ns-train.exe\__main__.py", line 7, in <module>
  File "C:\Users\user\nerfstudio\nerfstudio\scripts\train.py", line 262, in entrypoint
    main(
  File "C:\Users\user\nerfstudio\nerfstudio\scripts\train.py", line 247, in main
    launch(
  File "C:\Users\user\nerfstudio\nerfstudio\scripts\train.py", line 189, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "C:\Users\user\nerfstudio\nerfstudio\scripts\train.py", line 100, in train_loop
    trainer.train()
  File "C:\Users\user\nerfstudio\nerfstudio\engine\trainer.py", line 252, in train
    loss, loss_dict, metrics_dict = self.train_iteration(step)
  File "C:\Users\user\nerfstudio\nerfstudio\utils\profiler.py", line 112, in inner
    out = func(*args, **kwargs)
  File "C:\Users\user\nerfstudio\nerfstudio\engine\trainer.py", line 473, in train_iteration
    _, loss_dict, metrics_dict = self.pipeline.get_train_loss_dict(step=step)
  File "C:\Users\user\nerfstudio\nerfstudio\utils\profiler.py", line 112, in inner
    out = func(*args, **kwargs)
  File "C:\Users\user\nerfstudio\nerfstudio\pipelines\base_pipeline.py", line 300, in get_train_loss_dict
    model_outputs = self._model(ray_bundle)  # train distributed data parallel model if world_size > 1
  File "C:\Users\user\.conda\envs\nerfstudio\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\user\.conda\envs\nerfstudio\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\user\nerfstudio\nerfstudio\models\base_model.py", line 143, in forward
    return self.get_outputs(ray_bundle)
  File "C:\Users\user\nerfstudio\nerfstudio\models\splatfacto.py", line 717, in get_outputs
    self.xys, depths, self.radii, conics, num_tiles_hit, cov3d = project_gaussians(  # type: ignore
  File "C:\Users\user\.conda\envs\nerfstudio\lib\site-packages\gsplat\project_gaussians.py", line 59, in project_gaussians
    return _ProjectGaussians.apply(
  File "C:\Users\user\.conda\envs\nerfstudio\lib\site-packages\torch\autograd\function.py", line 539, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "C:\Users\user\.conda\envs\nerfstudio\lib\site-packages\gsplat\project_gaussians.py", line 107, in forward
    ) = _C.project_gaussians_forward(
  File "C:\Users\user\.conda\envs\nerfstudio\lib\site-packages\gsplat\cuda\__init__.py", line 7, in call_cuda
    from ._backend import _C
  File "C:\Users\user\.conda\envs\nerfstudio\lib\site-packages\gsplat\cuda\_backend.py", line 86, in <module>
    _C = load(
  File "C:\Users\user\.conda\envs\nerfstudio\lib\site-packages\torch\utils\cpp_extension.py", line 1308, in load
    return _jit_compile(
  File "C:\Users\user\.conda\envs\nerfstudio\lib\site-packages\torch\utils\cpp_extension.py", line 1736, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "C:\Users\user\.conda\envs\nerfstudio\lib\site-packages\torch\utils\cpp_extension.py", line 2136, in _import_module_from_library
    module = importlib.util.module_from_spec(spec)
ImportError: DLL load failed while importing gsplat_cuda: The specified module could not be found.`

Please help me to resolve this issue if possible.
Nerfstudio i use the latest one on Windows 11 x64.

UPDATE: I try to reinstall torch using commands below, but error is still occurs.
`pip uninstall torch torchvision functorch tinycudann`
`pip install torch==2.1.2+cu118 torchvision==0.16.2+cu118 --extra-index-url https://download.pytorch.org/whl/cu118`
`conda install -c "nvidia/label/cuda-11.8.0" cuda-toolkit`
`pip install ninja git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch`

**Comment by IvanTymoshenko** [comment]
Issue is solved!
I found simmilar issue on Github, but using nerfacto model
LINK: https://github.com/nerfstudio-project/nerfstudio/issues/2029
So i try to reinstall Gsplat model. 2 strokes of code help me out. Please note that i was located in Anaconda nerfstudio enviroment.
```
pip uninstall gsplat
pip install git+https://github.com/nerfstudio-project/gsplat.git
```
As i understand, Gsplat needs to be updated. After reinstalling it, being inside anaconda nerfstudio enviroment, i receive an error
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
nerfstudio 1.0.0 requires gsplat==0.1.2.1, but you have gsplat 0.1.3 which is incompatible.
```

But i ignore it and try to run training. And it worked!
I agnovledge that it might not be the solution, or fix, but it worked for me. If there will be any recommendation on how to fix it in a propper way - please advice.
