### ISSUE TITLE
ns-train splatfacto for nerfstudio-data with mask_path report RuntimeError

### ISSUE THREAD

**Issue by a11enL** [nerfstudio-project/nerfstudio#2904]
ns-train splatfacto for nerfstudio-data with mask_path report:
RuntimeError: The size of tensor a (3) must match the size of tensor b (3839) at non-singleton dimension 2

ns-train nerfacto works for this same dataset, but splatfacto failed

nerfstudio 1.0.1
ubuntu 22.04
pytorch 2.1.2
cuda 11.8

**To Reproduce**
1. ns-train splatfacto --pipeline.datamanager.masks-on-gpu True --data data/test-data nerfstudio-data 
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/ns-train", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/ubuntu/nerfstudio-1.0.1/nerfstudio/scripts/train.py", line 262, in entrypoint
    main(
  File "/home/ubuntu/nerfstudio-1.0.1/nerfstudio/scripts/train.py", line 247, in main
    launch(
  File "/home/ubuntu/nerfstudio-1.0.1/nerfstudio/scripts/train.py", line 189, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "/home/ubuntu/nerfstudio-1.0.1/nerfstudio/scripts/train.py", line 100, in train_loop
    trainer.train()
  File "/home/ubuntu/nerfstudio-1.0.1/nerfstudio/engine/trainer.py", line 250, in train
    loss, loss_dict, metrics_dict = self.train_iteration(step)
  File "/home/ubuntu/nerfstudio-1.0.1/nerfstudio/utils/profiler.py", line 112, in inner
    out = func(*args, **kwargs)
  File "/home/ubuntu/nerfstudio-1.0.1/nerfstudio/engine/trainer.py", line 471, in train_iteration
    _, loss_dict, metrics_dict = self.pipeline.get_train_loss_dict(step=step)
  File "/home/ubuntu/nerfstudio-1.0.1/nerfstudio/utils/profiler.py", line 112, in inner
    out = func(*args, **kwargs)
  File "/home/ubuntu/nerfstudio-1.0.1/nerfstudio/pipelines/base_pipeline.py", line 302, in get_train_loss_dict
    loss_dict = self.model.get_loss_dict(model_outputs, batch, metrics_dict)
  File "/home/ubuntu/nerfstudio-1.0.1/nerfstudio/models/splatfacto.py", line 838, in get_loss_dict
    gt_img = gt_img * mask
RuntimeError: The size of tensor a (3) must match the size of tensor b (3839) at non-singleton dimension 2

**Comment by maturk** [comment]
masks should be shape [h,w] not [h,w,1] for splatfacto i think... hmm

**Comment by a11enL** [comment]
masks with shape [h,w,1] work (trainning works)

**Comment by alchemz** [comment]
@a11enL Hi, how did you fix this issue?

**Comment by a11enL** [comment]
> @a11enL Hi, how did you fix this issue?

Hi, you can refer #2987 and commit https://github.com/nerfstudio-project/nerfstudio/commit/ae6c46cfeaebbe28f9cd48fa986755e27b5f0ae2
