### ISSUE TITLE
Splatfacto during test . NotImplementedError: Saving images is not implemented yet

### ISSUE THREAD

**Issue by liu-bohan** [nerfstudio-project/nerfstudio#2906]
```
Traceback (most recent call last):
  File "/home/liubohan/anaconda3/envs/nerfstudio/bin/ns-eval", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/liubohan/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/scripts/eval.py", line 66, in entrypoint
    tyro.cli(ComputePSNR).main()
  File "/home/liubohan/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/scripts/eval.py", line 49, in main
    metrics_dict = pipeline.get_average_eval_image_metrics(output_path=self.render_output_path, get_std=True)
  File "/home/liubohan/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/utils/profiler.py", line 112, in inner
    out = func(*args, **kwargs)
  File "/home/liubohan/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/pipelines/base_pipeline.py", line 380, in get_average_eval_image_metrics
    raise NotImplementedError("Saving images is not implemented yet")
NotImplementedError: Saving images is not implemented yet
```

**Comment by liu-bohan** [comment]
and a very similar problem when testing and trying to render using Nerfacto-huge. 
Although the types of errors reported are different, the order of errors reported in the trace file is the same.
Any help is appreciated!

```
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /home/user/.local/bin/ns-eval:8 in <module>                                  │
│                                                                              │
│   5 from nerfstudio.scripts.eval import entrypoint                           │
│   6 if __name__ == '__main__':                                               │
│   7 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])     │
│ ❱ 8 │   sys.exit(entrypoint())                                               │
│   9                                                                          │
│                                                                              │
│ /home/user/nerfstudio/nerfstudio/scripts/eval.py:67 in entrypoint            │
│                                                                              │
│   64 def entrypoint():                                                       │
│   65 │   """Entrypoint for use with pyproject scripts."""                    │
│   66 │   tyro.extras.set_accent_color("bright_yellow")                       │
│ ❱ 67 │   tyro.cli(ComputePSNR).main()                                        │
│   68                                                                         │
│   69                                                                         │
│   70 if __name__ == "__main__":                                              │
│                                                                              │
│ /home/user/nerfstudio/nerfstudio/scripts/eval.py:50 in main                  │
│                                                                              │
│   47 │   │   if self.render_output_path is not None:                         │
│   48 │   │   │   if not os.path.isdir(str(self.render_output_path)):         │
│   49 │   │   │   │   self.render_output_path.mkdir(parents=True)             │
│ ❱ 50 │   │   metrics_dict = pipeline.get_average_eval_image_metrics(output_p │
│   51 │   │   self.output_path.parent.mkdir(parents=True, exist_ok=True)      │
│   52 │   │   # Get the output and define the names to save to                │
│   53 │   │   benchmark_info = {                                              │
│                                                                              │
│ /home/user/nerfstudio/nerfstudio/utils/profiler.py:127 in inner              │
│                                                                              │
│   124 │   │   def inner(*args, **kwargs):                                    │
│   125 │   │   │   self._function_call_args = (args, kwargs)                  │
│   126 │   │   │   with self:                                                 │
│ ❱ 127 │   │   │   │   out = func(*args, **kwargs)                            │
│   128 │   │   │   self._function_call_args = None                            │
│   129 │   │   │   return out                                                 │
│   130                                                                        │
│                                                                              │
│ /home/user/nerfstudio/nerfstudio/pipelines/base_pipeline.py:448 in           │
│ get_average_eval_image_metrics                                               │
│                                                                              │
│   445 │   │   │   │   │   )                                                  │
│   446 │   │   │   │   │                                                      │
│   447 │   │   │   │   │                                                      │
│ ❱ 448 │   │   │   │   │   np.save(Path(str(output_path).replace('images','me │
│   449 │   │   │   │   │   # print('now write', os.path.basename(batch['image │
│   450 │   │   │   │   │   print('now write', image_name)                     │
│   451                                                                        │
│ in save:200                                                                  │
│                                                                              │
│ /home/user/.local/lib/python3.10/site-packages/numpy/lib/npyio.py:518 in     │
│ save                                                                         │
│                                                                              │
│    515 │   │   file = os_fspath(file)                                        │
│    516 │   │   if not file.endswith('.npy'):                                 │
│    517 │   │   │   file = file + '.npy'                                      │
│ ❱  518 │   │   file_ctx = open(file, "wb")                                   │
│    519 │                                                                     │
│    520 │   with file_ctx as fid:                                             │
│    521 │   │   arr = np.asanyarray(arr)                                      │
╰──────────────────────────────────────────────────────────────────────────────╯
FileNotFoundError: [Errno 2] No such file or directory: 
'rendered_metadata/siteA01-camA003-2023-05-16-12-52-50-000049.npy'
```

**Comment by kevinycy** [comment]
I also meet this problem ,How do you solve it?
