### ISSUE TITLE
Unable to train via splatfacto (ValueError: too many values to unpack (expected 6))

### ISSUE THREAD

**Issue by fjschuler** [nerfstudio-project/nerfstudio#2942]
I hope someone can help me!

I attempted to train a splatfacto model but consistently run into the following error message:  ValueError: too many values to unpack (expected 6)

Here's the command I ran that produced the error (note that I am able to run the nerfacto method without issue):  ns-train splatfacto --data C:\Users\fjsch\nerfstudio\data\xfrmr_sm_splat

Here's the full error output:

Traceback (most recent call last):
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\fjsch\.conda\envs\nerfstudio\Scripts\ns-train.exe\__main__.py", line 7, in <module>
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\site-packages\nerfstudio\scripts\train.py", line 262, in entrypoint
    main(
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\site-packages\nerfstudio\scripts\train.py", line 247, in main
    launch(
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\site-packages\nerfstudio\scripts\train.py", line 189, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\site-packages\nerfstudio\scripts\train.py", line 100, in train_loop
    trainer.train()
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\site-packages\nerfstudio\engine\trainer.py", line 250, in train
    loss, loss_dict, metrics_dict = self.train_iteration(step)
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\site-packages\nerfstudio\utils\profiler.py", line 112, in inner
    out = func(*args, **kwargs)
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\site-packages\nerfstudio\engine\trainer.py", line 471, in train_iteration
    _, loss_dict, metrics_dict = self.pipeline.get_train_loss_dict(step=step)
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\site-packages\nerfstudio\utils\profiler.py", line 112, in inner
    out = func(*args, **kwargs)
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\site-packages\nerfstudio\pipelines\base_pipeline.py", line 300, in get_train_loss_dict
    model_outputs = self._model(ray_bundle)  # train distributed data parallel model if world_size > 1
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\site-packages\nerfstudio\models\base_model.py", line 143, in forward
    return self.get_outputs(ray_bundle)
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\site-packages\nerfstudio\models\splatfacto.py", line 719, in get_outputs
    self.xys, depths, self.radii, conics, num_tiles_hit, cov3d = project_gaussians(  # type: ignore
ValueError: too many values to unpack (expected 6)

**Comment by jb-ye** [comment]
Please (1) sync your local nerfstudio code to the latest main branch OR (2) you must use older version of gsplat (0.1.4) with released version 1.0.1.

**Comment by fjschuler** [comment]
Thanks!  I am using nerfstudio 1.0.1 and gsplat 0.1.3  I installed gsplat 0.1.4, and received an error message that it is incompatible with my version of nerfstudio.  I uninstalled gsplat 0.1.4 and installed 0.1.3 and tried to run the model again...got the following error(s).  Sorry!  I'm a total python noob over here.

Traceback (most recent call last):
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\site-packages\gsplat\cuda\_backend.py", line 56, in <module>
    from gsplat import csrc as _C
ImportError: cannot import name 'csrc' from 'gsplat' (C:\Users\fjsch\.conda\envs\nerfstudio\lib\site-packages\gsplat\__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\site-packages\nerfstudio\viewer\render_state_machine.py", line 218, in run
    outputs = self._render_img(action.camera_state)
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\site-packages\nerfstudio\viewer\render_state_machine.py", line 164, in _render_img
    outputs = self.viewer.get_model().get_outputs_for_camera(camera, obb_box=obb)
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\site-packages\nerfstudio\models\splatfacto.py", line 871, in get_outputs_for_camera
    outs = self.get_outputs(camera.to(self.device))
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\site-packages\nerfstudio\models\splatfacto.py", line 719, in get_outputs
    self.xys, depths, self.radii, conics, num_tiles_hit, cov3d = project_gaussians(  # type: ignore
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\site-packages\gsplat\project_gaussians.py", line 59, in project_gaussians
    return _ProjectGaussians.apply(
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\site-packages\torch\autograd\function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\site-packages\gsplat\project_gaussians.py", line 109, in forward
    ) = _C.project_gaussians_forward(
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\site-packages\gsplat\cuda\__init__.py", line 7, in call_cuda
    from ._backend import _C
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\site-packages\gsplat\cuda\_backend.py", line 88, in <module>
    _C = load(
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\site-packages\torch\utils\cpp_extension.py", line 1284, in load
    return _jit_compile(
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\site-packages\torch\utils\cpp_extension.py", line 1509, in _jit_compile
    _write_ninja_file_and_build_library(
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\site-packages\torch\utils\cpp_extension.py", line 1611, in _write_ninja_file_and_build_library
    _write_ninja_file_to_build_library(
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\site-packages\torch\utils\cpp_extension.py", line 2048, in _write_ninja_file_to_build_library
    _write_ninja_file(
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\site-packages\torch\utils\cpp_extension.py", line 2188, in _write_ninja_file
    cl_paths = subprocess.check_output(['where',
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['where', 'cl']' returned non-zero exit status 1.
Printing profiling stats, from longest to shortest duration in seconds
VanillaPipeline.get_train_loss_dict: 0.0420
Trainer.train_iteration: 0.0420
Traceback (most recent call last):
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\site-packages\gsplat\cuda\_backend.py", line 56, in <module>
    from gsplat import csrc as _C
ImportError: cannot import name 'csrc' from 'gsplat' (C:\Users\fjsch\.conda\envs\nerfstudio\lib\site-packages\gsplat\__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\fjsch\.conda\envs\nerfstudio\Scripts\ns-train.exe\__main__.py", line 7, in <module>
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\site-packages\nerfstudio\scripts\train.py", line 262, in entrypoint
    main(
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\site-packages\nerfstudio\scripts\train.py", line 247, in main
    launch(
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\site-packages\nerfstudio\scripts\train.py", line 189, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\site-packages\nerfstudio\scripts\train.py", line 100, in train_loop
    trainer.train()
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\site-packages\nerfstudio\engine\trainer.py", line 250, in train
    loss, loss_dict, metrics_dict = self.train_iteration(step)
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\site-packages\nerfstudio\utils\profiler.py", line 112, in inner
    out = func(*args, **kwargs)
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\site-packages\nerfstudio\engine\trainer.py", line 471, in train_iteration
    _, loss_dict, metrics_dict = self.pipeline.get_train_loss_dict(step=step)
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\site-packages\nerfstudio\utils\profiler.py", line 112, in inner
    out = func(*args, **kwargs)
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\site-packages\nerfstudio\pipelines\base_pipeline.py", line 300, in get_train_loss_dict
    model_outputs = self._model(ray_bundle)  # train distributed data parallel model if world_size > 1
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\site-packages\nerfstudio\models\base_model.py", line 143, in forward
    return self.get_outputs(ray_bundle)
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\site-packages\nerfstudio\models\splatfacto.py", line 719, in get_outputs
    self.xys, depths, self.radii, conics, num_tiles_hit, cov3d = project_gaussians(  # type: ignore
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\site-packages\gsplat\project_gaussians.py", line 59, in project_gaussians
    return _ProjectGaussians.apply(
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\site-packages\torch\autograd\function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\site-packages\gsplat\project_gaussians.py", line 109, in forward
    ) = _C.project_gaussians_forward(
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\site-packages\gsplat\cuda\__init__.py", line 7, in call_cuda
    from ._backend import _C
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\site-packages\gsplat\cuda\_backend.py", line 88, in <module>
    _C = load(
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\site-packages\torch\utils\cpp_extension.py", line 1284, in load
    return _jit_compile(
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\site-packages\torch\utils\cpp_extension.py", line 1535, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\site-packages\torch\utils\cpp_extension.py", line 1929, in _import_module_from_library
    module = importlib.util.module_from_spec(spec)
ImportError: DLL load failed while importing gsplat_cuda: The specified module could not be found.

**Comment by fjschuler** [comment]
I also tried gsplat versions 0.1.6 and 0.1.5 and received error messages.

**Comment by fjschuler** [comment]
I'm still trying to work through this issue.  After a reboot, I tried re-running the splatfacto model and got a different error...see below.  Could it simply be that I am missing a necessary entry in my Windows PATH statement or something simple like that??

C:\Users\fjsch\.conda\envs\nerfstudio\lib\site-packages\torch\utils\cpp_extension.py:359: UserWarning: Error checking
compiler version for cl: [WinError 2] The system cannot find the file specified
  warnings.warn(f'Error checking compiler version for {compiler}: {error}')
(  ●   ) gsplat: Setting up CUDA (This may take a few minutes the first time)INFO: Could not find files for the given pattern(s).
Printing profiling stats, from longest to shortest duration in seconds
VanillaPipeline.get_train_loss_dict: 2.3977
Trainer.train_iteration: 2.3977
Traceback (most recent call last):
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\site-packages\gsplat\cuda\_backend.py", line 56, in <module>
    from gsplat import csrc as _C
ImportError: cannot import name 'csrc' from 'gsplat' (C:\Users\fjsch\.conda\envs\nerfstudio\lib\site-packages\gsplat\__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\fjsch\.conda\envs\nerfstudio\Scripts\ns-train.exe\__main__.py", line 7, in <module>
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\site-packages\nerfstudio\scripts\train.py", line 262, in entrypoint
    main(
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\site-packages\nerfstudio\scripts\train.py", line 247, in main
    launch(
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\site-packages\nerfstudio\scripts\train.py", line 189, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\site-packages\nerfstudio\scripts\train.py", line 100, in train_loop
    trainer.train()
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\site-packages\nerfstudio\engine\trainer.py", line 250, in train
    loss, loss_dict, metrics_dict = self.train_iteration(step)
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\site-packages\nerfstudio\utils\profiler.py", line 112, in inner
    out = func(*args, **kwargs)
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\site-packages\nerfstudio\engine\trainer.py", line 471, in train_iteration
    _, loss_dict, metrics_dict = self.pipeline.get_train_loss_dict(step=step)
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\site-packages\nerfstudio\utils\profiler.py", line 112, in inner
    out = func(*args, **kwargs)
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\site-packages\nerfstudio\pipelines\base_pipeline.py", line 300, in get_train_loss_dict
    model_outputs = self._model(ray_bundle)  # train distributed data parallel model if world_size > 1
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\site-packages\nerfstudio\models\base_model.py", line 143, in forward
    return self.get_outputs(ray_bundle)
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\site-packages\nerfstudio\models\splatfacto.py", line 719, in get_outputs
    self.xys, depths, self.radii, conics, num_tiles_hit, cov3d = project_gaussians(  # type: ignore
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\site-packages\gsplat\project_gaussians.py", line 59, in project_gaussians
    return _ProjectGaussians.apply(
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\site-packages\torch\autograd\function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\site-packages\gsplat\project_gaussians.py", line 109, in forward
    ) = _C.project_gaussians_forward(
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\site-packages\gsplat\cuda\__init__.py", line 7, in call_cuda
    from ._backend import _C
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\site-packages\gsplat\cuda\_backend.py", line 88, in <module>
    _C = load(
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\site-packages\torch\utils\cpp_extension.py", line 1284, in load
    return _jit_compile(
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\site-packages\torch\utils\cpp_extension.py", line 1509, in _jit_compile
    _write_ninja_file_and_build_library(
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\site-packages\torch\utils\cpp_extension.py", line 1611, in _write_ninja_file_and_build_library
    _write_ninja_file_to_build_library(
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\site-packages\torch\utils\cpp_extension.py", line 2048, in _write_ninja_file_to_build_library
    _write_ninja_file(
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\site-packages\torch\utils\cpp_extension.py", line 2188, in _write_ninja_file
    cl_paths = subprocess.check_output(['where',
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\fjsch\.conda\envs\nerfstudio\lib\subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['where', 'cl']' returned non-zero exit status 1.

**Comment by fjschuler** [comment]
Got it!!  It is now training a splatfacto model (for the moment, lol...).

I did the following:

pip uninstall nerfstudio
pip install nerfstudio==1.0.2
pip uninstall gsplat
pip install gsplat==0.1.8
