### ISSUE TITLE
Cannot download poster dataset using ns-download-data

### ISSUE THREAD

**Issue by abrbhat** [nerfstudio-project/nerfstudio#2959]
**Describe the bug**
Getting an error while downloading poster dataset using ns-download-data

**To Reproduce**
1. Run ns-download-data nerfstudio --capture-name=poster

**Expected behavior**
Dataset should be downloaded

**Screenshots**
Error log:
```
(nerfstudio) PS C:\Users\Divya\nerfstudio> ns-download-data nerfstudio --capture-name=poster
Traceback (most recent call last):
  File "C:\Users\Divya\.conda\envs\nerfstudio\lib\site-packages\gdown\download.py", line 253, in download
    url = get_url_from_gdrive_confirmation(res.text)
  File "C:\Users\Divya\.conda\envs\nerfstudio\lib\site-packages\gdown\download.py", line 54, in get_url_from_gdrive_confirmation
    raise FileURLRetrievalError(
gdown.exceptions.FileURLRetrievalError: Cannot retrieve the public link of the file. You may need to change the permission to 'Anyone with the link', or have had many accesses. Check FAQ in https://github.com/wkentaro/gdown?tab=readme-ov-file#faq.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Divya\.conda\envs\nerfstudio\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Divya\.conda\envs\nerfstudio\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Divya\.conda\envs\nerfstudio\Scripts\ns-download-data.exe\__main__.py", line 7, in <module>
  File "C:\Users\Divya\.conda\envs\nerfstudio\lib\site-packages\nerfstudio\scripts\downloads\download_data.py", line 573, in entrypoint
    main(tyro.cli(Commands))
  File "C:\Users\Divya\.conda\envs\nerfstudio\lib\site-packages\nerfstudio\scripts\downloads\download_data.py", line 567, in main
    dataset.download(dataset.save_dir)
  File "C:\Users\Divya\.conda\envs\nerfstudio\lib\site-packages\nerfstudio\scripts\downloads\download_data.py", line 207, in download
    download_capture_name(save_dir, "nerfstudio", self.capture_name, capture_name_to_file_id=nerfstudio_file_ids)
  File "C:\Users\Divya\.conda\envs\nerfstudio\lib\site-packages\nerfstudio\scripts\downloads\download_data.py", line 170, in download_capture_name
    gdown.download(url, output=str(download_path))
  File "C:\Users\Divya\.conda\envs\nerfstudio\lib\site-packages\gdown\download.py", line 264, in download
    raise FileURLRetrievalError(message)
gdown.exceptions.FileURLRetrievalError: Failed to retrieve file url:

        Cannot retrieve the public link of the file. You may need to change
        the permission to 'Anyone with the link', or have had many accesses.
        Check FAQ in https://github.com/wkentaro/gdown?tab=readme-ov-file#faq.

You may still be able to access the file from the browser:

        https://drive.google.com/uc?id=1dmjWGXlJnUxwosN6MVooCDQe970PkD-1

but Gdown can't. Please check connections and permissions.
```

**Comment by VictorEscribano** [comment]
Try download the zip files directly from the drive, take a look at [this issue](https://github.com/nerfstudio-project/nerfstudio/issues/2544)

**Comment by abrbhat** [comment]
Had tried it but getting File does not exist error on the link for the file in GDrive.

![image](https://github.com/nerfstudio-project/nerfstudio/assets/4189727/ee61fbd5-306c-4953-9cf1-e64ccf81a011)

![image](https://github.com/nerfstudio-project/nerfstudio/assets/4189727/4c4226e1-d3eb-4623-8939-0b0240a70671)

**Comment by jackdaus** [comment]
I'm also seeing the same message, "Sorry, the file you have requested does not exist." when trying to access https://drive.google.com/file/d/1dmjWGXlJnUxwosN6MVooCDQe970PkD-1/view?usp=sharing from a browser. 

This is the latest url from the source code:

- https://github.com/nerfstudio-project/nerfstudio/blob/f31f3bba12841955102f3f3846ee9f855f4a6878/nerfstudio/scripts/downloads/download_data.py#L115-L142

I also tested the the `library` and `sculpture` gdrive links. Interestingly, I can download both of those from the browser but not from the CLI. But when I try to run, 
```
ns-download-data nerfstudio --capture-name=sculpture
```
I get this error in my console,
```
Access denied with the following error:

        Cannot retrieve the public link of the file. You may need to change
        the permission to 'Anyone with the link', or have had many accesses.

You may still be able to access the file from the browser:

         https://drive.google.com/uc?id=1CUU_k0Et2gysuBn_R5qenDMfYXEhNsd1
```

**Comment by benkelaci** [comment]
yeah, it still not available

can someone share at least one sample dataset?

**Comment by dlazares** [comment]
yep, still down

**Comment by Yo-AvA** [comment]
ah, still not available

**Comment by SibylGao** [comment]
any solutions?

**Comment by SibylGao** [comment]
try `bww_entrance` instead of `poster `, like:
`ns-download-data nerfstudio --capture-name=bww_entrance`

**Comment by TaylorPzreal** [comment]
Not available.

```txt
	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses.
	Check FAQ in https://github.com/wkentaro/gdown?tab=readme-ov-file#faq.

You may still be able to access the file from the browser:

	https://drive.google.com/uc?id=1ylkRHtfB3n3IRLf2wplpfxzPTq7nES9I

but Gdown can't. Please check connections and permissions.
```

**Comment by boijuny** [comment]
Not working, maybe someone should reopen the issue  ?
