### ISSUE TITLE
[splatfacto] TypeError: project_gaussians_forward(): incompatible function arguments.

### ISSUE THREAD

**Issue by jeonggwanlee** [nerfstudio-project/nerfstudio#2967]
**Describe the bug**

I'd like to train method "splatfacto" with custom dataset.
I already check "nerfacto" with my dataset, first.

an error is related to *mismatch of arguments in project_gaussians_forward function* and I guess the reason is mismatching gsplat and nerfstudio version.

major python library version is,
nerfstudio 1.0.2
gsplat 0.1.5

Below are the error messages.

Traceback (most recent call last):                                                                                                                                                      
  File "/home/jovyan/myconda_envs/autonerfstudio_v2/bin/ns-train", line 8, in <module>                                                                                                  
    sys.exit(entrypoint())                                                                                                                                                              
  File "/data/clap/projects/jglee/dlt_rl/autonerf_gitlab/autonerf/nerfstudio/nerfstudio/scripts/train.py", line 262, in entrypoint                                                      
    main(                                                                                                                                                                               
  File "/data/clap/projects/jglee/dlt_rl/autonerf_gitlab/autonerf/nerfstudio/nerfstudio/scripts/train.py", line 247, in main
    launch(
  File "/data/clap/projects/jglee/dlt_rl/autonerf_gitlab/autonerf/nerfstudio/nerfstudio/scripts/train.py", line 189, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "/data/clap/projects/jglee/dlt_rl/autonerf_gitlab/autonerf/nerfstudio/nerfstudio/scripts/train.py", line 100, in train_loop
    trainer.train()
  File "/data/clap/projects/jglee/dlt_rl/autonerf_gitlab/autonerf/nerfstudio/nerfstudio/engine/trainer.py", line 250, in train    loss, loss_dict, metrics_dict = self.train_iteration(step)
  File "/data/clap/projects/jglee/dlt_rl/autonerf_gitlab/autonerf/nerfstudio/nerfstudio/utils/profiler.py", line 112, in inner
    out = func(*args, **kwargs)
  File "/data/clap/projects/jglee/dlt_rl/autonerf_gitlab/autonerf/nerfstudio/nerfstudio/engine/trainer.py", line 471, in train_iteration
    _, loss_dict, metrics_dict = self.pipeline.get_train_loss_dict(step=step)
  File "/data/clap/projects/jglee/dlt_rl/autonerf_gitlab/autonerf/nerfstudio/nerfstudio/utils/profiler.py", line 112, in inner
    out = func(*args, **kwargs)
  File "/data/clap/projects/jglee/dlt_rl/autonerf_gitlab/autonerf/nerfstudio/nerfstudio/pipelines/base_pipeline.py", line 300, in get_train_loss_dict
    model_outputs = self._model(ray_bundle)  # train distributed data parallel model if world_size > 1
  File "/home/jovyan/myconda_envs/autonerfstudio_v2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/jovyan/myconda_envs/autonerfstudio_v2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)  File "/data/clap/projects/jglee/dlt_rl/autonerf_gitlab/autonerf/nerfstudio/nerfstudio/models/base_model.py", line 143, in forward
    return self.get_outputs(ray_bundle)
  File "/data/clap/projects/jglee/dlt_rl/autonerf_gitlab/autonerf/nerfstudio/nerfstudio/models/splatfacto.py", line 740, in get_outputs
    self.xys, depths, self.radii, conics, comp, num_tiles_hit, cov3d = project_gaussians(  # type: ignore
  File "/home/jovyan/myconda_envs/autonerfstudio_v2/lib/python3.9/site-packages/gsplat/project_gaussians.py", line 60, in project_gaussians
    return _ProjectGaussians.apply(
  File "/home/jovyan/myconda_envs/autonerfstudio_v2/lib/python3.9/site-packages/torch/autograd/function.py", line 553, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/jovyan/myconda_envs/autonerfstudio_v2/lib/python3.9/site-packages/gsplat/project_gaussians.py", line 111, in forward
    ) = _C.project_gaussians_forward(
  File "/home/jovyan/myconda_envs/autonerfstudio_v2/lib/python3.9/site-packages/gsplat/cuda/__init__.py", line 9, in call_cuda
    return getattr(_C, name)(*args, **kwargs)
TypeError: project_gaussians_forward(): incompatible function arguments. The following argument types are supported:
    1. (arg0: int, arg1: torch.Tensor, arg2: torch.Tensor, arg3: float, arg4: torch.Tensor, arg5: torch.Tensor, arg6: torch.Tensor, arg7: float, arg8: float, arg9: float, arg10: float, arg11: int, arg12: int, arg13: Tuple[int, int, int], arg14: float) -> Tuple[torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor]

Invoked with: 50000, Parameter containing:
tensor([[ 3.8227,  4.1500, -1.1714],
        [ 4.5931, -1.0955,  1.0090],
        [-2.4343,  2.9364,  4.4077],
        ...,
        [ 4.2985, -4.9558, -4.1033],
        [-2.8893,  2.3538, -0.4661],
        [-3.4045, -3.0413, -3.5534]], device='cuda:0', requires_grad=True), tensor([[0.2192, 0.2192, 0.2192],
        [0.0771, 0.0771, 0.0771],
        [0.1027, 0.1027, 0.1027],
        ...,
        [0.1316, 0.1316, 0.1316],
        [0.1561, 0.1561, 0.1561],
        [0.1754, 0.1754, 0.1754]], device='cuda:0', grad_fn=<ExpBackward0>), 1, tensor([[-0.6499, -0.3086, -0.4516, -0.5277],
        [ 0.2193, -0.6681, -0.6980, -0.1355],
        [-0.2783,  0.4081,  0.3069, -0.8135],
        ...,
        [ 0.0702, -0.9207, -0.0157,  0.3835],
        [ 0.4044,  0.1410,  0.4986, -0.7536],
        [-0.5802, -0.2840,  0.7633, -0.0014]], device='cuda:0',
       grad_fn=<DivBackward0>), tensor([[ 8.3462e-01,  5.5083e-01,  4.2144e-18, -1.7042e-01],
        [ 1.3996e-16, -2.0442e-16, -1.0000e+00, -7.0658e-09],
        [-5.5083e-01,  8.3462e-01, -2.4771e-16,  4.0456e-01]], device='cuda:0'), tensor([[ 8.3462e-01,  5.5083e-01,  4.2144e-18, -1.7042e-01],
        [ 1.3996e-16, -2.0442e-16, -1.0000e+00, -7.0658e-09],
        [-5.5083e-01,  8.3462e-01, -2.4771e-16,  4.0356e-01],
        [-5.5083e-01,  8.3462e-01, -2.4771e-16,  4.0456e-01]], device='cuda:0'), 320.0, 240.0, 319.5, 239.5, 480, 640, 16, 0.01

I also tried gsplat 0.1.4, but same errors.

**Comment by jeonggwanlee** [comment]
When I tried to install gsplat 0.1.6, I got this error.

  × python setup.py bdist_wheel did not run successfully.                                                                                                                               
  │ exit code: 1                                                                                                                                                                        
  ╰─> [2561 lines of output]                                                                                                                                                            
      running bdist_wheel                                                                                                                                                               
      running build                                                                                                                                                                     
      running build_py                                                                                                                                                                  
      creating build                                                                                                                                                                    
      creating build/lib.linux-x86_64-cpython-39                                                                                                                                        
      creating build/lib.linux-x86_64-cpython-39/gsplat                                                                                                                                 
      copying gsplat/_torch_impl.py -> build/lib.linux-x86_64-cpython-39/gsplat                                                                                                         
      copying gsplat/project_gaussians.py -> build/lib.linux-x86_64-cpython-39/gsplat                                                                                                   
      copying gsplat/sh.py -> build/lib.linux-x86_64-cpython-39/gsplat                                                                                                                  
      copying gsplat/rasterize.py -> build/lib.linux-x86_64-cpython-39/gsplat                                                                                                           
      copying gsplat/__init__.py -> build/lib.linux-x86_64-cpython-39/gsplat                                                                                                            
      copying gsplat/version.py -> build/lib.linux-x86_64-cpython-39/gsplat                                                                                                             
      copying gsplat/utils.py -> build/lib.linux-x86_64-cpython-39/gsplat                                                                                                               
      creating build/lib.linux-x86_64-cpython-39/gsplat/cuda                                                                                                                            
      copying gsplat/cuda/_backend.py -> build/lib.linux-x86_64-cpython-39/gsplat/cuda                                                                                                  
      copying gsplat/cuda/__init__.py -> build/lib.linux-x86_64-cpython-39/gsplat/cuda                                                                                                  
      running egg_info                                                                                                                                                                  
      creating gsplat.egg-info                                                                                                                                                          
      writing gsplat.egg-info/PKG-INFO                                                                                                                                                  
      writing dependency_links to gsplat.egg-info/dependency_links.txt                                                                                                                  
      writing requirements to gsplat.egg-info/requires.txt                                                                                                                              
      writing top-level names to gsplat.egg-info/top_level.txt                                                                                                                          
      writing manifest file 'gsplat.egg-info/SOURCES.txt'                                                                                                                               
      reading manifest file 'gsplat.egg-info/SOURCES.txt'                                                                                                                               
      reading manifest template 'MANIFEST.in'                                                                                                                                           
      adding license file 'LICENSE'                                                                                                                                                     
      writing manifest file 'gsplat.egg-info/SOURCES.txt'                                                                                                                               
      /home/jovyan/myconda_envs/autonerfstudio_v2/lib/python3.9/site-packages/setuptools/command/build_py.py:207: _Warning: Package 'gsplat.cuda.csrc' is absent from the `packages` con
figuration.                                                                                                                                                                             
      !!    
      
      ............................................
      .........................................
      .......................................


      /home/jovyan/myconda_envs/autonerfstudio_v2/lib/python3.9/site-packages/torch/utils/cpp_extension.py:415: UserWarning: The detected CUDA version (11.3) has a minor version mismat
ch with the version that was used to compile PyTorch (11.8). Most likely this shouldn't be a problem.                                                                                   
        warnings.warn(CUDA_MISMATCH_WARN.format(cuda_str_version, torch.version.cuda))                                                                                                  
      building 'gsplat.csrc' extension                                                                                                                                                  
      creating build/temp.linux-x86_64-cpython-39                                                                                                                                       
      creating build/temp.linux-x86_64-cpython-39/gsplat                                                                                                                                
      creating build/temp.linux-x86_64-cpython-39/gsplat/cuda                                                                                                                           
      creating build/temp.linux-x86_64-cpython-39/gsplat/cuda/csrc                                                                                                                      
      /usr/local/cuda/bin/nvcc -Igsplat/cuda/csrc/third_party/glm -I/home/jovyan/myconda_envs/autonerfstudio_v2/lib/python3.9/site-packages/torch/include -I/home/jovyan/myconda_envs/au
tonerfstudio_v2/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/home/jovyan/myconda_envs/autonerfstudio_v2/lib/python3.9/site-packages/torch/include/TH -I/home/jovy
an/myconda_envs/autonerfstudio_v2/lib/python3.9/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/jovyan/myconda_envs/autonerfstudio_v2/include/python3.9 -c gsplat/cuda
/csrc/backward.cu -o build/temp.linux-x86_64-cpython-39/gsplat/cuda/csrc/backward.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__C
UDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -O3 --use_fast_math --expt-relaxed-constexpr -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gc
c\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -DTORCH_EXTENSION_NAME=csrc -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_52,code=sm_52 -gencode=arch=compu
te_60,code=sm_60 -gencode=arch=compute_61,code=sm_61 -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_75,code=sm_75 -gencode=arch=compute_80,code=sm_80 -gencode=arch=compute_8
6,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++17                                                                                                                        
      gsplat/cuda/csrc/backward.cu(350): warning: variable "cx" was declared but never referenced                                                                                       
                                                                                                                                                                                        
      gsplat/cuda/csrc/backward.cu(351): warning: variable "cy" was declared but never referenced                                                                             
                                                                                                                                                                                        
      gsplat/cuda/csrc/backward.cu(112): error: no suitable conversion function from "half" to "int" exists                                                                             
                                                                                                                                                                                        
      gsplat/cuda/csrc/backward.cu(112): error: no suitable conversion function from "__half" to "int" exists                                                                 
                                                                                                                                                                                        
      gsplat/cuda/csrc/backward.cu(350): warning: variable "cx" was declared but never referenced                                                                             
                                                                                                                                                                                        
      gsplat/cuda/csrc/backward.cu(351): warning: variable "cy" was declared but never referenced                                                                             
                                                                                                                                                                                        
      2 errors detected in the compilation of "gsplat/cuda/csrc/backward.cu".                                                                                                           
      error: command '/usr/local/cuda/bin/nvcc' failed with exit code 1                                                                                                                 
      [end of output]                                                                                                                                                                   
                                                                                                                                                                                        
  note: This error originates from a subprocess, and is likely not a problem with pip.                                                                                                  
  ERROR: Failed building wheel for gsplat                                                                                                                                               
  Running setup.py clean for gsplat                                                                                                                                                     
Failed to build gsplat                                                                                                                                                                  
ERROR: Could not build wheels for gsplat, which is required to install pyproject.toml-based projects

**Comment by jeonggwanlee** [comment]
I resolved my problem.
I downgrade nerfstudio v1.0.1 and install gsplat 0.1.3.
