### ISSUE TITLE
Can't access the viewer on the LAN

### ISSUE THREAD

**Issue by vindia9** [nerfstudio-project/nerfstudio#2972]
**Describe the bug**

nerfstudio v1.0.2
Windows 10
Chrome 122.0.6261.69

I start with a command
`ns-viewer --load-config D:\nerf\v-tree\v-tree\nerfacto\2024-02-29_000059\config.yml`

On another machine, open the Chrome browser and navigate to `https://viewer.nerf.studio/`
With WebSocket URL field `ws://192.168.1.10:7007`
also `ssh -L 7007:127.0.0.1:7007` and use `ws://localhost:7007`

The viewer in the browser is displaying "Renderer Disconnected", and the console starts looping errors.

```
(viser) Connection opened (244, 241 total), 3865 persistent messages
connection handler failed
Traceback (most recent call last):
  File "C:\Users\admin\miniconda3\envs\nerfstudio\lib\site-packages\websockets\legacy\server.py", line 236, in handler
    await self.ws_handler(self)
  File "C:\Users\admin\miniconda3\envs\nerfstudio\lib\site-packages\viser\infra\_infra.py", line 275, in serve
    await asyncio.gather(
  File "C:\Users\admin\miniconda3\envs\nerfstudio\lib\site-packages\viser\infra\_infra.py", line 451, in _consumer
    message = message_class.deserialize(raw)
  File "C:\Users\admin\miniconda3\envs\nerfstudio\lib\site-packages\viser\infra\_messages.py", line 97, in deserialize
    message_type = cls._subclass_from_type_string()[cast(str, mapping.pop("type"))]
KeyError: 'CameraMessage'
```

If I use SSH forwarding to my local machine `ssh -L 7007:127.0.0.1:7007` and open `http://localhost:7007` in chrome
or directly enter the viewer's IP address (`http://192.168.1.10:7007/`) in Chrome to access it

 the page opens to a **blank screen**, and the following errors are displayed in Chrome's console

![image](https://github.com/nerfstudio-project/nerfstudio/assets/9072630/5520f1c4-5142-48a0-ad5c-8bcc94912681)

How do I access the viewer on the LAN?

<details>

```
index-656df4e0.js:40 TypeError: Cannot read properties of null (reading '_currentValue')
    at Object.oa (index-656df4e0.js:38:6419)
    at kze (index-656df4e0.js:3536:34241)
    at Ize (index-656df4e0.js:3536:34305)
    at index-656df4e0.js:3536:36091
    at Nk (index-656df4e0.js:38:19551)
    at m5 (index-656df4e0.js:40:1575)
    at xW (index-656df4e0.js:40:46064)
    at gW (index-656df4e0.js:40:39806)
    at Cce (index-656df4e0.js:40:39732)
    at qw (index-656df4e0.js:40:39583)
UO  @ index-656df4e0.js:40
KG.n.callback @ index-656df4e0.js:40
s5  @ index-656df4e0.js:38
S5  @ index-656df4e0.js:40
fW  @ index-656df4e0.js:40
bce @ index-656df4e0.js:40
Mce @ index-656df4e0.js:40
Dd  @ index-656df4e0.js:40
pW  @ index-656df4e0.js:40
E @ index-656df4e0.js:25
G @ index-656df4e0.js:25


index-656df4e0.js:38 Uncaught TypeError: Cannot read properties of null (reading '_currentValue')
    at Object.oa (index-656df4e0.js:38:6419)
    at kze (index-656df4e0.js:3536:34241)
    at Ize (index-656df4e0.js:3536:34305)
    at index-656df4e0.js:3536:36091
    at Nk (index-656df4e0.js:38:19551)
    at m5 (index-656df4e0.js:40:1575)
    at xW (index-656df4e0.js:40:46064)
    at gW (index-656df4e0.js:40:39806)
    at Cce (index-656df4e0.js:40:39732)
    at qw (index-656df4e0.js:40:39583)
oa  @ index-656df4e0.js:38
kze @ index-656df4e0.js:3536
Ize @ index-656df4e0.js:3536
（匿名）  @ index-656df4e0.js:3536
Nk  @ index-656df4e0.js:38
m5  @ index-656df4e0.js:40
xW  @ index-656df4e0.js:40
gW  @ index-656df4e0.js:40
Cce @ index-656df4e0.js:40
qw  @ index-656df4e0.js:40
QO  @ index-656df4e0.js:40
pW  @ index-656df4e0.js:40
E @ index-656df4e0.js:25
G @ index-656df4e0.js:25

```

**Comment by brentyi** [comment]
Hi! Can you try navigating to `http://localhost:7007` or `http://192.168.1.10:7007` directly, instead of using `viewer.nerf.studio`? 

That URL was for the older (legacy) viewer, and shouldn't be needed anymore.
