### ISSUE TITLE
Bug when trying to run nerfstudio on CPU

### ISSUE THREAD

**Issue by 4eJIoBek1** [nerfstudio-project/nerfstudio#2993]
**Describe the bug**
Maybe nerfstudio is not purposed to run on cpu, but if you try to run it with --machine.device-type cpu
, this error will be displayed:

Traceback (most recent call last):
  File "C:\Users\GM\Desktop\a\miniconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\GM\Desktop\a\miniconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\GM\Desktop\a\miniconda3\Scripts\ns-train.exe\__main__.py", line 7, in <module>
    sys.exit(entrypoint())
  File "C:\Users\GM\Desktop\a\miniconda3\lib\site-packages\nerfstudio\scripts\train.py", line 262, in entrypoint
    main(
  File "C:\Users\GM\Desktop\a\miniconda3\lib\site-packages\nerfstudio\scripts\train.py", line 247, in main
    launch(
  File "C:\Users\GM\Desktop\a\miniconda3\lib\site-packages\nerfstudio\scripts\train.py", line 189, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "C:\Users\GM\Desktop\a\miniconda3\lib\site-packages\nerfstudio\scripts\train.py", line 100, in train_loop
    trainer.train()
  File "C:\Users\GM\Desktop\a\miniconda3\lib\site-packages\nerfstudio\engine\trainer.py", line 250, in train
    loss, loss_dict, metrics_dict = self.train_iteration(step)
  File "C:\Users\GM\Desktop\a\miniconda3\lib\site-packages\nerfstudio\utils\profiler.py", line 112, in inner
    out = func(*args, **kwargs)
  File "C:\Users\GM\Desktop\a\miniconda3\lib\site-packages\nerfstudio\engine\trainer.py", line 471, in train_iteration
    _, loss_dict, metrics_dict = self.pipeline.get_train_loss_dict(step=step)
  File "C:\Users\GM\Desktop\a\miniconda3\lib\site-packages\nerfstudio\utils\profiler.py", line 112, in inner
    out = func(*args, **kwargs)
  File "C:\Users\GM\Desktop\a\miniconda3\lib\site-packages\nerfstudio\pipelines\base_pipeline.py", line 300, in get_train_loss_dict
    model_outputs = self._model(ray_bundle)  # train distributed data parallel model if world_size > 1
  File "C:\Users\GM\Desktop\a\miniconda3\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\GM\Desktop\a\miniconda3\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\GM\Desktop\a\miniconda3\lib\site-packages\nerfstudio\models\base_model.py", line 143, in forward
    return self.get_outputs(ray_bundle)
  File "C:\Users\GM\Desktop\a\miniconda3\lib\site-packages\nerfstudio\models\splatfacto.py", line 739, in get_outputs
    self.xys, depths, self.radii, conics, comp, num_tiles_hit, cov3d = project_gaussians(  # type: ignore
  File "C:\Users\GM\Desktop\a\miniconda3\lib\site-packages\gsplat\project_gaussians.py", line 61, in project_gaussians
    return _ProjectGaussians.apply(
  File "C:\Users\GM\Desktop\a\miniconda3\lib\site-packages\torch\autograd\function.py", line 539, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "C:\Users\GM\Desktop\a\miniconda3\lib\site-packages\gsplat\project_gaussians.py", line 112, in forward
    ) = _C.project_gaussians_forward(
  File "C:\Users\GM\Desktop\a\miniconda3\lib\site-packages\gsplat\cuda\__init__.py", line 9, in call_cuda
    return getattr(_C, name)(*args, **kwargs)
RuntimeError: t == DeviceType::CUDA INTERNAL ASSERT FAILED at "C:/Users/GM/Desktop/nstst/miniconda3/lib/site-packages/torch/include\\c10/cuda/impl/CUDAGuardImpl.h":25, please report a bug to PyTorch.

**To Reproduce**
install visual studio community
pip install torch==2.1.2+cu118 torchvision==0.16.2+cu118 --extra-index-url https://download.pytorch.org/whl/cu118
conda install -c "nvidia/label/cuda-11.8.0" cuda-toolkit
pip install ninja git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch
git clone https://github.com/nerfstudio-project/nerfstudio.git
cd nerfstudio
pip install --upgrade pip setuptools
pip install -e .
ns-train splatfacto --data %~dp0workspace\nerf_format --viewer.websocket-port 7007 --machine.device-type cpu
OR
download this: https://huggingface.co/datasets/4eJIoBek/PAIT-Downloads/resolve/main/NERFStudio-1.0.2-portable-win.7z?download=true
then edit 3) train splatfacto and add to ns-train line  --machine.device-type cpu
run all bats in order

**Comment by maturk** [comment]
splatfacto wont work unfortunately, the backend is tied to cuda. Other models, like nerfacto, are able to run since they have pytorch cpu counterparts.

**Comment by 4eJIoBek1** [comment]
nerfacto is also wont works
File "C:\Users\GM\Desktop\NERFStudio-1.0.2\miniconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\GM\Desktop\NERFStudio-1.0.2\miniconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\GM\Desktop\NERFStudio-1.0.2\miniconda3\Scripts\ns-train.exe\__main__.py", line 7, in <module>
    sys.exit(entrypoint())
  File "C:\Users\GM\Desktop\NERFStudio-1.0.2\miniconda3\lib\site-packages\nerfstudio\scripts\train.py", line 262, in entrypoint
    main(
  File "C:\Users\GM\Desktop\NERFStudio-1.0.2\miniconda3\lib\site-packages\nerfstudio\scripts\train.py", line 247, in main
    launch(
  File "C:\Users\GM\Desktop\NERFStudio-1.0.2\miniconda3\lib\site-packages\nerfstudio\scripts\train.py", line 189, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "C:\Users\GM\Desktop\NERFStudio-1.0.2\miniconda3\lib\site-packages\nerfstudio\scripts\train.py", line 100, in train_loop
    trainer.train()
  File "C:\Users\GM\Desktop\NERFStudio-1.0.2\miniconda3\lib\site-packages\nerfstudio\engine\trainer.py", line 250, in train
    loss, loss_dict, metrics_dict = self.train_iteration(step)
  File "C:\Users\GM\Desktop\NERFStudio-1.0.2\miniconda3\lib\site-packages\nerfstudio\utils\profiler.py", line 112, in inner
    out = func(*args, **kwargs)
  File "C:\Users\GM\Desktop\NERFStudio-1.0.2\miniconda3\lib\site-packages\nerfstudio\engine\trainer.py", line 471, in train_iteration
    _, loss_dict, metrics_dict = self.pipeline.get_train_loss_dict(step=step)
  File "C:\Users\GM\Desktop\NERFStudio-1.0.2\miniconda3\lib\site-packages\nerfstudio\utils\profiler.py", line 112, in inner
    out = func(*args, **kwargs)
  File "C:\Users\GM\Desktop\NERFStudio-1.0.2\miniconda3\lib\site-packages\nerfstudio\pipelines\base_pipeline.py", line 300, in get_train_loss_dict
    model_outputs = self._model(ray_bundle)  # train distributed data parallel model if world_size > 1
  File "C:\Users\GM\Desktop\NERFStudio-1.0.2\miniconda3\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\GM\Desktop\NERFStudio-1.0.2\miniconda3\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\GM\Desktop\NERFStudio-1.0.2\miniconda3\lib\site-packages\nerfstudio\models\base_model.py", line 143, in forward
    return self.get_outputs(ray_bundle)
  File "C:\Users\GM\Desktop\NERFStudio-1.0.2\miniconda3\lib\site-packages\nerfstudio\models\nerfacto.py", line 303, in get_outputs
    ray_samples, weights_list, ray_samples_list = self.proposal_sampler(ray_bundle, density_fns=self.density_fns)
  File "C:\Users\GM\Desktop\NERFStudio-1.0.2\miniconda3\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\GM\Desktop\NERFStudio-1.0.2\miniconda3\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\GM\Desktop\NERFStudio-1.0.2\miniconda3\lib\site-packages\nerfstudio\model_components\ray_samplers.py", line 50, in forward
    return self.generate_ray_samples(*args, **kwargs)
  File "C:\Users\GM\Desktop\NERFStudio-1.0.2\miniconda3\lib\site-packages\nerfstudio\model_components\ray_samplers.py", line 607, in generate_ray_samples
    density = density_fns[i_level](ray_samples.frustums.get_positions())
  File "C:\Users\GM\Desktop\NERFStudio-1.0.2\miniconda3\lib\site-packages\nerfstudio\fields\base_field.py", line 67, in density_fn
    density, _ = self.get_density(ray_samples)
  File "C:\Users\GM\Desktop\NERFStudio-1.0.2\miniconda3\lib\site-packages\nerfstudio\fields\density_fields.py", line 107, in get_density
    self.mlp_base(positions_flat).view(*ray_samples.frustums.shape, -1).to(positions)
  File "C:\Users\GM\Desktop\NERFStudio-1.0.2\miniconda3\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\GM\Desktop\NERFStudio-1.0.2\miniconda3\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\GM\Desktop\NERFStudio-1.0.2\miniconda3\lib\site-packages\torch\nn\modules\container.py", line 215, in forward
    input = module(input)
  File "C:\Users\GM\Desktop\NERFStudio-1.0.2\miniconda3\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\GM\Desktop\NERFStudio-1.0.2\miniconda3\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\GM\Desktop\NERFStudio-1.0.2\miniconda3\lib\site-packages\nerfstudio\field_components\encodings.py", line 465, in forward
    return self.tcnn_encoding(in_tensor)
  File "C:\Users\GM\Desktop\NERFStudio-1.0.2\miniconda3\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\GM\Desktop\NERFStudio-1.0.2\miniconda3\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\GM\Desktop\NERFStudio-1.0.2\miniconda3\lib\site-packages\tinycudann\modules.py", line 186, in forward
    output = _module_function.apply(
  File "C:\Users\GM\Desktop\NERFStudio-1.0.2\miniconda3\lib\site-packages\torch\autograd\function.py", line 539, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "C:\Users\GM\Desktop\NERFStudio-1.0.2\miniconda3\lib\site-packages\tinycudann\modules.py", line 98, in forward
    native_ctx, output = native_tcnn_module.fwd(input, params)
RuntimeError: C:\Users\GM\AppData\Local\Temp\pip-req-build-q1n_nuat\bindings\torch\tinycudann\bindings.cpp:81 check failed params.device().is_cuda()

**Comment by maturk** [comment]
It is trying to use the tinycudann library, which is only supported for cuda. This is similar to the gsplat lib (for splatfacto) which is only for cuda. But you can use nerfacto with pytorch cpu, does this command not work? `ns-train nerfacto --machine.device-type cpu --data [path to data]`. For mac you can use the `mps` flag as well, this works for me since I have a mac.

**Comment by 4eJIoBek1** [comment]
yay, it really works lol, thx. If your PC already has CUDA device, youneed to disable it manually by adding CUDA_VISIBLE_DEVICES=-1 env variable and it ll works :3 For those who are want to run it on cpu (why, lol) the final command is:ns-train nerfacto --machine.device-type cpu  --pipeline.model.implementation torch --data (your datafolder)

**Comment by 4eJIoBek1** [comment]
![image](https://github.com/nerfstudio-project/nerfstudio/assets/109795993/4d538e34-db16-45b6-9d62-615b5e73f11d)
