### ISSUE TITLE
Hi, when I try to run nerfacto with nerfosr dataset, I found a bug in "nerfstudio/data/pixel_samplers.py". When num_rays_in_batch%2!=0, num_rays_in_batch += 1, which will cause the num_rays_in_batch of last image is negative. 

### ISSUE THREAD

**Issue by MoyangLi00** [nerfstudio-project/nerfstudio#3017]
`        num_rays_in_batch = num_rays_per_batch // num_images
        if num_rays_in_batch % 2 != 0:
            num_rays_in_batch += 1

        if "mask" in batch:
            for i in range(num_images):
                image_height, image_width, _ = batch["image"][i].shape

                if i == num_images - 1:
                    num_rays_in_batch = num_rays_per_batch - (num_images - 1) * num_rays_in_batch

                indices = self.sample_method(
                    num_rays_in_batch, 1, image_height, image_width, mask=batch["mask"][i].unsqueeze(0), device=device
                )
                indices[:, 0] = i
                all_indices.append(indices)
                all_images.append(batch["image"][i][indices[:, 1], indices[:, 2]])
                if "depth_image" in batch:
                    all_depth_images.append(batch["depth_image"][i][indices[:, 1], indices[:, 2]])
`

Error looks like this:
`Traceback (most recent call last):
  File "/home/rsl/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/multiprocess/process.py", line 315, in _bootstrap
    self.run()
  File "/home/rsl/Desktop/Moyang/code/nerfstudio/nerfstudio/data/datamanagers/parallel_datamanager.py", line 101, in run
    batch = self.pixel_sampler.sample(self.img_data)
  File "/home/rsl/Desktop/Moyang/code/nerfstudio/nerfstudio/data/pixel_samplers.py", line 374, in sample
    pixel_batch = self.collate_image_dataset_batch_list(
  File "/home/rsl/Desktop/Moyang/code/nerfstudio/nerfstudio/data/pixel_samplers.py", line 335, in collate_image_dataset_batch_list
    indices = self.sample_method(num_rays_in_batch, 1, image_height, image_width, device=device)
  File "/home/rsl/Desktop/Moyang/code/nerfstudio/nerfstudio/data/pixel_samplers.py", line 99, in sample_method
    torch.rand((batch_size, 3), device=device)
RuntimeError: Trying to create tensor with negative dimension -44: [-44, 3]
`

**Comment by MoyangLi00** [comment]
The following code could resolve aforementioned issue(just for reference)


     
      temp_num_rays_in_batch = num_rays_per_batch // num_images
              if temp_num_rays_in_batch % 2 != 0:
                  temp_num_rays_in_batch += 1
                  bd_id = (num_images - num_rays_per_batch % num_images) // 2
              else:
                  temp_num_rays_in_batch += 2
                  bd_id = num_images - num_rays_per_batch % num_images // 2

            if "mask" in batch:
                for i in range(num_images):
                    image_height, image_width, _ = batch["image"][i].shape
    
                    if i >= bd_id:
                        num_rays_in_batch = temp_num_rays_in_batch
                    else:
                        num_rays_in_batch = temp_num_rays_in_batch - 2
    
                    indices = self.sample_method(
                        num_rays_in_batch, 1, image_height, image_width, mask=batch["mask"][i].unsqueeze(0), device=device
                    )
                    indices[:, 0] = i
                    all_indices.append(indices)
                    all_images.append(batch["image"][i][indices[:, 1], indices[:, 2]])
                    if "depth_image" in batch:
                        all_depth_images.append(batch["depth_image"][i][indices[:, 1], indices[:, 2]])
    
            else:
                for i in range(num_images):
                    image_height, image_width, _ = batch["image"][i].shape
    
                    if i >= bd_id:
                        num_rays_in_batch = temp_num_rays_in_batch
                    else:
                        num_rays_in_batch = temp_num_rays_in_batch - 2
                    
                    if self.config.is_equirectangular:
                        indices = self.sample_method_equirectangular(
                            num_rays_in_batch, 1, image_height, image_width, device=device
                        )
                    else:
                        indices = self.sample_method(num_rays_in_batch, 1, image_height, image_width, device=device)
                    indices[:, 0] = i
                    all_indices.append(indices)
                    all_images.append(batch["image"][i][indices[:, 1], indices[:, 2]])
                    if "depth_image" in batch:
                        all_depth_images.append(batch["depth_image"][i][indices[:, 1], indices[:, 2]])
