### ISSUE TITLE
Splatfacto AssertionError: block_width must be between 2 and 16

### ISSUE THREAD

**Issue by aeaeaeaeaeae** [nerfstudio-project/nerfstudio#3033]
**Describe the bug**
Training failes with AssertionError: block_width must be between 2 and 16.

Looking at the source it seems that `splatfacto.py` call to `project_gaussians()` contains an extra `projmat.squeeze() @ viewmat.squeeze()` argument? Seems like nerfstudio installed with `pip install nerfstudio` is outdated.

**To Reproduce**

1. regular installation.
2. `pip install nerfstudio`
3. `pip install gsplat`
4. run `ns-download-data nerfstudio --capture-name=kitchen`
5. run `ns-train splatfacto --data data/nerfstudio/kitchen`

**Expected behavior**
Training would start as expected

**Additional context**
Running nerfstudio on Windows 11 PyTorch 2.1.2 with CUDA 11.8

from `splatfacto.py`
```python
        BLOCK_WIDTH = 16  # this controls the tile size of rasterization, 16 is a good default
        self.xys, depths, self.radii, conics, comp, num_tiles_hit, cov3d = project_gaussians(  # type: ignore
            means_crop,
            torch.exp(scales_crop),
            1,
            quats_crop / quats_crop.norm(dim=-1, keepdim=True),
            viewmat.squeeze()[:3, :],
            projmat.squeeze() @ viewmat.squeeze(),
            camera.fx.item(),
            camera.fy.item(),
            cx,
            cy,
            H,
            W,
            BLOCK_WIDTH,
        )  # type: ignore
```

from `project_gaussians.py` from `gsplat` 
```python
def project_gaussians(
    means3d: Float[Tensor, "*batch 3"],
    scales: Float[Tensor, "*batch 3"],
    glob_scale: float,
    quats: Float[Tensor, "*batch 4"],
    viewmat: Float[Tensor, "4 4"],
    fx: float,
    fy: float,
    cx: float,
    cy: float,
    img_height: int,
    img_width: int,
    block_width: int,
    clip_thresh: float = 0.01,
) -> Tuple[Tensor, Tensor, Tensor, Tensor, Tensor, Tensor, Tensor]:
    """ ...
    """
    assert block_width > 1 and block_width <= 16, "block_width must be between 2 and 16"
```

Traceback
```
...
[NOTE] Not running eval iterations since only viewer is enabled.
Use --vis {wandb, tensorboard, viewer+wandb, viewer+tensorboard} to run with eval.
No Nerfstudio checkpoint to load, so training from scratch.
Disabled comet/tensorboard/wandb event writers
Printing profiling stats, from longest to shortest duration in seconds
Trainer.train_iteration: 0.1144
VanillaPipeline.get_train_loss_dict: 0.1134
Traceback (most recent call last):
  File "D:\anaconda3\nerfstudio\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\anaconda3\nerfstudio\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\anaconda3\nerfstudio\Scripts\ns-train.exe\__main__.py", line 7, in <module>
  File "D:\anaconda3\nerfstudio\lib\site-packages\nerfstudio\scripts\train.py", line 262, in entrypoint
    main(
  File "D:\anaconda3\nerfstudio\lib\site-packages\nerfstudio\scripts\train.py", line 247, in main
    launch(
  File "D:\anaconda3\nerfstudio\lib\site-packages\nerfstudio\scripts\train.py", line 189, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "D:\anaconda3\nerfstudio\lib\site-packages\nerfstudio\scripts\train.py", line 100, in train_loop
    trainer.train()
  File "D:\anaconda3\nerfstudio\lib\site-packages\nerfstudio\engine\trainer.py", line 250, in train
    loss, loss_dict, metrics_dict = self.train_iteration(step)
  File "D:\anaconda3\nerfstudio\lib\site-packages\nerfstudio\utils\profiler.py", line 112, in inner
    out = func(*args, **kwargs)
  File "D:\anaconda3\nerfstudio\lib\site-packages\nerfstudio\engine\trainer.py", line 471, in train_iteration
    _, loss_dict, metrics_dict = self.pipeline.get_train_loss_dict(step=step)
  File "D:\anaconda3\nerfstudio\lib\site-packages\nerfstudio\utils\profiler.py", line 112, in inner
    out = func(*args, **kwargs)
  File "D:\anaconda3\nerfstudio\lib\site-packages\nerfstudio\pipelines\base_pipeline.py", line 300, in get_train_loss_dict
    model_outputs = self._model(ray_bundle)  # train distributed data parallel model if world_size > 1
  File "D:\anaconda3\nerfstudio\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\anaconda3\nerfstudio\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\anaconda3\nerfstudio\lib\site-packages\nerfstudio\models\base_model.py", line 143, in forward
    return self.get_outputs(ray_bundle)
  File "D:\anaconda3\nerfstudio\lib\site-packages\nerfstudio\models\splatfacto.py", line 739, in get_outputs
    self.xys, depths, self.radii, conics, comp, num_tiles_hit, cov3d = project_gaussians(  # type: ignore
  File "D:\anaconda3\nerfstudio\lib\site-packages\gsplat\project_gaussians.py", line 59, in project_gaussians
    assert block_width > 1 and block_width <= 16, "block_width must be between 2 and 16"
AssertionError: block_width must be between 2 and 16
```

**Comment by ZhenWusi** [comment]
I face same problem

**Comment by jsilvcast** [comment]
Same problem here

**Comment by jb-ye** [comment]
If you use pip install nerfstudio, you can choose to downgrade the gsplat library to v0.1.8. Alternatively, you can choose to install from source and use gsplat==0.1.10.

**Comment by ivanpuhachov** [comment]
see https://github.com/nerfstudio-project/gsplat/issues/159
