### ISSUE TITLE
Nerfacto on Windows

### ISSUE THREAD

**Issue by Renbry** [nerfstudio-project/nerfstudio#3055]
Hello,

I hope this doesn't sound like too much of a whinge.

My studio is mostly Windows based and I've had a darn of a time with Nerfstudio over the last few months.

To get specific in the here and now : I follow the instructions to install the prerequisites and finally Nerfstudio under Anaconda; no deviations, no curious hacks - just follow the instructions.

While training a Nerfacto model behaves predictably, GSplat/Splatfacto is a pain in the bum and as of today crashes out across 5 different Windows10/11 machines with the same error. THIS error is different than past GSplat versions; some worked, some didn't for different reasons but it's a wacky endeavour to try and use this platform for getting reliable training done. I come to the Issues forum and kind of expect to see someone saying "the latest version crashes" but no mentions so I feel like i'm taking crazy pills : )

Perhaps there's an assumption that this isn't made for work but is for pure research and development ? Perhaps I should be in Linux and Windows is considered unsupported and obviously unsuitable for NerfStudio ?

I wonder what attitude I should have towards the project ?

In comparison - I load up the Beta for PostShot and within 10 minutes have the best Splat I've ever seen (locally) because that project seems to have a different approach (static, compiled libraries that work when following install instructions?)

Pasting the error log here and going off hunting down what I can do to hack NerfStudio into working this month, this week, this day.

Using the latest v1.0.3 NerfStudio and v1.0.10 GSplat

           Saving config to: outputs\Hydrant_v01\splatfacto\2024-04-08_084539\config.yml        experiment_config.py:136
           Saving checkpoints to: outputs\Hydrant_v01\splatfacto\2024-04-08_084539\nerfstudio_models      trainer.py:136
           Auto image downscale factor of 4                                                 nerfstudio_dataparser.py:484
[08:45:40] Caching / undistorting train images                                            full_images_datamanager.py:182
[08:45:44] Caching / undistorting eval images                                             full_images_datamanager.py:196
┌─────────────── viser ───────────────┐
│             ╷                       │
│   HTTP      │ http://0.0.0.0:7007   │
│   Websocket │ ws://0.0.0.0:7007     │
│             ╵                       │
└─────────────────────────────────────┘
[NOTE] Not running eval iterations since only viewer is enabled.
Use --vis {wandb, tensorboard, viewer+wandb, viewer+tensorboard} to run with eval.
No Nerfstudio checkpoint to load, so training from scratch.
Disabled comet/tensorboard/wandb event writers
C:\Users\renbr\anaconda3\envs\nerfstudio\lib\site-packages\torch\utils\cpp_extension.py:383: UserWarning: Error
checking compiler version for cl: [WinError 2] The system cannot find the file specified
  warnings.warn(f'Error checking compiler version for {compiler}: {error}')
(  ●   ) gsplat: Setting up CUDA (This may take a few minutes the first time)INFO: Could not find files for the given pattern(s).
Printing profiling stats, from longest to shortest duration in seconds
Trainer.train_iteration: 0.8481
VanillaPipeline.get_train_loss_dict: 0.8471
Traceback (most recent call last):
  File "C:\Users\renbr\anaconda3\envs\nerfstudio\lib\site-packages\gsplat\cuda\_backend.py", line 56, in <module>
    from gsplat import csrc as _C
ImportError: cannot import name 'csrc' from 'gsplat' (C:\Users\renbr\anaconda3\envs\nerfstudio\lib\site-packages\gsplat\__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\renbr\anaconda3\envs\nerfstudio\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\renbr\anaconda3\envs\nerfstudio\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\renbr\anaconda3\envs\nerfstudio\Scripts\ns-train.exe\__main__.py", line 7, in <module>
  File "C:\Users\renbr\anaconda3\envs\nerfstudio\lib\site-packages\nerfstudio\scripts\train.py", line 262, in entrypoint
    main(
  File "C:\Users\renbr\anaconda3\envs\nerfstudio\lib\site-packages\nerfstudio\scripts\train.py", line 247, in main
    launch(
  File "C:\Users\renbr\anaconda3\envs\nerfstudio\lib\site-packages\nerfstudio\scripts\train.py", line 189, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "C:\Users\renbr\anaconda3\envs\nerfstudio\lib\site-packages\nerfstudio\scripts\train.py", line 100, in train_loop
    trainer.train()
  File "C:\Users\renbr\anaconda3\envs\nerfstudio\lib\site-packages\nerfstudio\engine\trainer.py", line 250, in train
    loss, loss_dict, metrics_dict = self.train_iteration(step)
  File "C:\Users\renbr\anaconda3\envs\nerfstudio\lib\site-packages\nerfstudio\utils\profiler.py", line 112, in inner
    out = func(*args, **kwargs)
  File "C:\Users\renbr\anaconda3\envs\nerfstudio\lib\site-packages\nerfstudio\engine\trainer.py", line 471, in train_iteration
    _, loss_dict, metrics_dict = self.pipeline.get_train_loss_dict(step=step)
  File "C:\Users\renbr\anaconda3\envs\nerfstudio\lib\site-packages\nerfstudio\utils\profiler.py", line 112, in inner
    out = func(*args, **kwargs)
  File "C:\Users\renbr\anaconda3\envs\nerfstudio\lib\site-packages\nerfstudio\pipelines\base_pipeline.py", line 300, in get_train_loss_dict
    model_outputs = self._model(ray_bundle)  # train distributed data parallel model if world_size > 1
  File "C:\Users\renbr\anaconda3\envs\nerfstudio\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\renbr\anaconda3\envs\nerfstudio\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\renbr\anaconda3\envs\nerfstudio\lib\site-packages\nerfstudio\models\base_model.py", line 143, in forward
    return self.get_outputs(ray_bundle)
  File "C:\Users\renbr\anaconda3\envs\nerfstudio\lib\site-packages\nerfstudio\models\splatfacto.py", line 711, in get_outputs
    self.xys, depths, self.radii, conics, comp, num_tiles_hit, cov3d = project_gaussians(  # type: ignore
  File "C:\Users\renbr\anaconda3\envs\nerfstudio\lib\site-packages\gsplat\project_gaussians.py", line 61, in project_gaussians
    return _ProjectGaussians.apply(
  File "C:\Users\renbr\anaconda3\envs\nerfstudio\lib\site-packages\torch\autograd\function.py", line 539, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "C:\Users\renbr\anaconda3\envs\nerfstudio\lib\site-packages\gsplat\project_gaussians.py", line 110, in forward
    ) = _C.project_gaussians_forward(
  File "C:\Users\renbr\anaconda3\envs\nerfstudio\lib\site-packages\gsplat\cuda\__init__.py", line 7, in call_cuda
    from ._backend import _C
  File "C:\Users\renbr\anaconda3\envs\nerfstudio\lib\site-packages\gsplat\cuda\_backend.py", line 88, in <module>
    _C = load(
  File "C:\Users\renbr\anaconda3\envs\nerfstudio\lib\site-packages\torch\utils\cpp_extension.py", line 1308, in load
    return _jit_compile(
  File "C:\Users\renbr\anaconda3\envs\nerfstudio\lib\site-packages\torch\utils\cpp_extension.py", line 1710, in _jit_compile
    _write_ninja_file_and_build_library(
  File "C:\Users\renbr\anaconda3\envs\nerfstudio\lib\site-packages\torch\utils\cpp_extension.py", line 1810, in _write_ninja_file_and_build_library
    _write_ninja_file_to_build_library(
  File "C:\Users\renbr\anaconda3\envs\nerfstudio\lib\site-packages\torch\utils\cpp_extension.py", line 2242, in _write_ninja_file_to_build_library
    _write_ninja_file(
  File "C:\Users\renbr\anaconda3\envs\nerfstudio\lib\site-packages\torch\utils\cpp_extension.py", line 2382, in _write_ninja_file
    cl_paths = subprocess.check_output(['where',
  File "C:\Users\renbr\anaconda3\envs\nerfstudio\lib\subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\renbr\anaconda3\envs\nerfstudio\lib\subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['where', 'cl']' returned non-zero exit status 1.

**Comment by Renbry** [comment]
Found another hapless Windows user in a Cuda-related forum expressing the same error.

While I'd previously already sleuthed that Visual Studio Build Tools was an assumed essential install (and had it installed),
There's a critical need for "cl.exe" to be in one's PATH env var for example : 

"C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.39.33519\bin\Hostx86\x64"

Which now lets the "Cuda Setup" happen as part of Splatfacto/GSplat's prerequisite boot up/compilation stage happen.

I'm now training a Splat model today, right now!

Putting this here for any future travellers.
