### ISSUE TITLE
NerfRobusters dataset processing Bug for the new released version

### ISSUE THREAD

**Issue by ZejiHui** [nerfstudio-project/nerfstudio#3079]
when processing the nerfbuster dataset, i.e. split the dataet into trian and eval sets. the new version has a bug:

> ns-process-data images --data data/cups/clean --eval-data data/cups/eval --output-dir data/cups/cups_clean
> [12:34:11] 🎉 Done copying images with prefix 'frame_train_'.                                  process_data_utils.py:340
> [12:34:14] 🎉 Done copying images with prefix 'frame_eval_'.                                   process_data_utils.py:340
> Traceback (most recent call last):
>   File "/home/anaconda3/envs/nerfstudio/bin/ns-process-data", line 8, in <module>
>     sys.exit(entrypoint())
>   File "/home/NeRF/experiments/nerfstudio/nerfstudio/scripts/process_data.py", line 524, in entrypoint
>     tyro.cli(Commands).main()
>   File "/home/NeRF/experiments/nerfstudio/nerfstudio/process_data/images_to_nerfstudio_dataset.py", line 90, in main
>     image_rename_map = dict(
>   File "/home/zeji/NeRF/experiments/nerfstudio/nerfstudio/process_data/images_to_nerfstudio_dataset.py", line 91, in <genexpr>
>     (a.relative_to(self.data).as_posix(), b.name) for a, b in image_rename_map_paths.items()
>   File "/home/zeji/anaconda3/envs/nerfstudio/lib/python3.8/pathlib.py", line 908, in relative_to
>     raise ValueError("{!r} does not start with {!r}"
> ValueError: 'data/cups/eval/image_1.JPG' does not start with 'data/cups/clean'

**Comment by ZejiHui** [comment]
tested V1.0.0, there is no problem
