### ISSUE TITLE
Improve Error Feedback in colab/demo.ipynb Data Processing Steps 

### ISSUE THREAD

**Issue by ichuniq** [nerfstudio-project/nerfstudio#3123]
**Is your feature request related to a problem? Please describe.**

Yes, when running the "Downloading and Processing Data" step in `colab/demo.ipynb`, the message "Data Processing Succeeded!" is displayed regardless of whether the actual processing was successful. 

This is because the script checks for the existence of `transforms.json` during the training step. If the file is missing, the system advises, "Please re-run 'Downloading and Processing Data', or view the FAQ for more info." This may cause confusion, especially for beginners, as the message suggest successful processing when there may be underlying errors, such as those related to COLMAP and its dependencies. Simply re-running the block does not necessarily resolve these failures.

**Describe the solution you'd like**

A straightforward solution is to move the verification step earlier. The message "Data Processing Succeeded!" should only be displayed if the required output file is present. If not, a more informative error message should guide the user. For example:
```python
if os.path.exists(f"data/nerfstudio/{scene}/transforms.json"):
    print("Data Processing Succeeded!")
else:
    print("Some errors occurred during `ns-process-data`. Check the output message to identify the failure (e.g. failures when running COLMAP) or view the FAQ for more info.")
```

**Comment by olejorgenb** [comment]
It currently fail for me with

```
/content
2024-05-07 17:54:35.115972: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-05-07 17:54:35.116028: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-05-07 17:54:35.211905: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-05-07 17:54:35.402975: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-05-07 17:54:37.309024: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Downloading...
From (original): https://drive.google.com/uc?id=1FceQ5DX7bbTbHeL26t0x6ku56cwsRs6t
From (redirected): https://drive.google.com/uc?id=1FceQ5DX7bbTbHeL26t0x6ku56cwsRs6t&confirm=t&uuid=6085d7a8-6a24-4cd1-b836-21748251a359
To: /content/data/nerfstudio/poster.zip
100% 749M/749M [00:08<00:00, 92.8MB/s]
Traceback (most recent call last):
  File "/usr/local/bin/ns-download-data", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.10/dist-packages/nerfstudio/scripts/downloads/download_data.py", line 573, in entrypoint
    main(tyro.cli(Commands))
  File "/usr/local/lib/python3.10/dist-packages/nerfstudio/scripts/downloads/download_data.py", line 567, in main
    dataset.download(dataset.save_dir)
  File "/usr/local/lib/python3.10/dist-packages/nerfstudio/scripts/downloads/download_data.py", line 207, in download
    download_capture_name(save_dir, "nerfstudio", self.capture_name, capture_name_to_file_id=nerfstudio_file_ids)
  File "/usr/local/lib/python3.10/dist-packages/nerfstudio/scripts/downloads/download_data.py", line 174, in download_capture_name
    assert len(inner_folders) == 1, f"There is more than one folder inside this zip file: {inner_folders}"
AssertionError: There is more than one folder inside this zip file: ['poster', '__MACOSX']
Data Processing Succeeded!
```
