### ISSUE TITLE
Google Drive Permission Error when running `ns-download-data nerfstudio --capture-name=poster`

### ISSUE THREAD

**Issue by branyang02** [nerfstudio-project/nerfstudio#3134]
**Describe the bug**
Running `ns-download-data nerfstudio --capture-name=poster` results in a gdown google drive permission error.

**To Reproduce**
1. Run `ns-download-data nerfstudio --capture-name=poster` after installation.

**Expected behavior**
Download Data

**Screenshots**
<img width="567" alt="image" src="https://github.com/nerfstudio-project/nerfstudio/assets/107154811/dd3b5fed-f525-4aed-b62d-d7230dc803d3">

**Comment by NishanthARao** [comment]
Hi, I had the same issue. 
However, they have updated the link for the poster dataset here:
https://github.com/nerfstudio-project/nerfstudio/pull/3045

For convenience, I have posted the Gdrive link here:
https://drive.google.com/file/d/1FceQ5DX7bbTbHeL26t0x6ku56cwsRs6t/view?usp=sharing

But if you installed using `pip` command, this link may not be updated in the files. You will have to manually replace the above link in a file called `download_data.py` file whose path (atleast in my system!) is:
`/home/user/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/scripts/downloads/download_data.py`
 (I used conda here)
 
 This solved the issue for me. Hope this helps!

**Comment by spicelion1802** [comment]
The new Google drive link is the same as what is already in the download_data.py file. I tried updating the link manually but it did not work.

**Comment by NishanthARao** [comment]
Can you download the files from the google drive and manually place the "poster" folder in the datasets folder? I think that gdrive link also has a "_MACOSX" folder, and the code cannot parse it.

**Comment by spicelion1802** [comment]
Other datasets like dozer work but poster does not. I just to get a trial model up and running but atfer downloading the dataset for dozer I run into the following issues when I try to train the model:

$ns-train nerfacto --pipeline.model.predict-normals True --data data/nerfstudio/dozer$

It throws the following error:
$OSError: [Errno 22] Invalid argument
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\sr218\anaconda3\envs\nerfstudio\lib\site-packages\multiprocess\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\sr218\anaconda3\envs\nerfstudio\lib\site-packages\multiprocess\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
  File "C:\Users\sr218\anaconda3\envs\nerfstudio\lib\site-packages\dill\_dill.py", line 289, in load
    return Unpickler(file, ignore=ignore, **kwds).load()
  File "C:\Users\sr218\anaconda3\envs\nerfstudio\lib\site-packages\dill\_dill.py", line 444, in load
    obj = StockUnpickler.load(self)
_pickle.UnpicklingError: pickle data was truncated
Exception ignored in: <function ParallelDataManager.__del__ at 0x0000015E63D83430>
Traceback (most recent call last):
  File "C:\Users\sr218\anaconda3\envs\nerfstudio\lib\site-packages\nerfstudio\data\datamanagers\parallel_datamanager.py", line 339, in __del__
    proc.terminate()
  File "C:\Users\sr218\anaconda3\envs\nerfstudio\lib\site-packages\multiprocess\process.py", line 133, in terminate
    self._popen.terminate()
AttributeError: 'NoneType' object has no attribute 'terminate'$

Any help is appreciated!
