### ISSUE TITLE
Tiny-cude-nn installation fails on WSL2 (Ubuntu 22.04.3 LTS)

### ISSUE THREAD

**Issue by SchmidL** [nerfstudio-project/nerfstudio#3178]
**Describe the bug**

First i followed all the steps in instruction

while installing tiny-cuda-nn I first face the following issue:

```
 pip install git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch
Collecting git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch
  Cloning https://github.com/NVlabs/tiny-cuda-nn/ to /tmp/pip-req-build-zgrm3ap4
  Running command git clone --filter=blob:none --quiet https://github.com/NVlabs/tiny-cuda-nn/ /tmp/pip-req-build-zgrm3ap4
  Resolved https://github.com/NVlabs/tiny-cuda-nn/ to commit 4892659e015b12bd2fce446b8a8e33e646b21746
  Running command git submodule update --init --recursive -q
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      /tmp/pip-req-build-zgrm3ap4/bindings/torch/setup.py:5: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
        from pkg_resources import parse_version
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-zgrm3ap4/bindings/torch/setup.py", line 11, in <module>
          from torch.utils.cpp_extension import BuildExtension, CUDAExtension
        File "/scratch/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 28, in <module>
          from pkg_resources import packaging  # type: ignore[attr-defined]
      ImportError: cannot import name 'packaging' from 'pkg_resources' (/scratch/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/pkg_resources/__init__.py)
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

After downgrading setuptools as suggested in https://github.com/nerfstudio-project/nerfstudio/issues/3159#issue-2312986239 to version 69.5.1 with ` pip install setuptools==69.5.1`

it worked a bit further but then faced the following issue

```
 pip install git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch
Collecting git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch
  Cloning https://github.com/NVlabs/tiny-cuda-nn/ to /tmp/pip-req-build-l3424bhj
  Running command git clone --filter=blob:none --quiet https://github.com/NVlabs/tiny-cuda-nn/ /tmp/pip-req-build-l3424bhj
  Resolved https://github.com/NVlabs/tiny-cuda-nn/ to commit 4892659e015b12bd2fce446b8a8e33e646b21746
  Running command git submodule update --init --recursive -q
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: tinycudann
  Building wheel for tinycudann (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [103 lines of output]
      /tmp/pip-req-build-l3424bhj/bindings/torch/setup.py:5: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
        from pkg_resources import parse_version
      Building PyTorch extension for tiny-cuda-nn version 1.7
      Obtained compute capability 86 from PyTorch
      nvcc: NVIDIA (R) Cuda compiler driver
      Copyright (c) 2005-2022 NVIDIA Corporation
      Built on Wed_Sep_21_10:33:58_PDT_2022
      Cuda compilation tools, release 11.8, V11.8.89
      Build cuda_11.8.r11.8/compiler.31833905_0
      Detected CUDA version 11.8
      Targeting C++ standard 17
      running bdist_wheel
      /scratch/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/utils/cpp_extension.py:502: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
        warnings.warn(msg.format('we could not find ninja.'))
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-38
      creating build/lib.linux-x86_64-cpython-38/tinycudann
      copying tinycudann/modules.py -> build/lib.linux-x86_64-cpython-38/tinycudann
      copying tinycudann/__init__.py -> build/lib.linux-x86_64-cpython-38/tinycudann
      running egg_info
      creating tinycudann.egg-info
      writing tinycudann.egg-info/PKG-INFO
      writing dependency_links to tinycudann.egg-info/dependency_links.txt
      writing top-level names to tinycudann.egg-info/top_level.txt
      writing manifest file 'tinycudann.egg-info/SOURCES.txt'
      reading manifest file 'tinycudann.egg-info/SOURCES.txt'
      writing manifest file 'tinycudann.egg-info/SOURCES.txt'
      copying tinycudann/bindings.cpp -> build/lib.linux-x86_64-cpython-38/tinycudann
      running build_ext
      /scratch/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/utils/cpp_extension.py:424: UserWarning: There are no g++ version bounds defined for CUDA version 11.8
        warnings.warn(f'There are no {compiler_name} version bounds defined for CUDA version {cuda_str_version}')
      building 'tinycudann_bindings._86_C' extension
      creating dependencies
      creating dependencies/fmt
      creating dependencies/fmt/src
      creating src
      creating build/temp.linux-x86_64-cpython-38
      creating build/temp.linux-x86_64-cpython-38/tinycudann
      gcc -pthread -B /scratch/miniconda3/envs/nerfstudio/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /scratch/miniconda3/envs/nerfstudio/include -fPIC -O2 -isystem /scratch/miniconda3/envs/nerfstudio/include -fPIC -I/tmp/pip-req-build-l3424bhj/include -I/tmp/pip-req-build-l3424bhj/dependencies -I/tmp/pip-req-build-l3424bhj/dependencies/cutlass/include -I/tmp/pip-req-build-l3424bhj/dependencies/cutlass/tools/util/include -I/tmp/pip-req-build-l3424bhj/dependencies/fmt/include -I/scratch/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/include -I/scratch/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/scratch/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/include/TH -I/scratch/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/include/THC -I/scratch/miniconda3/envs/nerfstudio/include -I/scratch/miniconda3/envs/nerfstudio/include/python3.8 -c ../../dependencies/fmt/src/format.cc -o build/temp.linux-x86_64-cpython-38/../../dependencies/fmt/src/format.o -std=c++17 -DTCNN_PARAMS_UNALIGNED -DTCNN_MIN_GPU_ARCH=86 -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -DTORCH_EXTENSION_NAME=_86_C -D_GLIBCXX_USE_CXX11_ABI=0
      gcc -pthread -B /scratch/miniconda3/envs/nerfstudio/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /scratch/miniconda3/envs/nerfstudio/include -fPIC -O2 -isystem /scratch/miniconda3/envs/nerfstudio/include -fPIC -I/tmp/pip-req-build-l3424bhj/include -I/tmp/pip-req-build-l3424bhj/dependencies -I/tmp/pip-req-build-l3424bhj/dependencies/cutlass/include -I/tmp/pip-req-build-l3424bhj/dependencies/cutlass/tools/util/include -I/tmp/pip-req-build-l3424bhj/dependencies/fmt/include -I/scratch/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/include -I/scratch/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/scratch/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/include/TH -I/scratch/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/include/THC -I/scratch/miniconda3/envs/nerfstudio/include -I/scratch/miniconda3/envs/nerfstudio/include/python3.8 -c ../../dependencies/fmt/src/os.cc -o build/temp.linux-x86_64-cpython-38/../../dependencies/fmt/src/os.o -std=c++17 -DTCNN_PARAMS_UNALIGNED -DTCNN_MIN_GPU_ARCH=86 -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -DTORCH_EXTENSION_NAME=_86_C -D_GLIBCXX_USE_CXX11_ABI=0
      /scratch/miniconda3/envs/nerfstudio/bin/nvcc -I/tmp/pip-req-build-l3424bhj/include -I/tmp/pip-req-build-l3424bhj/dependencies -I/tmp/pip-req-build-l3424bhj/dependencies/cutlass/include -I/tmp/pip-req-build-l3424bhj/dependencies/cutlass/tools/util/include -I/tmp/pip-req-build-l3424bhj/dependencies/fmt/include -I/scratch/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/include -I/scratch/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/scratch/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/include/TH -I/scratch/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/include/THC -I/scratch/miniconda3/envs/nerfstudio/include -I/scratch/miniconda3/envs/nerfstudio/include/python3.8 -c ../../src/common_host.cu -o build/temp.linux-x86_64-cpython-38/../../src/common_host.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -std=c++17 --extended-lambda --expt-relaxed-constexpr -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -Xcompiler=-Wno-float-conversion -Xcompiler=-fno-strict-aliasing -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -DTCNN_PARAMS_UNALIGNED -DTCNN_MIN_GPU_ARCH=86 -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -DTORCH_EXTENSION_NAME=_86_C -D_GLIBCXX_USE_CXX11_ABI=0
      /tmp/pip-req-build-l3424bhj/dependencies/fmt/include/fmt/core.h(288): warning #1675-D: unrecognized GCC pragma

      /tmp/pip-req-build-l3424bhj/dependencies/fmt/include/fmt/core.h(288): warning #1675-D: unrecognized GCC pragma

      /scratch/miniconda3/envs/nerfstudio/bin/nvcc -I/tmp/pip-req-build-l3424bhj/include -I/tmp/pip-req-build-l3424bhj/dependencies -I/tmp/pip-req-build-l3424bhj/dependencies/cutlass/include -I/tmp/pip-req-build-l3424bhj/dependencies/cutlass/tools/util/include -I/tmp/pip-req-build-l3424bhj/dependencies/fmt/include -I/scratch/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/include -I/scratch/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/scratch/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/include/TH -I/scratch/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/include/THC -I/scratch/miniconda3/envs/nerfstudio/include -I/scratch/miniconda3/envs/nerfstudio/include/python3.8 -c ../../src/cpp_api.cu -o build/temp.linux-x86_64-cpython-38/../../src/cpp_api.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -std=c++17 --extended-lambda --expt-relaxed-constexpr -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -Xcompiler=-Wno-float-conversion -Xcompiler=-fno-strict-aliasing -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -DTCNN_PARAMS_UNALIGNED -DTCNN_MIN_GPU_ARCH=86 -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -DTORCH_EXTENSION_NAME=_86_C -D_GLIBCXX_USE_CXX11_ABI=0
      /tmp/pip-req-build-l3424bhj/dependencies/fmt/include/fmt/core.h(288): warning #1675-D: unrecognized GCC pragma

      /tmp/pip-req-build-l3424bhj/dependencies/fmt/include/fmt/core.h(288): warning #1675-D: unrecognized GCC pragma

      /scratch/miniconda3/envs/nerfstudio/bin/nvcc -I/tmp/pip-req-build-l3424bhj/include -I/tmp/pip-req-build-l3424bhj/dependencies -I/tmp/pip-req-build-l3424bhj/dependencies/cutlass/include -I/tmp/pip-req-build-l3424bhj/dependencies/cutlass/tools/util/include -I/tmp/pip-req-build-l3424bhj/dependencies/fmt/include -I/scratch/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/include -I/scratch/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/scratch/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/include/TH -I/scratch/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/include/THC -I/scratch/miniconda3/envs/nerfstudio/include -I/scratch/miniconda3/envs/nerfstudio/include/python3.8 -c ../../src/cutlass_mlp.cu -o build/temp.linux-x86_64-cpython-38/../../src/cutlass_mlp.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -std=c++17 --extended-lambda --expt-relaxed-constexpr -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -Xcompiler=-Wno-float-conversion -Xcompiler=-fno-strict-aliasing -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -DTCNN_PARAMS_UNALIGNED -DTCNN_MIN_GPU_ARCH=86 -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -DTORCH_EXTENSION_NAME=_86_C -D_GLIBCXX_USE_CXX11_ABI=0
      /tmp/pip-req-build-l3424bhj/dependencies/fmt/include/fmt/core.h(288): warning #1675-D: unrecognized GCC pragma

      /tmp/pip-req-build-l3424bhj/dependencies/fmt/include/fmt/core.h(288): warning #1675-D: unrecognized GCC pragma

      /scratch/miniconda3/envs/nerfstudio/bin/nvcc -I/tmp/pip-req-build-l3424bhj/include -I/tmp/pip-req-build-l3424bhj/dependencies -I/tmp/pip-req-build-l3424bhj/dependencies/cutlass/include -I/tmp/pip-req-build-l3424bhj/dependencies/cutlass/tools/util/include -I/tmp/pip-req-build-l3424bhj/dependencies/fmt/include -I/scratch/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/include -I/scratch/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/scratch/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/include/TH -I/scratch/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/include/THC -I/scratch/miniconda3/envs/nerfstudio/include -I/scratch/miniconda3/envs/nerfstudio/include/python3.8 -c ../../src/encoding.cu -o build/temp.linux-x86_64-cpython-38/../../src/encoding.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -std=c++17 --extended-lambda --expt-relaxed-constexpr -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -Xcompiler=-Wno-float-conversion -Xcompiler=-fno-strict-aliasing -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -DTCNN_PARAMS_UNALIGNED -DTCNN_MIN_GPU_ARCH=86 -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -DTORCH_EXTENSION_NAME=_86_C -D_GLIBCXX_USE_CXX11_ABI=0
      /tmp/pip-req-build-l3424bhj/dependencies/fmt/include/fmt/core.h(288): warning #1675-D: unrecognized GCC pragma

      /tmp/pip-req-build-l3424bhj/dependencies/fmt/include/fmt/core.h(288): warning #1675-D: unrecognized GCC pragma

      /scratch/miniconda3/envs/nerfstudio/bin/nvcc -I/tmp/pip-req-build-l3424bhj/include -I/tmp/pip-req-build-l3424bhj/dependencies -I/tmp/pip-req-build-l3424bhj/dependencies/cutlass/include -I/tmp/pip-req-build-l3424bhj/dependencies/cutlass/tools/util/include -I/tmp/pip-req-build-l3424bhj/dependencies/fmt/include -I/scratch/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/include -I/scratch/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/scratch/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/include/TH -I/scratch/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/include/THC -I/scratch/miniconda3/envs/nerfstudio/include -I/scratch/miniconda3/envs/nerfstudio/include/python3.8 -c ../../src/fully_fused_mlp.cu -o build/temp.linux-x86_64-cpython-38/../../src/fully_fused_mlp.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -std=c++17 --extended-lambda --expt-relaxed-constexpr -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -Xcompiler=-Wno-float-conversion -Xcompiler=-fno-strict-aliasing -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -DTCNN_PARAMS_UNALIGNED -DTCNN_MIN_GPU_ARCH=86 -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -DTORCH_EXTENSION_NAME=_86_C -D_GLIBCXX_USE_CXX11_ABI=0
      /tmp/pip-req-build-l3424bhj/dependencies/fmt/include/fmt/core.h(288): warning #1675-D: unrecognized GCC pragma

      /tmp/pip-req-build-l3424bhj/dependencies/fmt/include/fmt/core.h(288): warning #1675-D: unrecognized GCC pragma

      /scratch/miniconda3/envs/nerfstudio/bin/nvcc -I/tmp/pip-req-build-l3424bhj/include -I/tmp/pip-req-build-l3424bhj/dependencies -I/tmp/pip-req-build-l3424bhj/dependencies/cutlass/include -I/tmp/pip-req-build-l3424bhj/dependencies/cutlass/tools/util/include -I/tmp/pip-req-build-l3424bhj/dependencies/fmt/include -I/scratch/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/include -I/scratch/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/scratch/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/include/TH -I/scratch/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/include/THC -I/scratch/miniconda3/envs/nerfstudio/include -I/scratch/miniconda3/envs/nerfstudio/include/python3.8 -c ../../src/network.cu -o build/temp.linux-x86_64-cpython-38/../../src/network.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -std=c++17 --extended-lambda --expt-relaxed-constexpr -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -Xcompiler=-Wno-float-conversion -Xcompiler=-fno-strict-aliasing -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -DTCNN_PARAMS_UNALIGNED -DTCNN_MIN_GPU_ARCH=86 -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -DTORCH_EXTENSION_NAME=_86_C -D_GLIBCXX_USE_CXX11_ABI=0
      /tmp/pip-req-build-l3424bhj/dependencies/fmt/include/fmt/core.h(288): warning #1675-D: unrecognized GCC pragma

      /tmp/pip-req-build-l3424bhj/dependencies/fmt/include/fmt/core.h(288): warning #1675-D: unrecognized GCC pragma

      /scratch/miniconda3/envs/nerfstudio/bin/nvcc -I/tmp/pip-req-build-l3424bhj/include -I/tmp/pip-req-build-l3424bhj/dependencies -I/tmp/pip-req-build-l3424bhj/dependencies/cutlass/include -I/tmp/pip-req-build-l3424bhj/dependencies/cutlass/tools/util/include -I/tmp/pip-req-build-l3424bhj/dependencies/fmt/include -I/scratch/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/include -I/scratch/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/scratch/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/include/TH -I/scratch/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/include/THC -I/scratch/miniconda3/envs/nerfstudio/include -I/scratch/miniconda3/envs/nerfstudio/include/python3.8 -c ../../src/object.cu -o build/temp.linux-x86_64-cpython-38/../../src/object.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -std=c++17 --extended-lambda --expt-relaxed-constexpr -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -Xcompiler=-Wno-float-conversion -Xcompiler=-fno-strict-aliasing -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -DTCNN_PARAMS_UNALIGNED -DTCNN_MIN_GPU_ARCH=86 -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -DTORCH_EXTENSION_NAME=_86_C -D_GLIBCXX_USE_CXX11_ABI=0
      /tmp/pip-req-build-l3424bhj/dependencies/fmt/include/fmt/core.h(288): warning #1675-D: unrecognized GCC pragma

      /tmp/pip-req-build-l3424bhj/dependencies/fmt/include/fmt/core.h(288): warning #1675-D: unrecognized GCC pragma

      gcc -pthread -B /scratch/miniconda3/envs/nerfstudio/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /scratch/miniconda3/envs/nerfstudio/include -fPIC -O2 -isystem /scratch/miniconda3/envs/nerfstudio/include -fPIC -I/tmp/pip-req-build-l3424bhj/include -I/tmp/pip-req-build-l3424bhj/dependencies -I/tmp/pip-req-build-l3424bhj/dependencies/cutlass/include -I/tmp/pip-req-build-l3424bhj/dependencies/cutlass/tools/util/include -I/tmp/pip-req-build-l3424bhj/dependencies/fmt/include -I/scratch/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/include -I/scratch/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/scratch/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/include/TH -I/scratch/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/include/THC -I/scratch/miniconda3/envs/nerfstudio/include -I/scratch/miniconda3/envs/nerfstudio/include/python3.8 -c tinycudann/bindings.cpp -o build/temp.linux-x86_64-cpython-38/tinycudann/bindings.o -std=c++17 -DTCNN_PARAMS_UNALIGNED -DTCNN_MIN_GPU_ARCH=86 -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -DTORCH_EXTENSION_NAME=_86_C -D_GLIBCXX_USE_CXX11_ABI=0
      In file included from /scratch/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/include/torch/csrc/Exceptions.h:14,
                       from /scratch/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/python.h:11,
                       from /scratch/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/include/torch/extension.h:9,
                       from tinycudann/bindings.cpp:34:
      /scratch/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/include/pybind11/pybind11.h: In instantiation of ‘class pybind11::class_<tcnn::cpp::LogSeverity>’:
      /scratch/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/include/pybind11/pybind11.h:2170:7:   required from ‘class pybind11::enum_<tcnn::cpp::LogSeverity>’
      tinycudann/bindings.cpp:283:52:   required from here
      /scratch/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/include/pybind11/pybind11.h:1496:7: warning: ‘pybind11::class_<tcnn::cpp::LogSeverity>’ declared with greater visibility than its base ‘pybind11::detail::generic_type’ [-Wattributes]
       1496 | class class_ : public detail::generic_type {
            |       ^~~~~~
      /scratch/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/include/pybind11/pybind11.h: In instantiation of ‘class pybind11::class_<tcnn::cpp::Precision>’:
      /scratch/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/include/pybind11/pybind11.h:2170:7:   required from ‘class pybind11::enum_<tcnn::cpp::Precision>’
      tinycudann/bindings.cpp:292:48:   required from here
      /scratch/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/include/pybind11/pybind11.h:1496:7: warning: ‘pybind11::class_<tcnn::cpp::Precision>’ declared with greater visibility than its base ‘pybind11::detail::generic_type’ [-Wattributes]
      /scratch/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/include/pybind11/pybind11.h: In instantiation of ‘class pybind11::class_<tcnn::cpp::Context>’:
      tinycudann/bindings.cpp:309:45:   required from here
      /scratch/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/include/pybind11/pybind11.h:1496:7: warning: ‘pybind11::class_<tcnn::cpp::Context>’ declared with greater visibility than its base ‘pybind11::detail::generic_type’ [-Wattributes]
      /scratch/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/include/pybind11/pybind11.h: In instantiation of ‘class pybind11::class_<Module>’:
      tinycudann/bindings.cpp:316:32:   required from here
      /scratch/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/include/pybind11/pybind11.h:1496:7: warning: ‘pybind11::class_<Module>’ declared with greater visibility than its base ‘pybind11::detail::generic_type’ [-Wattributes]
      creating build/lib.linux-x86_64-cpython-38/tinycudann_bindings
      g++ -pthread -B /scratch/miniconda3/envs/nerfstudio/compiler_compat -shared -Wl,--allow-shlib-undefined -Wl,-rpath,/scratch/miniconda3/envs/nerfstudio/lib -Wl,-rpath-link,/scratch/miniconda3/envs/nerfstudio/lib -L/scratch/miniconda3/envs/nerfstudio/lib -Wl,--allow-shlib-undefined -Wl,-rpath,/scratch/miniconda3/envs/nerfstudio/lib -Wl,-rpath-link,/scratch/miniconda3/envs/nerfstudio/lib -L/scratch/miniconda3/envs/nerfstudio/lib build/temp.linux-x86_64-cpython-38/../../dependencies/fmt/src/format.o build/temp.linux-x86_64-cpython-38/../../dependencies/fmt/src/os.o build/temp.linux-x86_64-cpython-38/../../src/common_host.o build/temp.linux-x86_64-cpython-38/../../src/cpp_api.o build/temp.linux-x86_64-cpython-38/../../src/cutlass_mlp.o build/temp.linux-x86_64-cpython-38/../../src/encoding.o build/temp.linux-x86_64-cpython-38/../../src/fully_fused_mlp.o build/temp.linux-x86_64-cpython-38/../../src/network.o build/temp.linux-x86_64-cpython-38/../../src/object.o build/temp.linux-x86_64-cpython-38/tinycudann/bindings.o -L/scratch/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/lib -L/scratch/miniconda3/envs/nerfstudio/lib -lcuda -lc10 -ltorch -ltorch_cpu -ltorch_python -lcudart -lc10_cuda -ltorch_cuda -o build/lib.linux-x86_64-cpython-38/tinycudann_bindings/_86_C.cpython-38-x86_64-linux-gnu.so
      /scratch/miniconda3/envs/nerfstudio/compiler_compat/ld: cannot find -lcuda: No such file or directory
      collect2: error: ld returned 1 exit status
      error: command '/usr/bin/g++' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for tinycudann
  Running setup.py clean for tinycudann
Failed to build tinycudann
ERROR: Could not build wheels for tinycudann, which is required to install pyproject.toml-based projects
```

**To Reproduce**
see steps above

**Comment by Achllle** [comment]
Same issue when I check out the latest tagged version, v1.1.0

**Comment by KevinXu02** [comment]
Hi! I've installed nerfstudio env successfully recently following https://gist.github.com/SharkWipf/0a3fc1be3ea88b0c9640db6ce15b44b9.

**Comment by abubake** [comment]
Faced same issue when installing torch bindings for nerfstudio setup Ubuntu 22.04 LTS. Downgrade solution mentioned above worked.
