### ISSUE TITLE
from nerfstudio.fields.visibility_field import VisibilityField ModuleNotFoundError: No module named 'nerfstudio.fields.visibility_field'

### ISSUE THREAD

**Issue by NaveenV2506** [nerfstudio-project/nerfstudio#3185]
I'm facing error during, train the nerfbusters model in nerf studio.

(nerfstudio) C:\Users\NEW>ns-train nerfbusters --data C:\Users\NEW\Documents\NV\Data\beam_data
Traceback (most recent call last):
  File "C:\Users\NEW\anaconda3\envs\nerfstudio\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\NEW\anaconda3\envs\nerfstudio\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\NEW\anaconda3\envs\nerfstudio\Scripts\ns-train.exe\__main__.py", line 4, in <module>
  File "C:\Users\NEW\nerfstudio\nerfstudio\scripts\train.py", line 62, in <module>
    from nerfstudio.configs.method_configs import AnnotatedBaseConfigUnion
  File "C:\Users\NEW\nerfstudio\nerfstudio\configs\method_configs.py", line 729, in <module>
    all_methods, all_descriptions = merge_methods(all_methods, all_descriptions, *discover_methods())
  File "C:\Users\NEW\nerfstudio\nerfstudio\plugins\registry.py", line 43, in discover_methods
    spec = discovered_entry_points[name].load()
  File "C:\Users\NEW\anaconda3\envs\nerfstudio\lib\site-packages\importlib_metadata\__init__.py", line 184, in load
    module = import_module(match.group('module'))
  File "C:\Users\NEW\anaconda3\envs\nerfstudio\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\NEW\anaconda3\envs\nerfstudio\lib\site-packages\nerfbusters\nerf\nerfbusters_config.py", line 16, in <module>
    from nerfbusters.nerf.nerfbusters_pipeline import NerfbustersPipelineConfig
  File "C:\Users\NEW\anaconda3\envs\nerfstudio\lib\site-packages\nerfbusters\nerf\nerfbusters_pipeline.py", line 42, in <module>
    from nerfstudio.fields.visibility_field import VisibilityField
ModuleNotFoundError: No module named 'nerfstudio.fields.visibility_field'

**Comment by brentyi** [comment]
It may make sense to raise this issue in the nerfbusters repo instead. It looks like they might also expect a specific branch of nerfstudio:
![image](https://github.com/nerfstudio-project/nerfstudio/assets/6992947/a49cad67-b6f0-4617-9efb-b504db10dd18)
