### ISSUE TITLE
filenotfounderror when url_share is set to True 

### ISSUE THREAD

**Issue by sumanttyagi** [nerfstudio-project/nerfstudio#3225]
when i am using below command 
```
ns-viewer --load-config outputs\colmappano_14\splatfacto\2024-06-13_144633\config.yml --viewer.make-share-url True
```
below error is showing 
```
Traceback (most recent call last):
  File "C:\Users\sum11525\Anaconda3\envs\nerfstudio1\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\sum11525\Anaconda3\envs\nerfstudio1\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\sum11525\Anaconda3\envs\nerfstudio1\Scripts\ns-viewer.exe\__main__.py", line 7, in <module>
  File "C:\Users\sum11525\Anaconda3\envs\nerfstudio1\lib\site-packages\nerfstudio\scripts\viewer\run_viewer.py", line 135, in entrypoint
    tyro.cli(tyro.conf.FlagConversionOff[RunViewer]).main()
  File "C:\Users\sum11525\Anaconda3\envs\nerfstudio1\lib\site-packages\nerfstudio\scripts\viewer\run_viewer.py", line 74, in main
    _start_viewer(config, pipeline, step)
  File "C:\Users\sum11525\Anaconda3\envs\nerfstudio1\lib\site-packages\nerfstudio\scripts\viewer\run_viewer.py", line 105, in _start_viewer
    viewer_state = ViewerState(
  File "C:\Users\sum11525\Anaconda3\envs\nerfstudio1\lib\site-packages\nerfstudio\viewer\viewer.py", line 114, in __init__
    share_url = self.viser_server.request_share_url()
  File "C:\Users\sum11525\Anaconda3\envs\nerfstudio1\lib\site-packages\viser\_viser.py", line 529, in request_share_url
    self._share_tunnel = ViserTunnel("share.viser.studio", self._server._port)
  File "C:\Users\sum11525\Anaconda3\envs\nerfstudio1\lib\site-packages\viser\_tunnel.py", line 36, in __init__
    self._multiprocess_ok = _is_multiprocess_ok()
  File "C:\Users\sum11525\Anaconda3\envs\nerfstudio1\lib\site-packages\viser\_tunnel.py", line 18, in _is_multiprocess_ok
    src = Path(__main__.__file__).read_text()
  File "C:\Users\sum11525\Anaconda3\envs\nerfstudio1\lib\pathlib.py", line 1236, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "C:\Users\sum11525\Anaconda3\envs\nerfstudio1\lib\pathlib.py", line 1222, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "C:\Users\sum11525\Anaconda3\envs\nerfstudio1\lib\pathlib.py", line 1078, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\sum11525\\Anaconda3\\envs\\nerfstudio1\\Scripts\\ns-viewer.exe\\__main__.py'
```

**Comment by ajean757** [comment]
Hmm, I have the same issue when I run it in windows, but it seems to work fine with WSL. I've been having weird issues like this with windows, so I would honestly try using WSL instead. Other than initial setup, I've encountered far less headaches on there.
