### ISSUE TITLE
"Downloading and Processing Data" section in Collab Notebook doesn't work

### ISSUE THREAD

**Issue by feoandrew** [nerfstudio-project/nerfstudio#3250]
I have an issue with collab notebook when i an trying to launch "Downloading and Processing Data".
When i am choosed the dozer scene and launched section i saw this error report:

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/usr/local/bin/ns-download-data", line 5, in <module>
    from nerfstudio.scripts.downloads.download_data import entrypoint
  File "/usr/local/lib/python3.10/dist-packages/nerfstudio/scripts/downloads/download_data.py", line 33, in <module>
    from nerfstudio.process_data import process_data_utils
  File "/usr/local/lib/python3.10/dist-packages/nerfstudio/process_data/process_data_utils.py", line 25, in <module>
    import cv2
  File "/usr/local/lib/python3.10/dist-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/usr/local/lib/python3.10/dist-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
AttributeError: _ARRAY_API not found
Traceback (most recent call last):
  File "/usr/local/bin/ns-download-data", line 5, in <module>
    from nerfstudio.scripts.downloads.download_data import entrypoint
  File "/usr/local/lib/python3.10/dist-packages/nerfstudio/scripts/downloads/download_data.py", line 33, in <module>
    from nerfstudio.process_data import process_data_utils
  File "/usr/local/lib/python3.10/dist-packages/nerfstudio/process_data/process_data_utils.py", line 25, in <module>
    import cv2
  File "/usr/local/lib/python3.10/dist-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/usr/local/lib/python3.10/dist-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: numpy.core.multiarray failed to import
Data Processing Succeeded!

The section "Start Training" also doesn't work and returns this output:

Error: Data processing did not complete
Please re-run `Downloading and Processing Data`, or view the FAQ for more info.

**Comment by bcongdon** [comment]
I hit this too. I was able to fix this by running `!pip install "numpy<2.0"` in a new cell
