### ISSUE TITLE
Calling viewer from VS code

### ISSUE THREAD

**Issue by TafnesBarbosa** [nerfstudio-project/nerfstudio#3261]
I tried to create an instance of the class viewer=RunViewer(Path("path/to/config/file")) and called viewer.main(). But there is some part where the code breaks and does not call the viewer. It says that is a problem of initiating another process while one is still running.

How can I create an instance of the viewer and call it by my own, without the common command "ns-viewer --load-config config/file"?

**Comment by ginazhouhuiwu** [comment]
What you did seems reasonable to me, do you mind copy and pasting down your exact errors please?

**Comment by TafnesBarbosa** [comment]
Sure.

Here is the error itself:
`from nerfstudio.scripts.viewer.run_viewer import *

viewer = RunViewer(load_config=Path('/media/tafnes/0E94B37D94B365BD/Users/tafne/Documents/Videos_externo/externo_horizontal_30_sol_normal/output/externo_horizontal_30_sol_normal/nerfacto/2024-06-23_021420/config.yml'))
viewer.main()`

And here is the error after running it:
`Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/tafnes/.local/lib/python3.10/site-packages/multiprocess/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/tafnes/.local/lib/python3.10/site-packages/multiprocess/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/home/tafnes/.local/lib/python3.10/site-packages/multiprocess/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/tafnes/.local/lib/python3.10/site-packages/multiprocess/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/usr/lib/python3.10/runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/tafnes/Documentos/Python/nerfstudio/teste_viewer.py", line 4, in <module>
    viewer.main()
  File "/home/tafnes/Documentos/Python/nerfstudio/nerfstudio/scripts/viewer/run_viewer.py", line 61, in main
    config, pipeline, _, step = eval_setup(
  File "/home/tafnes/Documentos/Python/nerfstudio/nerfstudio/utils/eval_utils.py", line 105, in eval_setup
    pipeline = config.pipeline.setup(device=device, test_mode=test_mode)
  File "/home/tafnes/Documentos/Python/nerfstudio/nerfstudio/configs/base_config.py", line 54, in setup
    return self._target(self, **kwargs)
  File "/home/tafnes/Documentos/Python/nerfstudio/nerfstudio/pipelines/base_pipeline.py", line 255, in __init__
    self.datamanager: DataManager = config.datamanager.setup(
  File "/home/tafnes/Documentos/Python/nerfstudio/nerfstudio/configs/base_config.py", line 54, in setup
    return self._target(self, **kwargs)
  File "/home/tafnes/Documentos/Python/nerfstudio/nerfstudio/data/datamanagers/parallel_datamanager.py", line 178, in __init__
    super().__init__()
  File "/home/tafnes/Documentos/Python/nerfstudio/nerfstudio/data/datamanagers/base_datamanager.py", line 181, in __init__
    self.setup_train()
  File "/home/tafnes/Documentos/Python/nerfstudio/nerfstudio/data/datamanagers/parallel_datamanager.py", line 255, in setup_train
    proc.start()
  File "/home/tafnes/.local/lib/python3.10/site-packages/multiprocess/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/home/tafnes/.local/lib/python3.10/site-packages/multiprocess/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/home/tafnes/.local/lib/python3.10/site-packages/multiprocess/context.py", line 288, in _Popen
    return Popen(process_obj)
  File "/home/tafnes/.local/lib/python3.10/site-packages/multiprocess/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/home/tafnes/.local/lib/python3.10/site-packages/multiprocess/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home/tafnes/.local/lib/python3.10/site-packages/multiprocess/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/home/tafnes/.local/lib/python3.10/site-packages/multiprocess/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/home/tafnes/.local/lib/python3.10/site-packages/multiprocess/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Exception ignored in: <function ParallelDataManager.__del__ at 0x7eb616362290>
Traceback (most recent call last):
  File "/home/tafnes/Documentos/Python/nerfstudio/nerfstudio/data/datamanagers/parallel_datamanager.py", line 339, in __del__
    proc.terminate()
  File "/home/tafnes/.local/lib/python3.10/site-packages/multiprocess/process.py", line 133, in terminate
    self._popen.terminate()
AttributeError: 'NoneType' object has no attribute 'terminate'`

**Comment by aayushg55** [comment]
I can confirm that error. The fix is to use the `if __name__ == '__main__':` guard around your main code since the viewer uses Python multiprocessing. It should look like so:

```
from nerfstudio.scripts.viewer.run_viewer import *

if __name__ == '__main__':
    viewer = RunViewer(load_config=Path('/path/to/your/config.yml'))
    viewer.main()
```
