### ISSUE TITLE
Bug training splatfacto

### ISSUE THREAD

**Issue by Alecapra96** [nerfstudio-project/nerfstudio#3285]
(nerfstudio) C:\nerfstudio>ns-train splatfacto --data data/ale
C:\Users\local_account\anaconda3\envs\nerfstudio\lib\site-packages\nerfstudio\utils\misc.py:184: RuntimeWarning: Windows does not yet support torch.compile and the performance will be affected.
  warnings.warn(
C:\Users\local_account\anaconda3\envs\nerfstudio\lib\site-packages\tyro\_fields.py:330: UserWarning: The field colmap_path is annotated with type <class 'pathlib.Path'>, but the default value sparse/0 has type <class 'str'>. We'll try to handle this gracefully, but it may cause unexpected behavior.
  warnings.warn(
[13:26:18] Using --data alias for --data.pipeline.datamanager.data                                          train.py:230──────────────────────────────────────────────────────── Config ────────────────────────────────────────────────────────TrainerConfig(
    _target=<class 'nerfstudio.engine.trainer.Trainer'>,
    output_dir=WindowsPath('outputs'),
    method_name='splatfacto',
    experiment_name=None,
    project_name='nerfstudio-project',
    timestamp='2024-07-03_132618',
    machine=MachineConfig(seed=42, num_devices=1, num_machines=1, machine_rank=0, dist_url='auto', device_type='cuda'),
    logging=LoggingConfig(
        relative_log_dir=WindowsPath('.'),
        steps_per_log=10,
        max_buffer_size=20,
        local_writer=LocalWriterConfig(
            _target=<class 'nerfstudio.utils.writer.LocalWriter'>,
            enable=True,
            stats_to_track=(
                <EventName.ITER_TRAIN_TIME: 'Train Iter (time)'>,
                <EventName.TRAIN_RAYS_PER_SEC: 'Train Rays / Sec'>,
                <EventName.CURR_TEST_PSNR: 'Test PSNR'>,
                <EventName.VIS_RAYS_PER_SEC: 'Vis Rays / Sec'>,
                <EventName.TEST_RAYS_PER_SEC: 'Test Rays / Sec'>,
                <EventName.ETA: 'ETA (time)'>
            ),
            max_log_size=10
        ),
        profiler='basic'
    ),
    viewer=ViewerConfig(
        relative_log_filename='viewer_log_filename.txt',
        websocket_port=None,
        websocket_port_default=7007,
        websocket_host='0.0.0.0',
        num_rays_per_chunk=32768,
        max_num_display_images=512,
        quit_on_train_completion=False,
        image_format='jpeg',
        jpeg_quality=75,
        make_share_url=False,
        camera_frustum_scale=0.1,
        default_composite_depth=True
    ),
    pipeline=VanillaPipelineConfig(
        _target=<class 'nerfstudio.pipelines.base_pipeline.VanillaPipeline'>,
        datamanager=FullImageDatamanagerConfig(
            _target=<class 'nerfstudio.data.datamanagers.full_images_datamanager.FullImageDatamanager'>,
            data=WindowsPath('data/ale'),
            masks_on_gpu=False,
            images_on_gpu=False,
            dataparser=NerfstudioDataParserConfig(
                _target=<class 'nerfstudio.data.dataparsers.nerfstudio_dataparser.Nerfstudio'>,
                data=WindowsPath('.'),
                scale_factor=1.0,
                downscale_factor=None,
                scene_scale=1.0,
                orientation_method='up',
                center_method='poses',
                auto_scale_poses=True,
                eval_mode='fraction',
                train_split_fraction=0.9,
                eval_interval=8,
                depth_unit_scale_factor=0.001,
                mask_color=None,
                load_3D_points=True
            ),
            camera_res_scale_factor=1.0,
            eval_num_images_to_sample_from=-1,
            eval_num_times_to_repeat_images=-1,
            eval_image_indices=(0,),
            cache_images='gpu',
            cache_images_type='uint8',
            max_thread_workers=None,
            train_cameras_sampling_strategy='random',
            train_cameras_sampling_seed=42,
            fps_reset_every=100
        ),
        model=SplatfactoModelConfig(
            _target=<class 'nerfstudio.models.splatfacto.SplatfactoModel'>,
            enable_collider=True,
            collider_params={'near_plane': 2.0, 'far_plane': 6.0},
            loss_coefficients={'rgb_loss_coarse': 1.0, 'rgb_loss_fine': 1.0},
            eval_num_rays_per_chunk=4096,
            prompt=None,
            warmup_length=500,
            refine_every=100,
            resolution_schedule=3000,
            background_color='random',
            num_downscales=2,
            cull_alpha_thresh=0.1,
            cull_scale_thresh=0.5,
            continue_cull_post_densification=True,
            reset_alpha_every=30,
            densify_grad_thresh=0.0008,
            densify_size_thresh=0.01,
            n_split_samples=2,
            sh_degree_interval=1000,
            cull_screen_size=0.15,
            split_screen_size=0.05,
            stop_screen_size_at=4000,
            random_init=False,
            num_random=50000,
            random_scale=10.0,
            ssim_lambda=0.2,
            stop_split_at=15000,
            sh_degree=3,
            use_scale_regularization=False,
            max_gauss_ratio=10.0,
            output_depth_during_training=False,
            rasterize_mode='classic',
            camera_optimizer=CameraOptimizerConfig(
                _target=<class 'nerfstudio.cameras.camera_optimizers.CameraOptimizer'>,
                mode='off',
                trans_l2_penalty=0.01,
                rot_l2_penalty=0.001,
                optimizer=None,
                scheduler=None
            )
        )
    ),
    optimizers={
        'means': {
            'optimizer': AdamOptimizerConfig(
                _target=<class 'torch.optim.adam.Adam'>,
                lr=0.00016,
                eps=1e-15,
                max_norm=None,
                weight_decay=0
            ),
            'scheduler': ExponentialDecaySchedulerConfig(
                _target=<class 'nerfstudio.engine.schedulers.ExponentialDecayScheduler'>,
                lr_pre_warmup=1e-08,
                lr_final=1.6e-06,
                warmup_steps=0,
                max_steps=30000,
                ramp='cosine'
            )
        },
        'features_dc': {
            'optimizer': AdamOptimizerConfig(
                _target=<class 'torch.optim.adam.Adam'>,
                lr=0.0025,
                eps=1e-15,
                max_norm=None,
                weight_decay=0
            ),
            'scheduler': None
        },
        'features_rest': {
            'optimizer': AdamOptimizerConfig(
                _target=<class 'torch.optim.adam.Adam'>,
                lr=0.000125,
                eps=1e-15,
                max_norm=None,
                weight_decay=0
            ),
            'scheduler': None
        },
        'opacities': {
            'optimizer': AdamOptimizerConfig(
                _target=<class 'torch.optim.adam.Adam'>,
                lr=0.05,
                eps=1e-15,
                max_norm=None,
                weight_decay=0
            ),
            'scheduler': None
        },
        'scales': {
            'optimizer': AdamOptimizerConfig(
                _target=<class 'torch.optim.adam.Adam'>,
                lr=0.005,
                eps=1e-15,
                max_norm=None,
                weight_decay=0
            ),
            'scheduler': None
        },
        'quats': {
            'optimizer': AdamOptimizerConfig(
                _target=<class 'torch.optim.adam.Adam'>,
                lr=0.001,
                eps=1e-15,
                max_norm=None,
                weight_decay=0
            ),
            'scheduler': None
        },
        'camera_opt': {
            'optimizer': AdamOptimizerConfig(
                _target=<class 'torch.optim.adam.Adam'>,
                lr=0.0001,
                eps=1e-15,
                max_norm=None,
                weight_decay=0
            ),
            'scheduler': ExponentialDecaySchedulerConfig(
                _target=<class 'nerfstudio.engine.schedulers.ExponentialDecayScheduler'>,
                lr_pre_warmup=0,
                lr_final=5e-07,
                warmup_steps=1000,
                max_steps=30000,
                ramp='cosine'
            )
        }
    },
    vis='viewer',
    data=WindowsPath('data/ale'),
    prompt=None,
    relative_model_dir=WindowsPath('nerfstudio_models'),
    load_scheduler=True,
    steps_per_save=2000,
    steps_per_eval_batch=0,
    steps_per_eval_image=100,
    steps_per_eval_all_images=1000,
    max_num_iterations=30000,
    mixed_precision=False,
    use_grad_scaler=False,
    save_only_latest_checkpoint=True,
    load_dir=None,
    load_step=None,
    load_config=None,
    load_checkpoint=None,
    log_gradients=False,
    gradient_accumulation_steps={}
)
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────           Saving config to: outputs\ale\splatfacto\2024-07-03_132618\config.yml                experiment_config.py:136           Saving checkpoints to: outputs\ale\splatfacto\2024-07-03_132618\nerfstudio_models              trainer.py:137           Auto image downscale factor of 4                                                 nerfstudio_dataparser.py:484╭─────────────── viser ───────────────╮
│             ╷                       │
│   HTTP      │ http://0.0.0.0:7007   │
│   Websocket │ ws://0.0.0.0:7007     │
│             ╵                       │
╰─────────────────────────────────────╯
[13:26:22] Caching / undistorting eval images                                             full_images_datamanager.py:230[NOTE] Not running eval iterations since only viewer is enabled.
Use --vis {wandb, tensorboard, viewer+wandb, viewer+tensorboard} to run with eval.
No Nerfstudio checkpoint to load, so training from scratch.
Disabled comet/tensorboard/wandb event writers
[13:26:28] Caching / undistorting train images                                            full_images_datamanager.py:230Printing profiling stats, from longest to shortest duration in seconds
Trainer.train_iteration: 55.1450
VanillaPipeline.get_train_loss_dict: 55.1431
Traceback (most recent call last):
  File "C:\Users\local_account\anaconda3\envs\nerfstudio\lib\site-packages\gsplat\cuda\_backend.py", line 41, in <module>
    from gsplat import csrc as _C
ImportError: cannot import name 'csrc' from 'gsplat' (C:\Users\local_account\anaconda3\envs\nerfstudio\lib\site-packages\gsplat\__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\local_account\anaconda3\envs\nerfstudio\lib\site-packages\torch\utils\cpp_extension.py", line 2100, in _run_ninja_build
    subprocess.run(
  File "C:\Users\local_account\anaconda3\envs\nerfstudio\lib\subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\local_account\anaconda3\envs\nerfstudio\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\local_account\anaconda3\envs\nerfstudio\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\local_account\anaconda3\envs\nerfstudio\Scripts\ns-train.exe\__main__.py", line 7, in <module>
  File "C:\Users\local_account\anaconda3\envs\nerfstudio\lib\site-packages\nerfstudio\scripts\train.py", line 262, in entrypoint
    main(
  File "C:\Users\local_account\anaconda3\envs\nerfstudio\lib\site-packages\nerfstudio\scripts\train.py", line 247, in main
    launch(
  File "C:\Users\local_account\anaconda3\envs\nerfstudio\lib\site-packages\nerfstudio\scripts\train.py", line 189, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "C:\Users\local_account\anaconda3\envs\nerfstudio\lib\site-packages\nerfstudio\scripts\train.py", line 100, in train_loop
    trainer.train()
  File "C:\Users\local_account\anaconda3\envs\nerfstudio\lib\site-packages\nerfstudio\engine\trainer.py", line 261, in train
    loss, loss_dict, metrics_dict = self.train_iteration(step)
  File "C:\Users\local_account\anaconda3\envs\nerfstudio\lib\site-packages\nerfstudio\utils\profiler.py", line 112, in inner
    out = func(*args, **kwargs)
  File "C:\Users\local_account\anaconda3\envs\nerfstudio\lib\site-packages\nerfstudio\engine\trainer.py", line 496, in train_iteration
    _, loss_dict, metrics_dict = self.pipeline.get_train_loss_dict(step=step)
  File "C:\Users\local_account\anaconda3\envs\nerfstudio\lib\site-packages\nerfstudio\utils\profiler.py", line 112, in inner
    out = func(*args, **kwargs)
  File "C:\Users\local_account\anaconda3\envs\nerfstudio\lib\site-packages\nerfstudio\pipelines\base_pipeline.py", line 301, in get_train_loss_dict
    model_outputs = self._model(ray_bundle)  # train distributed data parallel model if world_size > 1
  File "C:\Users\local_account\anaconda3\envs\nerfstudio\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\local_account\anaconda3\envs\nerfstudio\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\local_account\anaconda3\envs\nerfstudio\lib\site-packages\nerfstudio\models\base_model.py", line 143, in forward
    return self.get_outputs(ray_bundle)
  File "C:\Users\local_account\anaconda3\envs\nerfstudio\lib\site-packages\nerfstudio\models\splatfacto.py", line 760, in get_outputs
    render, alpha, info = rasterization(
  File "C:\Users\local_account\anaconda3\envs\nerfstudio\lib\site-packages\gsplat\rendering.py", line 212, in rasterization
    proj_results = fully_fused_projection(
  File "C:\Users\local_account\anaconda3\envs\nerfstudio\lib\site-packages\gsplat\cuda\_wrapper.py", line 260, in fully_fused_projection
    return _FullyFusedProjection.apply(
  File "C:\Users\local_account\anaconda3\envs\nerfstudio\lib\site-packages\torch\autograd\function.py", line 539, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "C:\Users\local_account\anaconda3\envs\nerfstudio\lib\site-packages\gsplat\cuda\_wrapper.py", line 692, in forward
    radii, means2d, depths, conics, compensations = _make_lazy_cuda_func(
  File "C:\Users\local_account\anaconda3\envs\nerfstudio\lib\site-packages\gsplat\cuda\_wrapper.py", line 10, in call_cuda
    from ._backend import _C
  File "C:\Users\local_account\anaconda3\envs\nerfstudio\lib\site-packages\gsplat\cuda\_backend.py", line 84, in <module>
    _C = load(
  File "C:\Users\local_account\anaconda3\envs\nerfstudio\lib\site-packages\torch\utils\cpp_extension.py", line 1308, in load
    return _jit_compile(
  File "C:\Users\local_account\anaconda3\envs\nerfstudio\lib\site-packages\torch\utils\cpp_extension.py", line 1710, in _jit_compile
    _write_ninja_file_and_build_library(
  File "C:\Users\local_account\anaconda3\envs\nerfstudio\lib\site-packages\torch\utils\cpp_extension.py", line 1823, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "C:\Users\local_account\anaconda3\envs\nerfstudio\lib\site-packages\torch\utils\cpp_extension.py", line 2116, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'gsplat_cuda': [1/5] cl /showIncludes -DTORCH_EXTENSION_NAME=gsplat_cuda -DTORCH_API_INCLUDE_EXTENSION_H -IC:\Users\local_account\anaconda3\envs\nerfstudio\lib\site-packages\gsplat\cuda\csrc -IC:\Users\local_account\anaconda3\envs\nerfstudio\lib\site-packages\torch\include -IC:\Users\local_account\anaconda3\envs\nerfstudio\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\local_account\anaconda3\envs\nerfstudio\lib\site-packages\torch\include\TH -IC:\Users\local_account\anaconda3\envs\nerfstudio\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include" -IC:\Users\local_account\anaconda3\envs\nerfstudio\Include -D_GLIBCXX_USE_CXX11_ABI=0 /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /wd4624 /wd4067 /wd4068 /EHsc /std:c++17 -O3 -c C:\Users\local_account\anaconda3\envs\nerfstudio\lib\site-packages\gsplat\cuda\csrc\ext.cpp /Foext.o
Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30154 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

cl : Command line warning D9002 : ignoring unknown option '-O3'
C:\Users\local_account\anaconda3\envs\nerfstudio\lib\site-packages\torch\include\pybind11\detail/common.h(210): warning C4005: 'HAVE_SNPRINTF': macro redefinition
C:\Users\local_account\anaconda3\envs\nerfstudio\Include\pyerrors.h(315): note: see previous definition of 'HAVE_SNPRINTF'
[2/5] C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin\nvcc --generate-dependencies-with-compile --dependency-output projection.cuda.o.d -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcompiler /EHsc -Xcompiler /wd4068 -Xcompiler /wd4067 -Xcompiler /wd4624 -Xcompiler /wd4190 -Xcompiler /wd4018 -Xcompiler /wd4275 -Xcompiler /wd4267 -Xcompiler /wd4244 -Xcompiler /wd4251 -Xcompiler /wd4819 -Xcompiler /MD -DTORCH_EXTENSION_NAME=gsplat_cuda -DTORCH_API_INCLUDE_EXTENSION_H -IC:\Users\local_account\anaconda3\envs\nerfstudio\lib\site-packages\gsplat\cuda\csrc -IC:\Users\local_account\anaconda3\envs\nerfstudio\lib\site-packages\torch\include -IC:\Users\local_account\anaconda3\envs\nerfstudio\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\local_account\anaconda3\envs\nerfstudio\lib\site-packages\torch\include\TH -IC:\Users\local_account\anaconda3\envs\nerfstudio\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include" -IC:\Users\local_account\anaconda3\envs\nerfstudio\Include -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++17 -O3 --use_fast_math -c C:\Users\local_account\anaconda3\envs\nerfstudio\lib\site-packages\gsplat\cuda\csrc\projection.cu -o projection.cuda.o
FAILED: projection.cuda.o
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin\nvcc --generate-dependencies-with-compile --dependency-output projection.cuda.o.d -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcompiler /EHsc -Xcompiler /wd4068 -Xcompiler /wd4067 -Xcompiler /wd4624 -Xcompiler /wd4190 -Xcompiler /wd4018 -Xcompiler /wd4275 -Xcompiler /wd4267 -Xcompiler /wd4244 -Xcompiler /wd4251 -Xcompiler /wd4819 -Xcompiler /MD -DTORCH_EXTENSION_NAME=gsplat_cuda -DTORCH_API_INCLUDE_EXTENSION_H -IC:\Users\local_account\anaconda3\envs\nerfstudio\lib\site-packages\gsplat\cuda\csrc -IC:\Users\local_account\anaconda3\envs\nerfstudio\lib\site-packages\torch\include -IC:\Users\local_account\anaconda3\envs\nerfstudio\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\local_account\anaconda3\envs\nerfstudio\lib\site-packages\torch\include\TH -IC:\Users\local_account\anaconda3\envs\nerfstudio\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include" -IC:\Users\local_account\anaconda3\envs\nerfstudio\Include -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++17 -O3 --use_fast_math -c C:\Users\local_account\anaconda3\envs\nerfstudio\lib\site-packages\gsplat\cuda\csrc\projection.cu -o projection.cuda.o
C:\Users\local_account\anaconda3\envs\nerfstudio\lib\site-packages\torch\include\pybind11\detail/common.h(210): warning C4005: 'HAVE_SNPRINTF': macro redefinition
C:\Users\local_account\anaconda3\envs\nerfstudio\Include\pyerrors.h(315): note: see previous definition of 'HAVE_SNPRINTF'
C:\Users\local_account\anaconda3\envs\nerfstudio\lib\site-packages\torch\include\pybind11\detail/common.h(210): warning C4005: 'HAVE_SNPRINTF': macro redefinition
C:\Users\local_account\anaconda3\envs\nerfstudio\Include\pyerrors.h(315): note: see previous definition of 'HAVE_SNPRINTF'
C:\Users\local_account\anaconda3\envs\nerfstudio\lib\site-packages\gsplat\cuda\csrc\third_party\glm\glm\ext\../detail/type_vec2.hpp(101): warning #20012-D: __device__ annotation is ignored on a function("vec") that is explicitly defaulted on its first declaration

C:\Users\local_account\anaconda3\envs\nerfstudio\lib\site-packages\gsplat\cuda\csrc\third_party\glm\glm\ext\../detail/type_vec2.hpp(101): warning #20012-D: __host__ annotation is ignored on a function("vec") that is explicitly defaulted on its first declaration

**.....
I cut because it is repeated
.....**

C:\Users\local_account\anaconda3\envs\nerfstudio\lib\site-packages\gsplat\cuda\csrc\third_party\glm\glm\ext\../detail/type_mat4x2.hpp(36): warning #20012-D: __host__ annotation is ignored on a function("mat") that is explicitly defaulted on its first declaration

C:\Users\local_account\anaconda3\envs\nerfstudio\lib\site-packages\gsplat\cuda\csrc\third_party\glm\glm\ext\../detail/type_mat4x3.hpp(36): warning #20012-D: __device__ annotation is ignored on a function("mat") that is explicitly defaulted on its first declaration

C:\Users\local_account\anaconda3\envs\nerfstudio\lib\site-packages\gsplat\cuda\csrc\third_party\glm\glm\ext\../detail/type_mat4x3.hpp(36): warning #20012-D: __host__ annotation is ignored on a function("mat") that is explicitly defaulted on its first declaration

C:\Users\local_account\anaconda3\envs\nerfstudio\lib\site-packages\gsplat\cuda\csrc\third_party\glm\glm\ext\../detail/type_mat4x4.hpp(35): warning #20012-D: __device__ annotation is ignored on a function("mat") that is explicitly defaulted on its first declaration

C:\Users\local_account\anaconda3\envs\nerfstudio\lib\site-packages\gsplat\cuda\csrc\third_party\glm\glm\ext\../detail/type_mat4x4.hpp(35): warning #20012-D: __host__ annotation is ignored on a function("mat") that is explicitly defaulted on its first declaration

C:\Users\local_account\anaconda3\envs\nerfstudio\lib\site-packages\gsplat\cuda\csrc\third_party\glm\glm\ext\../detail/type_quat.hpp(73): warning #20012-D: __device__ annotation is ignored on a function("qua") that is explicitly defaulted on its first declaration

C:\Users\local_account\anaconda3\envs\nerfstudio\lib\site-packages\gsplat\cuda\csrc\third_party\glm\glm\ext\../detail/type_quat.hpp(73): warning #20012-D: __host__ annotation is ignored on a function("qua") that is explicitly defaulted on its first declaration

sh.cu
ninja: build stopped: subcommand failed.

It fails when I want to train splatfacto, nerfacto works fine

**Comment by Alecapra96** [comment]
Fixed  https://github.com/nerfstudio-project/gsplat/blob/main/docs/INSTALL_WIN.md
with the script for VS2019

**Comment by elliotmarks06** [comment]
I'm getting the same error. How did you fix it?
