### ISSUE TITLE
gsplat mcmc windows dataset load error

### ISSUE THREAD

**Issue by henrypearce4D** [nerfstudio-project/nerfstudio#3299]
I am testing the gsplat mcmc method on windows using this setup procedure;

```
# clean up
pip uninstall gsplat pycolmap -y

# it uses custom pycolmap, so here is it
pip install git+https://github.com/rmbrualla/pycolmap@cc7ea4b7301720ac29287dbe450952511b32125e

# make sure you already have torch2.1.2+cu118
pip install torch==2.1.2 \
    torchvision==0.16.2 torchaudio==2.1.2 --index-url https://download.pytorch.org/whl/cu118

# I personally freeze this version for reproducibility
pip install jaxtyping==0.2.31 markdown-it-py==3.0.0 mdurl==0.1.2 ninja==1.11.1.1 \
    rich==13.7.1 typeguard==2.13.3 imageio==2.34.2 \
    docstring-parser==0.16 shtab==1.7.1 typing-extensions==4.12.2 tyro==0.8.5 viser==0.2.2 \
    chardet==5.2.0 colorlog==6.8.2 embreex==2.17.7.post4 h11==0.14.0 httpcore==1.0.5 \
    httpx==0.27.0 lazy-loader==0.4 mapbox-earcut==1.0.1 msgpack==1.0.8 nodeenv==1.9.1 \
    pycollada==0.8 pyliblzfse==0.4.1 rtree==1.2.0 scikit-image==0.24.0 scipy==1.14.0 \
    shapely==2.0.4 svg.path==6.3 tifffile==2024.6.18 trimesh==4.4.1 vhacdx==0.0.8.post1 \
    websockets==12.0 xatlas==0.0.9 xxhash==3.4.1 yourdfpy==0.0.56 \
    nerfview==0.0.3 opencv-python==4.10.0.84 imageio-ffmpeg==0.5.1 plyfile==1.0.3 \
    torchmetrics==1.4.0.post0 tensorboard==2.17.0 scikit-learn==1.5.0

# Install gsplat again
pip install git+https://github.com/nerfstudio-project/gsplat.git@18a9aa384bccf165aba3ea12db27e6ec7d6bf202
```
And get an error when loading the dataset;
```
(nerfstudio) c:\nerfstudio>python  gsplat/examples/simple_trainer_mcmc.py --data-dir data/360_v2/garden
Warning: image_path not found for reconstruction
Traceback (most recent call last):
  File "c:\nerfstudio\gsplat\examples\simple_trainer_mcmc.py", line 830, in <module>
    main(cfg)
  File "c:\nerfstudio\gsplat\examples\simple_trainer_mcmc.py", line 810, in main
    runner = Runner(cfg)
  File "c:\nerfstudio\gsplat\examples\simple_trainer_mcmc.py", line 181, in __init__
    self.parser = Parser(
  File "c:\nerfstudio\gsplat\examples\datasets\colmap.py", line 50, in __init__
    manager.load_cameras()
  File "C:\Users\admin\anaconda3\envs\nerfstudio\lib\site-packages\pycolmap\scene_manager.py", line 90, in load_cameras
    self._load_cameras_bin(input_file)
  File "C:\Users\admin\anaconda3\envs\nerfstudio\lib\site-packages\pycolmap\scene_manager.py", line 102, in _load_cameras_bin
    num_cameras = struct.unpack('L', f.read(8))[0]
struct.error: unpack requires a buffer of 4 bytes
```
Changing L to Q in the scene_manager.py doesn't work;
```
   camera_id, camera_type, w, h = struct.unpack('IiLL', f.read(24))
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
struct.error: unpack requires a buffer of 16 bytes
```

 And also changing to <L and >L doesn't work.

Discord thread to this issue here;
https://discord.com/channels/1025504971606724712/1259877064773861446

**Comment by henrypearce4D** [comment]
created new issue in the gsplat repo instead
