### ISSUE TITLE
cant connect to https://viewer.nerf.studio/

### ISSUE THREAD

**Issue by DrAwkward33** [nerfstudio-project/nerfstudio#3300]
Attemping to use the websocket viewer throws and error and fails to display:

`(viser) Connection opened (434, 418 total), 148 persistent messages
connection handler failed
Traceback (most recent call last):
  File "C:\Users\dsheremet\AppData\Local\anaconda3\envs\nerfstudio\lib\site-packages\websockets\legacy\server.py", line 236, in handler
    await self.ws_handler(self)
  File "C:\Users\dsheremet\AppData\Local\anaconda3\envs\nerfstudio\lib\site-packages\viser\infra\_infra.py", line 327, in serve
    await asyncio.gather(
  File "C:\Users\dsheremet\AppData\Local\anaconda3\envs\nerfstudio\lib\site-packages\viser\infra\_infra.py", line 475, in _message_consumer
    message = message_class.deserialize(raw)
  File "C:\Users\dsheremet\AppData\Local\anaconda3\envs\nerfstudio\lib\site-packages\viser\infra\_messages.py", line 137, in deserialize
    message_type = cls._subclass_from_type_string()[cast(str, mapping.pop("type"))]
KeyError: 'CameraMessage'`

**Comment by bigcomma** [comment]
sam Error:
(viser) Connection opened (39, 40 total), 267 persistent messages
connection handler failed
Traceback (most recent call last):
  File "C:\Users\user\.conda\envs\nerfstudio\lib\site-packages\websockets\legacy\server.py", line 236, in handler
    await self.ws_handler(self)
  File "C:\Users\user\.conda\envs\nerfstudio\lib\site-packages\viser\infra\_infra.py", line 327, in serve
    await asyncio.gather(
  File "C:\Users\user\.conda\envs\nerfstudio\lib\site-packages\viser\infra\_infra.py", line 475, in _message_consumer
    message = message_class.deserialize(raw)
  File "C:\Users\user\.conda\envs\nerfstudio\lib\site-packages\viser\infra\_messages.py", line 137, in deserialize
    message_type = cls._subclass_from_type_string()[cast(str, mapping.pop("type"))]
KeyError: 'CameraMessage'

**Comment by brentyi** [comment]
Hello! Can you see if https://github.com/nerfstudio-project/nerfstudio/issues/2972 or https://github.com/nerfstudio-project/viser/issues/148 help?

**Comment by bsjj777** [comment]
> Hello! Can you see if #2972 or [nerfstudio-project/viser#148](https://github.com/nerfstudio-project/viser/issues/148) help?

I've tried all the methods mentioned in the link you provided, but none of them worked.

1. Directly accessing http://localhost:7007/
2. Removing plugins like Tampermonkey
Is there any other solution? I would appreciate your help.

**Comment by PeetKiattisak** [comment]
just got the same error.did you get any solution?

**Comment by yydslc** [comment]
+1

**Comment by yanyide123** [comment]
+1

**Comment by yanyide123** [comment]
**error message：**
connection handler failed
Traceback (most recent call last):
  File "D:\miniconda3\envs\nerfstudio\lib\site-packages\websockets\legacy\server.py", line 236, in handler
    await self.ws_handler(self)
  File "D:\miniconda3\envs\nerfstudio\lib\site-packages\viser\infra\_infra.py", line 379, in serve
    await asyncio.gather(
  File "D:\miniconda3\envs\nerfstudio\lib\site-packages\viser\infra\_infra.py", line 533, in _message_consumer
    message = message_class.deserialize(raw)
  File "D:\miniconda3\envs\nerfstudio\lib\site-packages\viser\infra\_messages.py", line 149, in deserialize
    message_type = cls._subclass_from_type_string()[cast(str, mapping.pop("type"))]
KeyError: 'CameraMessage'
**Printed the mapping, mapping result.**
mapping {'type': 'CameraMessage', 'aspect': 1.7392638036809815, 'render_aspect': 1.7777777777777777, 'fov': 50, 'matrix': (0.7071067811865476, 0.7071067
811865475, 0, 0, -0.20507577810739902, 0.20507577810739896, 0.9570202978345286, 0, 0.6767155423319645, -0.6767155423319646, 0.29002094671369916, 0, 0.69
99999999999997, -0.6999999999999998, 0.29999999999999993, 1), 'camera_type': 'perspective', 'is_moving': False, 'timestamp': 1736837390932.0}

The source of the error is：
Startup command：ns-train nerfacto --data data/nerfstudio/poster --viewer.websocket-port 9000
Then access through： https://viewer.nerf.studio/?websocket_url=ws://localhost:9000
The error occurs as soon as the connection is made.

**Comment by brentyi** [comment]
You probably don't want to be using viewer.nerf.studio, you can see https://github.com/nerfstudio-project/viser/issues/148 and #2972 for explanation.
