### ISSUE TITLE
Unable to use custom data from Metashape/Reality Capture

### ISSUE THREAD

**Issue by Broken1334** [nerfstudio-project/nerfstudio#3365]
Hi! 
Tried to use custom data from Metashape, but `ns-process-data metashape --data C:/input --xml C:/input/test.xml --output-dir C:/output` gives me an error. Same issue with Reality Capture data using `ns-process-data realitycapture`. 
Test data `ns-download-data nerfstudio --capture-name=poster` works as expected.

```
Traceback (most recent call last):
  File "C:\ProgramData\miniconda3\envs\nerfstudio\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\miniconda3\envs\nerfstudio\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\miniconda3\envs\nerfstudio\Scripts\ns-process-data.exe\__main__.py", line 7, in <module>
  File "C:\ProgramData\miniconda3\envs\nerfstudio\lib\site-packages\nerfstudio\scripts\process_data.py", line 551, in entrypoint
    tyro.cli(Commands).main()
  File "C:\ProgramData\miniconda3\envs\nerfstudio\lib\site-packages\nerfstudio\scripts\process_data.py", line 376, in main
    copied_image_paths = process_data_utils.copy_images_list(
  File "C:\ProgramData\miniconda3\envs\nerfstudio\lib\site-packages\nerfstudio\process_data\process_data_utils.py", line 309, in copy_images_list
    ffmpeg_cmd = f'ffmpeg -y -noautorotate -i "{image_dir / f"{framename}{copied_image_paths[0].suffix}"}" '
IndexError: list index out of range
```

**Comment by jb-ye** [comment]
Could you elaborate your folder structure of metashape exported data? Where are images and xmls.

**Comment by naga-k** [comment]
Hi @jb-ye For me, I see that it is happening with HEIC images. I capture on my iPhone. Any suggestions?
