### ISSUE TITLE
Converts COLMAP's cameras.bin and images.bin to a JSON file.

### ISSUE THREAD

**Issue by mixtresh** [nerfstudio-project/nerfstudio#826]
if i make camera tracking in colmap, how i can save data for nerfstudio? transforms.json
script for "Converts COLMAP's cameras.bin and images.bin to a JSON file."

"ns-process-data, you can add the argument --skip-colmap. You should place the two .bin files in OUT_DIR/colmap/sparse/0/" this help not work 

(base) E:\NN\nerf\nerfstudio>ns-process-data images --data data --output-dir output --skip-colmap
[11:56:27] 🎉 Done copying images.                                                                   process_data.py:283
[11:56:28] 🎉 Done downscaling images.                                                               process_data.py:322
Traceback (most recent call last):
  File "C:\Users\work\miniconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\work\miniconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\work\miniconda3\Scripts\ns-process-data.exe__main__.py", line 7, in <module>
  File "E:\NN\nerf\nerfstudio\scripts\process_data.py", line 781, in entrypoint
    tyro.cli(Commands).main()
  File "E:\NN\nerf\nerfstudio\scripts\process_data.py", line 580, in main
    num_matched_frames = colmap_to_json(
  File "E:\NN\nerf\nerfstudio\scripts\process_data.py", line 463, in colmap_to_json
    "k1": float(camera_params[4]),
IndexError: index 4 is out of bounds for axis 0 with size 4

**Comment by kwea123** [comment]
I still have this problem, how did you solve?

**Comment by mixtresh** [comment]
> I still have this problem, how did you solve?

after open COLMAP, add image and change in database camera type to OPENCV. After that start reconstruction (dont use automatic, automatic change camera type)

**Comment by MatanFriedmann** [comment]
Hi @mixtresh, can you please elaborate on how you solved this issue please? 
I'm still experiencing the same issue. 
Where and how did you "add image" and how did you "change in database camera type to OPENCV"? 
Thank you

**Comment by MatanFriedmann** [comment]
got it to work. 
if anyone is back here with this issue: 
when running colmap reconstruction, try to change the camera type to OPENCV with this parameter: 
`image_options = {'camera_model': 'OPENCV'}`
`model = reconstruction.main(......, image_options=image_options)`
then you get the cameras.bin to have OPENCV cameras with the right number of parameters, and then ns-process-data can work as written now.

**Comment by hugosbnarciso** [comment]
hello, this error appears today, but yesterday it didn't, any suggestion?

`[13:26:20] 🎉 Done refining intrinsics.                                                              colmap_utils.py:182
Traceback (most recent call last):
  File "D:\Anaconda3\envs\nerfstudio\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Anaconda3\envs\nerfstudio\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Anaconda3\envs\nerfstudio\Scripts\ns-process-data.exe\__main__.py", line 7, in <module>
  File "D:\nerfstudio\scripts\process_data.py", line 970, in entrypoint
    tyro.cli(Commands).main()
  File "D:\nerfstudio\scripts\process_data.py", line 434, in main
    num_matched_frames = colmap_utils.colmap_to_json(
  File "D:\nerfstudio\nerfstudio\process_data\colmap_utils.py", line 459, in colmap_to_json
    applied_transform = applied_transform[np.array([1, 0, 2, 3]), :]
IndexError: index 3 is out of bounds for axis 0 with size 3`
