### ISSUE TITLE
KeyError: 'pipeline' when running ns-train

### ISSUE THREAD

**Issue by jfaust** [nerfstudio-project/nerfstudio#882]
**Describe the bug**
I just did a fresh install of Anaconda3 & nerf studio, following the guide at https://docs.nerf.studio/en/latest/quickstart/installation.html

When running `ns-train`, even without any arguments, I get the following error:
```
Traceback (most recent call last):
  File "/home/josh/anaconda3/envs/nerfstudio/bin/ns-train", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/josh/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/scripts/train.py", line 249, in entrypoint
    tyro.cli(
  File "/home/josh/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/tyro/_cli.py", line 125, in cli
    _cli_impl(
  File "/home/josh/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/tyro/_cli.py", line 289, in _cli_impl
    parser_definition.apply(parser)
  File "/home/josh/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/tyro/_parsers.py", line 241, in apply
    prev_subparser_tree_nodes = subparsers.apply(
  File "/home/josh/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/tyro/_parsers.py", line 499, in apply
    subparser_def.apply(subparser)
  File "/home/josh/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/tyro/_parsers.py", line 235, in apply
    arg.add_argument(group_from_prefix[arg.prefix])
KeyError: 'pipeline'
```

**To Reproduce**
Not sure exactly how to reproduce, other than to follow the installation instructions. 

**Additional context**
Running in WSL2, Ubuntu 20.04.4, Anaconda 22.9.0, and nerfstudio 0.1.7 is installed - I tried with 0.1.6 as well.

Weirdly, this was working yesterday with a previous installation on the same machine. I reinstalled Anaconda and the nerfstudio env to try to fix an instant-ngp issue, but nerfacto was working yesterday.

Any thoughts on what could be going on here?

**Comment by tancik** [comment]
Odd. I'm unable to replicate on my machine. Maybe @brentyi has an idea.

**Comment by jfaust** [comment]
Not sure where the bug belongs, but modifying tyro's `_parsers.py` line 238 to:
```
if arg.lowered.help is not argparse.SUPPRESS:
    arg.add_argument(group_from_prefix[arg.prefix])
```

gets me working

**Comment by jfaust** [comment]
Spoke too soon in my last (deleted) comment - it got no-arguments working, but didn't pass in the pipeline to run

**Comment by patricknomad** [comment]
Getting the same issue when trying to run in colab:
```
Traceback (most recent call last):
  File "/usr/local/bin/ns-train", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.7/site-packages/scripts/train.py", line 251, in entrypoint
    description=convert_markup_to_ansi(__doc__),
  File "/usr/local/lib/python3.7/site-packages/tyro/_cli.py", line 132, in cli
    **deprecated_kwargs,
  File "/usr/local/lib/python3.7/site-packages/tyro/_cli.py", line 289, in _cli_impl
    parser_definition.apply(parser)
  File "/usr/local/lib/python3.7/site-packages/tyro/_parsers.py", line 242, in apply
    self, prev_subparser_tree_nodes
  File "/usr/local/lib/python3.7/site-packages/tyro/_parsers.py", line 499, in apply
    subparser_def.apply(subparser)
  File "/usr/local/lib/python3.7/site-packages/tyro/_parsers.py", line 235, in apply
    arg.add_argument(group_from_prefix[arg.prefix])
KeyError: 'pipeline'
```

**Comment by jfaust** [comment]
This appears to be a bug in tyro 0.3.28, which was released 3 hours ago. I downgraded to 0.3.27 & all is good.

**Comment by enbyautumn** [comment]
i used the command `pip install --upgrade tyro==0.3.27` to do that (to save a few seconds of googling for anyone here)

**Comment by brentyi** [comment]
Just yanked 0.3.28 from PyPI, sorry for the inconvenience!

Will make sure whatever's causing this is in tyro's unit tests before re-releasing.

**Comment by jfaust** [comment]
Thanks @brentyi!
