### ISSUE TITLE
Error in ns-render command

### ISSUE THREAD

**Issue by myaldiz** [nerfstudio-project/nerfstudio#897]
**Describe the bug**
Hi there!

I created a camera path in the viewer and copied the command generated. When I run that command it prints following output:
```bash
Traceback (most recent call last):
  File "/opt/conda/bin/ns-render", line 33, in <module>
    sys.exit(load_entry_point('nerfstudio', 'console_scripts', 'ns-render')())
  File "/opt/conda/bin/ns-render", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/opt/conda/lib/python3.9/importlib/metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "/opt/conda/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/host/dependencies/nerfstudio/scripts/render.py", line 26, in <module>
    from nerfstudio.cameras.camera_paths import get_path_from_json, get_spiral_path
  File "/host/dependencies/nerfstudio/nerfstudio/cameras/camera_paths.py", line 26, in <module>
    from nerfstudio.cameras.cameras import Cameras
  File "/host/dependencies/nerfstudio/nerfstudio/cameras/cameras.py", line 25, in <module>
    import torchvision
  File "/opt/conda/lib/python3.9/site-packages/torchvision/__init__.py", line 5, in <module>
    from torchvision import datasets
  File "/opt/conda/lib/python3.9/site-packages/torchvision/datasets/__init__.py", line 11, in <module>
    from .fakedata import FakeData
  File "/opt/conda/lib/python3.9/site-packages/torchvision/datasets/fakedata.py", line 5, in <module>
    from .. import transforms
  File "/opt/conda/lib/python3.9/site-packages/torchvision/transforms/__init__.py", line 1, in <module>
    from .transforms import *
  File "/opt/conda/lib/python3.9/site-packages/torchvision/transforms/transforms.py", line 17, in <module>
    from . import functional as F
  File "/opt/conda/lib/python3.9/site-packages/torchvision/transforms/functional.py", line 18, in <module>
    from . import functional_pil as F_pil
  File "/opt/conda/lib/python3.9/site-packages/torchvision/transforms/functional_pil.py", line 13, in <module>
    from . import _pil_constants
  File "/opt/conda/lib/python3.9/site-packages/torchvision/transforms/_pil_constants.py", line 12, in <module>
    AFFINE = Image.Transform.AFFINE
  File "/opt/conda/lib/python3.9/site-packages/PIL/Image.py", line 65, in __getattr__
    raise AttributeError(f"module '{__name__}' has no attribute '{name}'")
AttributeError: module 'PIL.Image' has no attribute 'Transform'
```

I install my environment with following commands (which follows same versions from `pyproject.toml`:
```bash
conda install -y pytorch=1.12.1 torchvision cudatoolkit=11.3 -c pytorch
python -m pip --no-cache-dir install cmake==3.23.3 \
        opencv-python==4.6.0.66 opencv-contrib-python==4.6.0.66 \
        aiohttp==3.8.1 aiortc==1.3.2 appdirs>=1.4 av==9.2.0 tyro>=0.3.23 gdown==4.5.1 \
        ninja==1.10.2.3 functorch==0.2.1 h5py>=2.9.0 imageio==2.21.1 ipywidgets>=7.6 \
        jupyterlab==3.3.4 matplotlib==3.5.3 mediapy==1.1.0 msgpack==1.0.4 \
        msgpack_numpy==0.4.8 nerfacc==0.2.1 plotly==5.7.0 protobuf==3.20.0 \
        pyngrok==5.1.0 python-socketio==5.7.1 requests rich==12.5.1 tensorboard==2.9.0 \
        u-msgpack-python>=2.4.1 wandb>=0.13.3 \
        hydra-core hydra-colorlog hydra-optuna-sweeper tqdm 
```
Would appreciate your help for fixing this.

**Comment by tancik** [comment]
Just to clarify, `ns-train` in that environment is working for you?

**Comment by myaldiz** [comment]
Hi @tancik, yeah ns-train works well

**Comment by tancik** [comment]
Can you run `python` and then `from nerfstudio.cameras.cameras import Cameras` to see if that fails?

**Comment by myaldiz** [comment]
It can import Cameras without issues

**Comment by tancik** [comment]
Oh weird, that is quite odd. What version of mediapy are you using?

**Comment by myaldiz** [comment]
When I update Pillow (`python3 -m pip install --upgrade Pillow
`), somehow it is able to render now

**Comment by myaldiz** [comment]
You may include newer version as a requirement in the `pyproject.toml` file I guess, will close the issue.
