### ISSUE TITLE
ModuleNotFound error

### ISSUE THREAD

**Issue by omigeot** [nerfstudio-project/nerfstudio#934]
On master, can't currently run ns-train. Fails with `ModuleNotFoundError: No module named 'nerfstudio.data.datamanagers.base_datamanager'; 'nerfstudio.data.datamanagers' is not a package`

**To Reproduce**

Just run `ns-train nerfacto` without any argument (or really just `ns-train`). It fails with the following backtrace : 

```Traceback (most recent call last):
  File "/home/olivier/Work/_AI/nerfstudio/env/bin/ns-train", line 5, in <module>
    from scripts.train import entrypoint
  File "/home/olivier/Work/_AI/nerfstudio/env/lib/python3.10/site-packages/scripts/train.py", line 48, in <module>
    from nerfstudio.configs import base_config as cfg
  File "/home/olivier/Work/_AI/nerfstudio/env/lib/python3.10/site-packages/nerfstudio/configs/base_config.py", line 185, in <module>
    from nerfstudio.pipelines.base_pipeline import VanillaPipelineConfig
  File "/home/olivier/Work/_AI/nerfstudio/env/lib/python3.10/site-packages/nerfstudio/pipelines/base_pipeline.py", line 40, in <module>
    from nerfstudio.data.datamanagers.base_datamanager import (
ModuleNotFoundError: No module named 'nerfstudio.data.datamanagers.base_datamanager'; 'nerfstudio.data.datamanagers' is not a package
```

**Comment by brentyi** [comment]
If you `pip install -e .` instead of `pip install .` it seems to work, looks like the `datamanagers/` directory is missing an `__init__.py`: https://github.com/nerfstudio-project/nerfstudio/tree/main/nerfstudio/data/datamanagers
