### ISSUE TITLE
Error when install Tiny cuda

### ISSUE THREAD

**Issue by GuillaumeJeu** [nerfstudio-project/nerfstudio#980]
`D:\Bureau\Nerf\nerfstudio>pip install git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch
Collecting git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch
  Cloning https://github.com/NVlabs/tiny-cuda-nn/ to c:\users\guilla~1\appdata\local\temp\pip-req-build-zpkkvldo
  Running command git clone --filter=blob:none --quiet https://github.com/NVlabs/tiny-cuda-nn/ 'C:\Users\GUILLA~1\AppData\Local\Temp\pip-req-build-zpkkvldo'
  Resolved https://github.com/NVlabs/tiny-cuda-nn/ to commit c18f6803668dec3a56a36deaa48d53f7a0582d8d
  Running command git submodule update --init --recursive -q
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\GUILLA~1\AppData\Local\Temp\pip-req-build-zpkkvldo\bindings/torch\setup.py", line 30, in <module>
          raise EnvironmentError("Unknown compute capability. Specify the target compute capabilities in the TCNN_CUDA_ARCHITECTURES environment variable or install PyTorch with the CUDA backend to detect it automatically.")
      OSError: Unknown compute capability. Specify the target compute capabilities in the TCNN_CUDA_ARCHITECTURES environment variable or install PyTorch with the CUDA backend to detect it automatically.
      Building PyTorch extension for tiny-cuda-nn version 1.6
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.`

Thank You

**Comment by xxsgh** [comment]
try "pip install --upgrade setuptools"

**Comment by minsoo5403** [comment]
What command did you use to install the pytorch? Are you using Visual Studio 2019?

**Comment by minsoo5403** [comment]
I installed it using Visual Studio 2019 as follows. Operates on CUDA 11.6.

pip install torch==1.12.1+cu116 torchvision==0.13.1+cu116 -f https://download.pytorch.org/whl/torch_stable.html
pip install git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch

Built in Ubuntu 22.04, too. but not in GCC-10. GCC-9 and G++-9 build.

TCNN was not built when using too high a version of the C++ compiler.
Similarly, it is successfully built on VS2019 rather than VS2022 based.

**Comment by THE-COB** [comment]
> I installed it using Visual Studio 2019 as follows. Operates on CUDA 11.6.
> 
> pip install torch==1.12.1+cu116 torchvision==0.13.1+cu116 -f https://download.pytorch.org/whl/torch_stable.html pip install git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch
> 
> Built in Ubuntu 22.04, too. but not in GCC-10. GCC-9 and G++-9 build.
> 
> TCNN was not built when using too high a version of the C++ compiler. Similarly, it is successfully built on VS2019 rather than VS2022 based.

^^, 2017-2019 inclusive works

**Comment by vasion18** [comment]
I am facing the same issue 
![image](https://user-images.githubusercontent.com/118062853/219970369-20705b34-6ed8-4c76-a130-8b103288854f.png)

**Comment by Jalim19** [comment]
I also surffer from this bug. HELP!

**Comment by sha-abhishek** [comment]
You need to ensure your cuda-toolkit version matches with the version your pytorch was compiled with. If you installed torch 2.0.1 with CUDA 11.7, you need to make sure you install the cuda toolkit 11.7. In order to install a specific version of cuda toolkit, make sure your nvidia driver is of the correct version. You can check the cuda compatibility in this table
![image](https://github.com/nerfstudio-project/nerfstudio/assets/113858734/d2790514-dd43-4e48-b178-dd0ad9bec888)
https://docs.nvidia.com/deploy/cuda-compatibility/index.html
