### ISSUE TITLE
Installed and built but getting AssertionError

### ISSUE THREAD

**Issue by IvRogoz** [nerfstudio-project/nerfstudio#988]
Download git and built using pip install -e .
Everything went ok but Im getting AssertionError ...?

```
PS D:\Programing\nerfstudio> ns-train --help
Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python310\Scripts\ns-train.exe\__main__.py", line 7, in <module>
  File "D:\Programing\nerfstudio\scripts\train.py", line 249, in entrypoint
    tyro.cli(
  File "C:\Python310\lib\site-packages\tyro\_cli.py", line 125, in cli
    _cli_impl(
  File "C:\Python310\lib\site-packages\tyro\_cli.py", line 290, in _cli_impl
    parser_definition.apply(parser)
  File "C:\Python310\lib\site-packages\tyro\_parsers.py", line 232, in apply
    leaves = self.subparsers.apply(parser)
  File "C:\Python310\lib\site-packages\tyro\_parsers.py", line 549, in apply
    subparser_tree_leaves.extend(subparser_def.apply(subparser))
  File "C:\Python310\lib\site-packages\tyro\_parsers.py", line 232, in apply
    leaves = self.subparsers.apply(parser)
  File "C:\Python310\lib\site-packages\tyro\_parsers.py", line 549, in apply
    subparser_tree_leaves.extend(subparser_def.apply(subparser))
  File "C:\Python310\lib\site-packages\tyro\_parsers.py", line 245, in apply
    assert parser._action_groups[1].title == "optional arguments"
AssertionError
PS D:\Programing\nerfstudio> 
```

**Comment by tancik** [comment]
Which version of `tyro` is installed? You can find this by running `pip list`

**Comment by brentyi** [comment]
Sorry, `tyro` seems to have broken with Python 3.10. `pip install tyro==0.3.33` will fix it.
